Solidity helper function for testing fixed points
ethereum/solidity pull request #1079
Opened 2016-09-10 02:16 UTC by VoR0220

Signed-off-by: VoR0220 <rj@erisindustries.com>

2016-09-10 10:46 UTC, axic commented
> Do we need to do something about getting the signature of a (u)fixed parameter?

I think that would be useful, to have`ufixed(M,N)` in the tests for clarity.

2016-09-10 10:48 UTC, axic commented on test/libsolidity/SolidityExecutionFramework.h
> +		rational value = _value * boost::multiprecision::pow(bigint(2), _fixedBits);
Cannot you do this without having two variables?

2016-09-10 17:23 UTC, VoR0220 commented on test/libsolidity/SolidityExecutionFramework.h
> +		rational value = _value * boost::multiprecision::pow(bigint(2), _fixedBits);
This is how we create fixed point types in the current code...do you have a different suggestion?

2016-09-10 18:14 UTC, axic commented on test/libsolidity/SolidityExecutionFramework.h
> +		rational value = _value * boost::multiprecision::pow(bigint(2), _fixedBits);
I wonder if you can merge the multiplication into the first line?

2016-09-12 06:05 UTC, VoR0220 commented on test/libsolidity/SolidityExecutionFramework.h
> +		rational value = _value * boost::multiprecision::pow(bigint(2), _fixedBits);
ah, that's what you meant. I mean you could...but I think that would look very messy.

2016-09-14 18:19 UTC, axic requested changes
(Wanted to try out the new Github review system)

Please simplify to one intermediate variable.

2016-10-05 10:43 UTC, axic commented
@VoR0220 @chriseth can we finish and merge this?

2016-10-05 18:18 UTC, VoR0220 commented
@axic not yet. We need to get the inputs working properly. The outputs work. Just can't seem to figure out why the inputs won't take.

2016-10-05 18:21 UTC, axic commented
Inputs? Outputs? Are you sure we're talking about the same PR? :)

2016-10-05 19:36 UTC, VoR0220 commented
Yes, we are. So, when checking against the output, this fixed function works, but when trying to send arguments into the function call, this fails. I still don't know why this is.

2016-10-10 19:05 UTC, chriseth commented on test/libsolidity/SolidityExecutionFramework.h
> +		rational value = _value * boost::multiprecision::pow(bigint(2), _fixedBits);
Wouldn't it be useful to also have this function overloaded for `double`? Not sure about rounding errors, though.

2016-10-10 19:05 UTC, chriseth commented
@VoR0220 please explain what is not working in this pull request

2016-10-10 20:48 UTC, VoR0220 commented on test/libsolidity/SolidityExecutionFramework.h
> +		rational value = _value * boost::multiprecision::pow(bigint(2), _fixedBits);
Yeah I don't think that's necessarily the best way to go, unless it was automatically given the ``` << fixed ``` bit...somehow....probably doable.

2016-10-10 20:50 UTC, VoR0220 commented
@chriseth @axic So here is the problem in a nutshell. And it's a simple one. 

This does not work:

```BOOST_CHECK(callContractFunction("f(fixed,fixed)", u256(fixed(1, 3, 128)), u256(fixed(1, 2, 128))) == encodeArgs(fixed(1, 3, 128), fixed(1, 2, 128)));```

But this does:

```BOOST_CHECK(callContractFunction("f()") == encodeArgs(fixed(1, 32, 128)));```

I think that before merging this, the top should be confirmed working. I can't seem to get the top function to pass in the encoded fixed argument. Any and all suggestions are more than welcome.

2016-10-10 21:32 UTC, axic commented
@VoR0220 have you tried a simple one:

`BOOST_CHECK(callContractFunction("f(uint256)", u256(fixed(1, 32, 128)) == encodeArgs(fixed(1, 32, 128)));`

where `function f(uint256 a) returns (uint) { return a; }`?

2016-10-10 22:09 UTC, axic commented on test/libsolidity/SolidityExecutionFramework.h
> +		rational value = _value * boost::multiprecision::pow(bigint(2), _fixedBits);
> ah, that's what you meant. I mean you could...but I think that would look very messy.

Would this work?

``` diff
+       rational value = rational(dev::bigint(_numerator), dev::bigint(_denominator));
+       value *= boost::multiprecision::pow(bigint(2), _fixedBits);
```

2016-10-10 22:18 UTC, VoR0220 commented
@axic no I haven't...but still...shouldn't it be set to the signature of fixed? Am I completely wrong here? I think as a hack this could work, but I really think this should be correct all out....I can try that approach though (and I bet it will work), but still...

2016-10-10 22:19 UTC, axic commented
@VoR0220 I think the point of this PR is not to implement `fixed`, but to add the helper method. I wouldn't be worried if those signatures are not working yet?

2016-10-10 22:20 UTC, VoR0220 commented
I suppose you're right. If @chriseth agrees, lets get this merged up.

2016-10-11 23:06 UTC, axic commented on test/libsolidity/SolidityExecutionFramework.h
> +		rational value = _value * boost::multiprecision::pow(bigint(2), _fixedBits);
@VoR0220 what you think re the above syntax? :)

2016-10-12 15:29 UTC, chriseth commented
@VoR0220 sorry for hijacking this pull request, but I really think we should keep this uniform.

2016-10-13 18:08 UTC, axic commented
I think the make_pair is a horrible syntax C++ has, but since there's nothing better and the overloading matches the rest, it should be better this way.

2016-10-13 18:08 UTC, axic approved these changes

2016-10-13 20:18 UTC, merged