Update libraries.rst
ethereum/solidity pull request #11683
Opened 2021-07-22 10:38 UTC by GuLiPing-Hz

add unchecked

2021-07-23 16:40 UTC, cameel requested changes
Thanks for spotting this! Looks like this example indeed reverts without the `unchecked` block.

You need to update the pragma though - `unchecked` was only added in 0.8.0. CI checks are failing because of this.

2021-07-26 11:08 UTC, hrkrshnn commented
I'll fix the pragma and push.

2021-07-26 11:24 UTC, hrkrshnn approved these changes

2021-07-26 11:24 UTC, hrkrshnn approved these changes

2021-07-26 11:38 UTC, cameel approved these changes

2021-07-26 12:02 UTC, merged