Removed all the generic handlers for things like "...", "std::exception", "util::Exception" or "InternalCompilerError" inside various functions of CommandLineInterface.cpp file and added The top-level handler inside main()
ethereum/solidity pull request #11762
Opened 2021-08-09 09:43 UTC by s0sharma

removed some try/catch and placed the catch inside main();

2021-08-16 16:08 UTC, cameel requested changes, later dismissed
Thanks for the PR!

It still needs some changes. Also, please make sure the code actually compiles. I see that CI is reporting lots of errors.

2021-08-16 16:08 UTC, cameel commented on solc/CommandLineInterface.cpp
> -			}
You can't just remove the `catch` clause and leave the `try` hanging there :) You need to remove it and leave only the code that was inside it.

2021-08-16 16:08 UTC, cameel commented on solc/CommandLineInterface.cpp
> -	catch (smtutil::SMTLogicError const& _exception)
Please leave `SMTLogicError` here. It's not a generic exception type, it should only happen in `compile()`.

2021-08-16 16:08 UTC, cameel commented on solc/main.cpp
> +	catch (InternalCompilerError const& _exception)
This inherits from `boost::exception` so it must be higher. Otherwise the compiler will never enter here.

2021-08-16 16:08 UTC, cameel commented on solc/main.cpp
> +		cerr << "Uncaught exception" << boost::diagnostic_information(_exception) << endl;
There should be some whitespace between the messages:
```suggestion
		cerr << "Uncaught exception: " << boost::diagnostic_information(_exception) << endl;
```
Please run the compiler locally and test that all of these messages are actually printed correctly.

2021-08-16 16:08 UTC, cameel commented on solc/main.cpp
> +	catch (Exception const& _exc)
You need to import this exception type to be able to use it. It's defined in [`libsolutil/Exceptions.h`](https://github.com/ethereum/solidity/blob/develop/libsolutil/Exceptions.h).

Also, it inherits from both `std::exception` and `boost::exception` so it must be above them.

2021-08-16 16:08 UTC, cameel commented on solc/main.cpp
> +		cerr() << "Uncaught exception" << (_e.what() ? ": " + string(_e.what()) : ".") << endl;
I originally did not do this in #10295 but I think that `boost::diagnostic_information` is usable with `std::exception` too. Could you try it?

2021-08-16 16:08 UTC, cameel commented on solc/main.cpp
> +		cerr() << "Uncaught exception" << _exc.what() << endl;
And it's definitely usable with `Exception`.

Also, the whole point of cathing it as a separate type is to use the extra info it stores. It has `lineInfo()` and `comment()`. If `boost::diagnostic_information()` prints that then you don't need this handler at all. If it does not, please print it.

2021-08-17 07:06 UTC, s0sharma commented
I'll make the changes.

2021-08-26 09:14 UTC, hrkrshnn commented
This seems to be stalled. Pinging @s0sharma. Would it be possible for you to make the changes from the review comments? Thanks for the PR.

2021-08-27 12:28 UTC, s0sharma commented
sorry for the delay. I'm busy right now. It may take a couple of days to work on it.

2021-10-04 13:25 UTC, cameel commented
@s0sharma I can take over if you don't have time to finish this. We have a ton of pending PRs right now and we'd like trim that number down a bit :)

2021-10-07 14:51 UTC, cameel commented on solc/CommandLineInterface.cpp
> -	catch (smtutil::SMTLogicError const& _exception)
Looks like it is a generic exception after all (it's thrown by `smtAssert()`).

2021-10-07 14:58 UTC, cameel commented
This is now finished and ready for review.

2021-10-07 15:23 UTC, chriseth approved these changes

2021-10-07 16:17 UTC, cameel commented
#12106 should fix the failing `b_osx`. I'd rebase the PR on it but github will probably close it once the base PR is merged since it's an external PR so I'll just wait for that base PR to be merged instead.

2021-10-07 20:58 UTC, merged