formal: ignore pragmas during Why3 code generation
ethereum/solidity pull request #1181
Opened 2016-10-07 13:35 UTC by pirapira

Fixes #1177

2016-10-07 16:29 UTC, pirapira commented
The `appveyor/branch` failure seems to be a mining timeout.

2016-10-07 19:06 UTC, axic approved these changes

2016-10-10 10:24 UTC, axic commented
Can you add a test for this so it is not forgotten? Or better leave it to #1180?

2016-10-10 19:52 UTC, chriseth requested changes

2016-10-10 19:52 UTC, chriseth commented on libsolidity/formal/Why3Translator.cpp
> +	return false;
Since we might be adding new pragmas in the future which could change the semantics of the language, please only ignore the "version" pragma.

2016-10-10 21:18 UTC, pirapira commented on libsolidity/formal/Why3Translator.cpp
> +	return false;
I changed the code to use the SemVerParser to detect a version.  However, the parse accepts too many strings.  Currently most malformed pragmas are parsed as version pragmas; see #1192.

2016-10-10 21:25 UTC, pirapira commented on libsolidity/formal/Why3Translator.cpp
> +	return false;
@chriseth I have a question.  In the future, can there be a pragma that starts with `pragma solidity` but is not a version pragma?  Or, can I assume that whenever a pragma starts with `pragma solidity` it is a version pragma?

2016-10-10 21:45 UTC, chriseth commented on libsolidity/formal/Why3Translator.cpp
> +	return false;
The idea is that pragma statements are identified by their first identifier, so `pragma solidity` should always be a version pragma.

2016-10-10 21:47 UTC, chriseth requested changes

2016-10-10 21:47 UTC, chriseth commented on libsolidity/ast/AST.h
> +	SemVerMatchExpression parseSemVer() const;
It is quite dangerous to expose this as a public function because the internal use is preceded by some checks against the length of `tokens()`

2016-10-10 21:47 UTC, chriseth commented on test/libsolidity/SolidityEndToEndTest.cpp
> +		dev::keccak256(
Please rebase.

2016-10-10 21:47 UTC, chriseth commented on libsolidity/formal/Why3Translator.cpp
> +	auto semVerMatch = _pragma.parseSemVer();
As per the comments above, it is probably fine to check only the first identifier. You could add a helper function to `PragmaDirective` that returns the first identifier as a string.

2016-10-10 22:11 UTC, pirapira commented on libsolidity/formal/Why3Translator.cpp
> +	auto semVerMatch = _pragma.parseSemVer();
I chose a primitive way.

2016-10-10 22:11 UTC, pirapira commented on test/libsolidity/SolidityEndToEndTest.cpp
> +		dev::keccak256(
Done.

2016-10-10 22:11 UTC, pirapira commented on libsolidity/formal/Why3Translator.cpp
> +	return false;
Thank you.

2016-10-10 22:12 UTC, pirapira commented on libsolidity/ast/AST.h
> +	SemVerMatchExpression parseSemVer() const;
I removed this function.

2016-10-10 22:17 UTC, pirapira commented
@axic adding the test requires another separate "figuring out" process.

2016-10-11 14:29 UTC, chriseth approved these changes

2016-10-11 14:29 UTC, merged