Disallow magic variables in inline assembly
ethereum/solidity pull request #1182
Opened 2016-10-07 23:06 UTC by axic

Fixes #1144.

2016-10-10 15:43 UTC, yann300 commented on test/libsolidity/InlineAssembly.cpp
> +	BOOST_CHECK(successAssemble("{ let ecrecover := 1 ecrecover }"));
I'm not sure but this test should fail no?

2016-10-10 18:29 UTC, axic commented on Changelog.md
> + * Inline assembly: disallow magic variables (`this`, `super`, etc.)
I think this should be reworded. What really happens is that *magic variables* are not given as identifiers to inline assembly and there can be used as local identifiers.

2016-10-10 18:29 UTC, axic commented on test/libsolidity/InlineAssembly.cpp
> +	BOOST_CHECK(successAssemble("{ let ecrecover := 1 ecrecover }"));
Actually no, it is properly. Added a comment to clarify the changelog.

2016-10-10 19:40 UTC, chriseth requested changes

2016-10-10 19:40 UTC, chriseth commented on libsolidity/analysis/TypeChecker.cpp
> +				return false;
Wouldn't the proper fix be to put `else return false;` at the end (and / or call `fatalTypeError()`)?

2016-10-10 19:44 UTC, axic commented on Changelog.md
> + * Inline assembly: disallow magic variables (`this`, `super`, etc.)
Does this sound better: `magic variables (`this`, `super`, etc.) are not visible in inline assembly and they can be used as local variables names` ?

2016-10-10 22:01 UTC, axic commented on libsolidity/analysis/TypeChecker.cpp
> +				return false;
Yeah probably that is simpler :)

2016-10-11 10:45 UTC, chriseth requested changes

2016-10-11 10:45 UTC, chriseth commented on libsolidity/analysis/TypeChecker.cpp
> +			} else
`else` should go on its own line.

2016-10-11 10:45 UTC, chriseth commented on Changelog.md
> +   in inline assembly and they can be used as local variables names
Everything that is not a keyword can be used as local variable names, they just shadow.

I think the actual fix here is that external variables of unsupported types are properly detected.

2016-10-11 10:57 UTC, axic commented on Changelog.md
> +   in inline assembly and they can be used as local variables names
Would you mind writing the text here for the changelog?

2016-10-12 19:04 UTC, axic commented on Changelog.md
> +   in inline assembly and they can be used as local variables names
Added some rewording.

2016-10-12 19:04 UTC, axic commented
@chriseth is this accepted now?

2016-10-13 10:18 UTC, chriseth approved these changes

2016-10-13 10:18 UTC, chriseth commented
@axic @yann please review my changes to the changelog.

2016-10-13 18:07 UTC, axic commented on Changelog.md
> +   are properly detected as unusable.
I think it is useful to mention that they are indeed usable as locals.

2016-10-19 23:00 UTC, merged