Pragma keyword check
ethereum/solidity pull request #1193
Opened 2016-10-10 21:23 UTC by pirapira

This is a one line check that fixes #1192.

2016-10-10 21:43 UTC, chriseth requested changes

2016-10-10 21:43 UTC, chriseth commented on test/libsolidity/SolidityEndToEndTest.cpp
> +		dev::keccak256(
Please rebase.

2016-10-10 21:43 UTC, chriseth commented
The hard science of boolean negation :-)

2016-10-11 10:37 UTC, pirapira commented on test/libsolidity/SolidityEndToEndTest.cpp
> +		dev::keccak256(
Done.

2016-10-11 10:40 UTC, chriseth approved these changes

2016-10-11 13:02 UTC, merged