Bound functions
ethereum/solidity pull request #1194
Opened 2016-10-10 23:06 UTC by axic

Fixes #561.

The reason this is becoming increasingly complex is that when a `FunctionType` is bound, `parameterTypes()`, `parameterNames()`, etc. will skip the first argument without validation.

2016-10-11 10:43 UTC, chriseth requested changes
We should probably talk about this PR personally.

2016-10-11 10:43 UTC, chriseth commented on libsolidity/analysis/TypeChecker.cpp
> +	if (functionType->bound() && !functionType->hasSelfType()) {
Shouldn't that be an internal compiler error?

2016-10-11 10:43 UTC, chriseth commented on libsolidity/ast/Types.h
> +	virtual bool hasSelfType() const { return bound() && m_parameterTypes.size() > 0; }
I think it should not be possible to construct a function type that is bound but does not have a self type.

2016-10-11 11:26 UTC, axic commented on libsolidity/analysis/TypeChecker.cpp
> +	if (functionType->bound() && !functionType->hasSelfType()) {
`b.b()` will first cause `MemberAccess` and then `FunctionCall` visits, if the latter is an ICE then the whole thing is an ICE.

2016-10-13 16:20 UTC, pirapira commented on libsolidity/ast/Types.h
> +	virtual bool hasSelfType() const { return bound() && m_parameterTypes.size() > 0; }
I created #1216 for this.

2016-10-13 16:21 UTC, pirapira commented
To me the changes made sense.

2016-10-14 09:22 UTC, axic commented on libsolidity/ast/Types.h
> +	virtual bool hasSelfType() const { return bound() && m_parameterTypes.size() > 0; }
I think the above code in the typechecker is the place where it should be checked. How can you check during the `using` statement? The contract should be able to have non-bound functions too.

2016-10-14 10:01 UTC, chriseth requested changes

2016-10-14 10:01 UTC, chriseth commented on libsolidity/analysis/TypeChecker.cpp
> +	if (functionType->bound() && !functionType->hasSelfType()) {
I think that the member lookup should fail in the first place, or do I have a example case in mind? Could you add a test case for this?

2016-10-15 15:44 UTC, axic commented
This was updated to refuse creating bound functions without a self type. This feels like the proper fix, with a downside: error reporting is negatively impacted.

2016-10-19 12:44 UTC, chriseth approved these changes

2016-10-19 12:44 UTC, merged