Make evaluation of sting literals more generic
ethereum/solidity pull request #12060
Opened 2021-09-29 20:17 UTC by acoglio

This is based on a discussion on Gitter.

We could add, after the interpreter, an explanation of what the `str`, `dec`, and `hex` decoding functions are. In particular, we could add a reference to the Literals section (https://docs.soliditylang.org/en/latest/yul.html#literals) that explains how `str` works for the EVM dialect (from the previous PR I made). But we can do this in a separate PR.

2021-10-06 15:04 UTC, chriseth requested changes
I think this should add a bit more what the string decoding function is. Also - but I think we already argued about something similar elsewhere - I think it should be "encoding" and not "decoding".

2021-10-09 04:19 UTC, acoglio commented
@chriseth I just added a commit that changes 'decoding' to 'encoding' as you suggested, for all three kinds of literals. I was actually thinking whether 'evaluation' may be a better term than both 'decoding' and 'encoding', i.e. `str` evaluates a string, `hex` evaluates a hexadecimal literal, and `dec` evaluates a decimal literal. What do you think?

(You also mention adding more detail. I agree, but I wanted to finalize the encoding/decoding/evaluation terminology first.)

2021-10-13 15:03 UTC, chriseth commented
Oh I'm so sorry! Now I see why you had "decoding" in the first place. The problem is that for strings, it is kind of both decoding and encoding (decoding: Interpret escape sequences and so on, encoding: left align / pad with zeros)

2021-10-13 18:23 UTC, acoglio commented
No problem! What do you think about my above proposal of using 'evaluation' instead?

2021-11-03 10:26 UTC, leonardoalt commented
ping @chriseth

2021-11-08 12:27 UTC, chriseth commented
I'm sorry, but I'm a bit lost here :)
I think that hex and dec count as "decoding" functions, but the string part is a bit more difficult because we do not really talk about how the source code is actually represented. I think before this can be merged we should expand what the string function actually does somewhere is the documentation and then maybe also briefly mention the other two functions.

2021-11-10 06:28 UTC, acoglio commented
@chriseth I just pushed a commit that adds some explanation of what the `str`, `hex`, and `dec` functions are.

The commit also calls them 'evaluation' functions, which in my opinion is the best term for them because they evaluate pieces of abstract syntax to semantic values. However, I'm happy to change the text if you prefer a different term.

I realize that the description of `str` is not perfect, making reference to a previous section and being only EVM-specific. Nonetheless, perhaps it is better than the current text, which refers to a `utf8EncodeLeftAligned` function.

(I guess that a dialect-independent definition of `str` may need to refer to a type for the literal.)

2021-11-10 09:06 UTC, chriseth commented on docs/yul.rst
> +        which turns a sequence of decimal digits into their little endian value
Why do you say little endian here?

2021-11-10 09:06 UTC, chriseth commented
Looks good apart from the endianness question - can you squash it into a single commit please?

2021-11-11 05:49 UTC, acoglio commented on docs/yul.rst
> +        which turns a sequence of decimal digits into their little endian value
It's a mistake, sorry. Just fixed it.

2021-11-11 05:50 UTC, acoglio commented
> Looks good apart from the endianness question - can you squash it into a single commit please?

That got fixed, and yes, I'll squash.

2021-11-11 07:25 UTC, acoglio commented
I've squashed the commits.

2021-11-11 10:31 UTC, chriseth approved these changes
Thanks a lot and sorry for the long back and forth!

2021-11-11 10:31 UTC, merged

2021-11-11 17:52 UTC, acoglio commented
@chriseth It's all good. We all want good documentation, and that takes time and thought.