LLL: move broken parsing of Ethereum subunits to macros
ethereum/solidity pull request #1228
Opened 2016-10-15 13:50 UTC by axic

Fixes #1197.

This is a breaking change. Current parser zealously will replace all `<number> szabo` occurences (even replacing `1 szabounit` with `1000000000000 unit`).

2016-10-15 13:55 UTC, axic commented on liblll/CompilerState.cpp
> +	"(def 'eth 1000000000000000000)"
Should this be `eth` or `ether`?

It was `ether` in the parser and Solidity uses `ether`.

2016-10-15 13:57 UTC, zigguratt commented on liblll/CompilerState.cpp
> +	"(def 'eth 1000000000000000000)"
I guess to maintain consistency it should be `ether`. Or maybe we could have both.

2016-10-15 14:15 UTC, zigguratt requested changes
Change `eth` to `ether` for consistency with both old LLL usage and current Solidity usage.

2016-10-15 14:51 UTC, zigguratt approved these changes

2016-10-15 14:54 UTC, zigguratt commented
Damn. Meant to approve only one of the commits. Didn't know it was going to approve both at once.

2016-10-17 12:18 UTC, chriseth commented
Please check that this does not break any of the tests in github.com/ethereum/tests

2016-10-17 12:19 UTC, chriseth requested changes
Might change existing tests in https://github.com/ethereum/tests and https://github.com/ethereum/cpp-ethereum - please check.

2016-10-17 12:31 UTC, axic commented
I don't see anywhere LLL is being used in the tests. Do you have any pointers?

2016-10-18 09:50 UTC, chriseth commented
One example: https://github.com/ethereum/cpp-ethereum/blob/develop/test/libevm/VMTestsFiller/vmIOandFlowOperationsTestFiller.json#L148

2016-10-18 19:44 UTC, axic commented
@chriseth thanks. I did a search on the repos for `wei`, `szabo`, `finney`, `ether` without any results.

2016-10-19 08:26 UTC, chriseth approved these changes

2016-10-19 08:26 UTC, merged