Changed the message of the error thrown when the structure has all it's members omitted
ethereum/solidity pull request #12361
Opened 2021-12-02 11:39 UTC by mejsiej

Closes #12302

2021-12-08 18:04 UTC, cameel requested changes, later dismissed

2021-12-08 18:04 UTC, cameel commented on libsolidity/analysis/TypeChecker.cpp
> +				m_errorReporter.typeError(5359_error, _variable.location(), "The structure has all it's members omitted, therefore the getter cannot return any values.");
I think you can assume that there are as many names as there are types:
```suggestion
			solAssert(getter.returnParameterNames().size() == getter.returnParameterTypes().size());
			solAssert(getter.parameterNames().size() == getter.parameterTypes().size());
			if (getter.returnParameterTypes().empty() && getter.parameterTypes().empty())
				m_errorReporter.typeError(5359_error, _variable.location(), "The structure has all it's members omitted, therefore the getter cannot return any values.");
```
Or might be `<=` - not sure if in case like `function f(uint x, uint)` you'll get less names or just `""` as names. Please see if tests will pass with one of these.

2021-12-08 18:04 UTC, cameel commented on libsolidity/analysis/TypeChecker.cpp
> +				m_errorReporter.typeError(5359_error, _variable.location(), "The structure has all it's members omitted, therefore the getter cannot return any values.");
```suggestion
				m_errorReporter.typeError(5359_error, _variable.location(), "The struct has all its members omitted, therefore the getter cannot return any values.");
```

2021-12-08 18:04 UTC, cameel commented on libsolidity/analysis/TypeChecker.cpp
> +				m_errorReporter.typeError(5359_error, _variable.location(), "The structure has all it's members omitted, therefore the getter cannot return any values.");
Adding this message changes the expected output in some syntax tests. Please run `isoltest` with the `--update` option locally and commit the changes.

Also note that the `chk_errorcodes` is failing because it ensures that we have at least one case covering each error. There's no test for the newly added error 5359. Running `isoltest` will probably change that but it seems we only have one test case for such getters and I think we need more to test this properly. Could you add some more cases, covering various situations that can result in such a getter?
- Mapping in the struct.
- Dynamic arrays other than `bytes`/`string` in the struct.
- Multiple fields being omitted (rather than just one).
- Struct containing a struct that has all its fields omitted (see https://github.com/ethereum/solidity/issues/11826#issuecomment-902835510).
    ```solidity
    struct T { mapping(uint => uint) m; }
    struct S { T t; }
    ```
    or
    ```solidity
    struct U { mapping(uint => uint) m; }
    struct T { U u; }
    struct S { T t; }
    ```
- A struct that contains two fields: one that won't be omitted (e.g. `uint`) and another that is also a struct and would have all of its members omitted.
    ```solidity
    struct U { mapping(uint => uint) m; }
    struct T { U u; }
    struct S { uint i; T t; }
    ```
- Nested dynamic array. Surprisingly, this does not fail. Apparently the rule for dynamic arrays is not recursive.
    ```solidity
    struct T { uint[] u; }
    struct S { T t; }
    ```

2021-12-08 18:17 UTC, mejsiej commented on libsolidity/analysis/TypeChecker.cpp
> +				m_errorReporter.typeError(5359_error, _variable.location(), "The structure has all it's members omitted, therefore the getter cannot return any values.");
Yeah, I can try.

2021-12-20 17:18 UTC, chriseth approved these changes
Looks good now, thanks a lot!

2021-12-20 20:06 UTC, merged