ast: super contract type does not contain native members
ethereum/solidity pull request #1240
Opened 2016-10-17 17:48 UTC by pirapira

When members are sought for a contract whose type is super, the result should not contain the members of the derived contract.

Fixes #1151

2016-10-17 18:26 UTC, pirapira commented
Now I think it's better to change `nativeMembers`

2016-10-18 10:18 UTC, chriseth requested changes

2016-10-18 10:18 UTC, chriseth commented on libsolidity/ast/Types.cpp
> +			if (base == _current)
Please change this to start from index 1 and also add a test for this fix.

2016-10-18 13:08 UTC, pirapira commented
@chriseth I've accommodated your review comments.

2016-10-19 12:24 UTC, chriseth requested changes

2016-10-19 12:24 UTC, chriseth commented on libsolidity/ast/Types.cpp
> +			BOOST_THROW_EXCEPTION(
Perhaps easier to do `solAssert(bases.size() > 1, "linearized...");`

2016-10-19 12:24 UTC, chriseth commented on libsolidity/ast/Types.cpp
> +		bases.erase(bases.begin()); // Remove the most derived contract, which should not be searchable from `super`.
What about the following:
```
#include <boost/range/adaptor/sliced.hpp>;
...
for (ContractDefinition const* base: bases | sliced(1, bases.size()))
```

2016-10-20 09:11 UTC, pirapira commented on libsolidity/ast/Types.cpp
> +			BOOST_THROW_EXCEPTION(
I will do something similar.

2016-10-20 09:23 UTC, pirapira commented on libsolidity/ast/Types.cpp
> +		bases.erase(bases.begin()); // Remove the most derived contract, which should not be searchable from `super`.
This is cheaper computationally.  So I choose this one.

2016-10-20 09:24 UTC, pirapira commented
@chriseth I've accommodated all your change requests.

2016-10-20 11:24 UTC, chriseth commented
Please add an entry to the changelog.

2016-10-20 14:13 UTC, pirapira commented
@chriseth done.

2016-10-24 09:45 UTC, merged