`super`'s size on stack is zero
ethereum/solidity pull request #1244
Opened 2016-10-18 12:23 UTC by pirapira

because the expression compiler does not push anything onto stack when it sees `super`.

2016-10-18 13:52 UTC, chriseth requested changes
Please add an entry into the changelog.

2016-10-18 13:57 UTC, pirapira commented
I added a point in `Changelog.md`

2016-10-18 19:33 UTC, axic commented
If we have NameAndTypeResolution and EndToEnd tests in the other PRs, perhaps useful to add here both?

2016-10-19 08:33 UTC, chriseth approved these changes

2016-10-19 08:33 UTC, chriseth commented
@axic this was not a bug in the type checker, only in the code generator.

2016-10-19 08:33 UTC, merged