Note about storage compatability mode
ethereum/solidity pull request #12638
Opened 2022-02-07 03:56 UTC by fulldecent

For #12547

2022-02-08 12:23 UTC, cameel requested changes

2022-02-08 12:23 UTC, cameel commented on docs/internals/layout_in_storage.rst
> +     compatability mode which supports these the existing rules here.
```suggestion
     compatibility mode which supports the existing rules here.
```

2022-02-08 12:29 UTC, cameel submitted a review, later dismissed

2022-02-08 12:29 UTC, cameel commented on docs/internals/layout_in_storage.rst
> +     compatability mode which supports these the existing rules here.
I would also reword this a bit:
```suggestion
     compatibility mode in which the compiler would generate bytecode supporting the old layout.
```

2022-02-08 17:23 UTC, chriseth commented
Sounds good! Can you squash the two commits, please?

2022-02-10 02:32 UTC, fulldecent commented
@chriseth squashed 🍞🥩🧀🥬➡️🍔

2022-02-10 09:20 UTC, chriseth approved these changes

2022-02-10 09:20 UTC, merged

2022-02-10 09:20 UTC, chriseth commented
Thanks!