[WIP] State variable under contract's name
ethereum/solidity pull request #1264
Opened 2016-10-21 10:23 UTC by pirapira

An attempt at #988.  I'm opening a pull-request just to see test results.

2016-10-21 18:25 UTC, pirapira commented
message for @pirapira next Monday: I still need to add more end-to-end tests from the comments in #988.

2016-10-21 18:27 UTC, pirapira commented
message for @pirapira monday: also add tests that use libraries.

2016-10-24 16:09 UTC, chriseth requested changes

2016-10-24 16:09 UTC, chriseth commented on test/libsolidity/SolidityEndToEndTest.cpp
> +				return A.x;
Can you please add a second function that returns `B.x`? And also a function that does `B.x = 10` and another `A.x=12`?

2016-10-24 18:16 UTC, pirapira commented
@chriseth this one is ready.

2016-10-25 10:48 UTC, chriseth commented on libsolidity/analysis/TypeChecker.cpp
> +	else if (TypeType const* typeType = dynamic_cast<decltype(typeType)>(exprType.get()))
oh wow, learned something new :-)

2016-10-25 10:50 UTC, chriseth approved these changes

2016-10-25 10:50 UTC, merged