fix: corrects _ prefixes
ethereum/solidity pull request #12680
Opened 2022-02-16 03:52 UTC by devtooligan

This pr aims to remove the use of the `_` prefix used in variable, parameter, and function names throughout the code examples used in the docs.
 
The style guide currently does not endorse or suggest the use of the prefix `_` and for the most part, this convention is not used in the examples provided.

There are 3 main situations the prefix `_` is currently found in examples in the docs:
1) Used in function parameters for no clear reason.  While this is a practice used by some in the wild, we should not appear to endorse this convention and more importantly we should be consistent throughout our examples where the vast majority do not do this.
2) Used when shadowing an existing variable or function name.  The style guide currently states the `_` suffix should be used when the name collides with a reserved word and[ there is a proposal to expand this definition](https://github.com/ethereum/solidity/pull/12679) to include collisions with function and state variable names.  In these cases, the pr changes the variable name from a `_`prefix to a suffix`_`
3) There is [one example](https://github.com/ethereum/solidity/blame/v0.8.11/docs/types/mapping-types.rst#L76) of the `_` prefix being used with a private function name.  Because there is ongoing discussion about adding this convention to the style guide, this pr currently does not attempt to correct this.

2022-02-16 04:50 UTC, fulldecent requested changes
Please factor out this change:

> This convention is suggested when the desired name collides with that of an existing state variable, function, built-in or otherwise reserved name.

That is out of scope of the PR.

2022-02-16 05:03 UTC, fulldecent commented
I reviewed by doing this search:

> `\b_[a-z]`

And it seems this PR is good. And if the following are also updated then it is 100% good to merge:

```diff
diff --git a/docs/common-patterns.rst b/docs/common-patterns.rst
index da96478f3..1793ebd2f 100644
--- a/docs/common-patterns.rst
+++ b/docs/common-patterns.rst
@@ -163,9 +163,9 @@ restrictions highly readable.
         // prepend a check that only passes
         // if the function is called from
         // a certain address.
-        modifier onlyBy(address _account)
+        modifier onlyBy(address account)
         {
-            if (msg.sender != _account)
+            if (msg.sender != account)
                 revert Unauthorized();
             // Do not forget the "_;"! It will
             // be replaced by the actual function
@@ -182,8 +182,8 @@ restrictions highly readable.
             owner = newOwner;
         }
 
-        modifier onlyAfter(uint _time) {
-            if (block.timestamp < _time)
+        modifier onlyAfter(uint time) {
+            if (block.timestamp < time)
                 revert TooEarly();
             _;
         }
@@ -205,13 +205,13 @@ restrictions highly readable.
         // refunded, but only after the function body.
         // This was dangerous before Solidity version 0.4.0,
         // where it was possible to skip the part after `_;`.
-        modifier costs(uint _amount) {
-            if (msg.value < _amount)
+        modifier costs(uint amount) {
+            if (msg.value < amount)
                 revert NotEnoughEther();
 
             _;
-            if (msg.value > _amount)
-                payable(msg.sender).transfer(msg.value - _amount);
+            if (msg.value > amount)
+                payable(msg.sender).transfer(msg.value - amount);
         }
 
         function forceOwnerChange(address newOwner)
diff --git a/docs/contracts/constant-state-variables.rst b/docs/contracts/constant-state-variables.rst
index b62b0bffc..0cabae7cb 100644
--- a/docs/contracts/constant-state-variables.rst
+++ b/docs/contracts/constant-state-variables.rst
@@ -47,8 +47,8 @@ Not all types for constants and immutables are implemented at this time. The onl
             maxBalance = reference.balance;
         }
 
-        function isBalanceTooHigh(address _other) public view returns (bool) {
-            return _other.balance > maxBalance;
+        function isBalanceTooHigh(address other) public view returns (bool) {
+            return other.balance > maxBalance;
         }
     }
 
diff --git a/docs/contracts/function-modifiers.rst b/docs/contracts/function-modifiers.rst
index 0d4c8e8c2..2445895e4 100644
--- a/docs/contracts/function-modifiers.rst
+++ b/docs/contracts/function-modifiers.rst
@@ -72,8 +72,8 @@ if they are marked ``virtual``. For details, please see
             registeredAddresses[msg.sender] = true;
         }
 
-        function changePrice(uint _price) public onlyOwner {
-            price = _price;
+        function changePrice(uint price_) public onlyOwner {
+            price = price_;
         }
     }
 
diff --git a/docs/contracts/functions.rst b/docs/contracts/functions.rst
index b7f8a9cc2..35a8a5370 100644
--- a/docs/contracts/functions.rst
+++ b/docs/contracts/functions.rst
@@ -362,7 +362,7 @@ Fallback Function
 -----------------
 
 A contract can have at most one ``fallback`` function, declared using either ``fallback () external [payable]``
-or ``fallback (bytes calldata input) external [payable] returns (bytes memory _output)``
+or ``fallback (bytes calldata input) external [payable] returns (bytes memory output)``
 (both without the ``function`` keyword).
 This function must have ``external`` visibility. A fallback function can be virtual, can override
 and can have modifiers.
@@ -374,7 +374,7 @@ The fallback function always receives data, but in order to also receive Ether
 it must be marked ``payable``.
 
 If the version with parameters is used, ``input`` will contain the full data sent to the contract
-(equal to ``msg.data``) and can return data in ``_output``. The returned data will not be
+(equal to ``msg.data``) and can return data in ``output``. The returned data will not be
 ABI-encoded. Instead it will be returned without modifications (not even padding).
 
 In the worst case, if a payable fallback function is also used in
diff --git a/docs/introduction-to-smart-contracts.rst b/docs/introduction-to-smart-contracts.rst
index fa2fa34c1..25200a677 100644
--- a/docs/introduction-to-smart-contracts.rst
+++ b/docs/introduction-to-smart-contracts.rst
@@ -168,8 +168,8 @@ following:
 
 .. code-block:: solidity
 
-    function balances(address _account) external view returns (uint) {
-        return balances[_account];
+    function balances(address account) external view returns (uint) {
+        return balances[account];
     }
 
 You can use this function to query the balance of a single account.
diff --git a/docs/types/mapping-types.rst b/docs/types/mapping-types.rst
index 18f3bf827..69fc83ad5 100644
--- a/docs/types/mapping-types.rst
+++ b/docs/types/mapping-types.rst
@@ -4,12 +4,12 @@
 Mapping Types
 =============
 
-Mapping types use the syntax ``mapping(_KeyType => _ValueType)`` and variables
-of mapping type are declared using the syntax ``mapping(_KeyType => _ValueType) _VariableName``.
-The ``_KeyType`` can be any
+Mapping types use the syntax ``mapping(KeyType => ValueType)`` and variables
+of mapping type are declared using the syntax ``mapping(KeyType => ValueType) variableName``.
+The ``KeyType`` can be any
 built-in value type, ``bytes``, ``string``, or any contract or enum type. Other user-defined
 or complex types, such as mappings, structs or array types are not allowed.
-``_ValueType`` can be any type, including mappings, arrays and structs.
+``ValueType`` can be any type, including mappings, arrays and structs.
 
 You can think of mappings as `hash tables <https://en.wikipedia.org/wiki/Hash_table>`_, which are virtually initialised
 such that every possible key exists and is mapped to a value whose
@@ -29,10 +29,10 @@ of contract functions that are publicly visible.
 These restrictions are also true for arrays and structs that contain mappings.
 
 You can mark state variables of mapping type as ``public`` and Solidity creates a
-:ref:`getter <visibility-and-getters>` for you. The ``_KeyType`` becomes a parameter for the getter.
-If ``_ValueType`` is a value type or a struct, the getter returns ``_ValueType``.
-If ``_ValueType`` is an array or a mapping, the getter has one parameter for
-each ``_KeyType``, recursively.
+:ref:`getter <visibility-and-getters>` for you. The ``KeyType`` becomes a parameter for the getter.
+If ``ValueType`` is a value type or a struct, the getter returns ``ValueType``.
+If ``ValueType`` is an array or a mapping, the getter has one parameter for
+each ``KeyType``, recursively.
 
 In the example below, the ``MappingExample`` contract defines a public ``balances``
 mapping, with the key type an ``address``, and a value type a ``uint``, mapping
```

2022-02-16 05:14 UTC, devtooligan commented
@fulldecent 
Good catch!  And thanks for sharing how you found those, I hadn't used regex in a pr before

Requested changes sbgtg

2022-02-16 05:24 UTC, fulldecent approved these changes, later dismissed
I have reviewed code visually and:

- It is in-scope for our style guide.
- The change in uncontroversial—it implements an existing best practice we have documented and where there has been no demonstrated contention about.
- The issue it addresses is done consistently across the repo.
- The issue is addresses is done exhaustively across the repo.

Recommending to merge as-is.

2022-02-16 05:26 UTC, fulldecent commented
Now that this is ready to merge (from my opinion), please squash and rebase.

2022-02-16 09:49 UTC, leonardoalt commented
Thanks again @devtooligan !
It looks like also here some of the changed code won't compile:
```
Error: This declaration shadows a declaration outside the inline assembly block.
Note: The shadowed declaration is here
```

2022-02-16 14:48 UTC, fulldecent commented
Fix:

```diff
diff --git a/docs/assembly.rst b/docs/assembly.rst
--- docs/assembly.rst
+++ docs/assembly.rst
@@ -101,17 +101,17 @@
                 // Keep temporary variable so it can be incremented in place.
                 //
                 // NOTE: incrementing data would result in an unusable
                 //       data variable after this assembly block
-                let data := add(data, 0x20)
+                let dataElementLocation := add(data, 0x20)
 
                 // Iterate until the bound is not met.
                 for
-                    { let end := add(data, mul(len, 0x20)) }
-                    lt(data, end)
-                    { data := add(data, 0x20) }
+                    { let end := add(dataElementLocation, mul(len, 0x20)) }
+                    lt(dataElementLocation, end)
+                    { data := add(dataElementLocation, 0x20) }
                 {
-                    sum := add(sum, mload(data))
+                    sum := add(sum, mload(dataElementLocation))
                 }
             }
         }
     }
```

2022-02-23 05:03 UTC, dtedesco1 approved these changes, later dismissed
Reviewed visually.

2022-03-02 03:32 UTC, fulldecent requested changes
Fix build error

2022-03-02 03:33 UTC, fulldecent commented
Fixes build error:

```diff
diff --git a/docs/contracts/libraries.rst b/docs/contracts/libraries.rst
--- docs/contracts/libraries.rst
+++ docs/contracts/libraries.rst
@@ -149,14 +149,14 @@
         function add(bigint memory a, bigint memory b) internal pure returns (bigint memory r) {
             r.limbs = new uint[](max(a.limbs.length, b.limbs.length));
             uint carry = 0;
             for (uint i = 0; i < r.limbs.length; ++i) {
-                uint a = limb(a, i);
-                uint b = limb(b, i);
+                uint limbA = limb(a, i);
+                uint limbB = limb(b, i);
                 unchecked {
-                    r.limbs[i] = a + b + carry;
+                    r.limbs[i] = limbA + limbB + carry;
 
-                    if (a + b < a || (a + b == type(uint).max && carry > 0))
+                    if (limbA + limbB < limbA || (limbA + limbB == type(uint).max && carry > 0))
                         carry = 1;
                     else
                         carry = 0;
                 }
```

2022-03-02 05:22 UTC, fulldecent requested changes

2022-03-02 05:22 UTC, fulldecent commented on docs/contracts/using-for.rst
> +        function replace(uint old, uint new) public {
"new" is a reserved word as per https://docs.soliditylang.org/en/v0.8.12/cheatsheet.html?highlight=reserved#reserved-keywords

---

Maybe replace(from, to) ?

2022-03-08 23:37 UTC, fulldecent commented on docs/contracts/using-for.rst
> +        function replace(uint old, uint new) public {
@devtooligan ^ ping

2022-03-13 06:06 UTC, devtooligan commented
@fulldecent Finally got a passing build here!  Sorry for the delay and thx for your help

2022-03-14 02:45 UTC, fulldecent approved these changes, later dismissed

2022-03-14 02:45 UTC, fulldecent commented
Looks great, thank you!

2022-03-14 10:55 UTC, chriseth commented on docs/security-considerations.rst
> +`iterable mapping <https://github.com/ethereum/dapp-bin/blob/master/library/iterablemapping.sol>`_,
```suggestion
`iterable mapping <https://github.com/ethereum/dapp-bin/blob/master/library/iterable_mapping.sol>`_,
```

2022-03-14 10:56 UTC, chriseth commented on docs/types/mapping-types.rst
> +of mapping type are declared using the syntax ``mapping(KeyType => ValueType) _VariableName``.
Why not `VariableName`?

2022-03-14 15:02 UTC, devtooligan commented on docs/types/mapping-types.rst
> +of mapping type are declared using the syntax ``mapping(KeyType => ValueType) _VariableName``.
good catch!

2022-03-14 15:04 UTC, devtooligan commented on docs/security-considerations.rst
> +`iterable mapping <https://github.com/ethereum/dapp-bin/blob/master/library/iterablemapping.sol>`_,
✅

2022-03-14 15:42 UTC, devtooligan commented
@chriseth thanks for catching those. sb gtg

2022-03-14 18:34 UTC, chriseth commented
@fulldecent what is the policy for merging now?

2022-03-14 19:11 UTC, fulldecent approved these changes

2022-03-14 19:11 UTC, fulldecent commented
@chriseth Please help to merge anything I mark approved

2022-03-14 21:58 UTC, ekpyron approved these changes
Approving based on @fulldecent's approval.

2022-03-14 21:58 UTC, merged