updates to gas section
ethereum/solidity pull request #12751
Opened 2022-03-07 13:31 UTC by andreb0x

small modifications for clarity

2022-03-07 15:43 UTC, chriseth commented on docs/introduction-to-smart-contracts.rst
> +The **gas price** is a value set by the creator of the transaction (see `msg.sender), who
```suggestion
The **gas price** is a value set by the creator of the transaction (see `tx.origin`), who
```

2022-03-07 15:43 UTC, chriseth commented on docs/introduction-to-smart-contracts.rst
> +If some gas is left after execution, it is refunded to the transaction originator.
I think we should stick to one term: creator or originator

2022-03-07 15:44 UTC, chriseth commented on docs/introduction-to-smart-contracts.rst
> +Imposing a cost on operations that write to the blockchain serves to secure the network:
Most of this is a good change, but I'm worried about "write" being misleading, as it is also not free to merely read data e.g. from storage, as long as it is part of a transaction.

2022-03-07 15:45 UTC, chriseth commented on docs/introduction-to-smart-contracts.rst
>  the code at the target address is executed in the context of the calling
I think the most important aspect of "context" here is `address`. If you split up the sentence here this sounds like you are explaining what "context" means.

2022-03-07 15:48 UTC, chriseth commented on docs/introduction-to-smart-contracts.rst
> +For example, say Alice calls a method in contract A to modify
I think this example could be a bit misleading and you are making a lot of assumptions that are not explicitly stated. Does `B.foo` have the same source code as `A.foo`? Why do you say "according to A.foo"? Does Alice call `A.foo` or some other method?

2022-03-07 15:50 UTC, andreb0x commented on docs/introduction-to-smart-contracts.rst
> +The **gas price** is a value set by the creator of the transaction (see `msg.sender), who
thank you

2022-03-07 15:51 UTC, andreb0x commented on docs/introduction-to-smart-contracts.rst
> +If some gas is left after execution, it is refunded to the transaction originator.
agree. I went with originator because it stays closer to the `tx.origin` semantics

2022-03-07 15:54 UTC, andreb0x commented on docs/introduction-to-smart-contracts.rst
> +For example, say Alice calls a method in contract A to modify
I agree. I think we should revert his example for now.

2022-03-07 15:56 UTC, andreb0x commented on docs/introduction-to-smart-contracts.rst
> +Imposing a cost on operations that write to the blockchain serves to secure the network:
good point. thank you for exposing my misunderstanding. maybe

2022-03-07 15:58 UTC, andreb0x commented on docs/introduction-to-smart-contracts.rst
> +Imposing a cost on operations that write to the blockchain serves to secure the network:
made new commit switching back to "transactions"

2022-03-10 15:12 UTC, nishant-sachdeva requested changes
To resolve the coding style error on the CI

On your local systems, run the command 
`./scripts/check_style.sh` 

It will list out all the changes that need to be made to fix the coding style errors. Once resolved, you can push changes for further reviews

2022-04-04 10:09 UTC, leonardoalt commented
This PR seems stale. Does anyone want to take over? Or we can close it

2022-04-05 09:47 UTC, ekpyron commented on docs/introduction-to-smart-contracts.rst
> +The **gas price** is a value set by the creator of the transaction (see `msg.sender), who
```suggestion
The **gas price** is a value set by the creator of the transaction (see `msg.sender`), who
```

2022-04-05 09:50 UTC, ekpyron commented on docs/introduction-to-smart-contracts.rst
> +The **gas price** is a value set by the creator of the transaction (see `msg.sender), who
Also "see" kind of implies a link... maybe rather ``i.e.`` instead of ``see``?

2022-04-05 09:51 UTC, ekpyron commented on docs/introduction-to-smart-contracts.rst
> +The **gas price** is a value set by the creator of the transaction (see `msg.sender), who
Also https://github.com/ethereum/solidity/pull/12751/files#r820833741 is still not really addressed - if we want to keep it at "orginator" below, we should probably also say ``set by the originator of the transaction`` here instead.

2022-04-05 10:16 UTC, nishant-sachdeva commented on docs/introduction-to-smart-contracts.rst
> +For example, say Alice calls a method in contract A to modify
Removing this example in the latest push.

2022-04-06 09:39 UTC, ekpyron commented on docs/introduction-to-smart-contracts.rst
> +The **gas price** is a value set by the originator of the transaction i.e. `tx.origin`, who
```suggestion
The **gas price** is a value set by the originator of the transaction, i.e. `tx.origin`, who
```

2022-04-06 09:42 UTC, ekpyron commented on docs/introduction-to-smart-contracts.rst
> +In practice this means ``msg.sender`` and ``msg.value`` retain the values that were passed to the delegator,
It sounds a bit off to talk about ``msg.sender`` and ``msg.value`` being "passed to the delegator".
I'm not sure splitting this sentence really has that much merit in general.

2022-04-06 10:17 UTC, ekpyron submitted a review, later dismissed

2022-04-07 07:23 UTC, ekpyron approved these changes

2022-04-07 07:30 UTC, nishant-sachdeva approved these changes

2022-04-07 07:32 UTC, merged

2022-10-19 12:38 UTC, Sticknmove commented
Thanks

2022-10-19 12:39 UTC, Sticknmove commented
Thanks

2022-10-19 12:47 UTC, Sticknmove reviewed
Thanks

2022-10-19 12:47 UTC, Sticknmove reviewed
Thanks