Update control-structures.rst
ethereum/solidity pull request #12855
Opened 2022-03-24 19:50 UTC by aathan

As discussed

2022-07-11 11:20 UTC, Marenz requested changes, later dismissed

2022-07-11 11:20 UTC, Marenz commented on docs/control-structures.rst
> +Function calls that name parameters
```suggestion
Function calls with named parameters
```

2022-07-11 11:20 UTC, Marenz commented on docs/control-structures.rst
> +can still return a value to the caller by use of the ``return`` statement.
```suggestion
The names of parameters and return values in the function declaration can be omitted.
Those with omitted names will still be present on the stack, but they are
inaccessible by name. 
An omitted return value name can still return a value to the caller by use of the ``return`` statement.
```

I felt it was adding details that weren't really adding more value

2022-08-13 12:12 UTC, leonardoalt approved these changes

2022-08-15 13:53 UTC, leonardoalt approved these changes

2022-08-15 13:53 UTC, merged