Clarify leading relative path segments in import paths
ethereum/solidity pull request #12879
Opened 2022-03-30 21:25 UTC by aathan

Note: The "Preview" tab on github did *NOT* show the .. code:: block around line ~290 even before my changes. Not sure what's up with that. The rst seems correct, and it displays properly  at ``https://docs.soliditylang.org/en/latest/path-resolution.html#import-callback``

Also, I inferred the rule for ``.`` in the leading part of the import path based on the description that the import path itself is first normalized. My edit may therefore be incorrect if ``..`` segments in the leading part of the import path behave the same way as they do in the instant rule (e.g. if ``././../foo.bar`` in the import path means ``./foo.bar``). Doubtful.

Also note, the "normalization" of the import path is not exactly the normalization referred to in the CLI path normalization, since it remains relative. Probably ok not to mention explicitly.

2022-08-13 12:06 UTC, leonardoalt commented on docs/path-resolution.rst
> +      import path.
```suggestion
      Every ``.`` segment found in this part of the import path is removed.
```

2022-08-13 12:07 UTC, leonardoalt commented on docs/path-resolution.rst
> +      preceding slashes is removed from the prefix, and the corresponding element in the import path
```suggestion
      preceding slashes is removed from the prefix.
```

2022-08-13 12:08 UTC, leonardoalt commented
@cameel wanna take a quick look on the added `note`?

2022-09-27 13:03 UTC, cameel requested changes
Sorry, but I don't think that the proposed changes really add much to the page.

In any case, they would need some corrections first.

2022-09-27 13:03 UTC, cameel commented on docs/path-resolution.rst
> +    c) Then, the leading part of the normalized import path, consisting only of ``/`` and ``.``
I don't think this is a valid list in RST. You can use `#.` for ordered lists though:
```suggestion
    #. Prefix is initialized with the source unit name of the importing source unit.
    #. The last path segment with preceding slashes is removed from the prefix.
    #. Then, the leading part of the normalized import path, consisting only of ``/`` and ``.``
```

2022-09-27 13:03 UTC, cameel commented on docs/path-resolution.rst
> +      import path.
~I thought it was obvious. If we want to be pedantic here, we should also say that the slashes following the segment are removed too.~

2022-09-27 13:03 UTC, cameel commented on docs/path-resolution.rst
> +      preceding slashes is removed from the prefix, and the corresponding element in the import path
The sentence seems cut off but if we really want to add the sentence about `.`, it does make sense to say that about `..` too:

```suggestion
      preceding slashes is removed from the prefix, and the corresponding element in the import path with any slashes following it is removed as well.
```

2022-09-27 13:03 UTC, cameel commented on docs/path-resolution.rst
> +   ``a/b/../../bar.sol`` evaluates to ``bar.sol`` when normalized as a full path without this rule.
The examples above already show this case and more.

The initial draft of this page went into detail about this and other unintuitive cases but we intentionally tuned that down not to distract from the main point. I don't think it's a good idea to go back to that version.

2022-09-27 13:55 UTC, cameel commented on docs/path-resolution.rst
> +      import path.
Wait, no, this was actually omitted because it's implied by the import path being normalized.

2022-09-27 14:02 UTC, cameel commented
> Also note, the "normalization" of the import path is not exactly the normalization referred to in the CLI path normalization, since it remains relative. Probably ok not to mention explicitly.

It's not the CLI normalization. The normalization is explicitly defined later in the same section:
>> The normalization rules are the same as for UNIX paths, namely:
>> - All the internal ``.`` segments are removed.
>> - Every internal ``..`` segment backtracks one level up in the hierarchy.
>> - Multiple slashes are squashed into a single one.

> Also, I inferred the rule for ``.`` in the leading part of the import path based on the description that the import path itself is first normalized. My edit may therefore be incorrect if ``..`` segments in the leading part of the import path behave the same way as they do in the instant rule (e.g. if ``././../foo.bar`` in the import path means ``./foo.bar``). Doubtful.

Yes, the rule for `.` is implied by the fact that the import path is normalized. It's just that normalization can still leave leading `..` segments in the path. E.g. `.././../a//b/..//c/./d.sol` would be normalized to `../../a/c/d.sol` according to the rules stated in that section.

I think this whole confusion comes from the fact that the description does not explicitly say to remove these leading `..` segments from the import path before joining it with the prefix. I guess we can consider that a documentation bug.

Still, I don't think this PR is the best way to reword it. I have submitted my own, which fixes that and simplifies the whole description: #13572.

2022-10-04 15:31 UTC, closed without merging