Use rational number type as it is for computing the type of an inline array
ethereum/solidity pull request #1293
Opened 2016-10-26 13:27 UTC by pirapira

Before this pull-request, type checking on `[int8(1), 0]` failed because the mobile type of `0` is `uint8`, which is incompatible with `int8`.  There are no integer types that are compatible both with `uint8` and `int8`.  So I chose not to compute the mobile type of a rational number type here.

This fixes #621.

2016-11-09 01:54 UTC, axic commented
Can you add a changelog entry?

2016-11-09 11:04 UTC, pirapira commented
@axic Yes, I added one.

2016-11-09 13:41 UTC, chriseth requested changes

2016-11-09 13:41 UTC, chriseth commented on Changelog.md
> + * Type checker: now more eagerly searches for a commont type of tuple elements of mixed types
Typo: `common type` - also I would argue this is a feature.

2016-11-09 13:47 UTC, pirapira commented on Changelog.md
> + * Type checker: now more eagerly searches for a commont type of tuple elements of mixed types
OK, though it's a partial bug fix to me.  The common type should be even more generous.

2016-11-09 14:02 UTC, chriseth commented on Changelog.md
> + * Type checker: now more eagerly searches for a common type of tuple elements of mixed types
I'm sorry to bug again, but actually this is not about tuples but about inline arrays.

2016-11-09 14:13 UTC, pirapira commented on Changelog.md
> + * Type checker: now more eagerly searches for a common type of tuple elements of mixed types
Ah, OK, a tuple should be able to contain elements of different types.

2016-11-09 17:39 UTC, pirapira commented on Changelog.md
> + * Type checker: now more eagerly searches for a common type of tuple elements of mixed types
I've changed the changelog.

2016-11-11 14:44 UTC, chriseth approved these changes

2016-11-11 14:45 UTC, chriseth commented
@pirapira can you please rebase and merge?

2016-11-11 14:52 UTC, pirapira commented
Rebased.  Waiting for the test.

2016-11-11 15:18 UTC, merged