LLL: further improve error reporting
ethereum/solidity pull request #1298
Opened 2016-10-27 01:08 UTC by axic

2016-10-27 14:20 UTC, chriseth requested changes

2016-10-27 14:20 UTC, chriseth commented on liblll/CodeFragment.h
> +	template <class T> void error(std::string reason) const {
`const&`?

2016-10-27 14:20 UTC, chriseth commented on liblll/Parser.cpp
> +	try {
Brace to the next line.

2016-10-27 14:20 UTC, chriseth commented on liblll/Parser.cpp
> +	catch(const qi::expectation_failure<it>& e)
Space after `catch` and `const` should be right before `&`

2016-11-01 10:49 UTC, axic commented
@chriseth changes are done.

2016-11-01 10:58 UTC, chriseth approved these changes

2016-11-01 10:59 UTC, merged