Update solidity-by-example.rst
ethereum/solidity pull request #1323
Opened 2016-11-03 07:32 UTC by varunagarwal315

Might be trivial, but makes more sense to be able to directly return the name of the winner for the election. If the position of the winner on the proposal[] array is returned, then people still don't know the name of the person who won.

2016-11-03 12:01 UTC, pirapira requested changes
I think the new function can call `winningProposal()`, and then the code is much simpler.  Currently in this PR `winningProposal()` and `winnerName()` contain largely duplicate code.

2016-11-03 12:13 UTC, varunagarwal315 commented
Removed all the duplicate code as suggested and simply called the winningProposal() function. Added some comments to help explain the function to new users. Thanks pirapira for the suggestions

2016-11-03 16:48 UTC, pirapira commented on docs/solidity-by-example.rst
> +        //returns the name of the winner
Just for uniformity, will you add a space between `//` and the following text?

2016-11-03 16:57 UTC, pirapira commented
Thank you!  Let me compile it...

2016-11-03 17:04 UTC, pirapira approved these changes

2016-11-03 17:07 UTC, pirapira commented
@chriseth is there a particular reason why we do not allow returning structs?  Or shall I create an issue about that?

2016-11-03 17:12 UTC, VoR0220 commented
@pirapira there is an issue for this, but basically the capability currently does not exist due to the ABI needing to be defined for structs.

2016-11-04 09:06 UTC, varunagarwal315 commented
@pirapira Are there any further changes to be made by me before this can be merged? Or is the change too trivial for a merge with dev branch.

Thanks

2016-11-04 09:54 UTC, pirapira commented
@varunagarwal315 no, no, this was just a pause to hear people.

2016-11-04 09:55 UTC, merged