Create placeholders.rst
ethereum/solidity pull request #13239
Opened 2022-07-03 14:49 UTC by 0xUlquiorra

### Placeholder Documentation

**Why you made your change**

_When I recently read the Solidity docs, I felt that there wasn't enough information on placeholders used within modifiers._

This question has been [asked before](https://ethereum.stackexchange.com/questions/19171/what-does-underscore-do).

**What you did**

I wrote up a quick blurb on what the underscore (placeholder) operator does, with additional mentions that it is unrelated to _prefix or suffix_ uses of underscores. 

I also included a code example of a common _mutex_ modifier.

_Disclaimer: I am not experienced with .rst files, so if I have made a referencing mistake please let me know and I will fix it._

Thanks!

2022-07-03 16:13 UTC, 0xUlquiorra commented
CircleCI thinks I'm writing C++. 

Let me know what I need to do and I'll do it.

2022-07-04 15:02 UTC, cameel requested changes
Thanks for the PR! Here's some feedback.

I'm not sure if this is a good fit for the docs though and it's a bit repetitive. I think that it would be better to try to integrate it with what's already in `function-modifiers.rst`. That page does not even mention the word *placeholder* so it could be improved, but I don't think that the placeholder itself needs that much focus. It could be just a part of the bigger example that's already there.

2022-07-04 15:02 UTC, cameel commented on docs/contracts/placeholders.rst
> +******************
In RST the frame must match the header length

```suggestion
************************
The Placeholder Operator
************************
```

2022-07-04 15:02 UTC, cameel commented on docs/contracts/placeholders.rst
> +.. index:: ! function;placeholder
```suggestion
.. index:: ! modifier;placeholder
```

2022-07-04 15:02 UTC, cameel commented on docs/contracts/placeholders.rst
> +.. index:: ! function;placeholder
To be part of the docs, this file has to be included from `docs/index.rst` or some other file.

But I don't think this really needs to be a separate page. I think it should be a part of `docs/contracts/function-modifiers.rst`.

2022-07-04 15:02 UTC, cameel commented on docs/contracts/placeholders.rst
> +In function modifiers, it is necessary to tell Solidity when you want the function affected by the modifier to be run. The placeholder (denoted by an underscore character followed by a semicolon `_;`
```suggestion
In function modifiers, it is necessary to tell Solidity when you want the function affected by the modifier to be run.
The placeholder (denoted by an underscore character followed by a semicolon `_;` is used to denote where the
function being modified should be run within the modifier.
```

2022-07-04 15:02 UTC, cameel commented on docs/contracts/placeholders.rst
> +In function modifiers, it is necessary to tell Solidity when you want the function affected by the modifier to be run. The placeholder (denoted by an underscore character followed by a semicolon `_;`
```suggestion
In function modifiers, it is necessary to specify when you want the function to which the modifier is applied to be run. The placeholder (denoted by an underscore character followed by a semicolon `_;` is used to denote where the function being modified should be run within the modifier.
```

2022-07-04 15:02 UTC, cameel commented on docs/contracts/placeholders.rst
> +In function modifiers, it is necessary to tell Solidity when you want the function affected by the modifier to be run. The placeholder (denoted by an underscore character followed by a semicolon `_;`
```suggestion
In function modifiers, it is necessary to tell Solidity when you want the function affected by the modifier to be run. The placeholder (denoted by a single underscore character `_`) is used to denote where the body of the function being modified should be inserted.
```

2022-07-04 15:02 UTC, cameel commented on docs/contracts/placeholders.rst
> +Let's take a look at how the placeholder is used within a mutex modifier:
```suggestion
Let's take a look at how the placeholder can be used within a ``mutex`` modifier:
```

2022-07-04 15:02 UTC, cameel commented on docs/contracts/placeholders.rst
> +The Placeholder Operator
It's not really an operator.
```suggestion
The Placeholder Statement
```

2022-07-04 15:02 UTC, cameel commented on docs/contracts/placeholders.rst
> +Note that the placeholder operator is different from using underscores as leading or trailing characters in variable names, which is a stylistic choice.
I think it would be better off as a comment with your example. Then you could actually show a variable starting with an underscore and say that this does result in the function being executed.

2022-07-04 15:05 UTC, cameel commented
> CircleCI thinks I'm writing C++.
>
> Let me know what I need to do and I'll do it.

You probably mean the failing `chk_coding_style` job? It's exactly what it says, i.e. you seem to have left some whitespace past the end of line in a few places. This is flagged because randomly adding and removing this just adds noise to diffs and makes them harder to read. Please configure your editor to remove trailing whitespace automatically.

```
Error: Trailing whitespace found:
docs/contracts/placeholders.rst:15:	modifier mutex {  
docs/contracts/placeholders.rst:16:		require(!lock);  
docs/contracts/placeholders.rst:17:		lock = true;  
docs/contracts/placeholders.rst:19:		lock = false;  
docs/contracts/placeholders.rst:23:A simple way of thinking of this modifier is as a function which wraps the original function, in which case the placeholder operator would represent where we call our original function. 
```

2022-07-23 14:28 UTC, The-Arbiter commented
Thanks for this, I will close this one as I have created another PR for the function-modifiers.rst file.

2022-07-23 14:28 UTC, closed without merging