[Docs] Fixed link to internal-function-calls
ethereum/solidity pull request #13262
Opened 2022-07-11 14:35 UTC by xromrom

Fixed link in function.rst documentation file.

2022-07-11 14:55 UTC, chriseth commented on docs/contracts/functions.rst
>    by adding ``pragma abicoder v2;`` to your source file.
This is quite outdated - abicoder v2 has been the default for a while. We should convert this note into "until version ... it was not possible to...".

2022-07-11 18:05 UTC, cameel reviewed
Thanks for the fix! The change looks good but I agree with @chriseth that it would be good to update the part about ABI encoder too while we're touching this part.

2022-07-13 01:34 UTC, xromrom commented
Hi, thanks for the review and comments!
I updated the part about "abicoder v2", @chriseth could you please look once more?

2022-07-21 15:35 UTC, Marenz requested changes

2022-07-21 15:35 UTC, Marenz commented on docs/contracts/functions.rst
> +  (before that we had to enable it with ``pragma abicoder v2;``).
I would not use `we` here but `you` instead, that's more consistent with how the document started addressing the reader, e.g. in line 58 we also use `you`

Other than that, LGTM

2022-07-21 15:42 UTC, Marenz commented on docs/contracts/functions.rst
> +  (before that we had to enable it with ``pragma abicoder v2;``).
The coding style CI failure is due to trailing spaces in line 77 and 78

2022-07-26 01:45 UTC, xromrom commented
CI tests failed because of Z3 library issue:
_-- Found Z3: /usr/lib64/cmake/z3/Z3Config.cmake (found version "4.9.0.0") 
CMake Error at CMakeLists.txt:74 (message):
SMTChecker tests require Z3 4.8.17 for all tests to pass._
  
 Need more time to look into this.

2022-07-27 02:24 UTC, xromrom commented
@Marenz thanks for the review. I changed "we" to "you" and removed trailing spaces (CI code style now is ok).
There are 2 failed CI jobs but it seems they were broken not by me.

2022-07-27 10:05 UTC, Marenz approved these changes, later dismissed

2022-07-30 05:23 UTC, xromrom commented
@cameel, @chriseth hi!
Can we merge this PR?

2022-08-02 18:13 UTC, Marenz commented
If you do a rebase the tests will succeed and then we can merge it :)

2022-08-09 14:16 UTC, xromrom commented
The code was rebased.

2022-08-10 14:08 UTC, cameel submitted a review, later dismissed
Looks good, but the review fixes should be squashed into the original commit.

I'll squash and merge.

2022-08-10 14:10 UTC, cameel approved these changes

2022-08-10 17:07 UTC, merged