Compare source files in source locations
ethereum/solidity pull request #1333
Opened 2016-11-07 13:59 UTC by pirapira

This pull-request makes the equality comparison `==` of source locations more accurate by taking the file names into account.  At the same time `<` is also made accurate by considering the cases where the file name of both sides are null.

2016-11-07 15:32 UTC, chriseth requested changes

2016-11-07 15:32 UTC, chriseth commented on libevmasm/SourceLocation.h
> +			return std::make_tuple(start, end) < std::make_tuple(_other.start, _other.end);
Can this and the next line be shortened to
`return std::make_tuple(!!sourceName, start, end) < std::make_tuple(!!_other.sourceName, _other.start, _other.end);`?

2016-11-07 15:34 UTC, pirapira commented on libevmasm/SourceLocation.h
> +			return std::make_tuple(start, end) < std::make_tuple(_other.start, _other.end);
Yes, it's safe to do that.

2016-11-07 17:01 UTC, pirapira commented
@chriseth this is ready on my side.

2016-11-08 10:02 UTC, pirapira commented
The failure in appveyor is `block mining timeout!`

2016-11-08 10:08 UTC, chriseth commented on libevmasm/SourceLocation.h
> +	{
No braces needed, also I would prefer `if () return X else return Y` style here.

2016-11-08 10:11 UTC, pirapira commented on libevmasm/SourceLocation.h
> +	{
Done.

2016-11-08 10:20 UTC, chriseth approved these changes

2016-11-09 09:49 UTC, merged