More optimiser rules
ethereum/solidity pull request #1345
Opened 2016-11-09 02:23 UTC by axic

2016-11-09 08:34 UTC, chriseth requested changes

2016-11-09 08:34 UTC, chriseth commented on libevmasm/ExpressionClasses.cpp
> +		{{Instruction::SUB, {X, 0}}, [=]{ return X; }},
Please add a test for this to be sure that it means `x-0` and not `0-x`.

2016-11-09 11:30 UTC, axic commented
@chriseth added, hopefully?

2016-11-09 11:38 UTC, pirapira commented
Maybe `{{Instruction::DIV, {0, X}}, [=]{ return u256(0); }},`

Is it worth adding lengthier rules like
`{{Instruction::XOR, {{{X}, {Instruction::XOR, {X, Y}}}}}, [=]{ return Y; }},`?

2016-11-09 12:01 UTC, axic commented
So it seems like the parameter order is not enforced?

```
/home/travis/build/ethereum/solidity/test/libsolidity/SolidityOptimizer.cpp(128): error in "cse_sub_zero": check { _expectation.begin(), _expectation.end() } == { output.begin(), output.end() } failed. 

Mismatch in a position 0:  PUSH 5 !=  PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB

Collections size mismatch: 3 != 1
```

2016-11-09 12:02 UTC, axic commented
> Is it worth adding lengthier rules like
`{{Instruction::XOR, {{{X}, {Instruction::XOR, {X, Y}}}}}, [=]{ return Y; }},`?

I would think so if the optimiser actually executes it. Is it doing longest match first or all matches and comparing the results?

2016-11-09 13:27 UTC, chriseth commented
I don't think that the extended xor rule would be triggered often. I also never profiled the matching routine, it might be quite slow.

2016-11-09 13:29 UTC, chriseth commented
@axic if you use constants in the tests, the optimizer will just evaluate the full expression. You need a tests like `dup1 0 sub` and `0 dup1 sub`

2016-11-14 12:40 UTC, axic commented
@chriseth I have one more rule to inclue and perhaps some from @pirapira's changeset.

2016-11-15 19:06 UTC, axic commented
Cherry-picked 115d30e.

Need to add tests.

2016-11-16 14:31 UTC, chriseth approved these changes

2016-11-30 11:21 UTC, axic commented
Verified the optimisation for the correct case (`n - 0`).

However for the `0 - n` case it seems to be broken:

Mismatch in a position 0:  DUP2 !=  PUSH 0
Mismatch in a position 1:  PUSH 0 !=  DUP3
Mismatch in a position 2:  SUB !=  SWAP1

2016-11-30 11:50 UTC, axic commented
It actually "optimises" `DUP1, PUSH 0, SUB` to `PUSH 0, DUP2, SWAP1, SUB`, which is correct, but not very optimised.

Too bad `checkCSE` doesn't report the difference in instruction count so it wasn't apparent.

2016-11-30 13:25 UTC, chriseth approved these changes

2016-11-30 13:26 UTC, merged