adding parser support for code keyword for data location
ethereum/solidity pull request #13458
Opened 2022-08-30 14:29 UTC by nishant-sachdeva

closes https://github.com/ethereum/solidity/issues/13368

2022-08-30 15:11 UTC, Marenz requested changes
Looking at the CI there seem to be a few more places that require changes, mostly switch cases that don't handle `code` yet.

Overall the approach looks fine.

2022-08-30 15:11 UTC, Marenz commented on libsolidity/parsing/Parser.cpp
> +						syntaxError(
I think an `solUnimplementedError` (or something like that, not sure what the exact name is) would be desired here

2022-08-30 15:21 UTC, Marenz commented
Hmm there are a few CI failures that are fixed in `develop`, so we probably need to merge current `develop` into `breaking` after all.

2022-08-30 21:49 UTC, matheusaaguiar commented
This change is also affecting Yul. The following minimal example:
```
object "runtime" {
    code {

    }
}
```
compiled with `./solc --strict-assembly` will result in the error:
```Error: Expected keyword "code".```

2022-08-31 00:24 UTC, matheusaaguiar commented on libsolidity/parsing/Parser.cpp
> +						solUnimplemented("Code keyword as a data location specifier has not been implemented yet.");
I was checking and for this point to be reached, `TokenTraits::isLocationSpecifier` needs to be modified to recognize `Token::Code`. Also, this throws an exception and I understood from #13368 that it should be a syntax error.

2022-08-31 11:21 UTC, Marenz commented on libsolidity/parsing/Parser.cpp
> +						solUnimplemented("Code keyword as a data location specifier has not been implemented yet.");
My bad advice then, I thought we wanted to use `solUnimplemented()`

2022-09-01 09:36 UTC, ekpyron commented
I'm actually not quite sure how to react to this... did any of you actually read the issue?
The task is to add the keyword **and** to actually parse it as a data location, while making any use of the keyword a syntax error. As in an error in ``SyntaxChecker``.
While, technically, this PR is an initial step towards that, this by no means solves the issue.
Also the interactions with Yul should have become apparent with a single local CI run (the issue can be fixed by a minor adjustment of ``ObjectParser::parseCode``).

I also generally don't think it's beneficial to keep draft PRs in a state like this open. So please make sure you understand the scope of the underlying issue, if necessary ask for clarification on it, and reopen a proper PR actually addressing the issue.

2022-09-01 10:16 UTC, closed without merging