Grammer fix.
ethereum/solidity pull request #13463
Opened 2022-08-31 10:12 UTC by emmaodia

2022-08-31 11:23 UTC, Marenz requested changes

2022-08-31 11:23 UTC, Marenz commented on docs/types/value-types.rst
> +    To reduce conversion ambiguity version 0.4.24 and higher versions of the Solidity compiler force you to make the truncation explicit in the conversion.
```suggestion
    To reduce conversion ambiguity, starting with version 0.4.24 the compiler will force you to make the truncation explicit in the conversion.
```

I don't think we need to explicitly mention "solidity" in the solidity documentation :)

2022-08-31 14:58 UTC, matheusaaguiar commented on docs/types/value-types.rst
> +    To reduce conversion ambiguity, starting with version 0.4.24 the compiler will force you to make the truncation explicit in the conversion.
```suggestion
    To reduce conversion ambiguity, starting with version 0.4.24, the compiler will force you to make the truncation explicit in the conversion.
```
Don't want to be annoying but it seems to me that a comma is needed here.

2022-08-31 15:01 UTC, matheusaaguiar reviewed
I noticed the commit message has misspelled the word `Grammar`... guess it would be nice to amend it.

2022-08-31 15:22 UTC, matheusaaguiar approved these changes, later dismissed
LGTM.

2022-08-31 16:22 UTC, Marenz approved these changes

2022-09-05 14:08 UTC, nikola-matic commented
@emmaodia can you please rebase against `develop`, the failing steps should now be fixed (not all, but at least the required ones).

2022-09-05 14:09 UTC, leonardoalt commented
@nikola-matic @Marenz @matheusaaguiar if the author is unresponsive you can also just rebase and push directly into their branch/fork

2022-09-05 14:10 UTC, leonardoalt commented
re: merge commit which should be removed and squashing

2022-09-05 14:11 UTC, nikola-matic commented
> @nikola-matic @Marenz @matheusaaguiar if the author is unresponsive you can also just rebase and push directly into their branch/fork

Author pushed 5 days ago after receiving Mathias' approval, so let's wait for a day or two.

2022-09-05 14:37 UTC, Marenz requested changes
PR content is good, just waiting for a rebase + fixup/amending of commits into one.

2022-09-05 18:47 UTC, merged

2022-09-07 10:38 UTC, emmaodia commented
Thank you @ekpyron @nikola-matic @Marenz @leonardoalt I was away and I missed the messages. Thanks again.