Clarification to the documentation on converting payable to non payab…
ethereum/solidity pull request #13613
Opened 2022-10-05 16:08 UTC by Andy53

…le functions.

Added clarification to the documentation as described in [#13114](https://github.com/ethereum/solidity/issues/13114)

2022-10-10 11:19 UTC, NunoFilipeSantos requested changes
@christianparpart take a look here.

2022-10-10 11:19 UTC, NunoFilipeSantos commented on docs/types/value-types.rst
> +the same way.
```suggestion
To clarify, not rejecting ether is less restrictive than rejecting ether.
This means you can override a payable function with a non-payable but not the
other way around

Additionally, when you define a ``non-payable`` function pointer, 
the compiler does not enforce that the function will actually reject ether. 
Instead, it enforces that the function pointer is never used to send ether. 
Which makes it possible to assign a ``payable`` function pointer to a ``non-payable``
pointer due to not being able to send ether ensuring both types behave the same way.
```

2022-10-10 11:24 UTC, christianparpart commented on docs/types/value-types.rst
> +the same way.
:+1:

2022-10-24 16:50 UTC, matheusaaguiar reviewed
I guess this is confusing because it involves two different situations: functions and pointers to functions. I think that the difference is more apparent now in the text, but maybe there is room to be even more explicit.

2022-10-24 16:50 UTC, matheusaaguiar commented on docs/types/value-types.rst
> +other way around
```suggestion
other way around.
```

2022-10-24 16:50 UTC, matheusaaguiar commented on docs/types/value-types.rst
> +To clarify, not rejecting ether is less restrictive than rejecting ether.
```suggestion
To clarify, rejecting ether is more restrictive than not rejecting ether.
```
I feel that this is more straightforward.

2022-10-24 16:50 UTC, matheusaaguiar commented on docs/types/value-types.rst
> +the compiler does not enforce that the function will actually reject ether.
```suggestion
the compiler does not enforce that the pointed function will actually reject ether. 
```

2022-10-24 16:50 UTC, matheusaaguiar commented on docs/types/value-types.rst
> +pointer due to not being able to send ether ensuring both types behave the same way.
```suggestion
function pointer ensuring both types behave the same way, i.e, both cannot be used to send ether .
```

2022-10-25 18:03 UTC, matheusaaguiar commented
Hi @Andy53 , it seems that in your last commit you mistakenly merged branch `develop` on your PR branch instead of rebasing on top of the former.
You could fix it by first rewinding the last commit and then rebasing on top of develop.
```
git reset --hard HEAD~1
git rebase -i origin/develop
```
The rebase command should open an interactive session in which you can choose to squash some commits, like the `trailing whitespace` ones, for example.
Feel free to ask or dm if you need help.

2022-10-25 19:57 UTC, Andy53 commented
This rebase did not go to plan sadly :( I seem to have pulled 2 commits in from another branch.

2022-10-25 20:09 UTC, Andy53 commented
So the latest push [4357949](https://github.com/ethereum/solidity/commit/43579491e3ba267d23afaaefdd768e7906bd7973) seems to be correct. It's got just the changes to the documentation required for the PR and nothing else.

2022-10-25 21:59 UTC, matheusaaguiar commented
Sorry, maybe I misdirect you with the commands I suggested. Probably, the `origin/develop` you rebased onto is actually your own fork repository. Maybe you have a `upstream` remote which points to the solidity original repo? If not, you can add it with:
```
git remote add upstream https://github.com/ethereum/solidity.git
git fetch upstream
```
Anyway, there are still commits not belonging and also the last one you mentioned that seems ok is your first modification.
Try to see if you can still find the other relevant commits and then rebase on the `develop` branch of the original solidity repo. Otherwise, I have resumed the changes so far in my local copy and can push them later.

2022-10-26 02:16 UTC, Andy53 commented
I think I might have got it right this time. Files changed is down to 1 now.

2022-10-26 14:02 UTC, matheusaaguiar commented
Restored the lost modifications and rebased on top of `develop`.

2022-10-31 14:51 UTC, NunoFilipeSantos approved these changes, later dismissed
Thank you.

2022-11-10 18:44 UTC, matheusaaguiar approved these changes
I have rebased and squashed commits. Setting to auto-merge, since @NunoFilipeSantos  had previously approved.

2022-11-10 19:28 UTC, merged