[Documentation] Change text to be hyperlink
ethereum/solidity pull request #13666
Opened 2022-10-31 06:21 UTC by SavPhill

The documentation link incorrectly displays in the text along with the angled brackets. I believe this is incorrect, and should be a standard markdown hyperlink. The error also disrupts the spacing of the line.  My small PR fixes both issues.

![eth-docs](https://user-images.githubusercontent.com/38789408/198944119-81885bf1-8084-4436-ac5b-11a1fa21ecce.png)

2022-10-31 11:23 UTC, NunoFilipeSantos submitted a review, later dismissed
Thank you for your contribution.

2022-11-01 08:30 UTC, nikola-matic commented on docs/contributing.rst
> +We highly recommend going through our `review checklist <https://github.com/ethereum/solidity/blob/develop/ReviewChecklist.md>`_ before submitting the pull request. We thoroughly review every PR and
```suggestion
We highly recommend going through our `review checklist <https://github.com/ethereum/solidity/blob/develop/ReviewChecklist.md>`_ before submitting the pull request. 
We thoroughly review every PR and will help you get it right, but there are many common problems that can be easily avoided, making the review much smoother.
```

2022-11-01 08:36 UTC, nikola-matic requested changes
Thanks for the contribution! Note that when it comes to docs - we generally try to keep one sentence per line (unless the line is too long) in order to make any changes easier to see in the diff; e.g. in this case, the only thing you've really changes was adding one underscore character, but the diff is now significantly larger than that because you've merged the two sentences into the same line.

Please address this, and we'll merge this away :)

2022-11-01 11:55 UTC, NunoFilipeSantos commented
I've added your suggestion @nikola-matic .

2022-11-01 11:55 UTC, NunoFilipeSantos submitted a review, later dismissed
Looks good now.

2022-11-01 11:57 UTC, nikola-matic approved these changes, later dismissed

2022-11-01 11:58 UTC, nikola-matic commented on docs/contributing.rst
> +We highly recommend going through our `review checklist <https://github.com/ethereum/solidity/blob/develop/ReviewChecklist.md>`_ before submitting the pull request.
```suggestion
We highly recommend going through our `review checklist <https://github.com/ethereum/solidity/blob/develop/ReviewChecklist.md>`_ before submitting the pull request.
```

Build is failing due to the trailing whitespace, so you're gonna have to fix it before we merge.

2022-11-01 12:05 UTC, nikola-matic approved these changes

2022-11-01 12:53 UTC, merged