Enum overflow checking before writing to storage
ethereum/solidity pull request #1381
Opened 2016-11-15 17:01 UTC by pirapira

This fixes #1344 (all the remaining points).

It turned out no fixes are necessary for most cases, but I needed to add cleanups before storing values into the storage.

2016-11-21 16:09 UTC, pirapira commented
@chriseth now I'm calling `utils.convertType()` for cleaning up.

2016-11-24 10:05 UTC, chriseth requested changes
There are more comments, but better to talk in person.

2016-11-24 10:05 UTC, chriseth commented on libsolidity/codegen/CompilerUtils.h
> -	void convertType(Type const& _typeOnStack, Type const& _targetType, bool _cleanupNeeded = false);
Please document `_chopSignBits`

2016-11-24 12:14 UTC, axic commented on libsolidity/codegen/CompilerUtils.cpp
> +							<< Instruction::DIV;
Why is `MUL`/`DIV` better than bitwise and with a constant?

2016-11-24 14:15 UTC, pirapira commented on libsolidity/codegen/LValue.cpp
> +	solAssert(m_dataType, "");
Has the stack element already been converted?  In that case, the clean up should have done there.

2016-11-24 14:17 UTC, pirapira commented on libsolidity/codegen/LValue.cpp
> +
Put an assertion (source == target).

2016-11-24 16:02 UTC, pirapira commented on libsolidity/codegen/LValue.cpp
> +
@pirapira the assertion fails.

2016-11-24 16:03 UTC, pirapira commented on libsolidity/codegen/LValue.cpp
> +	solAssert(m_dataType, "");
@pirapira the stack element might not have been converted (because when I assert `_sourceType == *m_dataType` it fails).

2016-11-24 16:03 UTC, pirapira commented on libsolidity/codegen/CompilerUtils.h
> -	void convertType(Type const& _typeOnStack, Type const& _targetType, bool _cleanupNeeded = false);
This has been done.

2016-11-24 16:05 UTC, pirapira commented on libsolidity/codegen/CompilerUtils.cpp
> +							<< Instruction::DIV;
I was too lazy and just moved the code here.   Now I found bitwise `AND` easier to understand, so I changed the code.

2016-11-25 10:24 UTC, pirapira commented
@chriseth In `storeValue()` functions, `_sourceType` and `*m_dataType` are sometimes different.  Shall I try to fix that before continuing this pull-request?

2016-11-25 14:55 UTC, chriseth approved these changes

2016-11-25 15:22 UTC, merged