Check warning text in tests
ethereum/solidity pull request #1392
Opened 2016-11-17 15:21 UTC by pirapira

Trying to fix #1291.

2016-11-17 16:31 UTC, chriseth commented
I would propose to use macros in the actual tests (so that the boost failure references the correct line) which check: error type, error message.

2016-11-17 16:31 UTC, chriseth commented
Please also check that there is exactly one warning / exactly one error. If we have tests that report multiple errors, we might be able to fix them - if not, we can add another option to the macro.

2016-11-21 17:10 UTC, pirapira commented
@chriseth "exactly one error" is split out to #1412 because this involves fixing 33 tests.

2016-11-24 09:05 UTC, pirapira commented
@chriseth @axic I think this one is ready now.

2016-11-24 12:28 UTC, axic commented on test/libsolidity/SolidityNameAndTypeResolution.cpp
> +	CHECK_ERROR(text, DeclarationError, "");
One benefit I could see making these functions is that we could have two overloaded versions:

`check_error(text, DeclarationError);` vs `check_error(text, DeclarationError, "uint128 is invalid");`

2016-11-24 12:29 UTC, axic commented
Looks great! We should also add expected error texts in a later PR wherever it fits.

2016-11-24 17:59 UTC, chriseth requested changes

2016-11-24 17:59 UTC, chriseth commented on libsolidity/interface/Exceptions.h
> +	bool searchForSubstring(const std::string& _substr) const;
Declaration is still here.

2016-11-24 17:59 UTC, chriseth commented on test/libsolidity/ErrorCheck.cpp
> +	if (const std::string* errorMessage = boost::get_error_info<dev::errinfo_comment>(_err))
should be `std::string const*` - you can also add a `using namespace std;` above and remove the `std`

2016-11-24 17:59 UTC, chriseth commented on test/libsolidity/SolidityNameAndTypeResolution.cpp
> +			return make_pair(sourceUnit, errors[0]);
`errors.at(0)`?

2016-11-24 17:59 UTC, chriseth commented on test/libsolidity/SolidityNameAndTypeResolution.cpp
> +	CHECK_ERROR(text, DeclarationError, "");
Functions will report the wrong failure location, and I think we should check for a message everywhere anyway.

2016-11-24 17:59 UTC, chriseth commented on test/libsolidity/SolidityNameAndTypeResolution.cpp
> +	BOOST_CHECK(expectError(sourceCode1).type() == Error::Type::TypeError);
Why don't you use the `CHECK_ERROR` macro here?

2016-11-24 18:12 UTC, pirapira commented on test/libsolidity/SolidityNameAndTypeResolution.cpp
> +	BOOST_CHECK(expectError(sourceCode1).type() == Error::Type::TypeError);
Actually there are more of these.

2016-11-24 18:19 UTC, pirapira commented on test/libsolidity/SolidityNameAndTypeResolution.cpp
> +			return make_pair(sourceUnit, errors[0]);
Yes, that's better.

2016-11-24 18:23 UTC, pirapira commented on test/libsolidity/ErrorCheck.cpp
> +	if (const std::string* errorMessage = boost::get_error_info<dev::errinfo_comment>(_err))
I followed these.

2016-11-24 18:23 UTC, pirapira commented on test/libsolidity/SolidityNameAndTypeResolution.cpp
> +			return make_pair(sourceUnit, errors[0]);
I've changed this.

2016-11-24 18:24 UTC, pirapira commented on test/libsolidity/SolidityNameAndTypeResolution.cpp
> +	BOOST_CHECK(expectError(sourceCode1).type() == Error::Type::TypeError);
I've replaced all straightforward cases.

2016-11-24 19:56 UTC, chriseth approved these changes

2016-11-24 20:22 UTC, merged