fix licensing headers
ethereum/solidity pull request #1399
Opened 2016-11-18 23:14 UTC by VoR0220

Signed-off-by: VoR0220 <rj@erisindustries.com>

2016-11-21 10:14 UTC, chriseth commented
You accidentally added some binaries

2016-11-21 10:15 UTC, chriseth requested changes
Please remove binaries and rebase.

2016-11-21 10:15 UTC, chriseth commented on scripts/install_deps.sh
> -        curl -L -O https://github.com/bobsummerwill/cpp-ethereum/releases/download/v1.3.0/cpp-ethereum-osx-mavericks-v1.3.0.zip
This should not be changed.

2016-11-21 10:15 UTC, chriseth commented on scripts/install_eth.cmake
> -download_and_unpack("https://github.com/bobsummerwill/cpp-ethereum/releases/download/develop-v1.3.0.401/cpp-ethereum-develop-windows.zip" ${INSTALL_DIR})
No change here either.

2016-11-21 10:15 UTC, chriseth commented on test/libsolidity/SolidityNameAndTypeResolution.cpp
> -	// test for issue #1126 https://github.com/ethereum/cpp-ethereum/issues/1126
Please don't change.

2016-11-21 15:30 UTC, VoR0220 commented
Crap. My bad. Will change.

2016-11-23 11:24 UTC, chriseth commented
Superseded by https://github.com/ethereum/solidity/pull/1425

2016-11-23 11:24 UTC, closed without merging