fix(docs): fix missing backticks, remove latexpdfja, fix the missing help message of latexpdf, and remove unnecessary whitespace
ethereum/solidity pull request #14101
Opened 2023-04-06 17:31 UTC by minaminao

- Fixed the missing backticks in 080-breaking-changes, ir-breaking-changes, yul
- Removed the `latexpdfja` command in makefiles. `latexpdfja` is the command for Japanese, but this seems to have not been used since added in #282. (As a maintainer of the Japanese translation, I think this is unnecessary.)
- Removed the unnecessary whitespaces in directives and the header of the optimizer step
- Fixed the missing help message of `latexpdf` in make.bat

2023-04-07 12:32 UTC, r0qs requested changes
Thank you very much @minaminao! I have just some comments.

Could you please also fix the backticks here: https://github.com/ethereum/solidity/blob/develop/docs/control-structures.rst?plain=1#L654 and here: https://github.com/ethereum/solidity/blob/develop/docs/installing-solidity.rst?plain=1#L530

2023-04-07 17:47 UTC, minaminao commented
Fixed them!

2023-04-11 10:09 UTC, r0qs approved these changes, later dismissed
Thanks @minaminao! :D

2023-04-13 18:00 UTC, NunoFilipeSantos commented on docs/internals/optimizer.rst
>  The Expression Simplifier uses the Dataflow Analyzer and makes use
```suggestion
ExpressionSimplifier
^^^^^^^^^^^^^^^^^^^^

The ExpressionSimplifier uses the Dataflow Analyzer and makes use
```

For consistency sake it should also be removed here.

2023-04-13 18:10 UTC, minaminao commented
@NunoFilipeSantos If you remove it, the Dataflow Analyzer, Conditional Simplifier, etc., would also need to be changed.

2023-04-14 11:23 UTC, NunoFilipeSantos commented
> @NunoFilipeSantos If you remove it, the Dataflow Analyzer, Conditional Simplifier, etc., would also need to be changed.

No, that can be done later in another PR.
Right now since we're changing here this section this is closed.

2023-04-14 11:24 UTC, NunoFilipeSantos approved these changes
LGTM now.

2023-04-14 11:24 UTC, merged

2023-04-14 12:10 UTC, minaminao commented
Indeed it is, thank you! The name formats of the optimizer steps are not entirely consistent on this page, so it may be good that they are consistent someday (but this is a nit).