Adds NatSpec to AST for struct definitions.
ethereum/solidity pull request #14119
Opened 2023-04-13 11:07 UTC by veniger

Added NatSpec to AST for struct definitions
Similar pr for enums: https://github.com/ethereum/solidity/pull/13626

2023-04-13 11:39 UTC, nikola-matic requested changes

2023-04-13 11:39 UTC, nikola-matic commented on Changelog.md
> + * NatSpec: Add support for NatSpec documentation in ``struct`` definition.
This is the changelog for the already released 0.8.19 version; you're gonna have to move this up to line 10 (after the enum entry).

2023-04-17 07:18 UTC, nikola-matic commented on Changelog.md
> + * NatSpec: Add support for NatSpec documentation in ``struct`` definition.
```suggestion
 * NatSpec: Add support for NatSpec documentation in ``struct`` definitions.
```

2023-04-17 10:10 UTC, cameel reviewed
Looks good other than some minor indent/changelog issues.

BTW, please remember to switch draft PRs to reviewable when they're ready for review.

2023-04-17 10:10 UTC, cameel commented on test/libsolidity/SolidityNatspecJSON.cpp
> +	  "version": 1
This is indented with a mix of tabs and spaces.

2023-04-18 14:05 UTC, nikola-matic approved these changes

2023-04-18 14:05 UTC, merged