docs: add a section about calldata layout
ethereum/solidity pull request #1413
Opened 2016-11-21 14:49 UTC by pirapira

Part of #1390 

This would supersede the [section about the ABI](https://github.com/ethereum/wiki/wiki/Solidity-Features#abi-requires-arguments-to-be-padded-to-32-bytes) in a wiki page.

2016-11-23 11:19 UTC, chriseth requested changes

2016-11-23 11:19 UTC, chriseth commented on docs/miscellaneous.rst
> +When a Solidity contract is deployed and when it is called, the input data follows the format in `the ABI specification <https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI>`_.  The ABI speci
Please break the line.

2016-11-23 11:19 UTC, chriseth commented on docs/miscellaneous.rst
> +When a Solidity contract is deployed and when it is called, the input data follows the format in `the ABI specification <https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI>`_.  The ABI speci
Perhaps I am not paying attention to details, but these sentences seem largely redundant.

2016-11-23 14:25 UTC, pirapira commented
@chriseth here is my second try.

2016-11-24 10:05 UTC, chriseth approved these changes

2016-11-24 10:05 UTC, merged