docs: fix old wording
ethereum/solidity pull request #14147
Opened 2023-04-21 10:35 UTC by Vojtch159

Updated mining to attestation, but maybe it doesn't even make sense to put it like this. This is for the maintainers to decide but maybe it'd make sense to remove "(which is called "attestation")" altogether and just add a link to more information about LMD-GHOST.

2023-08-16 18:52 UTC, cameel commented on docs/introduction-to-smart-contracts.rst
> +As part of the "order selection mechanism" (which is called "attestation") it may happen that
Perhaps we could also make this a link to https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/attestations/

2023-08-16 18:52 UTC, cameel commented on docs/introduction-to-smart-contracts.rst
> +As part of the "order selection mechanism" (which is called "attestation") it may happen that
If we're changing this, we should also deal with some other references to mining. For example [in the description of `coinbase()` opcode in Yul](https://docs.soliditylang.org/en/latest/yul.html#evm-dialect) and in the cheatsheet or in the description of the `receive` function. There's even one in the note below.

2024-01-10 10:33 UTC, mehtavishwa30 requested changes

2024-01-10 10:33 UTC, mehtavishwa30 commented on docs/introduction-to-smart-contracts.rst
> +As part of the "order selection mechanism" (which is called "attestation") it may happen that
```suggestion
As part of the "order selection mechanism", which is called `attestation <https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/attestations/>`_, it may happen that
```

2024-02-05 13:31 UTC, mehtavishwa30 commented
Will commit a small suggestion made to address @cameel's comment and merge ultimately. :)

Thanks for your contribution @Vojtch159!

2024-02-29 09:58 UTC, mehtavishwa30 approved these changes

2024-02-29 09:58 UTC, merged