Stack optimizer fuzzer: Detect stack-too-deep during optimization
ethereum/solidity pull request #14227
Opened 2023-05-15 14:55 UTC by bshastry

2023-05-15 15:30 UTC, r0qs requested changes

2023-05-15 15:30 UTC, r0qs commented on test/tools/ossfuzz/StackReuseCodegenFuzzer.cpp
> +/// @returns true if there are no recursive functions, false otherwise.
```suggestion
/// @returns true if there are recursive functions, false otherwise.
```
Or the logic of the function should be inverted, since you are returning `true` when you find a recursive function.

2023-05-15 15:34 UTC, r0qs commented on test/tools/ossfuzz/StackReuseCodegenFuzzer.cpp
> +	if (!equal)
Why not?
```suggestion
	if (unoptimizedState.str() != optimizedState.str())
```

2023-05-15 15:40 UTC, ekpyron commented
Copied from matrix for the record:

I'm just noticing, though, that stack-to-memory won't have run on the latest case you posted in https://github.com/ethereum/solidity/issues/14187#issuecomment-1547998779, since the Yul code didn't contain a ``memoryguard`` - in that situation we expect a lot more stack-too-deep cases compared to the cases with ``memoryguard``.

So it might help to prefix the cases with ``pop(memoryguard(<random 32-bit value>))`` - that way stack-to-memory is run and we expect much fewer stack-too-deep errors (ideally none, but we're not there yet).
The memoryguard will make it harder to check for semantic equivalence, since code will only remain semantically the same, if it only accesses memory above the return value of the ``memoryguard``, but since we're only looking for stack-too-deep error, semantic equivalence between optimized and non-optimized code shouldn't be a huge problem, right?

2023-05-16 07:46 UTC, bshastry commented
> Copied from matrix for the record:
> 
> I'm just noticing, though, that stack-to-memory won't have run on the latest case you posted in [#14187 (comment)](https://github.com/ethereum/solidity/issues/14187#issuecomment-1547998779), since the Yul code didn't contain a `memoryguard` - in that situation we expect a lot more stack-too-deep cases compared to the cases with `memoryguard`.
> 
> So it might help to prefix the cases with `pop(memoryguard(<random 32-bit value>))` - that way stack-to-memory is run and we expect much fewer stack-too-deep errors (ideally none, but we're not there yet). The memoryguard will make it harder to check for semantic equivalence, since code will only remain semantically the same, if it only accesses memory above the return value of the `memoryguard`, but since we're only looking for stack-too-deep error, semantic equivalence between optimized and non-optimized code shouldn't be a huge problem, right?

Thank you! I addressed this issue by lowering the upper bound on memory accesses that the fuzzer generates and adding a `pop(memoryguard(upperbound))` so that we can both preserve semantic equivalence (since the fuzzer respects bound) and detect stack-too-deep.

2023-06-26 12:52 UTC, r0qs reviewed
@bshastry could you rebase it? :)

2023-06-27 12:18 UTC, r0qs approved these changes

2023-07-03 12:52 UTC, merged