Update natspec-format.rst : Added structs and enums to Tags
ethereum/solidity pull request #14267
Opened 2023-05-24 16:21 UTC by adityakode

Added structs and enums to `@title`, `@author`, `@notice`, and `@dev` in [Tags](https://docs.soliditylang.org/en/v0.8.20/natspec-format.html#tags) table in  [NatSpec Format](https://docs.soliditylang.org/en/v0.8.20/natspec-format.html#tags), 
as per [v0.8.20 release notes](https://github.com/ethereum/solidity/releases/tag/v0.8.20).

Fixes #14217

2023-05-29 08:13 UTC, nikola-matic commented
Hi @adityakode, can you please rebase on top of the latest develop (this should fix the failed CI steps), and also squash everything into one commit while you're at it? The PR looks good for merging.

2023-07-13 19:20 UTC, d1onys1us commented
i think an example would also be good

2023-09-13 13:31 UTC, astermirac1e commented on docs/natspec-format.rst
> +``@dev``        Explain to a developer any extra details                                               contract, library, interface, function, state variable, event, structs, enums
nit: use singular form. e.g. `struct`, `enum` instead of `structs`, `enums`

2023-09-15 05:34 UTC, ALIR86 commented on docs/natspec-format.rst
> +``@dev``        Explain to a developer any extra details                                               contract, library, interface, function, state variable, event, structs, enums
Hello I am sorry now what's  my roll sent me to my address email address contract that sent to etherscan.io  to ownership  contract and registering and confim sorry a question why any address contract I filling in forms their but am not saw in the list my token just I see they add to whashlist or add as watch address .now in blockchair.com ,github  collection I need to help to  need open bank account in swiss I wanna migrate this fined region and I wanna made my life am not housing with old mother I lived  I havnot control to my capital creator zNFT payment of my liquidity  who let such work give to thses  I need to a financial  consultant  for 3 goverence  and 3 currency financial investor also for me goverence no report no authority nothing attention and respect

2024-01-10 10:01 UTC, mehtavishwa30 requested changes

2024-01-10 10:01 UTC, mehtavishwa30 commented on docs/natspec-format.rst
> +``@dev``        Explain to a developer any extra details                                               contract, library, interface, function, state variable, event, structs, enums
```suggestion
``@title``      A title that should describe the contract/interface                                    contract, library, interface, struct, enum
``@author``     The name of the author                                                                 contract, library, interface, struct, enum
``@notice``     Explain to an end user what this does                                                  contract, library, interface, function, public state variable, event, struct, enum
``@dev``        Explain to a developer any extra details                                               contract, library, interface, function, state variable, event, struct, enum
```

Suggested singular forms for consistency.

2024-02-05 13:25 UTC, mehtavishwa30 commented
Made a small suggestion that I will commit and merge. :) Thank you for your contribution!

2024-02-29 10:08 UTC, mehtavishwa30 approved these changes

2024-02-29 10:08 UTC, merged