docs: a bit more about literals
ethereum/solidity pull request #1431
Opened 2016-11-23 14:24 UTC by pirapira

The [wiki](https://github.com/ethereum/wiki/wiki/The-Solidity-Programming-Language#byte-strings) was saying that string literals imply trailing zeros; this seems wrong now.

I added a sentence about the lack of trailing-zeros, and I changed a bit more.

2016-11-24 18:46 UTC, chriseth requested changes

2016-11-24 18:46 UTC, chriseth commented on docs/types.rst
> +The number literal type contains not just single literals
This sentence is a bit confusing - perhaps it is better to drop it?

2016-11-24 18:48 UTC, pirapira commented
If we drop it, we are not specifying the type of `1 + 2` anymore.  In Solidity every expression has a type.

On November 24, 2016 7:46:21 PM GMT+01:00, chriseth <notifications@github.com> wrote:
>chriseth requested changes on this pull request.
>
>
>
>> @@ -169,9 +169,13 @@ Fixed Point Numbers
> Rational and Integer Literals
> -----------------------------
> 
>-All number literals retain arbitrary precision until they are
>converted to a non-literal type (i.e. by
>-using them together with a non-literal type). This means that
>computations do not overflow but also
>-divisions do not truncate.
>+Integer literals and rational number literals belong to a special
>type.
>+The number literal type contains not just single literals
>
>This sentence is a bit confusing - perhaps it is better to drop it?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ethereum/solidity/pull/1431#pullrequestreview-10084174

2016-11-24 19:51 UTC, chriseth commented on docs/types.rst
> +The number literal type contains not just single literals
Ok, but actually we have one type for every possible value for the literal, not for every possible expression.

2016-11-25 09:46 UTC, pirapira commented on docs/types.rst
> +The number literal type contains not just single literals
OK.  Then I rewrite accordingly.

2016-11-25 09:55 UTC, pirapira commented on docs/types.rst
> +The number literal type contains not just single literals
Done.

2016-11-25 13:54 UTC, chriseth approved these changes

2016-11-25 14:33 UTC, merged