docs: Update compiler standard input docs to reflect all available evm options
ethereum/solidity pull request #14391
Opened 2023-07-10 05:36 UTC by alpinevm

2023-07-10 07:50 UTC, NunoFilipeSantos commented on docs/using-the-compiler.rst
> +        // tangerineWhistle, spuriousDragon, byzantium, constantinople, petersburg, istanbul, berlin, london, paris or shanghai
```suggestion
        // tangerineWhistle, spuriousDragon, byzantium, constantinople,
        // petersburg, istanbul, berlin, london, paris or shanghai (default)
```
Line break and mentions that shangai is the default option.

2023-07-10 07:50 UTC, NunoFilipeSantos requested changes
I left a suggestion.

2023-07-11 10:44 UTC, matheusaaguiar approved these changes

2023-07-11 11:15 UTC, NunoFilipeSantos approved these changes
Now it looks good. Thank you!

2023-07-11 20:50 UTC, merged