document missing keywords
ethereum/solidity pull request #1465
Opened 2016-12-01 15:28 UTC by pirapira

I added `null` and `default` as reserved keywords.  I added `assembly` in `grammar.txt` together with the inline assembly grammar.

This fixes #1403.

2016-12-01 22:02 UTC, axic commented on docs/grammar.txt
> +FiveArginstruction = 'log3'
I think this should be with a capital `Instruction`.

2016-12-01 22:02 UTC, axic commented on docs/grammar.txt
> +SevenArginstruction = 'call' | 'callcode'
Same as above.

2016-12-01 22:08 UTC, axic commented
I think we should only declare the syntax for assembly instructions, i.e. keywords and parenthesis.

Having the list there opens up a bigger problem when we have macros available in inline assembly - do we need to define every single one of them in the grammar?

2016-12-02 09:44 UTC, chriseth requested changes

2016-12-02 09:44 UTC, chriseth commented on docs/grammar.txt
> +AssemblyItem = SingleAssemblyInstruction | FunctionalAssemblyExpression | InlineAssemblyBlock | AssemblyLocalBinding | AssemblyAssignment | Identifier | NumbeerLiteral | StringLiteral | HexLiteral
Numbeer

2016-12-02 09:44 UTC, chriseth commented on docs/grammar.txt
> +AssemblyAssignment = Identifier ':=' FunctionalAssemblyExpression | '=:' Identifier
Probably better to move this up. In general, I think the `XArgInstruction` should go to the end.

2016-12-02 10:56 UTC, pirapira commented on docs/grammar.txt
> +AssemblyItem = SingleAssemblyInstruction | FunctionalAssemblyExpression | InlineAssemblyBlock | AssemblyLocalBinding | AssemblyAssignment | Identifier | NumbeerLiteral | StringLiteral | HexLiteral
Fixed.

2016-12-02 10:57 UTC, pirapira commented on docs/grammar.txt
> +AssemblyAssignment = Identifier ':=' FunctionalAssemblyExpression | '=:' Identifier
I moved the `AssemblyAssignment` item above; also I moved the whole inline assembly syntax at the end.

2016-12-02 10:57 UTC, pirapira commented on docs/grammar.txt
> +FiveArginstruction = 'log3'
Fixed.

2016-12-02 10:57 UTC, pirapira commented on docs/grammar.txt
> +SevenArginstruction = 'call' | 'callcode'
Fixed.

2016-12-02 10:58 UTC, pirapira commented
@axic I have a secret plan of following these definitions to generate inline assembly code randomly.  For macros I would just say `Identifier` followed by some arguments.

2016-12-02 11:03 UTC, axic commented
> For macros I would just say `Identifier` followed by some arguments.

The instructions aren't different from that though.

2016-12-02 11:07 UTC, pirapira commented
@axic That's a fair point.  I searched for `send` `call` and `deletetecall` but these don't get special treatments in `grammar.txt` either.  I'll just say `Identifier` followed by parameter list.

2016-12-02 11:20 UTC, pirapira commented
@axic done.

2016-12-02 11:21 UTC, axic commented
It must be noted though there three exceptions in our parser: https://github.com/ethereum/solidity/blob/develop/libsolidity/inlineasm/AsmParser.cpp#L156

`return`, `byte`, `address` is parsed as a keyword and not as an identifier as it needs to be amended for inline assembly.

2016-12-02 11:48 UTC, pirapira commented on docs/grammar.txt
> +AssemblyAssignment = Identifier ':=' FunctionalAssemblyExpression | '=:' Identifier
Even better, now `XArgInstruction`s disappeared.

2016-12-06 09:48 UTC, pirapira commented
@axic `grammar.txt` does not exclude keywords from the possible identifier.

2016-12-06 09:57 UTC, walter-weinmann commented
I think it is quite normal that a grammar specification does not explicitly specify that the use of keywords as an identifier is not allowed.

2016-12-06 12:47 UTC, chriseth approved these changes

2016-12-06 12:47 UTC, merged