Set date for 0.8.23 release
ethereum/solidity pull request #14672
Opened 2023-11-08 09:06 UTC by nikola-matic

Depends on https://github.com/ethereum/solidity/pull/14671

2023-11-08 10:00 UTC, cameel requested changes

2023-11-08 10:00 UTC, cameel commented on Changelog.md
> +### 0.8.23 (2023-11-8)
```suggestion
### 0.8.23 (2023-11-08)
```

2023-11-08 10:00 UTC, cameel commented on docs/bugs_by_version.json
> +        "released": "2023-11-8"
```suggestion
        "released": "2023-11-08"
```

2023-11-08 10:11 UTC, cameel approved these changes

2023-11-08 11:32 UTC, merged

2025-11-29 08:38 UTC, koa3398 commented on Changelog.md
> +### 0.8.23 (2023-11-8)
Fwd:docs@github.dev