Disallow mixin of functions and attributes under the same name
ethereum/solidity pull request #1479
Opened 2016-12-02 15:27 UTC by pirapira

This pull-request bans shadowing of variables by functions, modifiers by functions and so on.  There is one exception that a public function can be overwritten by a public state variable.

2016-12-04 18:24 UTC, VoR0220 commented
I feel like an idiot for asking this but what is "shadowing"?

2016-12-04 19:07 UTC, pirapira commented
@VoR0220  Something in a base class was visible by a name, but in the derived class it's not visible anymore because something else has taken the name.  It's called shadowing because it's like somebody bigger is in front of you and you are not visible in the picture.

2016-12-04 20:46 UTC, VoR0220 commented
Thanks @pirapira

2017-01-03 14:05 UTC, axic commented
@pirapira would it make sense extending the documentation with the edge case (*public function can be overwritten by a public state variable.*)?

2017-01-03 17:13 UTC, chriseth requested changes

2017-01-03 17:13 UTC, chriseth commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +		unique_ptr<FunctionType const> functionType {};
FunctionType is a "shared_from_this" type, i.e. it has a "built-in" `shared_ptr`, so it is probably better to use a `shared_ptr` here.

2017-01-03 17:13 UTC, chriseth commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +				if (FunctionDefinition const* functionDefinition = dynamic_cast<FunctionDefinition const*>(d))
Do you think it makes sense to create a double-dispatch wrapper for this one here? There might be other places where this code is already used.

2017-01-03 17:13 UTC, chriseth commented on test/libsolidity/SolidityNameAndTypeResolution.cpp
> +	// Error: Identifier already declared.
Why don't you use the error string checking feature here?

2017-01-03 17:25 UTC, pirapira commented
@axic I'll do that in this PR.

2017-01-03 17:58 UTC, pirapira commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +		unique_ptr<FunctionType const> functionType {};
I'll change it to `shared_ptr`.

2017-01-03 18:10 UTC, pirapira commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +				if (FunctionDefinition const* functionDefinition = dynamic_cast<FunctionDefinition const*>(d))
I prefer a function that takes two closures.  One closure takes a `FunctionDefinition const&` as an argument while the other takes `VariableDeclaration const&` as an argument.

2017-01-03 18:21 UTC, pirapira commented on test/libsolidity/SolidityNameAndTypeResolution.cpp
> +	// Error: Identifier already declared.
Because two error messages are shown.  I have no expectation about which one comes first and be searched.

2017-01-03 18:42 UTC, pirapira commented on docs/contracts.rst
> +As an exception, a state variable accessor can override a public function.
@axic I'm trying to write something about this.

2017-01-04 12:49 UTC, chriseth commented on docs/contracts.rst
>  .. index:: ! contract;abstract, ! abstract contract
Please move this below the new section.

2017-01-04 12:52 UTC, chriseth requested changes

2017-01-04 12:52 UTC, chriseth commented on docs/contracts.rst
> +When an inheritance chain contains a function and a modifier of the same name, it is considered as an error.
What do you mean by "inheritance chain" here? Can this be rephrased as something like "when inheritance would result in a contract having..."?

2017-01-05 13:52 UTC, pirapira commented
@chriseth now I remember why I used `unique_ptr`, because otherwise emscripten build fails.  Shall I go back to `unique_ptr`, or shall I somehow try to fix the emscripten build with `shared_ptr` here?

```
/emsdk_portable/emscripten/tag-1.35.4/system/include/libcxx/memory:3997:35: error: no viable overloaded '='

                __e->__weak_this_ = *this;

                ~~~~~~~~~~~~~~~~~ ^ ~~~~~

/emsdk_portable/emscripten/tag-1.35.4/system/include/libcxx/memory:4275:9: note: in instantiation of function template specialization 'std::__1::shared_ptr<const dev::solidity::FunctionType>::__enable_weak_this<dev::solidity::Type>' requested here

    __r.__enable_weak_this(__r.__ptr_);

        ^
```

2017-01-05 14:35 UTC, pirapira commented on test/libsolidity/SolidityNameAndTypeResolution.cpp
> +	// Error: Identifier already declared.
I had a discussion with @chriseth and the conclusion was to have a method `Declaration::funcitonType()`.

2017-01-05 15:11 UTC, pirapira commented
So I moved back to `unique_ptr`.

2017-01-09 11:19 UTC, chriseth commented
Can you add a changelog entry, please?

2017-01-10 15:38 UTC, pirapira commented
I forgot that events have function types too.

2017-01-11 17:52 UTC, pirapira commented
Remaining issues
* The second argument of `FunctionType()` is sometimes necessary
* The new parameter should also be called `_external` (or `_inernal`?), the same way as the second argument of `FunctionType()`.

2017-01-12 17:51 UTC, pirapira commented
@chriseth can this be merged?

2017-01-13 08:35 UTC, chriseth approved these changes

2017-01-13 08:36 UTC, merged