Shift operators
ethereum/solidity pull request #1487
Opened 2016-12-05 17:43 UTC by chriseth

Replaces https://github.com/ethereum/solidity/pull/527

2016-12-05 17:44 UTC, chriseth commented
Still work in progress. Changes in Types.cpp should already be final.

2016-12-05 21:15 UTC, axic commented
Too bad we lost history in git :(

2016-12-06 12:34 UTC, chriseth commented
@axic there were about 20 commits covering 50 lines of code and the majority of these 50 lines need to be changed again, that's why I squashed the commits.

2016-12-09 16:13 UTC, pirapira commented
Types.cpp looks good to me.

2016-12-10 06:35 UTC, federicobond commented on docs/types.rst
> +The shifting operator wors with any integer type as right operand (bit will
works

2016-12-13 14:39 UTC, pirapira commented on docs/types.rst
> +* Bit operators: ``&``, ``|``, ``^`` (bitwise exclusive or), ``~`` (bitwise negation), ``<<`` (left shift), ``>>`` (right shift)
I think the shifts are arithmetic operators, given that they extends signs.

2016-12-13 14:39 UTC, pirapira commented on docs/types.rst
> +* Bit operators: ``&``, ``|``, ``^`` (bitwise exclusive or), ``~`` (bitwise negation), ``<<`` (left shift), ``>>`` (right shift)
Here it's fine they are listed under bit operations.

2016-12-13 14:40 UTC, pirapira commented on docs/types.rst
> +The shifting operator wors with any integer type as right operand (bit will
also, bit -> but

2016-12-13 14:40 UTC, pirapira commented on docs/types.rst
> +sign extends. Shifting by a negative amount throws an exception.
Maybe `a runtime exception` as in the other paragraph.

2016-12-13 14:42 UTC, pirapira commented on docs/types.rst
> +
I'm wondering if shifts are counted by bytes or bits.

2016-12-13 14:59 UTC, pirapira commented on libsolidity/codegen/ExpressionCompiler.cpp
> +		Token::Value targetOp = Token::AssignmentToBinaryOp(op);
Is this the same as `binOp`?

2016-12-13 15:01 UTC, pirapira commented on libsolidity/codegen/ExpressionCompiler.cpp
> +	m_currentLValue->storeValue(*rightIntermediateType, _assignment.location());
I think this should be the `leftType`.

2016-12-13 15:36 UTC, pirapira commented on libsolidity/codegen/ExpressionCompiler.cpp
> +	m_currentLValue->storeValue(*rightIntermediateType, _assignment.location());
I added tests witnessing this.

2016-12-13 15:38 UTC, pirapira requested changes
The one about `storeValue`ed type is crucial, I think.

2016-12-13 16:03 UTC, chriseth commented
@pirapira your tests were wrong ;-) But I think the issue was still a real issue - should be fixed now.

2016-12-13 16:09 UTC, pirapira approved these changes

2016-12-13 16:09 UTC, pirapira commented
Looks good to me now.  Waiting for CIs.

2016-12-14 15:31 UTC, merged