Absolute path
ethereum/solidity pull request #1537
Opened 2017-01-02 15:50 UTC by pirapira

When paths are parsed, `.dir` is now considered as an absolute path.  This change fixes the disagreement of the doc and the implementation, as observed in #1534.

2017-01-02 15:51 UTC, pirapira commented
Are there any good ways to test private methods?

2017-01-03 09:32 UTC, chriseth requested changes

2017-01-03 09:32 UTC, chriseth commented on libsolidity/interface/CompilerStack.cpp
> +	size_t slashPos { _path.find_first_of('/') };
I think it is better to consistently use `boost::filesystem::path` throughout this function, i.e. first parse the whole path into a `boost::filesystem::path` (as done in line 600 / 605) and then just check for `p[0] == "." || p[0] == ".."`.

2017-01-03 09:33 UTC, chriseth commented
You could add a test that does something like `import ".file"`.

2017-01-03 13:44 UTC, pirapira commented on libsolidity/interface/CompilerStack.cpp
> +	size_t slashPos { _path.find_first_of('/') };
`boost::filesystem::path` has no `[]` operator.  I haven't found anything useful in the library.

2017-01-03 14:02 UTC, axic commented on docs/layout-of-source-files.rst
> +All path names are treated as absolute paths unless they start with the current ``.`` or the parent direcoty ``..``.
"direcoty" -> "directory"

2017-01-03 16:55 UTC, chriseth commented on libsolidity/interface/CompilerStack.cpp
> +	size_t slashPos { _path.find_first_of('/') };
What about `*p.begin()`?

2017-01-03 17:03 UTC, pirapira commented on libsolidity/interface/CompilerStack.cpp
> +	size_t slashPos { _path.find_first_of('/') };
I see.  Looks like it will do.

2017-01-03 17:48 UTC, pirapira commented on docs/layout-of-source-files.rst
> +All path names are treated as absolute paths unless they start with the current ``.`` or the parent direcoty ``..``.
Fixed.

2017-01-03 17:48 UTC, pirapira commented
@chriseth I added such a test.

2017-01-05 17:29 UTC, pirapira commented
@chriseth I think this one is ready.

2017-01-06 14:59 UTC, chriseth approved these changes

2017-01-06 14:59 UTC, chriseth commented
Could you add a changelog entry?

2017-01-06 16:11 UTC, merged