docs fix spelling issues
ethereum/solidity pull request #15452
Opened 2024-09-25 11:55 UTC by nnsW3

Hello
I fixed several minor spelling issues to ensure a better understanding.
Br, Elias.

2024-09-25 12:02 UTC, cameel requested changes

2024-09-25 12:02 UTC, cameel commented on docs/contracts/functions.rst
> +    is present. It is recommended to always define a received Ether
This one is not a typo. It's about a function literally named `receive`. If it's unclear, we may be better off rewording and putting it in backticks.

2024-09-25 12:02 UTC, cameel commented on docs/grammar/SolidityParser.g4
> + * A continued statement. Only allowed inside for, while or do-while loops.
This one too. We have a `continue` keyword in the language and this refers to it. You can actually see it defined below.

2024-10-08 07:31 UTC, nikola-matic commented
Hey @nnsW3, we generally don't accept typo fix PRs unless they're immediately ready to merge, so I'll be closing this.

2024-10-08 07:31 UTC, closed without merging