Type checking for contract explicit storage base location
ethereum/solidity pull request #15528
Opened 2024-10-21 01:36 UTC by matheusaaguiar

- [ ] depends on #15463.

2024-10-21 09:01 UTC, nikola-matic commented on libsolidity/parsing/Parser.cpp
> +		m_scanner->currentToken() != Token::Identifier ||
Identifier check is redundant here - it'll throw a fatal parsing error in `expectToken(...)` if it's not an identifier.

2024-10-21 14:02 UTC, matheusaaguiar commented on libsolidity/parsing/Parser.cpp
> +		m_scanner->currentToken() != Token::Identifier ||
This was part of a commit from the parser PR, but I forgot to set it as base branch when pushing this PR.
I will link your comment in the other PR and reply from there.

2024-12-02 13:48 UTC, stackenbotten commented on libsolidity/analysis/TypeChecker.cpp
> +
Coding style error

2024-12-02 13:48 UTC, stackenbotten commented on libsolidity/analysis/TypeChecker.cpp
> +
Coding style error

2025-02-07 14:01 UTC, cameel commented on Changelog.md
> + * Introduce syntax for specifying contract storage layout base.
Why change it here and not in the base PR?

2025-02-07 14:02 UTC, cameel commented on libsolidity/analysis/TypeChecker.cpp
> +	);
```suggestion
	if ((_contract.isLibrary() || _contract.abstract()) && _contract.storageLayoutSpecifier())
		m_errorReporter.typeError(
			7587_error,
			_contract.storageLayoutSpecifier()->location(),
			"Storage layout cannot be specified for abstract contracts or libraries"
		);
```

2025-02-07 14:16 UTC, matheusaaguiar commented on Changelog.md
> + * Introduce syntax for specifying contract storage layout base.
I guess I mixed the PRs :sweat_smile:

2025-02-07 14:25 UTC, matheusaaguiar commented on Changelog.md
> + * Introduce syntax for specifying contract storage layout base.
Actually, I think this is appearing here because this PR is out of sync with the base PR...

2025-02-07 21:50 UTC, cameel requested changes
Two main issues: layout on interfaces is not disallowed and also the issue unnecessarily restricts that a contract can only be inherited from once when there's a layout.

I also think that it would be good to move checks to parts of analysis other than `TypeChecker`. It seems perfectly feasible for this particular feature and `TypeChecker` is already a beast.

Other than that the usual stuff. Especially tests.

2025-02-07 21:50 UTC, cameel commented on libsolidity/ast/ASTAnnotations.h
> +	solidity::u256 value;
This is a pretty bad name :)

Also we're inside the `solidity` namespace here.

```suggestion
	u256 baseSlot;
```

2025-02-07 21:50 UTC, cameel commented on libsolidity/analysis/TypeChecker.cpp
> +	if ((_contract.isLibrary() || _contract.abstract()) && _contract.storageLayoutSpecifier())
What about interfaces?

2025-02-07 21:50 UTC, cameel commented on test/libsolidity/syntaxTests/storageLayoutSpecifier/same_ancestor_two_contracts.sol
> +// TypeError 2031: (46-77): Conflicting storage layout specifications:Storage layout for base contract 'A' was also specified by another contract which derives from it.
This is a perfectly valid case.

The `derivedContractSpecifyingStorageLayout` annotation seems to have been added just to check for it. You don't need it or the check. A contract that's not at the top-level of the hierarchy can be a part of multiple layouts.

2025-02-07 21:50 UTC, cameel commented on libsolidity/analysis/TypeChecker.cpp
> +			"The storage layout must be specified by an expression that can be evaluated at compilation time."
```suggestion
			"The base slot of the storage layout must be a compile-time constant expression."
```

2025-02-07 21:50 UTC, cameel commented on libsolidity/analysis/TypeChecker.cpp
> +	BoolResult result = expressionType->isImplicitlyConvertibleTo(*TypeProvider::uint256());
```suggestion
	auto const* baseSlotExpressionType = type(*baseLocation);
	BoolResult convertibleToUint = expressionType->isImplicitlyConvertibleTo(*TypeProvider::uint256());
```

2025-02-07 21:50 UTC, cameel commented on libsolidity/analysis/TypeChecker.cpp
> +	if (auto const* rationalType = dynamic_cast<RationalNumberType const*>(expressionType))
IMO you should check this first, then fractionals, then range. Finally just assert that the value is convertible to `uint` and evaluate the value. This will make the message in most weird cases very clear (it's not a number literal). Currently you get a message about exceeding `uint` range in many weird cases, which suboptimal.

Later, when we open the functionality up to non-literals, we'll replace the assert with a message saying that type X is not implicitly convertible, which should also be clear.

2025-02-07 21:50 UTC, cameel commented on libsolidity/analysis/TypeChecker.cpp
> +		_storageLayoutSpecifier.annotation().value = u256(rationalType->value().numerator());
Note that `u256()` conversion just truncates and does not throw when the value is out of range. You only indirectly check that it's in range, so you should also assert that it really is.

Also assert that denominator is in fact 1.

2025-02-07 21:50 UTC, cameel commented on libsolidity/ast/ASTAnnotations.h
> +	solidity::u256 value;
Also, you should make it `SetOnce`.

2025-02-07 21:50 UTC, cameel commented on libsolidity/analysis/TypeChecker.cpp
> +	if (!*baseLocation->annotation().isPure)
These checks would probably be better off in `PostTypeChecker`/`PostTypeContractLevelChecker`. `TypeChecker` is a beast already (4k+ lines) and we seem to be dumping everything in it :)

The checks and the annotation do not seem to be things that other checks will need to depend on so it should be fairly straightforward to move them. To the contrary - they use `isPure` annotation, which is fully filled out only after `TypeChecker`. We're in `endVisit()` so it should already be set on the expression, but still, it would be cleaner if all of it was not crammed into the same analysis pass.

2025-02-07 21:50 UTC, cameel commented on libsolidity/analysis/TypeChecker.cpp
> +	if (!*baseLocation->annotation().isPure)
Similarly, verifying that base contracts do not have layout specifiers seems like something that can be checked already by `ContractLevelChecker` and does not have to wait until we know the types.

2025-02-07 21:50 UTC, cameel commented on test/libsolidity/syntaxTests/storageLayoutSpecifier/layout_with_inheritance.sol
> +contract D layout at 0xABCD is Z { }
This should be changed back.

2025-02-07 21:50 UTC, cameel commented on test/libsolidity/syntaxTests/storageLayoutSpecifier/simple_layout.sol
Needs more tests. There's quite a few, but note that many of these will be simple one-liners and you can usually drop everything from one bullet point into one file because errors are not fatal.

The most necessary minimum:
- Numbers with denominations (`42 weeks`, `666 gwei`)
- Rational numbers with zero fractional part (`42.0`, `2.5e10`)
- Interface with a layout
- `layout at 1 / 0`
- `layout at -1`

Scoping
- Constants defined in inherited contracts
- State variables defined in inherited contracts
- Things defined in foreign contracts

Inheritance
- Contract with a layout inheriting from an abstract contract/interface
- Contract with a layout inheriting from itself
- Inheriting from multiple contracts where first/last already has layout

Things that are now rejected but will have to work eventually so we may as well cover them already:
- `type(uint).max`
- `uint(42)`
- `uint40(bytes5(hex"0011223344"))`
- `~uint(0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF)`
- `[1, 2, 3][0]`
- `string("ABCD").length`
- `abi.decode(abi.encode(42), (uint))`
- `uint(bytes32(type(I).interfaceId))`
- `uint32(f.selector)`
- `uint64(bytes8(bytes.concat("ABCD", "EFGH")))`
- `uint(keccak256(bytes.concat("ABCD"))`
- `uint8(b[1])`, where `b` is `bytes32 constant b`
- `N / ~N` where `N` is a constant.
- Ternary operator
- `T.unwrap()`

Wild things that should not work:
- `N / 0` where `N` is a constant
- Expressions that would overflow in checked arithmetic
- Expressions using custom operators defined on `uint`
- Various non-`uint` literals: address, hex string, string, boolean, enum, `[1, 2, 3]`, `(1, 2, 3)`
- `++2`, `1 = 2`, `delete 2`
- `T.wrap()`
- `f.selector`, `f.address`
- Builtins that depend on state: `blockhash()`, `block.chainid`, `block.number`, `msg.value`, `tx.gasprice`, `<address>.balance`, etc. Especially those that return `uint`.
- Precompiles returning `uint`: `addmod()` etc.
- Bound pure library function called on a literal (`1.f()`)
- Weird stuff: error, event, module, contract, type, magic, etc.
- `address(new C())`
- `uint160(address(this))`

2025-02-17 13:53 UTC, cameel commented
Needs rebase.

2025-02-19 12:46 UTC, cameel commented on libsolidity/analysis/ContractLevelChecker.cpp
> +		(_contract.isLibrary() || _contract.abstract() || _contract.isInterface()) &&
Since #15463 rejects libraries and interfaces during parsing now, you can just assert against them here. Abstract contracts are the only case that can reach type checking stage.

2025-02-19 17:26 UTC, cameel commented on libsolidity/analysis/TypeChecker.cpp
The new includes here are no longer needed.

2025-02-19 17:26 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +			solAssert(rationalType->value().numerator() <= u256(-1));
`rational` is signed, so you need to assert the lower bound too.

2025-02-19 17:26 UTC, cameel commented on test/cmdlineTests/storage_layout_already_defined_in_ancestor/input.json
Tests for secondary messages would be much less verbose if they weren't using Standard JSON.

2025-02-19 17:26 UTC, cameel commented on test/libsolidity/syntaxTests/storageLayoutSpecifier/simple_cast.sol
> +// TypeError 6396: (22-30): The storage layout can only be specified by number literals.
`stopAfter` is not needed here and in other tests that error out.

2025-02-19 17:26 UTC, cameel commented on test/libsolidity/syntaxTests/storageLayoutSpecifier/function_selector.sol
> +contract C layout at uint32(f.selector) {}
This one is supposed to work eventually, so please use something that actually has a selector. For example:

```suggestion
contract A {
    function f() public {}
}
contract C is A layout at uint32(this.f.selector) {}
```

In general for those tests you should get the error saying it's not a literal if done right.

2025-02-19 17:26 UTC, cameel commented on test/libsolidity/syntaxTests/storageLayoutSpecifier/layout_specified_by_function_with_call_options.sol
> +contract C layout at f{a: 2, b: 3}() { }
Let's use a function for which call options are actually valid:

```suggestion
contract A {
    function f() external pure returns (uint) {}
}    
contract C is A layout at this.f{value: 123}() {}
```

I'd also put this change already in the parsing PR.

2025-02-19 17:26 UTC, cameel commented on test/libsolidity/syntaxTests/storageLayoutSpecifier/simple_cast.sol
> +// TypeError 6396: (22-30): The storage layout can only be specified by number literals.
TBH I'm not sure it's a good idea to even use this option at all unless one of the later stages runs into an ICE. If you don't remove/update it, the test will still pass even if the later stage has a bug and it's hard to check in a review if they have been all removed as needed.

We used it in the past as a necessity because unimplemented errors were ICEs but that's no longer the case.

2025-02-19 17:26 UTC, cameel commented on test/libsolidity/syntaxTests/storageLayoutSpecifier/string_length_member.sol
> +contract C layout at string("ABCD").length {}
Oh, apparently we don't have `.length` member on strings.

```suggestion
contract C layout at bytes("ABCD").length {}
```

2025-02-19 17:26 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +			solAssert(rationalType->value().numerator() <= u256(-1));
Also:
```suggestion
			solAssert(rationalType->value().numerator() <= std::numeric_limits<u256>::max());
```

2025-02-19 17:30 UTC, cameel commented on libsolidity/analysis/TypeChecker.cpp
> +	if (auto const* rationalType = dynamic_cast<RationalNumberType const*>(expressionType))
The way it is now is better, bit you're still not checking the range explicitly. I think that would be better. In fact, looking at test cases, including the message saying why the value is not convertible is redundant (and maybe even confusing) in case of simple rationals and expressions on them.

2025-02-19 17:33 UTC, cameel commented on libsolidity/analysis/TypeChecker.cpp
> +	if (auto const* rationalType = dynamic_cast<RationalNumberType const*>(expressionType))
The way these checks are done could also be refactored a bit. Currently it's a bunch of nested `if`s, but you could just check things sequentially, with a return if you run into an error. The last thing in the function should be the default path, which is the assignment of `annotation().baseSlot`.

2025-02-19 17:37 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +			"The storage layout can only be specified by number literals."
```suggestion
			"The base slot of the storage layout must evaluate to a rational number."
```

2025-02-19 17:38 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +			"The storage layout can only be specified by number literals."
Also, not sure if there's much point in sharing the prefix of the error messages above. I'd simply repeat it in each messsage, it's not that long. It's generally easier to grep for messages in the code when they're in one chunk. You can use fmtlib to make it even less disjoint.

2025-02-20 21:34 UTC, matheusaaguiar commented on libsolidity/analysis/TypeChecker.cpp
> +	if (auto const* rationalType = dynamic_cast<RationalNumberType const*>(expressionType))
I think now I have adjusted as per your suggestions.

2025-02-24 13:21 UTC, cameel approved these changes
I have just one suggestion on how to make the error reporting less annoying. It's not critical to the PR and everything else seems to have been addressed to I'm approving regardless of that. It's simple to fix so I think we should still do that though.

There were a few minor things in tests/messages that needed minor adjustments/cleanup but I decided to just push them as fixups to avoid stalling the PR. Please take a look and squash if you accept them.

2025-02-24 13:21 UTC, cameel commented on libsolidity/analysis/ContractLevelChecker.cpp
> +			);
Looking at test output, the errors generated by this may be a bit annoying. It reports an error for every specifier in the hierarchy of every contract, which may be a lot. Consider this example:

```solidity
contract A      layout at 1 {}
contract B is A layout at 2 {}

contract C1 is B {}
contract C2 is A, B {}
contract C3 is B {}

contract D1 is C1 {}
contract D2 is C2 {}
contract D3 is C3 {}
```

You'll get 13 error messages here. I think it would be more useful to only report an error when a contract directly inherits from one with a layout specifier. The point where a fix needs to be applied is unlikely to be far from the specifier. It's either the specifier itself being applied to the wrong contract (secondary messages already point at this) or the first contract that inherits from it (that's what the primary message should point at). This would reduce the number of messages here to 5.

This should be very easy to implement simply by iterating over `baseContracts()` rather than the whole `annotation().linearizedBaseContract`. We could then point at the exact inheritance specifier that triggered the error rather than whole contract definition (`baseContracts()` contains specifiers rather than contract definitions, and we can easily report their locations).

We should also have the above as a test case.

2025-02-24 14:39 UTC, cameel commented
As discussed on the call, we can just merge this and do https://github.com/ethereum/solidity/pull/15528#discussion_r1967472244 as a separate PR on top.

Please remember to squash the fixups though :)

2025-02-24 16:10 UTC, cameel commented
I see you squashed it all into one commit :) No need to go that extreme, I left it in a state that would nicely autosquash into 3 clean commits without conflicts and with test additions being done first and the effect of code changes visible separately. That's generally a structure that I'd recommend and much prefer over it being smooshed together. Can you restore that version?

2025-02-24 18:31 UTC, cameel approved these changes

2025-02-26 13:55 UTC, merged

2025-02-28 03:25 UTC, matheusaaguiar commented on libsolidity/analysis/ContractLevelChecker.cpp
> +			);
Addressed in #15900.