Fix verbatim control flow size effects.
ethereum/solidity pull request #15542
Opened 2024-10-23 09:59 UTC by rodiazet

- Reasoning: https://github.com/ethereum/solidity/pull/15535#discussion_r1811557042

2024-10-24 18:22 UTC, matheusaaguiar commented on libyul/backends/evm/EVMDialect.cpp
> +	// Worse control flow side effects because verbatim can do anything.
```suggestion
	// Worst control flow side effects because verbatim can do anything.
```

2024-10-24 18:35 UTC, matheusaaguiar reviewed
Just a nitpick. And also, @cameel mentioned a changelog entry, but I am not sure about the actual bug he referred to.

2024-10-24 19:28 UTC, rodiazet commented on libyul/backends/evm/EVMDialect.cpp
> +	// Worse control flow side effects because verbatim can do anything.
fixed.

2024-10-24 19:29 UTC, rodiazet commented
> Just a nitpick. And also, @cameel mentioned a changelog entry, but I am not sure about the actual bug he referred to.

Also not sure. Typo fix pushed.

2024-10-25 02:04 UTC, cameel commented
#15535 is merged so now we can pass these via the parameter we added there.

2024-10-25 02:11 UTC, cameel requested changes
We discussed this bug on Wednesday and we do think that this may cause actual problems in the optimizer. E.g. UnusedStoreEliminator might mistakenly remove a store operation assuming that the code will revert, while a verbatim block actually makes it terminate successfully.

We need a repro test case to confirm it. I think that something like [`store_before_conditionally_terminating_function_call_revert.yul`](https://github.com/ethereum/solidity/blob/develop/test/libyul/yulOptimizerTests/unusedStoreEliminator/store_before_conditionally_terminating_function_call_revert.yul) should do it if you replace the `conditionallyStop()` call with a verbatim block that uses `RETURN`.

Still, we decided that we'll not treat it as an important bug (i.e. no blog post and no bug list entry, just a normal changelog entry), because doing something like this actually violates the prescribed usage rules for `verbatim`:

> - Control-flow should not jump into or out of verbatim blocks, but it can jump within the same verbatim block.

Instead, we should add a warning in [`verbatim` docs](https://docs.soliditylang.org/en/develop/yul.html#verbatim) saying that until 0.8.28 `verbatim` had this flaw. We could also clarify the point above to specifically say that reverting and returning within `verbatim` are not allowed.

2024-10-28 12:18 UTC, rodiazet commented
> We discussed this bug on Wednesday and we do think that this may cause actual problems in the optimizer. E.g. UnusedStoreEliminator might mistakenly remove a store operation assuming that the code will revert, while a verbatim block actually makes it terminate successfully.
> 
> We need a repro test case to confirm it. I think that something like [`store_before_conditionally_terminating_function_call_revert.yul`](https://github.com/ethereum/solidity/blob/develop/test/libyul/yulOptimizerTests/unusedStoreEliminator/store_before_conditionally_terminating_function_call_revert.yul) should do it if you replace the `conditionallyStop()` call with a verbatim block that uses `RETURN`.
> 
> Still, we decided that we'll not treat it as an important bug (i.e. no blog post and no bug list entry, just a normal changelog entry), because doing something like this actually violates the prescribed usage rules for `verbatim`:
> 
> > * Control-flow should not jump into or out of verbatim blocks, but it can jump within the same verbatim block.
> 
> Instead, we should add a warning in [`verbatim` docs](https://docs.soliditylang.org/en/develop/yul.html#verbatim) saying that until 0.8.28 `verbatim` had this flaw. We could also clarify the point above to specifically say that reverting and returning within `verbatim` are not allowed.

I added such a test but even without this fix it passes. After debugging of `UnusedStoreEliminator` I guessing the it works because in `UnusedStoreEliminator::applyOperation` the store considered as read from by the verbatim after it.

2024-10-29 16:56 UTC, cameel commented
Nice. I looked at the implementation and I think you're right. So we're safe here. In that case we do not need the changelog entry or the warning.

I'd still add the test case though, even if it does not fail. Best to have this corner case covered.

And we should till clarify the docs to say that reverting and returning within verbatim are not allowed.

2024-10-31 12:11 UTC, rodiazet commented
> Nice. I looked at the implementation and I think you're right. So we're safe here. In that case we do not need the changelog entry or the warning.
> 
> I'd still add the test case though, even if it does not fail. Best to have this corner case covered.
> 
> And we should till clarify the docs to say that reverting and returning within verbatim are not allowed.

Test added, but I don't fully get why it's not allowed to return or revert in verbatim.

2024-11-21 20:32 UTC, cameel submitted a review, later dismissed
Looks good, but I have two small suggestions.

2024-11-21 20:32 UTC, cameel commented on docs/yul.rst
> +- Reverting and returning within verbatim are *not* allowed.
I'd merge it with the previous point. It's really a consequence of it.
```suggestion
  In particular, reverting or returning from the block is *not* allowed.
```

2024-11-21 20:32 UTC, cameel commented on test/libyul/yulOptimizerTests/unusedStoreEliminator/store_before_terminating_verbatim_revert.yul
> +    revert(0,0)
Let's add some comments to make sure it's clear what the test is about:

```suggestion
    // opcodes: PUSH1 0x00 DUP1 RETURN
    // SSTORE is not redundant due to the RETURN hidden in the verbatim block. It must not be removed.
    verbatim_0i_0o(hex"600080F3")
    revert(0, 0)
```

2024-11-22 12:21 UTC, cameel commented on docs/yul.rst
> +- In particular, reverting or returning from the block is *not* allowed.
Note that in https://github.com/ethereum/solidity/pull/15542#discussion_r1852823712 this was supposed to be merged with the bullet point above.

```suggestion
  In particular, reverting or returning from the block is *not* allowed.
```

2024-11-22 12:21 UTC, cameel approved these changes, later dismissed

2024-11-22 12:31 UTC, cameel approved these changes

2024-11-22 13:03 UTC, merged