eof: Update `yulSyntaxTests` tests for EOF
ethereum/solidity pull request #15660
Opened 2024-12-19 10:09 UTC by rodiazet

- Disable test which don't make sense for EOF bytecode format.
- Create EOF yul syntax tests counterparts.

2024-12-20 23:16 UTC, cameel requested changes
Just like in #15661, there are better ways to resolve some of these than just disabling them on EOF.

2024-12-20 23:16 UTC, cameel commented on test/libyul/yulSyntaxTests/builtin_function_literal.yul
We should have a version of this for EOF, using one of the EOF builtins, e.g. `auxdataloadn()`.

2024-12-20 23:16 UTC, cameel commented on test/libyul/yulSyntaxTests/hex_switch_case.yul
Same situation as https://github.com/ethereum/solidity/pull/15661#discussion_r1894328821: replace `codesize()` with `calldataload(0)` and it will work on EOF too.

Same for `hex_switch_case_long.yul` and `string_literal_switch_case.yul`.

2024-12-20 23:16 UTC, cameel commented on test/libyul/yulSyntaxTests/metadata_access.yul
We should have a test for accessing `.metadata` (and more generally data starting with a dot like in `metadata_access_2.yul` and `metadata_access_subobject.yul`) with `auxdataloadn()`. Is it actually disallowed as it should?

2024-12-20 23:16 UTC, cameel commented on test/libyul/yulSyntaxTests/metadata_access.yul
We should have EOF variants of these as well (using `auxdataloadn()`):
- `data.yul` (accessing data objects longer than 32-bytes or using hex)
- `subobject_access.yul` (accessing non-data objects - should be forbidden)
- accessing data nested more than one level.

2024-12-20 23:16 UTC, cameel commented on test/libyul/yulSyntaxTests/opcode_for_function_args_1.yul
These three `opcode_for_function*.yul` tests will work fine with EOF if you switch to an opcode that's available on both EOF and legacy. E.g. `mload`.

2024-12-20 23:16 UTC, cameel commented on test/libyul/yulSyntaxTests/builtin_function_literal.yul
Same with `passing_builtin_with_literal_argument_into_literal_argument.yul`.

2024-12-20 23:16 UTC, cameel commented on test/libyul/yulSyntaxTests/selfdestruct.yul
Disabling tests for legacy-only opcodes here is fine, but just a reminder that we'll still need to have them covered eventually, just the way I listed in https://github.com/ethereum/solidity/pull/15559#discussion_r1873671693.

2024-12-20 23:16 UTC, cameel commented on test/libyul/yulSyntaxTests/hex_switch_case.yul
And the three `opcode_for_function*.yul` tests will work fine with EOF if you switch from `gas` to `mload` for example.

2024-12-20 23:50 UTC, cameel commented on test/libyul/yulSyntaxTests/selfdestruct.yul
Actually, while that test is not critical, we still haven't fixed the underlying issue. Those identifiers are still reserved in Yul and we absolutely have to fix that before the next release. I created an issue so that it does not get forgotten: #15672.

2025-01-07 14:50 UTC, rodiazet commented on test/libyul/yulSyntaxTests/metadata_access.yul
I'm not sure I follow. `auxdataloadn` accepts only number literal for now. So all these tests will just report an error saying about wrong literal type. Is it what you expect?

2025-01-21 22:57 UTC, cameel reviewed
The things I pointed out are now fixed but there's one more test needs to be adjusted (it was it either added after my last review or I missed it somehow).

2025-01-21 22:57 UTC, cameel commented on test/libyul/yulSyntaxTests/simple_functions.yul
`msize()` does not seem crucial in this test. Let's replace it with, say `balance()` and the test should pass on EOF as well.

2025-01-21 22:57 UTC, cameel commented on test/libyul/yulSyntaxTests/metadata_access.yul
Ah, right. I missed the fact that none of the builtins we added so far allows accessing Yul objects by name. `auxdataloadn()` uses byte offsets and `eofcreate()` only allows accessing code objects. I guess we have to skip these on EOF after all.

2025-01-22 14:27 UTC, rodiazet commented
I haven't added anything since your last review I think

2025-01-22 14:33 UTC, rodiazet commented on test/libyul/yulSyntaxTests/simple_functions.yul
Fixed.

2025-01-22 19:35 UTC, cameel approved these changes
Looks good now. Please squash the fixes and we can merge.

2025-01-28 10:16 UTC, rodiazet commented
Squashed and rebased. We can merge now.

2025-01-28 21:38 UTC, cameel approved these changes

2025-01-28 21:38 UTC, merged