eof: Semantic tests update
ethereum/solidity pull request #15665
Opened 2024-12-19 15:20 UTC by rodiazet

- Disable some which don't make sense for EOF.
- Modify tests to make them EOF compatible and move them to separated folders
- Adjust test expectation to avoid using deployed contract address as it can change between optimized and non-optimized versions for EOF

2025-01-24 02:35 UTC, cameel requested changes
I found one case where disabling the test actually hides broken behavior (`delete` on an external function pointer).

In most other cases I commented on we need an EOF version or a TODO to mark the test to be dealt with later.

There were also many tests where a separate EOF version was not really necessary - we can avoid duplication by adjusting the original to work on both EOF and legacy. I actually did that myself while going over the PR (see #15768) so you only need to rebase on that, remove the unnecessary copies for EOF and re-enable the original tests.

2025-01-24 02:35 UTC, cameel commented on test/libsolidity/semanticTests/constructor/eof/no_callvalue_check.sol
> +// gas legacyOptimized code: 4800
Please remove gas expectations when you're creating EOF versions of tests. We're not calculating them for EOF and I think they're not even checked for correctness here (because `legacy` is skipped) so they're misleading.

2025-01-24 02:35 UTC, cameel commented on test/libsolidity/semanticTests/constructor/callvalue_check.sol
This one is currently hard to recreate on EOF because we're planning to disallow `eofcreate()` (and without assembly this will be just a compilation error), but we should have it eventually. Please add a TODO.

2025-01-24 02:35 UTC, cameel commented on test/libsolidity/semanticTests/externalContracts/eof/deposit_contract.sol
What was wrong with this one? It passes for me on both EOF and legacy.

I see that the only changes here are the gas cost expectations, but those are not enforced on EOF/Prague so the test should not be failing just because of that.

2025-01-24 02:35 UTC, cameel commented on test/libsolidity/semanticTests/functionCall/eof/call_options_overload.sol
> +        z = this.f{value: 10}(2, 3);
We only have one option to test now so only two combinations really make sense. The rest is redundant:
```suggestion
    function call() public payable returns (uint x, uint y) {
        x = this.f{value: 10}(2);
        y = this.f{value: 10}(2, 3);
```

2025-01-24 02:35 UTC, cameel commented on test/libsolidity/semanticTests/functionTypes/eof/function_external_delete_storage.sol
> +// incrementIndirectly() ->
This one is actually broken on EOF, and only passes because the expectations are wrong. Note that the original test expected a revert here (due to `x` being reset to `0` by `delete`). Looks like the function pointer is not being reset properly on EOF.

2025-01-24 02:35 UTC, cameel commented on test/libsolidity/semanticTests/isoltestTesting/eof/balance_other_contract.sol
> +// checkBalance() -> true
The whole point of this test was to make sure the `balance` helper provided by soltest works. It's pointless if you don't use it :)

2025-01-24 02:35 UTC, cameel commented on test/libsolidity/semanticTests/events/event_emit_from_other_contract.sol
This one should have an EOF version.

2025-01-24 02:35 UTC, cameel commented on test/libsolidity/semanticTests/deployedCodeExclusion/subassembly_deduplication.sol
All the tests from `semanticTests/deployedCodeExclusion/` should have a TODO to eventually be recreated on EOF. They're testing subassembly deduplication, which is still relevant, just not implemented yet. Also, we likely won't be able to test it like this because we lose access to code introspection, but it could be checked by looking at produced bytecode in a commandline test. Or even better, by using the new artifact introduced by #15710 to directly check which assemblies were included.

2025-01-24 02:35 UTC, cameel commented on test/libsolidity/semanticTests/various/code_access_create.sol
Needs a TODO. I think that deploying a contract via `eofcreate` when you can reference it by name should be possible eventually, though not sure yet what the syntax would be.

Definitely not by getting its bytecode and passing it to assembly. Perhaps we should instead make `eofcreate()` take subcontainer index (rather than Yul object name) and allow accessing that index on `type(D)`? just like you currently can access `creationCode`?

2025-01-24 02:35 UTC, cameel commented on test/libsolidity/semanticTests/events/event_emit_from_other_contract.sol
Same for:
- `functionCall/calling_nonexisting_contract_throws.sol`
- `functionCall/external_call_at_construction_time.sol`
- `functionCall/external_call_to_nonexisting.sol`

We should just expect them not to revert on EOF. Does not need to be a copy of these tests, can also be a new one that combines all the relevant points from those.

2025-01-24 02:35 UTC, cameel commented on test/libsolidity/semanticTests/events/event_emit_from_other_contract.sol
Also:
- `salted_create/prediction_example.sol`: calculation on EOF is different, but should still be covered.
- `various/create_calldata.sol`: on EOF the calldata accessible via `msg.data` does contain constructor arguments and this should be tested.

2025-01-24 02:41 UTC, cameel commented on test/libsolidity/semanticTests/builtinFunctions/eof/keccak256_packed_complex_types.sol
> +// bytecodeFormat: >=EOFv1
`EVMVersion: >=prague` is redundant when the test is already restricted to EOF. You have that in multiple tests.

2025-01-24 13:01 UTC, rodiazet commented on test/libsolidity/semanticTests/externalContracts/eof/deposit_contract.sol
Probably some legacy change remained.

2025-01-24 13:08 UTC, rodiazet commented on test/libsolidity/semanticTests/isoltestTesting/eof/balance_other_contract.sol
> +// checkBalance() -> true
OK. I haven't noticed that it's in `isoltestTesting` directory. In this case there is now way to test it because the address differs between optimized and non-optimized version. So my idea is to disable optimizations from this test case or make it only runs when optimization enabled.

2025-01-24 13:16 UTC, rodiazet commented on test/libsolidity/semanticTests/isoltestTesting/eof/balance_other_contract.sol
> +// checkBalance() -> true
Unfortunately in current code there is no option to make this for semantic tests. I remember now that we talked about it and outcome was that semantic tests results should now depend on optimizations. so for now I would just add TODO to the test that it has to be handled later when additional support to passing addresses between test's calls is implemented. This also somehow interact with recent ideas on changing calculation of deployed contract address.

2025-01-24 13:30 UTC, rodiazet commented on test/libsolidity/semanticTests/events/event_emit_from_other_contract.sol
Problem with `event_emit_from_other_contact` is that the address in `Deposit` event expectation depends on contract bytecode. Which makes testing this in semantic tests impossible. 

Regarding `prediction_example` I don't see any option to jest it as we don't have access to contract bytecode and more over the bytecode differs between opt and non-opt versions.

2025-01-24 14:12 UTC, rodiazet commented on test/libsolidity/semanticTests/functionTypes/eof/function_external_delete_storage.sol
> +// incrementIndirectly() ->
The function pointer is being reset to 0. Problem is that for EOF we don't have (for now) a way to check that there is a code under an address. For legacy it fails because there is a check (using `extcodesize`) and in case when the code size is 0 it reverts.

2025-01-24 14:19 UTC, rodiazet commented on test/libsolidity/semanticTests/builtinFunctions/eof/keccak256_packed_complex_types.sol
> +// bytecodeFormat: >=EOFv1
Done

2025-01-24 14:23 UTC, rodiazet commented on test/libsolidity/semanticTests/deployedCodeExclusion/subassembly_deduplication.sol
Ok. Done

2025-01-24 14:26 UTC, rodiazet commented on test/libsolidity/semanticTests/various/code_access_create.sol
TODO added.

2025-01-27 13:21 UTC, cameel commented on test/libsolidity/semanticTests/functionTypes/eof/function_external_delete_storage.sol
> +// incrementIndirectly() ->
Ah, true. I assumed this must be failing because we have a sanity check check for zero, but of course we don't, that would cost gas :) It's actually the check against calling a non-contract.

So one of the indirect consequences of the removal of `extcodesize` check is that calling an uninitialized external function pointer will no longer revert. That's unfortunate, it seems like it could be a common error. We'll have to point it out in the docs.

As for the test, I think that in this case we should adjust it not to call the function because it's not the point. I'll add that to #15768.

2025-01-30 12:47 UTC, cameel commented
#15768 has been merged. Please rebase.

2025-01-30 12:50 UTC, cameel commented on test/libsolidity/semanticTests/isoltestTesting/eof/balance_other_contract.sol
> +// checkBalance() -> true
There's a way to work around it: change the test to send to a fixed address. It does not have to be an address of a contract.

I actually did just that in #15768, so now a special EOF version should not be necessary once you rebase.

2025-01-30 12:51 UTC, cameel commented on test/libsolidity/semanticTests/events/event_emit_from_other_contract.sol
> +// TODO: Implement this test for EOF. Now it's not possible because deployed contract address depends on contact bytecode.
```suggestion
// TODO: Implement this test for EOF. Now it's not possible because deployed contract address depends on contract bytecode.
```

2025-01-30 13:08 UTC, cameel commented on test/libsolidity/semanticTests/events/event_emit_from_other_contract.sol
> Problem with `event_emit_from_other_contact` is that the address in `Deposit` event expectation depends on contract bytecode.

Ah, true. I guess we can't test that now.

> Regarding `prediction_example` I don't see any option to jest it as we don't have access to contract bytecode and more over the bytecode differs between opt and non-opt versions.

Right, my bad. That will only be possible when address calculation in `eofcreate` gets changed not to include the bytecode hash.

I mean, we could technically consider allowing access to `type(C).creationCode`, because we know the bytecode, but we probably shouldn't.

2025-01-30 13:22 UTC, cameel commented on test/libsolidity/semanticTests/constructor/eof/no_callvalue_check.sol
> +// gas legacyOptimized code: 4800
You still have those in a few tests. `operator_making_pure_external_call.sol`, `interface_inheritance_conversions.sol`, `external_call_to_nonexisting.sol` and probably more.

2025-01-30 13:25 UTC, cameel commented on test/libsolidity/semanticTests/functionTypes/eof/function_external_delete_storage.sol
> +// incrementIndirectly() ->
I have rewritten that test in #15768, so you can just remove the EOF version after you rebase on `develop`.

2025-01-30 13:37 UTC, cameel commented on test/libsolidity/semanticTests/functionCall/eof/calling_nonexisting_contract_throws.sol
> +// there is non-empty code under an address. This should be fixed in with `ISCONTRACT` opcode or any other solution.
I'd remove this and just call the new test `calling_nonexisting_contract.sol`. Not throwing is the expected behavior for now and I'm not sure we can assume we'll get `ISCONTRACT` eventually (wasn't that changed to `EXTCODETYPE`?).

I'd just add a comment over `d.g()` saying that on legacy that would throw to make the purpose of the test clear.

2025-01-30 13:59 UTC, cameel commented on test/libsolidity/semanticTests/various/eof/create_calldata.sol
> +		assert(msg.data.length == 32);
I'd also check that the values match.

```suggestion
		// On EOF msg.data contains constructor arguments, while on legacy it's empty
		// (arguments are appended to the code).
		s = msg.data;
		assert(msg.data.length == 32);
		y = abi.decode(msg.data, (uint));
		assert(x == y);
```

Also would not hurt to have more than one argument.

2025-01-30 15:17 UTC, rodiazet commented on test/libsolidity/semanticTests/functionCall/eof/calling_nonexisting_contract_throws.sol
> +// there is non-empty code under an address. This should be fixed in with `ISCONTRACT` opcode or any other solution.
done

2025-01-30 15:53 UTC, rodiazet commented on test/libsolidity/semanticTests/various/eof/create_calldata.sol
> +		assert(msg.data.length == 32);
done.

2025-01-30 16:46 UTC, cameel commented on test/libsolidity/semanticTests/builtinFunctions/keccak256_packed_complex_types.sol
> +// bytecodeFormat: legacy
This should no longer need a separate EOF version after #15768. I see that quite a few tests I updated in that PR are still here. Do they not pass on EOF after all?

2025-01-31 09:14 UTC, rodiazet commented on test/libsolidity/semanticTests/builtinFunctions/keccak256_packed_complex_types.sol
> +// bytecodeFormat: legacy
It looks that something went totally wrong during rebasing on https://github.com/ethereum/solidity/pull/15768
Should be fixed now.

2025-01-31 15:06 UTC, cameel commented on test/libsolidity/semanticTests/various/eof/create_calldata.sol
> +// s() -> 0x20, 0x0120, 0x2a, 0x20, 0xc0, 1, 2, 3, 4, 5, 6
Please remove the costs.


While at it, I'd also use the same format for matching numbers to make it easier to see at a glance that they do match. The default formatting by isoltest is not always the greatest, but it will still accept a different one as long as the value is the same:
```suggestion
// constructor(): 42, 0x20, 0xc0, 1, 2, 3, 4, 5, 6 ->
// s() -> 0x20, 0x0120, 42, 0x20, 0xc0, 1, 2, 3, 4, 5, 6
```

2025-01-31 15:10 UTC, cameel commented on test/libsolidity/semanticTests/various/eof/value_complex.sol
I removed `value_complex.sol` and `value_insane.sol` (see https://github.com/ethereum/solidity/pull/15768#discussion_r1927992866 for context), so we no longer need their EOF versions.

2025-01-31 15:12 UTC, cameel approved these changes, later dismissed
Already approving since there are just two minor tweaks needed before we can merge.

2025-01-31 15:15 UTC, rodiazet commented on test/libsolidity/semanticTests/various/eof/value_complex.sol
done

2025-01-31 15:15 UTC, rodiazet commented on test/libsolidity/semanticTests/various/eof/create_calldata.sol
> +// s() -> 0x20, 0x0120, 0x2a, 0x20, 0xc0, 1, 2, 3, 4, 5, 6
done

2025-01-31 15:17 UTC, cameel approved these changes

2025-01-31 15:55 UTC, merged