Adjust storage layout to consider explicit storage base location
ethereum/solidity pull request #15668
Opened 2024-12-20 19:23 UTC by matheusaaguiar

- [ ] depends on #15528.

2025-02-05 16:48 UTC, matheusaaguiar commented
This change also affects codegen and tests are successful.

2025-02-24 13:36 UTC, cameel commented
Needs rebase.

2025-02-24 18:38 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/inline_assembly_direct_store.sol
> +// compileViaYul: true
Any reason all the new semantic tests are limited to Prague? They don't seem to be using any features not available on Cancun or even older EVMs.

Also, even if the feature is only implemented in the IR codegen, we should still have at least some of basic ones set to legacy and expecting the `UnimplementedFeatureError`.

2025-02-24 18:52 UTC, cameel commented on libsolidity/ast/ASTAnnotations.h
> +	ContractDefinition const* derivedContractSpecifyingStorageLayout = nullptr;
This probably still has the problem I mentioned in https://github.com/ethereum/solidity/pull/15528#discussion_r1947082546. I think that `ContractLevelChecker` will assign it multiple times in such a case (which is why you should make it `SetOnce`).

I see you have no semantic tests with inheritance structure similar to that case. They would probably be failing here. In fact, you don't seem to have any tests with multiple inheritance at all.

I recommend taking a look at syntax tests that pass without errors and using them as a base for constructing more varied semantic tests.

2025-02-24 18:55 UTC, cameel commented on test/cmdlineTests/storage_layout_specified_location/in.sol
> +pragma solidity >=0.8.27;
```suggestion
pragma solidity *;
```

2025-02-24 18:57 UTC, cameel commented on test/cmdlineTests/storage_layout_specified_location_two_contracts/input.json
> +				"": [ ]
```suggestion
				"A": ["storageLayout"],
				"": []
```

2025-02-24 19:01 UTC, cameel commented on test/cmdlineTests/storage_layout_specifier_codegen_error/output
This test needs renaming. You should probably have called it a "smoke" test rather than "codegen error" test from the beginning, since it was expected it would eventually pass. Unless you were planning to just remove it? I guess it's also fine to just replace it with a more specific test if you prefer.

2025-02-26 13:57 UTC, cameel requested changes

2025-02-26 13:57 UTC, cameel commented on libsolidity/ast/Types.cpp
> +	u256 startSlot = 0;
```suggestion
	u256 baseSlot = 0;
```

2025-02-26 13:57 UTC, cameel commented on libsolidity/ast/ASTUtils.h
> +u256 storageBaseLocationValue(ContractDefinition const& _contract);
This needs a docstring. There are quite a few corner cases where it's not obvious what the function will return and the docstring should clarify that:
- The same contract can have many different layouts depending on what inheritance hierarchy it's a part of. Does the function assume that it's a top-level contract?
- Contracts without layout specifier.
- Contracts that inherit from other contracts that already have storage variables. Do we point at contract's own state variables or are inherited contracts included too?
- Contracts that can have storage but are empty.
- Contracts that can't have storage at all (i.e. libraries/interfaces).

If the function does not support any of these cases it should also have asserts against them.

2025-02-26 13:57 UTC, cameel commented on libsolidity/ast/ASTUtils.h
> +u256 storageBaseLocationValue(ContractDefinition const& _contract);
Also, maybe the names should be adjusted so it's easier to realize some of the assumptions we're making here:
```suggestion
u256 storageLayoutBaseForInheritanceHierarchy(ContractDefinition const& _topLevelContract);
```

2025-02-26 13:57 UTC, cameel commented on libsolidity/ast/Types.cpp
> +	bigint slotOffset = bigint(_slotStart);
This breaks `storageSize()`, because `m_storageSize` now contains more than just size of the object itself.

Something should be failing because of this. Are we missing a semantic test?

2025-02-26 13:57 UTC, cameel commented on libsolidity/ast/Types.h
> +	void computeOffsets(TypePointers const& _types, u256 _slotStart = 0);
`_slotStart` should be documented and possibly renamed. Is it the base offset of the whole layout? Is it relative to parent?

The documentation for the class and other members should also clarify whether offsets are absolute or relative (and what they are relative to).

2025-02-26 14:11 UTC, matheusaaguiar commented on test/libsolidity/semanticTests/storageLayoutSpecifier/inline_assembly_direct_store.sol
> +// compileViaYul: true
Only the transient storage test needs Cancun as evm version. I think I forgot to remove this and copied it all over.
> Also, even if the feature is only implemented in the IR codegen, we should still have at least some of the basic tests set to legacy and expecting the UnimplementedFeatureError.

I just discovered `compileViaYul: also` which is what I thought it was doing with the value `true`. So now I guess it is running both IR and legacy codegen, right?

2025-02-26 14:11 UTC, matheusaaguiar commented on test/cmdlineTests/storage_layout_specifier_codegen_error/output
Renamed to "smoke".

2025-02-26 14:19 UTC, matheusaaguiar commented on libsolidity/ast/ASTAnnotations.h
> +	ContractDefinition const* derivedContractSpecifyingStorageLayout = nullptr;
Yeah, this annotation doesn't make sense. I incorrectly assumed at some point after re-reading the initial syntax document that no two contracts specifying the layout could have the same base.
I removed it completely.

2025-02-26 14:41 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/inline_assembly_direct_store.sol
> +// compileViaYul: true
Yes. `false` runs only legacy, `true` runs only IR, `also` runs both. But `also` is the default, so you can omit it.

2025-02-27 03:48 UTC, matheusaaguiar commented on libsolidity/ast/Types.cpp
> +	bigint slotOffset = bigint(_slotStart);
I separated the `slotOffset` from the actual `storageSize` and now it should be the correct size.
This also made me realize that we missed checking for cases where the contract is not too large for storage (max capacity) but do not fit due to the specified base slot value.
I added a commit fixing that, maybe small enough to be kept within this PR, but otherwise I can just create a brand new one.

2025-02-27 04:25 UTC, matheusaaguiar commented on libsolidity/ast/ASTUtils.h
> +u256 storageBaseLocationValue(ContractDefinition const& _contract);
It should only produce a value different from the default zero if the contract has an storage base specified. In any other case, including invalid ones like interfaces and libraries, it returns zero.
At the time I was just thinking of using it in places after type checking already happened and the value exists and is set or then the contract does not specifies a base value and/or it is not the most derived one.
Not sure if it is just better to have the `if` directly in `ContractType::stateVariables` where it is used...

2025-02-27 20:29 UTC, cameel commented on libsolidity/ast/ASTUtils.cpp
> +	}
You don't generally have to assert this on `SetOnce`. `*` already asserts this so you can make things simpler:
```suggestion
		return *storageLayoutSpecifier->annotation().baseSlot;
```

2025-02-27 20:29 UTC, cameel commented on libsolidity/ast/ASTUtils.h
> +/// @returns the value of the base slot of the contract's inheritance hierarchy storage if it is explicit specified.
```suggestion
/// @returns the value of the base slot of the contract's inheritance hierarchy storage if it is explicitly specified.
```

2025-02-27 20:29 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +	storageLayoutSpecifier->annotation().baseSlot = u256(baseSlot);
You should move `baseSlot` above the range check, and use it there as well.

Also, you're doing the `u256` connversion here twice.

2025-02-27 20:29 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +				size += variable->annotation().type->storageSizeUpperBound();
This calculation is also in `ContractLevelChecker::checkStorageSize()`. If we need it more than once, we should make it a helper.

`ContractDefinition::storageSizeUpperBound()` could be a good place. Though then it may be too easy to confuse with `ContractType::storageSizeUpperBound()` (which returns 1) so perhaps something like `contractStorageSizeUpperBound()` in `ASTUtils.h` is a better idea.

2025-02-27 20:29 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +	if (baseSlot + size >= bigint(1) << 256)
Size of 2^256 is still fine. Don't we have a test with something of that size?

```suggestion
	solAssert(size <= bigint(1) << 256);
	if (baseSlot + size > bigint(1) << 256)
```

2025-02-27 20:45 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +				size += variable->annotation().type->storageSizeUpperBound();
Oh, I think both of those checks are also buggy. This code does not distinguish between transient and non-transient variables so it probably adds up their sizes, which is wrong.

For `ContractLevelChecker::checkStorageSize()` that needs a changelog entry and should be fixed in a separate PR.

In your case it's actually more severe, because it can be easily triggered by an unrelated transient variable even when things are reasonably sized. It's enough that the layout places things close to the end of storage. Please make sure you have tests covering this.

2025-02-27 21:12 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +	if (baseSlot + size >= bigint(1) << 256)
Wait, looks like the length is actually capped at 2^256 - 1: https://github.com/ethereum/solidity/blob/5879562d17e181e53ad7adc29374dae21c863c04/libsolidity/analysis/DeclarationTypeChecker.cpp#L356-L361

Not sure why though. Is it a bug? Such a large array would be problematic for many reasons, but I don't see a good reason to arbitrarily choose a limit that's not the theoretical maximum, but one less.

Not sure if there's a use case for putting something in the very last slot but this limitation prevents it.

2025-02-27 21:25 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +				size += variable->annotation().type->storageSizeUpperBound();
#15899

2025-02-28 00:21 UTC, cameel commented on libsolidity/ast/Types.cpp
> +			++storageSize;
Wouldn't it be simpler to just subtract `_baseSlot` from `slotOffset` at the end?

2025-02-28 00:21 UTC, cameel commented on libsolidity/ast/Types.cpp
>  			byteOffset = 0;
Looks like this function assumes that `type->storageBytes() <= 32` but does not check it.

It's actually a very weird assumption. I'd expect it to return more than 32 for static arrays or structs. Apparently it's hard coded to 32 for anything that does not explicitly redefine it. We should at some point rename it to better reflect what it returns and and refactor to use an `optional`.

This is not something introduced by your PR, but please still add an assert against it. Just put it in a separate commit, since it's technically unrelated.

2025-02-28 00:21 UTC, cameel commented on libsolidity/ast/Types.cpp
>  			byteOffset = 0;
Also, the `!type->canBeStored()` check should be an assert. This flag is true for things like literals, tuples, modules, etc. Generally things whose types cannot be named. I can't think of any type like this that could be used on a state variable, so the condition should always be satisfied.

2025-02-28 00:21 UTC, cameel commented on libsolidity/ast/Types.cpp
>  			byteOffset = 0;
BTW, what's up with the weird space before comma in the asserts against 2^256 below?

2025-02-28 00:21 UTC, cameel commented on libsolidity/ast/Types.cpp
> +		baseSlot = storageLayoutBaseForInheritanceHierarchy(m_contract);
```suggestion
	u256 baseSlot{};
	if (_location == DataLocation::Storage)
		baseSlot = storageLayoutBaseForInheritanceHierarchy(m_contract);
	else
	{
		solAssert(_location == DataLocation::Transient);
		baseSlot = 0;
	}
```

2025-02-28 00:21 UTC, cameel commented on libsolidity/ast/Types.cpp
>  		for (VariableDeclaration const* variable: contract->stateVariables())
One thing that still somewhat bothers me here is that there's nothing preventing someone from running `ContractType::stateVariables()` on any contract in the inheritance hierarchy, even though you'll only get a valid result if it's the top level one.

I checked the uses and looks like we fortunately never do this. Still, I think it might be a good idea to rename the function to something like `linearizedStateVariables()` or even `variableLayout()` to make it clearer. Currently it's too easily confused with `ContractDefinition::stateVariables()` which *is* valid for any contract.

The docstring should also say that the function works like this and that the returned slots are absolute.

2025-02-28 00:21 UTC, cameel commented on libsolidity/ast/Types.h
> +	/// first slot of the storage
```suggestion
	/// Calculated positions are absolute and start at @a _baseSlot.
	/// Assumes that @a _types is small enough to fit in the area between @a _baseSlot and the end of storage
	/// (the caller is responsible for validating that).
```

2025-02-28 00:21 UTC, cameel commented on libsolidity/ast/Types.cpp
> +		baseSlot = storageLayoutBaseForInheritanceHierarchy(m_contract);
Might also be better to make `_location` a parameter of the helper and rename it to `layoutBaseForInheritanceHierarchy()`. This way all the information will be encapsulated there.

2025-02-28 00:29 UTC, cameel commented on libsolidity/ast/ASTUtils.h
> +u256 storageBaseLocationValue(ContractDefinition const& _contract);
It's a good idea to encapsulate it there. It should just be properly documented and have a clear name.

2025-02-28 00:31 UTC, cameel commented on libsolidity/ast/Types.cpp
> +	bigint slotOffset = bigint(_slotStart);
Yes, it should definitely be a part of this PR.

2025-02-28 00:36 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +		);
Note that this check makes the one in `ContractLevelChecker::checkStorageSize()` a bit redundant. Though the way it is now we distinguish between the variables being too large and the layout pushing them beyond the edge. Still, it would make sense to have those checks in one place. Actually, what was the reason for adding your checks here rather than there?

2025-02-28 00:43 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +		);
Also, I wonder if we should have a warning about stuff being placed too close to the end of storage. If your contract is exactly at the end, it becomes impossible to add more variables if you upgrade it. As long as we allow only literal expressions, it's easy to avoid but with `erc7201()` the user might not even realize that this is the case.

2025-02-28 01:01 UTC, matheusaaguiar commented on libsolidity/ast/Types.cpp
> +			++storageSize;
I was kinda undecided about which way to do. The value is needed in two asserts and one assignment, so I just used the variable. I see no problem changing it to just subtracting though.

2025-02-28 01:04 UTC, matheusaaguiar commented on libsolidity/ast/Types.cpp
>  			byteOffset = 0;
> BTW, what's up with the weird space before comma in the asserts against 2^256 below?

I blame the cats for those :_)

2025-02-28 01:07 UTC, matheusaaguiar commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +		);
> Actually, what was the reason for adding your checks here rather than there?

The `baseSlot` value is only properly checked and assigned here, so it could not be done reliably before.

2025-02-28 03:29 UTC, matheusaaguiar commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +	storageLayoutSpecifier->annotation().baseSlot = u256(baseSlot);
Fixed.

2025-02-28 03:35 UTC, cameel reviewed
I finally finished going through the tests. Here's the last batch of comments.

2025-02-28 03:35 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/inheritance_from_abstract_contract.sol
> +// f() -> 10
You should show the values of `x()` and `y()` as well to prove that they were properly stored and getters can retrieve them. Similarly in some other tests.

2025-02-28 03:35 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/inline_assembly_direct_load.sol
> +// f() -> 0x10
Expectations should be in the same form as values used in the code whenever possible. Makes it easier to verify at a glance that they are correct.

```suggestion
// f() -> 16
```

Same for some other tests.

2025-02-28 03:35 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/inline_assembly_direct_load.sol
> +// f() -> 0x10
Naming could be improved too. E.g. in `transient_state_variable_slot_offset.sol` you have a bunch of functions corresponding to variables (`f()`->`x`, `g()`->`y`, `h()`->`z`). I find myself having jumping back and forth to check which function returns the location for which variable. Especially since variables are not defined in alphabetical order (the third variable is `w`, not `z`) and correspond to different functions in different tests.

Something like `x`/`xSlotOffset()`, `y`/`ySlotOffset()`, `z`/`zSlotOffset()` would be way more intuitive.

2025-02-28 03:35 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/inheritance_state_variable_slot_offset.sol
> +    }
Since these are very short, almost identical and repeat in a lot of tests, I'd format them like this:

```suggestion
    function xSlotOffset() public returns(uint s, uint o) { assembly { s := x.slot o := x.offset } }
    function wSlotOffset() public returns(uint s, uint o) { assembly { s := w.slot o := w.offset } }
    function ySlotOffset() public returns(uint s, uint o) { assembly { s := y.slot o := y.offset } }
    function zSlotOffset() public returns(uint s, uint o) { assembly { s := z.slot o := z.offset } }
```

While it makes it harder to read just one, it's still a lot faster to read them in bulk because you immediately see where the differences are.

I wouldn't do this e.g. in `inheritance_from_same_base_state_var_slots.sol`, where there's some distance between them, but in cases where they can be next to each other, it's helpful.

2025-02-28 03:35 UTC, cameel commented on test/cmdlineTests/storage_layout_specifier_ir_codegen/args
Use `--optimize --ir-optimized --debug-info none` for more concise output.

2025-02-28 03:35 UTC, cameel commented on test/cmdlineTests/storage_layout_specified_location_two_contracts/input.json
Is `specified` in the file name a typo?

2025-02-28 03:35 UTC, cameel commented on test/cmdlineTests/evmasm_specific_storage_base_location/args
I'd merge this with the smoke test. It shows asm output too and the only interesting thing to check here is that the output contains `sstore(0x0abc)`, which is pretty much just a smoke test by itself.

2025-02-28 03:35 UTC, cameel commented on test/cmdlineTests/storage_layout_specified_location/in.sol
I'd reduce these CLI tests for `--storage-layout` to just one. It does not have to be a basic one, can include transient storage, inheritance and small types, etc, but one would be enough. The output is very tedious to verify so we should not go overboard with them when we have a better alternative.

And that better alternative here are semantic tests. In them you can have proper expectations for `.slot` and `.offset` so they're a better for covering corner cases.

I'd also make it a CLI test rather than Standard JSON.

2025-02-28 03:35 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/constructor.sol
We need a bit more coverage to make sure that existing features are not affected in presence of layout specifier:
- [x] State variables of reference types.
    - [x] Especially when contract storage is pushed to the very end of storage and the data of the reference type ends up *before* it, which is not normally the case.
    - [x] `push()`/`pop()` on a dynamic array.
- [x] Mappings.
- [x] Constant and immutable state variables.
- [x] Transient variables (I think you have no tests actually writing anything to them).
- [x] Storage references (as local variables or parameters).
    - [x] Especially passing them to library functions.
- [x] `delete` (both storage and transient storage).
- [x] Variable cleanup.
- [x] Variable covering 100% of available storage.
- [x] Accessing inherited storage variables in a constructor.
- [x] Writes to storage variables inside overridden virtual functions.
    - [x] Especially when the body is not in the top-level contract.
    - [x] Inside functions invoked via `super` or the name of inherited contract.

2025-02-28 03:41 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +		);
But I mean whether there is a reason for `baseSlot` being checked here in the first place. It was your earlier PR that put it here :) I'm not sure whether there was a specific reason that forced you to choose one over the other or if either would have worked.

2025-02-28 04:00 UTC, matheusaaguiar commented on libsolidity/ast/Types.cpp
>  			byteOffset = 0;
Added the assertions.

2025-02-28 04:01 UTC, matheusaaguiar commented on libsolidity/ast/Types.cpp
> +		baseSlot = storageLayoutBaseForInheritanceHierarchy(m_contract);
Refactored the helper as suggested.

2025-02-28 04:26 UTC, matheusaaguiar commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +		);
Sorry for not being more specific :) I meant that `ContractLevelChecker` runs prior to the `TypeChecker` where the base slot expression gets evaluated and after that, when `PostContractLevelChecker` runs, we can get the value of `baseSlot` here.
That was my reasoning in the previous PR.

2025-02-28 19:35 UTC, cameel commented
There's one more case we should have: an abstract contract inheriting from a non-abstract one. We don't generate code for abstract contracts so I'm not sure we don't skip some checks on them.

```solidity
contract A layout at 10 {}
abstract contract C is A {}
```

This would fit better in #15528 but that's merged so we can do that here.

2025-02-28 21:09 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
>  	)
```c++
	if (!(0 <= baseSlot && baseSlot <= std::numeric_limits<u256>::max()))
```

2025-02-28 21:09 UTC, cameel commented on libsolidity/ast/ASTUtils.h
> +/// In any other case, including invalid ones, returns the default value of zero.
```suggestion
/// @returns The base slot of the inheritance hierarchy rooted at the specified contract.
/// The value comes from the inheritance specifier of the contract and defaults to zero.
/// The value is zero also when the contract is an interface or a library (and cannot have storage).
```

BTW, I saw that you initially had an assert against interfaces and libraries and I thought that was a good idea. Better than returning a zero and pretending they have storage, which may easily lead to mistakes. Some tests were failing, but you probably just need an `if` in `StorageOffsets` to handle that.

2025-02-28 21:10 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +		);
Ok, makes sense.

2025-02-28 21:16 UTC, cameel commented on libsolidity/ast/Types.cpp
> +			++storageSize;
You don't actually need an assert against `storageSize` inside the loop. The one for `slotOffset` is there only because we're converting it to `u256` and that would silently truncate a value that's too big. And the opposite is true at the end of the function. You're only converting `storageSize` there.

And overall, the current approach duplicates the logic (however simple it may be) which is just gives you one more place for a mistake to creep in :)

2025-02-28 21:17 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +	if (baseSlot + size >= bigint(1) << 256)
Now that I think of it, the restriction against the size still does not prevent us from making the last slot reachable for smaller objects. We'll need to discuss that.

2025-03-01 14:41 UTC, matheusaaguiar commented on libsolidity/ast/Types.cpp
> +			++storageSize;
Right. Fixed.

2025-03-01 23:06 UTC, stackenbotten commented
There was an error when running `chk_coding_style` for commit `2c3bc897887a7e6e595400c6fe5515042b9bb07c`:
```
Error: Trailing whitespace found:
test/cmdlineTests/storage_layout_specifier_storage_layout_output/stdin:17:    uint128 z; 
test/libsolidity/semanticTests/storageLayoutSpecifier/state_variable_mapping.sol:12:        

```
Please check that your changes are working as intended.

2025-03-02 15:26 UTC, matheusaaguiar commented on libsolidity/ast/ASTUtils.h
> +/// In any other case, including invalid ones, returns the default value of zero.
Yeah, I removed the asserts to get tests green and was planning to fix it later. Should we include abstract contracts in the restrictios too?

2025-03-02 15:29 UTC, matheusaaguiar commented on test/cmdlineTests/storage_layout_specified_location_two_contracts/input.json
Yes. Fixed.

2025-03-02 19:02 UTC, cameel commented on libsolidity/ast/ASTUtils.h
> +/// In any other case, including invalid ones, returns the default value of zero.
Abstract contracts definitely should be allowed. Those can have storage variables and they are reported to start at 0 if you request `--storage-layout`.

The reason to exclude libraries and interfaces would be because for these even asking about the layout makes no sense. But looking at `ContractType::stateVariables()` now, I see that we actually do ask that question and `--storage-layout` even reports an empty layout for them (rather than giving no output). If that's the case I'd remove these assertions after all. My assumption was that for libraries and interfaces you wouldn't even run `computeOffsets()` at all and wouldn't need to use any value for the base slot in the first place. But you still do so it's better for `layoutBaseForInheritanceHierarchy()` to return it rather than hard-code it inside `stateVariables()`.

2025-03-03 17:44 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +				size += variable->annotation().type->storageSizeUpperBound();
You can now use the helper you added in #15901.

2025-03-03 17:45 UTC, cameel commented on libsolidity/analysis/PostTypeContractLevelChecker.cpp
> +	if (baseSlot + size >= bigint(1) << 256)
We decided to lift the restriction, but it will be done in a separate PR: #15911.

2025-03-03 17:49 UTC, cameel commented on libsolidity/ast/ASTUtils.h
> +/// In any other case, including invalid ones, returns the default value of zero.
Please update the docstring.

2025-03-03 17:51 UTC, cameel commented on libsolidity/ast/Types.cpp
> +	m_storageSize = u256(storageSize);
You checked `slotOffset` already and `_baseSlot` is `u256`, so this assert is redundant.

```suggestion
	m_storageSize = u256(slotOffset - _baseSlot);
```

2025-03-03 17:52 UTC, cameel commented on libsolidity/ast/Types.cpp
> +	offsets.computeOffsets(types, layoutBase);
```suggestion
	offsets.computeOffsets(types, layoutBaseForInheritanceHierarchy(m_contract, _location));
```

2025-03-03 19:16 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/delete_transient_storage.sol
> +    address transient a;
The idea was to test deleting transient storage in a contract with a layout, to prove that the layout does not affect it. You're not testing that if there's no layout :)

2025-03-03 19:16 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/multiple_inheritance.sol
> +// gas legacyOptimized: 110911
This is odd. Why does a simple getter reading an `uint` from storage cost 100k+ gas? And why only this single one?

Is the cost the same without a layout specifier?

2025-03-03 19:16 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/variable_cleanup sstore.sol
> +    function f(uint _x, int _y, bytes3 _b) public returns (uint16, int32, bytes2) {
This could use a comment. At first I thought that the results were wrong, because the returned types actually weren't small enough to truncate the input like this. Only then I noticed that the storage variable types do not match and are actually event smaller.

2025-03-03 19:18 UTC, cameel commented on libsolidity/ast/Types.cpp
> +	m_storageSize = u256(storageSize);
You still have the `storageSize` variable in there. Just unused now.

2025-03-03 19:42 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/inheritance_state_variable_slot_offset.sol
> +    }
Just to clarify, the point of this is to put each one on a single line and also align things if the names don't have the same length.

Doing something like this is a bit pointless:
```solidity
function zSlotOffset() public returns(uint s, uint o) {
    assembly { s := z.slot o := z.offset }
}
```
It's both harder to read than the original and still not compact enough for the differences to stand out immediately.

2025-03-03 19:45 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/inline_assembly_direct_load.sol
> +// f() -> 0x10
You still have a lot of tests with this opaque naming. E.g. `dynamic_array_storage_end.sol`, where good naming would make reading the expectations and the test much clearer: `f()` -> `initialize()`, `g()` -> `validate()`, `h()` -> `clear()`.

Other examples: `mapping_storage_end.sol`, `storage_reference_array.sol`, `state_variable_dynamic_array.sol`, `state_variable_struct.sol`, `from_same_base_state_var_slots.sol`.

2025-03-03 19:48 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/last_storage_slot.sol
> +contract C layout at 2**256 - 2 {
This isn't really the last slot. It's only the last allowed one. We're going to want this name for #15911.

2025-03-03 20:13 UTC, matheusaaguiar commented on test/libsolidity/semanticTests/storageLayoutSpecifier/delete_transient_storage.sol
> +    address transient a;
I forgot the layout. Fixed.

2025-03-03 20:58 UTC, matheusaaguiar commented on test/libsolidity/semanticTests/storageLayoutSpecifier/multiple_inheritance.sol
> +// gas legacyOptimized: 110911
I ran it again without the layout specifier and using the latest develop version and got the same result:

```
// ----
// test() -> 1, 2, 3, 5
// gas irOptimized: 110109
// gas legacy: 111876
// gas legacyOptimized: 110940
// x() -> 1
// y() -> 2
// w() -> 3
// z() -> 5
// gas irOptimized: 110016
// gas legacy: 111859
// gas legacyOptimized: 110911
```

2025-03-03 20:59 UTC, matheusaaguiar commented on test/libsolidity/semanticTests/storageLayoutSpecifier/last_storage_slot.sol
> +contract C layout at 2**256 - 2 {
I renamed it to "last_available_slot".

2025-03-03 20:59 UTC, matheusaaguiar commented on test/libsolidity/semanticTests/storageLayoutSpecifier/variable_cleanup sstore.sol
> +    function f(uint _x, int _y, bytes3 _b) public returns (uint16, int32, bytes2) {
Added a comment explaining the types are larger.

2025-03-03 22:38 UTC, matheusaaguiar commented on test/libsolidity/semanticTests/storageLayoutSpecifier/inline_assembly_direct_load.sol
> +// f() -> 0x10
I guess I renamed all the remaining functions in the tests.

2025-03-03 22:38 UTC, matheusaaguiar commented on test/libsolidity/semanticTests/storageLayoutSpecifier/inheritance_state_variable_slot_offset.sol
> +    }
Yes, you are right. I totally missed your point. Sorry.
Fixed.

2025-03-03 22:39 UTC, matheusaaguiar commented on test/libsolidity/semanticTests/storageLayoutSpecifier/multiple_inheritance.sol
> +// gas legacyOptimized: 110911
looking into this.

2025-03-04 00:06 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/multiple_inheritance.sol
> +// gas legacyOptimized: 110911
Well, if it does not happen without the specifier then at least it's not a bug in the PR.

2025-03-04 15:59 UTC, cameel reviewed
The PR looks good now. There are still a few minor things to clean up and the changelog entry needs to be changed but there are no big issues remaining.

2025-03-04 15:59 UTC, cameel commented on Changelog.md
> + * Code Generator: generate code for contracts with a specified storage layout base.
This is the same feature, just split into multiple PRs. There should be one changelog entry.

2025-03-04 15:59 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/variable_cleanup.sol
> +// f(uint256,int256,bytes3): 256, -129, "abc" -> 0, 127, 0x6162000000000000000000000000000000000000000000000000000000000000
This is another case where formatting the expectations manually makes it much quicker to verify their correctness at a glance:. You can see the truncation immediately if you use the right types of literals and keep them the same on both sides:

```suggestion
// f(uint256,int256,bytes3): 0x0100, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f, "abc" -> 0x00, 0x7f, "ab"
```

2025-03-04 15:59 UTC, cameel commented on test/cmdlineTests/storage_layout_specifier_ir_codegen/stdin
This one is a smoke test as well, isn't it? You should put that in the name too.

2025-03-04 15:59 UTC, cameel commented on test/cmdlineTests/storage_layout_specifier_storage_layout_output/args
> +--storage-layout --pretty-json --json-indent 4 -
```suggestion
--storage-layout --transient-storage-layout --pretty-json --json-indent 4 -
```

2025-03-04 16:01 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/multiple_inheritance.sol
> +// gas legacyOptimized: 110911
I see that the extra cost entries disappeared now. What did you change in the test?

2025-03-04 16:47 UTC, matheusaaguiar commented on test/libsolidity/semanticTests/storageLayoutSpecifier/multiple_inheritance.sol
> +// gas legacyOptimized: 110911
Not sure if it was that, but after I renamed the function names on the tests, I started getting some errors on the expectations and had to re-run tests.
I then erased all the computed costs from the tests and let isoltest write new ones.

2025-03-04 16:48 UTC, matheusaaguiar commented on Changelog.md
> + * Code Generator: generate code for contracts with a specified storage layout base.
Yeah, was wondering if that should be the case.
Fixed.

2025-03-04 17:01 UTC, matheusaaguiar commented on test/libsolidity/semanticTests/storageLayoutSpecifier/variable_cleanup.sol
> +// f(uint256,int256,bytes3): 256, -129, "abc" -> 0, 127, 0x6162000000000000000000000000000000000000000000000000000000000000
Fixed.

2025-03-04 17:01 UTC, matheusaaguiar commented on test/cmdlineTests/storage_layout_specifier_ir_codegen/stdin
Done.

2025-03-04 17:01 UTC, matheusaaguiar commented on test/cmdlineTests/storage_layout_specifier_storage_layout_output/args
> +--storage-layout --pretty-json --json-indent 4 -
Done.

2025-03-04 17:05 UTC, cameel commented
Please note that there are also two earlier unresolved comments here.

2025-03-04 18:25 UTC, matheusaaguiar commented
> Please note that there are also two earlier unresolved comments here.

@cameel I think I have addressed all the comments now.

2025-03-05 11:32 UTC, cameel reviewed
I noticed that two tests are still missing the layout specifier.

2025-03-05 11:32 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/variable_cleanup_sstore.sol
> +contract C {
Just noticed that this and `variable_cleanup.sol` are missing the layout specifier, which is the whole point of these tests.

2025-03-05 11:32 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/variable_cleanup_sstore.sol
> +            sstore(b.slot, _b)
This is actually wrong. Note that all variables are packed into a single slot so `b` overwrites all of them here. You need to combine them and store once if you want this to be the equivalent of Solidity version.

2025-03-05 11:32 UTC, cameel commented on Changelog.md
> + * Introduce syntax and code generation for custom contract storage layout base.
It's a complete feature now, not need to split hairs about syntax or code generation. The entry should just say what it does.

```suggestion
 * Allow relocating contract storage to an arbitrary location.
```

2025-03-05 11:34 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/multiple_inheritance.sol
> +// gas legacyOptimized: 110911
Ah, ok. Then these costs must have been just stale. isoltest doesn't actually verify costs that are below 100k. But it probably only checks if the actual cost is over 100k, not the one you put in the test. We should fix that at some point.

2025-03-05 11:35 UTC, cameel commented on libsolidity/ast/Types.cpp
> +	m_storageSize = u256(storageSize);
The unused variable is still there.

2025-03-05 13:35 UTC, matheusaaguiar commented on test/libsolidity/semanticTests/storageLayoutSpecifier/variable_cleanup_sstore.sol
> +            sstore(b.slot, _b)
Ah, right, that flew over my head.
Not sure what should be a good way to do that here though.

2025-03-05 13:36 UTC, matheusaaguiar commented on test/libsolidity/semanticTests/storageLayoutSpecifier/variable_cleanup_sstore.sol
> +contract C {
Fixed.

2025-03-05 13:37 UTC, matheusaaguiar commented on libsolidity/ast/Types.cpp
> +	m_storageSize = u256(storageSize);
Removed.

2025-03-05 13:42 UTC, matheusaaguiar commented on Changelog.md
> + * Introduce syntax and code generation for custom contract storage layout base.
Done.

2025-03-05 14:21 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/variable_cleanup_sstore.sol
> +            sstore(b.slot, _b)
You could just use types large enough that they will land in separate slots. Or use single-element static arrays.

2025-03-05 19:20 UTC, cameel commented on test/libsolidity/semanticTests/storageLayoutSpecifier/variable_cleanup_sstore.sol
> +            sstore(b.slot, _b)
Why the commented out code?

2025-03-06 13:14 UTC, matheusaaguiar commented on test/libsolidity/semanticTests/storageLayoutSpecifier/variable_cleanup_sstore.sol
> +            sstore(b.slot, _b)
I wanted to make it very clear, but didn't realize that the result itself already shows exactly what is happening.

2025-03-06 18:41 UTC, cameel approved these changes

2025-03-08 04:57 UTC, merged