Refactor NameAndTypeResolver and SyntaxChecker to allow other entry points.
ethereum/solidity pull request #1620
Opened 2017-01-27 17:49 UTC by chriseth

This is needed for the "snippets" feature, so that we can resolve identifiers starting from AST nodes that are not contracts.

2017-02-09 15:20 UTC, pirapira commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +	map<ASTNode const*, shared_ptr<DeclarationContainer>>& _scopes,
Do we know anything about the life time of this map?

2017-02-09 15:23 UTC, pirapira requested changes

2017-02-09 15:23 UTC, pirapira commented on libsolidity/analysis/NameAndTypeResolver.h
> +	/// @param _avoidCode if false, does not descend into nodes that contain code.
The parameter `_avoidCode` does not exist.

2017-02-09 15:55 UTC, pirapira commented on libsolidity/analysis/TypeChecker.cpp
> +		isLibraryFunction = true;
This can still be
```
bool isLibraryFunction =
    ... && ...;
```

2017-02-09 16:14 UTC, pirapira commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +				if (!resolveNamesAndTypes(*baseContract, false))
If you want to keep the old behavior, `!resolveNamesAndTypes(*baseContract, true)` looks more similar.

2017-02-09 16:16 UTC, pirapira commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +			// now resolve references inside the code
The comment looks like talking about the new `_resolveInsideCode` parameter, but the comment exists before this PR.  I'm confused.

2017-02-09 16:18 UTC, pirapira commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +				if (!resolveNamesAndTypes(*node, true))
Is it correct that there is a global invariant of the type `ASTPointer` that `*node` always succeeds when you have an object `node` of class `ASTPointer`?

2017-02-14 12:24 UTC, chriseth commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +	map<ASTNode const*, shared_ptr<DeclarationContainer>>& _scopes,
It has to be longer that the lifetime of this object, of course the shared pointers live on longer.

2017-02-14 12:28 UTC, chriseth commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +				if (!resolveNamesAndTypes(*baseContract, false))
It should not have any effect, but I will change it regardless.

2017-02-14 12:30 UTC, chriseth commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +			// now resolve references inside the code
Yes, the flag existed before, it was lifted from the constructor of ReferencesResolver to this function here.

2017-02-14 12:31 UTC, chriseth commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +				if (!resolveNamesAndTypes(*node, true))
Yes

2017-02-14 13:53 UTC, pirapira commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +	map<ASTNode const*, shared_ptr<DeclarationContainer>>& _scopes,
How do you guarantee the lifetime of the map?

2017-02-14 14:01 UTC, pirapira commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +			// now resolve references inside the code
The constructor of ReferencesResolver still has it.  I'll try to understand the relationship between the argument of the constructor and the argument of NameAndTypeResolver::registerDeclarations.

2017-02-14 14:04 UTC, chriseth commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +			// now resolve references inside the code
Yes, the flag is extended upwards, so we can use it from outside.

2017-02-14 14:04 UTC, pirapira commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +				if (!resolveNamesAndTypes(*node, true))
I take it off this PR: using a "shared pointer that is never null" for this purpose.

2017-02-14 14:04 UTC, chriseth commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +	map<ASTNode const*, shared_ptr<DeclarationContainer>>& _scopes,
Not at all, this is C++... If you pass in references, you have to check the documentation to see who will own it.

2017-02-14 14:09 UTC, pirapira commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +			return ReferencesResolver(m_errors, *this, _resolveInsideCode).resolve(_node);
Is there a need to recover the previous content of `m_currentScope` after calling `resolve`?

2017-02-14 14:20 UTC, chriseth commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +			return ReferencesResolver(m_errors, *this, _resolveInsideCode).resolve(_node);
not really, no

2017-02-14 14:35 UTC, pirapira approved these changes

2017-02-14 14:35 UTC, merged

2017-02-14 14:35 UTC, pirapira commented
The changes make sense to me now.

2017-02-14 15:17 UTC, pirapira commented on libsolidity/analysis/NameAndTypeResolver.cpp
> +			return ReferencesResolver(m_errors, *this, _resolveInsideCode).resolve(_node);
I don't know because I didn't check all uses of `m_currentScope`.