Integrate missed changes.
ethereum/solidity pull request #1625
Opened 2017-01-31 22:33 UTC by chriseth

It seems that I based the new assembly.rst file off of a really old version of the part inside control structures. This PR moves the changes over and especially also deletes the section inside control structures.

2017-01-31 22:40 UTC, VoR0220 commented on docs/assembly.rst
> +| call(g, a, v, in,       |      | call contract at address a with input mem[in..(in+insize))      |
Should be either a bracket at the end or needs a `(` at the beginning of `mem`

2017-01-31 22:40 UTC, VoR0220 commented on docs/assembly.rst
> +|                         |      | mem[out..(out+outsize)) returning 0 on error (eg. out of gas)   |
ibid

2017-01-31 22:41 UTC, VoR0220 requested changes
just change those bits and then this is GTM

2017-01-31 23:06 UTC, chriseth commented on docs/assembly.rst
> +| call(g, a, v, in,       |      | call contract at address a with input mem[in..(in+insize))      |
This is an internal that is open at one side, it is explained at the beginning of the table.

2017-01-31 23:50 UTC, VoR0220 commented on docs/assembly.rst
> +| call(g, a, v, in,       |      | call contract at address a with input mem[in..(in+insize))      |
Oops.

2017-02-01 00:29 UTC, VoR0220 approved these changes

2017-02-01 08:05 UTC, merged