Add safety checks to IPC (tests)
ethereum/solidity pull request #1662
Opened 2017-02-07 12:35 UTC by axic

2017-02-07 14:53 UTC, chriseth requested changes

2017-02-07 14:53 UTC, chriseth commented on test/RPCSession.cpp
> +	BOOST_CHECK(rpcCall("personal_unlockAccount", { quote(_address), quote(_password), to_string(_duration) }) == true);
Is the `== true` required?
Furthermore, if this call does not work, it does not make much sense in continuing the test, does it? So `BOOST_REQUIRE` might be better here.

2017-02-07 15:51 UTC, axic commented on test/RPCSession.cpp
> +	BOOST_CHECK(rpcCall("personal_unlockAccount", { quote(_address), quote(_password), to_string(_duration) }) == true);
Isn't `BOOST_REQUIRE(x)` == `BOOST_CHECK(x == true)`?

2017-02-08 12:02 UTC, chriseth commented on test/RPCSession.cpp
> +	BOOST_CHECK(rpcCall("personal_unlockAccount", { quote(_address), quote(_password), to_string(_duration) }) == true);
no, both of them basically to `== true`. The difference is that require leads to a termination of the test case, check continues.

2017-02-08 16:12 UTC, chriseth approved these changes

2017-02-08 16:12 UTC, chriseth approved these changes

2017-02-08 16:12 UTC, chriseth commented on test/RPCSession.cpp
> -	cerr << ".";  //Output for log activity
I think this might be needed for appveyor.

2017-02-08 21:49 UTC, merged