Add blockTimestamp and do not rely on mining time (soltest)
ethereum/solidity pull request #1676
Opened 2017-02-09 15:05 UTC by axic

2017-02-09 15:20 UTC, chriseth requested changes

2017-02-09 15:20 UTC, chriseth commented on test/libsolidity/SolidityEndToEndTest.cpp
> -	m_rpc.test_modifyTimestamp(0x776347e2);
Please add an additional assert that it changed between these calls, just to double check that the backend actually works.

2017-02-10 13:13 UTC, chriseth requested changes

2017-02-10 13:13 UTC, chriseth commented on test/libsolidity/SolidityEndToEndTest.cpp
> +	u256 startBlock = m_blockNumber;
Sorry, I meant please check that the timestamp changed between the blocks.

2017-02-10 13:26 UTC, axic commented on test/libsolidity/SolidityEndToEndTest.cpp
> +	u256 startBlock = m_blockNumber;
Added.

2017-02-13 13:51 UTC, chriseth approved these changes

2017-02-13 13:54 UTC, merged