Implement assert()
ethereum/solidity pull request #1678
Opened 2017-02-09 16:38 UTC by axic

Implement #1130.

2017-02-09 16:39 UTC, axic commented
I think this shouldn't be a breaking change given we allow user methods to shadow globals. (Even with the other PR it will only be a warning.)

2017-02-10 13:10 UTC, chriseth commented on libsolidity/codegen/ExpressionCompiler.cpp
> +			utils().convertType(*arguments.front()->annotation().type, *function.parameterTypes().front(), true);
You can actually use false here.

2017-02-10 13:11 UTC, chriseth requested changes
There is a section in the documentation that lists all reasons for exceptions, please add assert also there.

2017-02-10 13:32 UTC, axic commented
@chriseth Updated both.

2017-02-10 16:08 UTC, chriseth commented on Changelog.md
> + * Add ``assert(condition)`` to abort execution.
This is a bit too sloppy (people might stop reading here). What about:

    Add ``assert(condition)``, which throws if condition is false.

2017-02-10 16:08 UTC, chriseth commented on docs/miscellaneous.rst
> +- ``assert(bool condition)``: throws if the condition is not met
`if condition is false`?

2017-02-10 16:27 UTC, axic commented on Changelog.md
> + * Add ``assert(condition)`` to abort execution.
I can change these late today. Can you approve it? Would like to merge it before the weekend.

2017-02-10 16:29 UTC, chriseth approved these changes

2017-02-10 22:39 UTC, merged

2017-02-16 14:33 UTC, wuestholz commented
@axic @chriseth Could you please provide some more information about why you decided to treat assert-statements similar to throw-statements by encoding them using revert instructions?

Based on an earlier discussion (https://github.com/ethereum/solidity/pull/1598) it would seem more natural to me to treat assertions like runtime errors (e.g., division by zero) by encoding them using invalid instructions.

Just to provide some background, I'm working on a formal analysis tool for EVM bytecode and it would be very useful if errors (i.e., implicit or explicit assertion violations) could be distinguished from parameter validation (i.e., explicit throws or assumption/precondition violations in the verification community).

2017-02-16 14:47 UTC, chriseth commented
@wuestholz thanks for your input and for closely following the progress here! I indeed spent some thoughts on this but it seems not enough :-)

So the idea would be that safety conditions are violated if and only if `INVALID` can be reached in any way. External failures (failed call) and invalid input (manual throw) would not be considered violations of the safety conditions. I wonder whether conditions for invalid inputs can also be handled more expressively than `if (x) revert();`.

2017-02-16 14:54 UTC, chriseth commented
Please see https://github.com/ethereum/solidity/compare/assertError?expand=1

2017-02-16 15:02 UTC, axic commented
`assert()` can be pretty much used for input validation, e.g. it falls into the same category as `throw`.

2017-02-16 15:32 UTC, wuestholz commented
@axic @chriseth Thank you very much for the quick reply! It seems like there are certain discrepancies here.

I believe my view is consistent with what @chriseth wrote above. All errors or violations of safety conditions would use `INVALID`, whereas throws would use `REVERT`.

@chriseth What exactly do you mean by failed calls? For instance, does this include calls that run out of gas?

Another way to express such input validation would be a precondition or an assume-statement: `assume(expr)`. I think this would be somewhat nicer than throw statements (`assume(false)` is essentially `throw`), but this might be just due to my background. :) However, this wouldn't necessarily be backwards-compatible, if one would deprecate `throw` afterwards.

I understand the point about providing some indication of what went wrong (e.g., using a message). I think this would be nice for both errors and throws/reverts.

The cleanest solution might be to advocate an `ASSERT` opcode for the EVM that works similar to `REVERT`; i.e., take same inputs (incl. message), but possibly draining the gas like `INVALID`. What do you think? Would that be an option?

2017-02-16 16:04 UTC, axic commented
My motivation was to use `assert` as means of input validation (I'd be lazy adding a `if (x) revert(y)` for every field).

Then again we could think about having:
- `assume()` (invalid) and `assert()` (revert)
- `assert()` (invalid) and `ensure()` (revert)

I don't see the possibility to introducing an `ASSERT` opcode anytime soon.

2017-02-16 16:36 UTC, chriseth commented
assume / assert sounds good. @axic your comment about not being able to specify a message only concerns messages where callers might react to automatically. If you want to provide a message to the user, you can do that also with an invalid opcode: `PUSH "message" INVALID` - it will be visible in the debugger. A caller might respond differently to a failed input assumption (this might be invalid internal state because some other transaction went in earlier, invalid input that can be reported back to the user or an interface that is not supported to be used in a certain way), but a failed internal assertions - there is nothing you can do and they should all be treated identically.

2017-02-17 10:04 UTC, wuestholz commented
@chriseth @axic Great that `PUSH` allows for a convenient way to provide a message to the user in case of an assertion violation! (This would also be quite nice for "built-in" exceptions, such as division-by-zero.)

If deprecating `throw` is indeed an option I would go with the assume-assert solution I sketched earlier and allow for both commands to optionally take a message. Otherwise, a less invasive solution would keep throw and just change the encoding of `assert` as implemented in https://github.com/ethereum/solidity/pull/1702.