Update the sphinx highlighting rules
ethereum/solidity pull request #1684
Opened 2017-02-11 23:24 UTC by federicobond

Fixes #1654. Feedback welcome!

2017-02-11 23:46 UTC, axic commented
Now I have to keep this updated with my changes :( :)

2017-02-11 23:49 UTC, axic commented on docs/utils/SolidityLexer.py
>                   ['fixed%dx%d' % ((i), (j + 8)) for i in range(0, 256, 8) for j in range(0, 256 - i, 8)]
This will need an update too, since the notation was changed.

2017-02-11 23:54 UTC, axic requested changes

2017-02-11 23:54 UTC, axic commented on docs/utils/SolidityLexer.py
>                   ['fixed%dx%d' % ((i), (j + 8)) for i in range(0, 256, 8) for j in range(0, 256 - i, 8)]
This will need an update too, since the notation was changed.

2017-02-11 23:54 UTC, axic commented on docs/utils/SolidityLexer.py
> +            (r'(for|in|while|break|return|continue|if|else|throw|new|delete|this|super|'
I'm not sure about `this` and `super`, as they do seem like a keyword, but technically they are not declared as a keyword.

2017-02-11 23:54 UTC, axic commented on docs/utils/SolidityLexer.py
> +            (r'(for|in|while|break|return|continue|if|else|throw|new|delete|this|super|'
Can we maybe order these the order they are in `libsolidity/parsing/Token.h`? It is easier to verify that nothing is missing that way.

2017-02-11 23:54 UTC, axic commented on docs/utils/SolidityLexer.py
> +            (r'(abstract|after|case|catch|default|final|in|inline|interface|let|match|'
Thanks, this is also in the order they are defined in `Token.h`.

2017-02-11 23:54 UTC, axic commented on docs/utils/SolidityLexer.py
> +            (r'(block|msg|now|tx|assert|addmod|mulmod|keccak256|sha3|sha256|ripemd160|'
This is missing `suicide` and `log0` to `log4`.

2017-02-12 01:09 UTC, federicobond commented
@axic sorry, I didn't know you were already working on this. Will update this tomorrow.

2017-02-12 01:10 UTC, axic commented
> sorry, I didn't know you were already working on this.

I mean there's one more thing to update now every time we add a feature 😉

2017-02-12 03:37 UTC, federicobond commented on docs/utils/SolidityLexer.py
> +            (r'(block|msg|now|tx|assert|addmod|mulmod|keccak256|sha3|sha256|ripemd160|'
Fixed.

2017-02-12 03:42 UTC, federicobond commented on docs/utils/SolidityLexer.py
>                   ['fixed%dx%d' % ((i), (j + 8)) for i in range(0, 256, 8) for j in range(0, 256 - i, 8)]
Where can I find the updated notation?

2017-02-12 03:43 UTC, federicobond commented on docs/utils/SolidityLexer.py
> +            (r'(for|in|while|break|return|continue|if|else|throw|new|delete|this|super|'
Done. I kept the `this` and `super` as keywords though, because I couldn't find a better category.

2017-02-12 13:22 UTC, axic commented on docs/utils/SolidityLexer.py
>                   ['fixed%dx%d' % ((i), (j + 8)) for i in range(0, 256, 8) for j in range(0, 256 - i, 8)]
In `fixedMxN` `N` refers to the number of decimal digits now as opposed to bit width. However as I see it is not yet updated anywhere so probably fine to keep.

2017-02-12 13:26 UTC, axic commented on docs/utils/SolidityLexer.py
> +            (r'(assert|addmod|block|ecrecover|keccak256|log[0-4]|msg|mulmod|now|'
Can you please order this the same way as in `GlobalContext.cpp`? (We should change `GlobalContext.cpp` to be in lexical order at some point, but makes it easier to confirm.)

2017-02-12 13:28 UTC, axic commented on docs/utils/SolidityLexer.py
> +            (r'(anonymous|break|constant|continue|else|external|if|indexed|internal|'
This is missing a couple of keywords, `as` and `assembly` to name a few. See the keywords section in `Token.h`.

2017-02-13 00:08 UTC, federicobond commented
OK, I think I got them all.

2017-02-13 15:06 UTC, axic commented on docs/utils/SolidityLexer.py
> +             r'sha256|ecrecover|ripemd160|assert)', Name.Builtin),
Sorry, `revert` was merged since and needs to be added here.

2017-02-13 16:57 UTC, federicobond commented on docs/utils/SolidityLexer.py
> +             r'sha256|ecrecover|ripemd160|assert)', Name.Builtin),
Fixed.

2017-02-13 17:01 UTC, axic reviewed
I think these are last missing pieces.

2017-02-13 17:01 UTC, axic commented on docs/utils/SolidityLexer.py
> +            (r'(msg|tx|now|suicide|selfdestruct|addmod|mulmod|sha3|keccak256|log[0-4]|'
Missing `block`.

2017-02-13 17:01 UTC, axic commented on docs/utils/SolidityLexer.py
> +            (r'(anonymous|as|assembly|break|constant|continue|else|external|if|'
Missing `do` and `hex`.

2017-02-13 17:06 UTC, federicobond commented
Done! I'm sorry it took so much to get it right. I didn't mean to take that much time from you @axic.

2017-02-13 17:24 UTC, axic approved these changes

2017-02-13 17:24 UTC, axic commented
@federicobond no worries!

2017-02-13 18:38 UTC, merged