Publish soljson and alpine static build on github release page.
ethereum/solidity pull request #1796
Opened 2017-03-16 17:38 UTC by chriseth

This still needs to be tested using an actual release.

2017-03-16 18:00 UTC, konradkonrad requested changes
thanks for tackling this! there are two minor issues that I could spot right away.

2017-03-16 18:00 UTC, konradkonrad commented on .travis.yml
> +        tmp_container=$(docker create brainbot-com/solidity-static sh)
this should probably read:
```
tmp_container=$(docker create ethereum/solc:build sh)
```

2017-03-16 18:00 UTC, konradkonrad commented on .travis.yml
> +        docker cp ${tmp_container}:/usr/local/bin/solc upload/
```
docker cp ${tmp_container}:/usr/bin/solc upload/
```
-- your binary ends up in `/usr/bin`:
```
 docker run --rm -it ethereum/solc:stable sh -c 'which solc'
/usr/bin/solc
```

2017-03-17 00:32 UTC, axic commented on .travis.yml
> +        tmp_container=$(docker create brainbot-com/solidity-static sh)
Shouldn't this part be made into a script instead?

2017-03-17 11:58 UTC, chriseth commented
Tested this and it is working: https://github.com/chriseth/solidity/releases/tag/v0.0.3 (look at the nice small solc executable :-) )

2017-03-20 11:23 UTC, chriseth commented
@axic can this be merged?

2017-03-20 12:45 UTC, axic commented
Is there a way to name it a bit more expressively? It won't be mistaken for a Windows binary because lacking `.exe`, but it could be mistaken for an macOS binary.

Perhaps `solc-static-linux`?

2017-03-20 12:46 UTC, axic commented on .travis.yml
> -          condition: $SOLC_RELEASE == On
Is this intentional?

2017-03-20 12:47 UTC, axic commented
Otherwise looks good!

2017-03-20 13:02 UTC, chriseth commented on .travis.yml
> -          condition: $SOLC_RELEASE == On
Yes, it will just attach everything that is in the `upload` folder.

2017-03-20 13:03 UTC, chriseth commented
Renamed.

2017-03-20 13:05 UTC, axic approved these changes

2017-03-20 13:24 UTC, merged