Introduce formatExceptionInformation
ethereum/solidity pull request #2098
Opened 2017-03-29 21:40 UTC by axic

2017-03-30 07:37 UTC, chriseth approved these changes

2017-03-30 07:38 UTC, chriseth commented
An include seems to be missing, otherwise fine.

2017-03-30 10:20 UTC, axic commented
@chriseth changed the CLI too. It is more clear and the new line is controlled by the caller.

This reminds me that some of the newlines perhaps should be removed in SourceReferenceFormatter.

2017-03-30 12:06 UTC, chriseth requested changes

2017-03-30 12:06 UTC, chriseth commented on solc/CommandLineInterface.cpp
> +			cerr << SourceReferenceFormatter::formatExceptionInformation(
Can you move all these into a helper function that adds cerr and the newline?

2017-04-10 11:56 UTC, axic commented on solc/CommandLineInterface.cpp
> +			cerr << SourceReferenceFormatter::formatExceptionInformation(
I could just leave them at `printExceptionInformation`, that does that exactly.

2017-04-10 12:06 UTC, axic commented
@chriseth I think this can be merged

2017-04-10 12:54 UTC, chriseth approved these changes

2017-04-10 12:54 UTC, chriseth commented
Still not compiling.

2017-04-10 13:46 UTC, merged