Support --allow-path in the CLI
ethereum/solidity pull request #2133
Opened 2017-04-19 15:58 UTC by axic

2017-04-19 18:30 UTC, chriseth requested changes
Perhaps call it `--allow-paths` and please add an explanation in the documentation.

2017-04-19 18:30 UTC, chriseth commented on solc/CommandLineInterface.cpp
> +			po::value<string>()->value_name("path"),
`path(s)`?

2017-04-19 18:49 UTC, axic commented
Changed. Please review the docs, don't know if the sentence is true there :)

2017-04-20 11:50 UTC, chriseth commented on Changelog.md
> +   path(s) of the supplied contract(s) is always trusted.
Should be `supplied source file(s)`.

2017-04-20 11:51 UTC, chriseth commented on docs/using-the-compiler.rst
> +Important to note is that paths of included sources files and paths defined by remappings are allowed to include, but everything else is rejected. Additional paths can be added via the ``--allow-path
`paths of source files specified on the commandline and paths defined by remappings...`

It is probably better to put that in line 16.

2017-04-20 14:35 UTC, axic commented on docs/using-the-compiler.rst
> +Important to note is that paths of included sources files and paths defined by remappings are allowed to include, but everything else is rejected. Additional paths can be added via the ``--allow-path
Reworded, still not sure. Where exactly at line 16 should it go?

2017-04-20 14:53 UTC, chriseth approved these changes

2017-04-20 16:03 UTC, merged