Support tuple assignment in inline assembly
ethereum/solidity pull request #2244
Opened 2017-05-05 20:09 UTC by axic

2017-05-17 09:11 UTC, axic commented
Do we want to support multiple right hand side items?

2017-05-17 09:48 UTC, chriseth commented
I would not want to support "multiple right hand sides". The only reason of existence for this syntactical construct is to handle functions returning multiple values. Introducing tuple expressions would complicated the language.

2017-05-17 09:50 UTC, chriseth requested changes

2017-05-17 09:50 UTC, chriseth commented on libsolidity/inlineasm/AsmCodeGen.cpp
> +			var.stackHeight = --index;
I think this changes semantics. `height` can be much more than just the current expression stack.
The following could work:
```
index--;
var.stackHeight = height - index;
```

2017-05-19 09:28 UTC, axic commented
This is missing assignment, only support variable declaration.

2017-05-19 16:14 UTC, axic commented on test/libsolidity/InlineAssembly.cpp
> +	CHECK_PARSE_ERROR("{ function f() -> x, y {} let x, x := f() }", ParserError, "");
Need failure reason.

2017-05-23 09:56 UTC, axic commented
@chriseth happy to merge this?

2017-05-23 10:18 UTC, chriseth approved these changes

2017-05-23 10:18 UTC, merged