Analyze InlineAssembly for variable use
ethereum/solidity pull request #2265
Opened 2017-05-11 15:02 UTC by roadriverrail

The unused variable checker in StaticAnalyzer did not conssider
InlineAssembly objects.  This commit introduces that missing feature.

2017-05-11 19:23 UTC, axic commented
Thanks! Can you please add a changelog entry too?

2017-05-11 19:31 UTC, axic commented
There seems to be some kind of failure:

```
Testing soljson via the fuzzer...
Invalid error: "Internal compiler error (/home/travis/build/ethereum/solidity/libsolidity/analysis/StaticAnalyzer.cpp:58): 
"
scripts/../test/cmdlineTests.sh: line 80: 11462 Aborted                 (core dumped) "$REPO_ROOT"/build/test/solfuzzer --quiet < "$f"
```

2017-05-11 19:34 UTC, roadriverrail commented
I'm not familiar with the fuzzer, and I'm not sure how to see the source that broke it.  I see the `solAssert()` that caused the crash, though.

My first guess is that the input in question had an `assembly { }` block outside of a function definition, which then left `m_localVarUseCount( )` from being empty.  I could fix that by adding  an `m_currentFunction` check, but I'd love to know for sure that I'm describing the issue correctly.

2017-05-11 19:42 UTC, axic commented
> I'm not familiar with the fuzzer, and I'm not sure how to see the source that broke it.

The fuzzer test extracts all the cases form the `test` directory and runs the tool on it. There's no actual fuzzing happening :)

2017-05-11 20:25 UTC, axic commented on libsolidity/analysis/StaticAnalyzer.cpp
> +	if (m_currentFunction)
Not sure which is more readable, but alternatively `if (!m_currentFunction) return true` would reduce the indentation one level.

2017-05-11 20:35 UTC, roadriverrail commented on libsolidity/analysis/StaticAnalyzer.cpp
> +	if (m_currentFunction)
You have a point.  I'd followed the idiom from other functions, but I can change this if you have strong enough feelings about it.

2017-05-11 21:38 UTC, axic commented
```
  ℹ  08:11:09 PM.832|eth  Killing state database (WithExisting::Kill).
Warning: This is a pre-release compiler version, please do not use it in production.
:6:6: Error: Variable name n already taken in this scope.
					let n := calldataload(4)
					^----------------------^
:7:6: Error: Variable name a already taken in this scope.
					let a := 1
					^--------^
:8:6: Error: Variable name b already taken in this scope.
					let b := a
					^--------^
:9:5: Error: Label name loop already taken in this scope.
				loop:
				^--^
:14:5: Error: Label name loopend already taken in this scope.
				loopend:
				^-----^
/home/travis/build/ethereum/solidity/test/../test/libsolidity/SolidityExecutionFramework.h(68): error in "inline_assembly_jumps": Compiling contract failed
/home/travis/build/ethereum/solidity/test/libsolidity/../ExecutionFramework.h(72): fatal error in "inline_assembly_jumps": critical check !m_output.empty() failed
*** 2 failures detected in test suite "SolidityTests"
```

I think you'd need to have a copy of the analysis annotation otherwise multiple invocations will result in the above. I might be wrong though.

2017-05-11 22:01 UTC, roadriverrail commented
Hunh.  I thought I'd seen that happen without my changes in place, too.  Will re-investigate.

2017-05-12 00:21 UTC, roadriverrail commented
I was able to get around the issue by feeding in a fresh `AsmAnalysisInfo` when calling the function, so the analysis that gets run isn't being run with the state of prior analyses.  It simulates the state that's present when `TypeChecker` uses the `AsmAnalyzer`, but without interfering with any existing state.  I think this works, but the inline asm stuff is new to me.

2017-05-17 09:54 UTC, chriseth requested changes
I think it would be better to not re-run the full inline assembly anlysis and instead take a look at the result of this analysis:
The keys of `_inlineAssembly.annotation().externalReferences` are all identifiers that are referenced from within the inline assembly. You already use this mapping in your implementation, so the only change would be to loop over it completely instead of waiting for a callback from the analyzer to access it at a certain point.

2017-05-17 13:17 UTC, roadriverrail commented
@chriseth You know, I think that you're right.  I had previously rejected this idea because I thought that `ExternalIdentifierInfo` couldn't be used this way, since it references a `Declaration` with no clear indication that the `Declaration` was for a variable.  I didn't appreciate that I can do an `if (auto var = ...` and it'll naturally filter things that don't fit the `dynamic_cast` demands correctly.  Let me rewrite this and see if I can have it ready in time for today's meeting.

2017-05-19 13:46 UTC, chriseth commented on libsolidity/analysis/StaticAnalyzer.cpp
>  #include <memory>
We are in process of changing the header order to:

header that belongs to the cpp file

headers of the sub-project
headers of the project
boost
std

(i.e. in direction from most specific to most generic with an exception for the header belonging to the cpp file)

This has the advantage that some dependency problems between headers are more likely to be detected.

You don't need to change this here, though, if you don't want to.

2017-05-19 13:47 UTC, chriseth commented on libsolidity/analysis/StaticAnalyzer.cpp
> +using namespace dev::solidity::assembly;
I'm not sure if we should do this. There are some identifiers that exist both in `dev::solidity` and `dev::assembly`.

2017-05-19 13:47 UTC, chriseth commented on libsolidity/analysis/StaticAnalyzer.cpp
> +using namespace dev::solidity::assembly;
You can perhaps do it in individual functions.

2017-05-19 13:47 UTC, chriseth commented on libsolidity/analysis/StaticAnalyzer.cpp
> +	for (auto ref: _inlineAssembly.annotation().externalReferences)
Please use `auto const& ref` here.

2017-05-19 20:32 UTC, axic commented on libsolidity/analysis/StaticAnalyzer.cpp
> +using namespace dev::solidity::assembly;
I think this is not even needed anymore, as none of the assembly AST items are used.

2017-05-22 14:34 UTC, chriseth approved these changes

2017-05-22 14:34 UTC, merged

2017-05-22 17:15 UTC, axic commented on libsolidity/analysis/StaticAnalyzer.cpp
> +#include <libsolidity/inlineasm/AsmData.h>
Realised that none of these includes are needed now I think?

@roadriverrail could you remove in a subsequent PR?

2017-05-22 17:24 UTC, roadriverrail commented
@axic Roger that.  I'll get it out as soon as I can.  Funny, because I
bothered to reorder them. :)

On Mon, May 22, 2017 at 1:15 PM Alex Beregszaszi <notifications@github.com>
wrote:

> *@axic* commented on this pull request.
> ------------------------------
>
> In libsolidity/analysis/StaticAnalyzer.cpp
> <https://github.com/ethereum/solidity/pull/2265#discussion_r117798873>:
>
> >  #include <libsolidity/ast/AST.h>
> +#include <libsolidity/inlineasm/AsmAnalysis.h>
> +#include <libsolidity/inlineasm/AsmAnalysisInfo.h>
> +#include <libsolidity/inlineasm/AsmData.h>
>
> Realised that none of these includes are needed now I think?
>
> @roadriverrail <https://github.com/roadriverrail> could you remove in a
> subsequent PR?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum/solidity/pull/2265#pullrequestreview-39535843>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAlhYKZi848g4mIOECun6SMElVzA4Lgzks5r8cKlgaJpZM4NYIh0>
> .
>

2017-05-30 09:35 UTC, odapplications commented
Not sure if this is related. 

But when using the code found here - https://www.ethereum.org/crowdsale

the first line does not seem to work too well...

contract token { function transfer(address receiver, uint amount){  } }

The following error is returned:

 Could not compile source code. 

 Unused local variable
contract token { function transfer(address receiver, uint amount){  } }
                                                     ^---------^
, 

not sure what the problem maybe.. I even changed the word "token" to something else and still get an error...

2017-05-30 10:23 UTC, odapplications commented
This code solved my problem...
`pragma solidity ^0.4.0;

contract ERC20Constant {
    function totalSupply() constant returns (uint supply);
    function balanceOf( address who ) constant returns (uint value);
    function allowance(address owner, address spender) constant returns (uint _allowance);
}
contract ERC20Stateful {
    function transfer( address to, uint value) returns (bool ok);
    function transferFrom( address from, address to, uint value) returns (bool ok);
    function approve(address spender, uint value) returns (bool ok);
}
contract ERC20Events {
    event Transfer(address indexed from, address indexed to, uint value);
    event Approval( address indexed owner, address indexed spender, uint value);
}
contract ERC20 is ERC20Constant, ERC20Stateful, ERC20Events {}

contract owned {
    address public owner;

    function owned() {
        owner = msg.sender;
    }

    modifier onlyOwner {
        if (msg.sender != owner) throw;
        _;
    }

    function transferOwnership(address newOwner) onlyOwner {
        owner = newOwner;
    }
}

// contract can buy or sell tokens for ETH
// prices are in amount of wei per batch of token units

contract TokenTrader is owned {

    address public asset;       // address of token
    uint256 public buyPrice;   // contact buys lots of token at this price
    uint256 public sellPrice;  // contract sells lots at this price
    uint256 public units;       // lot size (token-wei)

    bool public sellsTokens;    // is contract selling
    bool public buysTokens;     // is contract buying

    event ActivatedEvent(bool sells, bool buys);
    event UpdateEvent();

    function TokenTrader (
        address _asset, 
        uint256 _buyPrice, 
        uint256 _sellPrice, 
        uint256 _units,
        bool    _sellsTokens,
        bool    _buysTokens
        )
    {
          asset         = _asset; 
          buyPrice     = _buyPrice; 
          sellPrice    = _sellPrice;
          units         = _units; 
          sellsTokens   = _sellsTokens;
          buysTokens    = _buysTokens;

          ActivatedEvent(sellsTokens,buysTokens);
    }

    // modify trading behavior
    function activate (
        bool    _sellsTokens,
        bool    _buysTokens
        ) onlyOwner
    {
          sellsTokens   = _sellsTokens;
          buysTokens    = _buysTokens;

          ActivatedEvent(sellsTokens,buysTokens);
    }

    // allows owner to deposit ETH
    // deposit tokens by sending them directly to contract
    // buyers must not send tokens to the contract, use: sell(...)
    function deposit() payable onlyOwner {
        UpdateEvent();
    }

    // allow owner to remove trade token
    function withdrawAsset(uint256 _value) onlyOwner returns (bool ok)
    {
        return ERC20(asset).transfer(owner,_value);
        UpdateEvent();
    }

    // allow owner to remove arbitrary tokens
    // included just in case contract receives wrong token
    function withdrawToken(address _token, uint256 _value) onlyOwner returns (bool ok)
    {
        return ERC20(_token).transfer(owner,_value);
        UpdateEvent();
    }

    // allow owner to remove ETH
    function withdraw(uint256 _value) onlyOwner returns (bool ok)
    {
        if(this.balance >= _value) {
            return owner.send(_value);
        }
        UpdateEvent();
    }

    //user buys token with ETH
    function buy() payable {
        if(sellsTokens || msg.sender == owner) 
        {
            uint order   = msg.value / sellPrice; 
            uint can_sell = ERC20(asset).balanceOf(address(this)) / units;

            if(order > can_sell)
            {
                uint256 change = msg.value - (can_sell * sellPrice);
                order = can_sell;
                if(!msg.sender.send(change)) throw;
            }

            if(order > 0) {
                if(!ERC20(asset).transfer(msg.sender,order * units)) throw;
            }
            UpdateEvent();
        }
        else if(!msg.sender.send(msg.value)) throw;  // return user funds if the contract is not selling
    }

    // user sells token for ETH
    // user must set allowance for this contract before calling
    function sell(uint256 amount) {
        if (buysTokens || msg.sender == owner) {
            uint256 can_buy = this.balance / buyPrice;  // token lots contract can buy
            uint256 order = amount / units;             // token lots available

            if(order > can_buy) order = can_buy;        // adjust order for funds

            if (order > 0)
            { 
                // extract user tokens
                if(!ERC20(asset).transferFrom(msg.sender, address(this), amount)) throw;

                // pay user
                if(!msg.sender.send(order * buyPrice)) throw;
            }
            UpdateEvent();
        }
    }

    // sending ETH to contract sells ETH to user
    function () payable {
        buy();
    }
}

// This contract deploys TokenTrader contracts and logs the event
// trade pairs are identified with sha3(asset,units)

contract TokenTraderFactory {

    event TradeListing(bytes32 bookid, address owner, address addr);
    event NewBook(bytes32 bookid, address asset, uint256 units);

    mapping( address => bool ) _verify;
    mapping( bytes32 => bool ) pairExits;
    
    function verify(address tradeContract)  constant returns (
        bool valid,
        address asset, 
        uint256 buyPrice, 
        uint256 sellPrice, 
        uint256 units,
        bool    sellsTokens,
        bool    buysTokens       
        ) {
            
            valid = _verify[tradeContract];
            
            if(valid) {
                TokenTrader t = TokenTrader(tradeContract);
                
                asset = t.asset();
                buyPrice =t.buyPrice();
                sellPrice = t.sellPrice();
                units = t.units();
                sellsTokens = t.sellsTokens();
                buysTokens = t.buysTokens();
            }
        
    }

    function createTradeContract(       
        address _asset, 
        uint256 _buyPrice, 
        uint256 _sellPrice, 
        uint256 _units,
        bool    _sellsTokens,
        bool    _buysTokens
        ) returns (address) 
    {
        if(_buyPrice > _sellPrice) throw; // must make profit on spread
        if(_units == 0) throw;              // can't sell zero units

        address trader = new TokenTrader (
                     _asset, 
                     _buyPrice, 
                     _sellPrice, 
                     _units,
                     _sellsTokens,
                     _buysTokens);

        var bookid = sha3(_asset,_units);

        _verify[trader] = true; // record that this factory created the trader

        TokenTrader(trader).transferOwnership(msg.sender); // set the owner to whoever called the function

        if(pairExits[bookid] == false) {
            pairExits[bookid] = true;
            NewBook(bookid, _asset, _units);
        }

        TradeListing(bookid,msg.sender,trader);
    }

    function () {
        throw;     // Prevents accidental sending of ether to the factory
    }
}`

2017-05-30 10:24 UTC, odapplications commented
Found here - https://etherscan.io/address/0x3398080b81a1cff1429af347ce2b17fc28de3937#code