add legacy/compact AST-format options to CL
ethereum/solidity pull request #2287
Opened 2017-05-22 14:40 UTC by djudjuu

- standard-json doc updated saying both formats are supported
- another option --ast-compact-json
- includes extra argument "compact-format" for option --combined-json

2017-05-22 15:23 UTC, chriseth commented on solc/CommandLineInterface.cpp
> +static string const g_strCompactJSON = "compact-format";
I think those are supposed to be sorted by variable name.

2017-05-22 15:35 UTC, djudjuu commented on solc/CommandLineInterface.cpp
> +static string const g_strCompactJSON = "compact-format";
oh..that was't obvious because the order was messed a bit already....I will adjust the other ones too

2017-05-23 09:48 UTC, axic commented on solc/CommandLineInterface.cpp
> +static string const g_argAstCompactJson = g_strAstCompactJson;
Should be before `AstJson`?

2017-05-23 09:48 UTC, axic commented on solc/CommandLineInterface.cpp
>  static string const g_argMetadataLiteral = g_strMetadataLiteral;
Please move these two as well :)

2017-05-23 09:48 UTC, axic commented on solc/CommandLineInterface.cpp
>  static string const g_strMetadataLiteral = "metadata-literal";
Please move these two as well.

2017-05-23 10:59 UTC, djudjuu commented on solc/CommandLineInterface.cpp
>  static string const g_strMetadataLiteral = "metadata-literal";
to where? I thought they are supposed to be alphabetically ordered...

2017-05-23 11:02 UTC, axic commented on solc/CommandLineInterface.cpp
>  static string const g_strMetadataLiteral = "metadata-literal";
`stdin` < `str` and `strM` < `strV` :)

2017-05-23 13:15 UTC, djudjuu commented
i am not sure why the travis tests fail. looks bytecode related. Any hints how to fix that?

2017-05-24 12:30 UTC, chriseth requested changes

2017-05-24 12:30 UTC, chriseth commented on solc/CommandLineInterface.cpp
> +		bool legacyFormat = true;
What about `bool legacyFormat = !requests.count(g_strCompactJSON);`?

2017-05-24 12:30 UTC, chriseth commented on solc/CommandLineInterface.cpp
> +		bool legacyFormat= true;
This can also be shortened.

2017-05-24 12:36 UTC, axic commented on solc/CommandLineInterface.cpp
> +		bool legacyFormat= true;
Also space before `=` please

2017-05-24 16:47 UTC, djudjuu commented on solc/CommandLineInterface.cpp
> +		bool legacyFormat= true;
done.

2017-05-29 12:24 UTC, merged