Fix scope assert in AsmAnalyzer
ethereum/solidity pull request #2294
Opened 2017-05-23 21:59 UTC by axic

2017-05-23 22:00 UTC, axic commented
For `.at`: 
> Returns a reference to the mapped value of the element with key equivalent to key. If no such element exists, an exception of type std::out_of_range is thrown.

Essentially the assert was useless.

2017-05-24 09:19 UTC, chriseth approved these changes

2017-05-24 09:20 UTC, chriseth requested changes

2017-05-24 09:20 UTC, chriseth commented on libsolidity/inlineasm/AsmAnalysis.cpp
> -	solAssert(scopePtr, "Scope requested but not present.");
This assert checks that `*scopePtr` is a valid operation, this is still a different check than below.

2017-05-24 09:23 UTC, axic commented on libsolidity/inlineasm/AsmAnalysis.cpp
> -	solAssert(scopePtr, "Scope requested but not present.");
True, though probably it should only be part of the map if it actually exists.

2017-05-24 12:19 UTC, chriseth approved these changes

2017-05-24 12:19 UTC, merged