Validate types for Julia (part 1)
ethereum/solidity pull request #2311
Opened 2017-05-25 01:12 UTC by axic

2017-05-26 11:05 UTC, axic commented
This is ready now.

2017-05-26 13:16 UTC, chriseth requested changes

2017-05-26 13:16 UTC, chriseth commented on libsolidity/inlineasm/AsmAnalysis.cpp
> +	if (!(set<string>{"bool", "u8", "s8", "u32", "s32", "u64", "s64", "u128", "s128", "u256", "s256"}).count(type))
Can you move the list of valid types to some more prominent position, e.g. a variable in an anonymous namespace in this cpp file?

2017-05-26 13:16 UTC, chriseth commented on libsolidity/inlineasm/AsmAnalysis.cpp
> +			"User defined types (\"" + type + "\") are not supported yet.",
Perhaps better `<type> is not a valid type (user defined types are not yet supported)`?

2017-05-26 20:13 UTC, axic commented
@chriseth updated

2017-05-29 12:12 UTC, chriseth commented on libsolidity/inlineasm/AsmAnalysis.h
> +	explicit AsmAnalyzer(
`explicit` is only useful if there is a constructor that takes only one (required) argument. But it does not hurt either.

2017-05-29 12:12 UTC, chriseth approved these changes

2017-05-29 12:12 UTC, merged