Parser cleanup (remove dependency on Solidity AST)
ethereum/solidity pull request #2312
Opened 2017-05-25 01:13 UTC by axic

2017-05-26 08:56 UTC, axic commented
This should be merged after #2224.

2017-05-26 12:52 UTC, chriseth requested changes

2017-05-26 12:52 UTC, chriseth commented on libsolidity/parsing/Parser.cpp
> +		if (Token::isElementaryTypeName(op)) //for the sake of accuracy in reporting
Can you pull out the common parts in the clauses here?

2017-05-26 12:52 UTC, chriseth commented on libsolidity/parsing/Parser.cpp
> +			fatalParserError(
Again, please combine the common parts.

2017-05-26 20:13 UTC, axic commented
@chriseth updated

2017-05-29 12:03 UTC, chriseth approved these changes

2017-05-29 12:04 UTC, merged