Print information about types of errors.
ethereum/solidity pull request #2334
Opened 2017-06-01 10:28 UTC by chriseth

2017-06-01 12:05 UTC, axic commented on test/libsolidity/SolidityNameAndTypeResolution.cpp
> +					message += *description + ", ";
comma or new line to separate them?

2017-06-01 12:05 UTC, axic commented
I think this could be added to most tests which require a single error. Though this really calls for a helper to pull that code into a single place.

2017-06-06 13:05 UTC, chriseth commented
@axic please request changes and do a proper review :-)

2017-06-06 13:05 UTC, chriseth commented
I mean either say "it's fine, can be merged" or "this and that has to be changed"

2017-06-08 14:31 UTC, axic requested changes
Please make this a helper and it to all tests.

2017-07-19 11:26 UTC, axic approved these changes

2017-07-19 20:25 UTC, merged