Silence implicit fallthrough warning
ethereum/solidity pull request #2339
Opened 2017-06-01 14:12 UTC by LefterisJP

In my system I have gcc 7.1.1 and there I get a lot of warnings which
fail the build due to implicit fallthroughs in switch statements.

Some examples can be seen here:
https://gist.github.com/LefterisJP/388c3ba5ad356f92a3b44e7efed89f9f

This PR proposes a simple solution, which is to ignore the warning for
both gcc and clang since implici fallthrough is actively used in the codebase and don;t know of a way to locally ignore it on a case by case basis.

2017-06-01 15:52 UTC, chriseth requested changes
I'm not in favour of disabling warnings. How many of them are there? I think there are portable ways to decorate intentional fall-throughs.

2017-06-01 21:45 UTC, LefterisJP commented
@chriseth 

I am also not in favour of disabling them but this is the easiest solution that I used locally (to have solc again) temporarily until I bring the matter to your attention.

>  How many of them are there? 

There were quite a few cases.

There is no standard way to disable them locally. According to [this](https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/) we can use the following non-standard ways:

```c++
switch (cond)
 {
 case 1:
   bar (1);
   __attribute__ ((fallthrough)); // C and C++03
 case 2:
   bar (2);
   [[gnu::fallthrough]]; // C++11 and C++14
 case 3:
   bar (3);
   [[fallthrough]]; // C++17 and above
 /* ... */
 }
```

You can also tweak the level of fallthrough ranging from `-Wimplicit-fallthrough=0` to `-Wimplicit-fallthrough=3`.

I am not sure what you guys think is the best for the codebase as it stands now but I suggest having a look at the aforementioned article and taking a decision depending on the seriousness (or lack of) of the places where the warning hits.

2017-06-15 16:47 UTC, LefterisJP commented
@chriseth I opted for the C++03 way as per our discussion. Let's hope all the tests pass.

2017-06-16 15:05 UTC, chriseth commented
It seems the compilers do not accept it. I read in some non-standard documents that this is part of C++03, but perhaps that is wrong?

2017-06-16 15:31 UTC, axic commented
Since we only have two such cases, would it make sense reordering the code so that it is not falling through?

2017-06-16 15:35 UTC, chriseth commented
If there are only two, then yes, indeed.

2017-06-22 11:51 UTC, axic commented
@LefterisJP would you be able to do the change above?

2017-06-22 17:33 UTC, chriseth commented
Refactored the code.

2017-06-25 23:41 UTC, axic commented on libsolidity/codegen/CompilerUtils.cpp
> +		if (stackTypeCategory == Type::Category::Function)
I think this should be `stackTypeCategory == Type::Category::Function && targetTypeCategory == Type::Category::Integer` as it checks for function type to address conversion.

2017-06-25 23:42 UTC, axic commented on libsolidity/codegen/CompilerUtils.cpp
> +			// "fall-through"
This should not fall through if conversion succeeded.

2017-06-25 23:57 UTC, axic commented on libsolidity/codegen/ExpressionCompiler.cpp
> +	switch (_memberAccess.expression().annotation().type->category())
This could also use `expressionTypeCategory` from above or is that to the deteriment of readability?

2017-06-27 12:39 UTC, chriseth commented
@axic these changes really look dangerous. I think we should just disable the warning until we have  gcc7 as part of our CI.

2017-06-28 09:22 UTC, LefterisJP commented
I tend to agree. I would do the following:

1. Disable the warning with this PR.
2. Create a new issue as a followup detailing that these particular code points need to be refactored and the warning re-enabled.

2017-06-28 13:19 UTC, chriseth commented
@LefterisJP if you could do that, this would be wonderful!

2017-06-29 14:46 UTC, chriseth approved these changes

2017-06-29 14:46 UTC, merged