Include license and warranty statement with solc.
ethereum/solidity pull request #2353
Opened 2017-06-08 09:57 UTC by chriseth

We should probably also clean some headers with this pull request.

2017-06-08 12:03 UTC, axic commented on solc/license_escaped.h
> +if any, to sign a "copyright disclaimer" for the program, if necessary.
This is not escaped here

2017-06-08 12:04 UTC, axic commented
Wouldn't it be better to have a script during the build process which creates the file out of `LICENSE`?

Escaping with `sed s/"/\\\"/` :)

2017-06-08 13:06 UTC, chriseth commented on solc/license_escaped.h
> +if any, to sign a "copyright disclaimer" for the program, if necessary.
It is correctly escaped, this juts seems to be an error in github's syntax hilighting.

2017-06-08 13:06 UTC, chriseth commented
@axic indeed, I added such a script with the help of @chfast.

2017-06-08 13:08 UTC, chriseth commented
Sorry, took a while but this should now be the working version.

2017-06-08 13:09 UTC, chfast approved these changes
Looks good.

2017-06-08 13:12 UTC, axic commented on solc/CommandLineInterface.cpp
> +Solidity Copyright (C) 2014-2017 Solidity contributors.
Do we need the copyright statement here? It is not even in the headers yet.

2017-06-09 09:27 UTC, chriseth commented on solc/CommandLineInterface.cpp
> +Solidity Copyright (C) 2014-2017 Solidity contributors.
Perhaps we can do without, but the GPL "how to apply the license" suggests this. The thing is that the copyright is just shared by the authors which I think is the default, so perhaps we can just remove it.

2017-06-09 11:14 UTC, axic commented on solc/CommandLineInterface.cpp
> +Solidity Copyright (C) 2014-2017 Solidity contributors.
I think we should sort this in a separate PR which also adds it to the files. Gives us more time to find the proper wording :)

2017-06-09 11:32 UTC, axic commented on solc/CommandLineInterface.cpp
> +Solidity Copyright (C) 2014-2017 Solidity contributors.
I guess "Copyright (C) 2014-2017 the Solidity authors and contributors." should be more clear. There seem to be a distinction between the two words, whereas author means the "initial creator", while contributor is anyone else.

2017-06-09 12:01 UTC, axic requested changes
Please change the CLI to "Copyright (C) 2014-2017 the Solidity authors and contributors."

2017-06-12 10:03 UTC, chriseth commented
Perhaps it is better to just drop the statement. I'm not sure if contributors actually would get the copyright by default (as opposed to just the authors).

2017-06-13 15:02 UTC, axic approved these changes

2017-06-13 15:03 UTC, merged