LLL: macro with zero args
ethereum/solidity pull request #2375
Opened 2017-06-12 13:00 UTC by pirapira

On `develop`, LLL macros with zero arguments were not definable because `()` was not a valid list.

However, #2350 found a usage for that:  `(panic)`.

This PR modifies the parser so that LLL macros with zero arguments can be defined.

2017-06-12 13:02 UTC, axic commented
I think this is a good short term fix, though we should aim at removing the "literal definitions" and just keep macros.

2017-06-12 13:03 UTC, axic requested changes
Use different names in the test cases please, because this could conflict with the current builtin instruction as well as when the macro is added to the standard list.

Perhaps go with `headlesschicken` :)

2017-06-12 13:10 UTC, pirapira commented
I chose something more neutral.

2017-06-12 13:14 UTC, axic commented on test/liblll/Parser.cpp
> +	char const* text = "(def 'panic () (asm INVALID))";
Can you change it here too for clarity? (You are right, change is not needed here.)

2017-06-12 13:16 UTC, pirapira commented on test/liblll/Parser.cpp
> +	char const* text = "(def 'panic () (asm INVALID))";
No, that was me being headless chicken.

2017-06-12 22:42 UTC, axic commented on test/liblll/Parser.cpp
>  	BOOST_CHECK(!successParse("()"));
Tests fail on this one.

2017-06-12 22:45 UTC, axic commented on test/liblll/EndToEndTest.cpp
> +				(def 'zeroarg () (asm INVALID))
I think we should have a better test here. Such as:
```
(def 'zeroarg () { (mstore 0 0x1234) (return 0 32) })
```

2017-06-13 13:39 UTC, pirapira commented
@axic ready to merge?

2017-06-13 13:44 UTC, axic approved these changes

2017-06-13 13:44 UTC, merged