Enforce function arguments when parsing functional instructions.
ethereum/solidity pull request #2384
Opened 2017-06-13 17:08 UTC by chriseth

2017-06-13 20:35 UTC, axic commented
So far my understanding was that every instruction can be written in functional notation. This changes that into only instructions which take no arguments can be written in non-functional notation.

I think this may be a breaking change.

2017-06-13 20:38 UTC, axic commented
If we are doing a breaking change, I'd rather just prefer eliminating:
- non-functional notation altogether
- literal pushes to the stack

2017-06-13 22:43 UTC, chriseth commented
I hope this is not a breaking change, at least on my machine, the tests did not break. Note that this change only applies to the `parseExpression` function which is only invoked if we already are in a functional context like in `let x := <...>` or `mul(<...>, 2)`.

2017-06-14 13:25 UTC, axic commented on Changelog.md
> + * Inline Assembly: Enforce function arguments when parsing functional instructions.
Would add a note, perhaps in the documentation, that functional instructions are enforced within higher level constructs (vardecl, function call, etc.)

2017-06-14 13:25 UTC, axic requested changes
Would add a note, perhaps in the documentation, that functional instructions are enforced within higher level constructs (vardecl, function call, etc.)

2017-06-14 13:46 UTC, chriseth commented
Clarified.

2017-06-14 13:54 UTC, axic approved these changes

2017-06-14 16:35 UTC, merged