Warn about copies in storage that might overwrite unexpectedly.
ethereum/solidity pull request #2437
Opened 2017-06-21 17:33 UTC by chriseth

Fixes https://github.com/ethereum/solidity/issues/2434

2017-06-22 10:31 UTC, axic commented on libsolidity/analysis/TypeChecker.cpp
> +	TupleType const& lhs = *dynamic_cast<TupleType const*>(type(_assignment.leftHandSide()).get());
Is it worth adding asserts here?

2017-06-22 10:34 UTC, axic commented
Can you add a test which actually corrupts the data?

I think this should do it?
```
contract A {
  uint8 a;
  uint248 b;

  function f() {
    (a, b) = (b, a);
  }
}
```

2017-06-22 10:37 UTC, chriseth commented on libsolidity/analysis/TypeChecker.cpp
> +	TupleType const& lhs = *dynamic_cast<TupleType const*>(type(_assignment.leftHandSide()).get());
Oh sorry, this should either be a different dynamic cast, or an assertion, right.

2017-06-22 10:38 UTC, chriseth commented
You mean and end-to-end test and check that data is corrupted (I actually would not call it corrupted, it is just that the order of assignments might be un-intuitive, or rather the programmer might expect the use of a temporary)? Your example would not do - value types are not affected by this behaviour.

2017-06-22 10:42 UTC, axic commented
Yes an end-to-end test expecting the corrupted value.

2017-06-26 12:09 UTC, axic requested changes
Please add two tests:
- tuple assignments for non-storage
- tuple assignments with pointers

Since the check is disabled for those.

2017-06-27 09:23 UTC, axic approved these changes

2017-06-27 09:24 UTC, merged