Support appendAssemblySize() in AbstractAssembly
ethereum/solidity pull request #2443
Opened 2017-06-22 12:14 UTC by axic

2017-06-22 12:20 UTC, axic commented
I've tried porting lll over to use AbstractAssembly and this was needed. We haven't designed yet how to handle "Julia objects" (sub assemblies, etc.) in AbstractAssembly, but this is one step towards that.

2017-06-22 12:53 UTC, chriseth requested changes

2017-06-22 12:53 UTC, chriseth commented on libjulia/backends/evm/EVMAssembly.cpp
> +		for (size_t i = 0; i < assemblySizeReferenceSize; i++)
Can you write a helper for inserting big endian numbers? (same code is also used below)

2017-06-22 12:59 UTC, axic commented on libjulia/backends/evm/EVMAssembly.cpp
> +		for (size_t i = 0; i < assemblySizeReferenceSize; i++)
Arbitrary size?

2017-06-22 12:59 UTC, axic commented on libjulia/backends/evm/EVMAssembly.cpp
> +size_t constexpr assemblySizeReferenceSize = 4;
@chriseth any better naming suggestion here?

2017-06-22 14:17 UTC, chriseth commented on libjulia/backends/evm/EVMAssembly.cpp
> +		for (size_t i = 0; i < assemblySizeReferenceSize; i++)
If also fine with forcing everything to four bytes for now.

2017-06-22 14:17 UTC, chriseth commented on libjulia/backends/evm/EVMAssembly.cpp
> +size_t constexpr assemblySizeReferenceSize = 4;
Nothing wrong about the name :-)

2017-06-22 23:57 UTC, axic commented on libjulia/backends/evm/EVMAssembly.cpp
> +		for (size_t i = 0; i < assemblySizeReferenceSize; i++)
Added one with u256, but we could change it to size_t or even a template.

2017-06-23 09:29 UTC, chriseth approved these changes

2017-06-23 09:30 UTC, merged