Fix address literals not being treated as compile-time constants
ethereum/solidity pull request #2448
Opened 2017-06-22 14:09 UTC by federicobond

The early return implemented for address literals in TypeChecker was preventing the isPure annotation from getting applied. Closes #2441

2017-06-22 14:15 UTC, chriseth requested changes
Can you add an entry into the changelog, please?

2017-06-22 14:28 UTC, federicobond commented
@chriseth done.

2017-06-22 14:33 UTC, chriseth approved these changes

2017-06-23 09:23 UTC, chriseth commented
Added a test.

2017-06-23 09:56 UTC, merged