Added links for the getter function.
ethereum/solidity pull request #2484
Opened 2017-06-30 09:11 UTC by jamesray1

2017-06-30 09:28 UTC, jamesray1 reviewed
Changed the URL for getter to a ref.

2017-06-30 10:36 UTC, chriseth requested changes

2017-06-30 10:36 UTC, chriseth commented on docs/types.rst
> +It is possible to mark arrays ``public`` and have Solidity create a :ref:`getters <visibility-and-getters>`.
Can you change that to `getter` (singular), please?

2017-06-30 10:36 UTC, chriseth commented on docs/types.rst
> +It is possible to mark mappings ``public`` and have Solidity create a :ref:`getters <visibility-and-getters>`.
Can you change that to `getter` (singular), please?

2017-07-07 01:46 UTC, jamesray1 commented
@chriseth, I updated to getter (singular).

2017-07-18 03:42 UTC, jamesray1 commented
@chriseth

2017-07-25 13:51 UTC, chriseth commented
Thanks, this works!

2017-07-25 13:51 UTC, merged