Add type error when attempting to transfer value to a non-payable contract
ethereum/solidity pull request #2544
Opened 2017-07-09 01:47 UTC by federicobond

Fixes #1665

2017-07-09 07:26 UTC, axic commented on libsolidity/analysis/TypeChecker.cpp
> +					!(fallbackFunction && fallbackFunction->isPayable())
It is a personal taste, but for me `(!fallbackFunction || !fallbackFunction->isPayable())` seems more readable.

2017-07-09 07:27 UTC, axic requested changes
Please:
- add a test for no fallback function present
- a successful test (payable fallback)
- and a changelog entry

2017-07-09 07:29 UTC, axic commented on test/libsolidity/SolidityNameAndTypeResolution.cpp
> +				if (!a.send(100)) throw;
Change this to `require(a.send(100))` as `throw` issues a deprecation warning now (and will be removed).

2017-07-09 14:16 UTC, federicobond commented
@axic updated.

2017-07-10 10:37 UTC, axic approved these changes

2017-07-10 10:46 UTC, axic commented
Looks good to me, but @chriseth you might want to double check the `TypeChecker` part.

2017-07-10 12:55 UTC, chriseth commented on Changelog.md
> + * Type Checker: Disallow value transfers to contracts without a payable fallback function
Please update the changelog (move it to 0.4.14).

2017-07-10 12:56 UTC, chriseth commented on libsolidity/analysis/TypeChecker.cpp
> +	if (auto memberAccess = dynamic_cast<MemberAccess const*>(&_functionCall.expression()))
Wouldn't it be better to check already at `MemberAccess`?
As it currently is, `a.transfer` would not generate an error, only `a.transfer(x)` would.

2017-07-10 12:57 UTC, chriseth commented on libsolidity/analysis/TypeChecker.cpp
> +					(!fallbackFunction || !fallbackFunction->isPayable())
Can you turn this into a function on the contract type? Something like `isPayable` (on the contract, not the fallback function)?

2017-07-10 17:42 UTC, federicobond commented on libsolidity/analysis/TypeChecker.cpp
> +	if (auto memberAccess = dynamic_cast<MemberAccess const*>(&_functionCall.expression()))
Makes sense, I started thinking about putting it in the function call at first and never questioned that assumption.

2017-07-10 17:42 UTC, federicobond commented on libsolidity/analysis/TypeChecker.cpp
> +					(!fallbackFunction || !fallbackFunction->isPayable())
Sure.

2017-07-11 01:57 UTC, federicobond commented on libsolidity/analysis/TypeChecker.cpp
>  	else if (TypeType const* typeType = dynamic_cast<decltype(typeType)>(exprType.get()))
Double check this else here. I fear there might be some overlap with the code I just added, but I couldn't reproduce it.

2017-07-11 09:39 UTC, chriseth commented on libsolidity/analysis/TypeChecker.cpp
>  	else if (TypeType const* typeType = dynamic_cast<decltype(typeType)>(exprType.get()))
It is probably better to do this at the end of this function. Perhaps even in the `PostTypeChecker`.

2017-07-11 09:39 UTC, chriseth commented on libsolidity/ast/Types.h
> +	bool isPayable() const;
Please add a comment about this returning true if and only if there is a payable fallback function.

2017-07-11 16:22 UTC, federicobond commented
@chriseth updated.

2017-07-11 17:30 UTC, axic commented on libsolidity/analysis/TypeChecker.cpp
> +					"Value transfer to a contract with a non-payable fallback function."
Perhaps `without a payable fallback function.` is more helpful at showing what needs to be done.

2017-07-12 12:23 UTC, axic commented
> Expected message "Value transfer to a contract with a non-payable fallback function." but foundValue transfer to a contract without a payable fallback function.

ie. need to change the expected message in tests.

Do you want to fix the message to be? (It is not related to this PR)

> Expected message "Value transfer to a contract with a non-payable fallback function." but found "Value transfer to a contract without a payable fallback function."

2017-07-13 03:00 UTC, federicobond commented
@chriseth rebased and updated.

2017-07-13 13:04 UTC, axic commented
@chriseth are we good to merge this?

2017-07-13 13:08 UTC, chriseth approved these changes

2017-07-13 13:08 UTC, merged