Metadata: only include relevant files in the source list
ethereum/solidity pull request #2566
Opened 2017-07-13 00:13 UTC by axic

Fixes #2561.

2017-07-13 00:15 UTC, axic commented
This works for me, but the cyclic import check is a mess at the moment.

`_2561.sol`:
```
pragma solidity ^0.4.0;

import "_2561_2.sol";

contract C {
}
```

`_2561_2.sol`:
```
pragma solidity ^0.4.0;

import "_2561_3.sol";
```

`_2561_3.sol`:
```
pragma solidity ^0.4.0;

import "_2561_2.sol";
import "_2561_4.sol";
```

2017-07-13 08:28 UTC, chriseth commented
Sorry, @VoR0220 it seems @axic was faster...

2017-07-13 08:30 UTC, axic commented
Sorry didn't know @VoR0220 picked it up. @VoR0220, do you want to clean up the cyclic import part? :)

2017-07-13 08:37 UTC, chriseth requested changes

2017-07-13 08:37 UTC, chriseth commented on libsolidity/ast/AST.cpp
> +	for (auto const& node: nodes())
You could use `for (ImportDirective const* importDirective: filteredNodes<ImportDirective>(nodes())) { ... }`

2017-07-13 08:37 UTC, chriseth commented on libsolidity/ast/AST.cpp
> +			auto annotation = importDirective->annotation();
Please use `auto const&` here, otherwise it performs a copy.

2017-07-13 08:37 UTC, chriseth commented on libsolidity/ast/AST.cpp
> +std::set<SourceUnit const*> SourceUnit::referencedSourceUnits(bool _flatten, std::set<SourceUnit const*> _skipList) const
No need for `std::` prefixes here.

2017-07-13 08:37 UTC, chriseth commented on libsolidity/ast/AST.h
> +	/// @returns a set of referenced SourceUnits. Flattens them if @a _flatten is true.
Please explain the term "flatten" and also explain the `_skipList` parameter.

2017-07-13 08:37 UTC, chriseth commented on libsolidity/ast/AST.h
> +	/// @returns a set of referenced SourceUnits. Flattens them if @a _flatten is true.
Shouldn't `flatten` be rather called `recurse`?

2017-07-13 08:37 UTC, chriseth commented on libsolidity/ast/AST.cpp
> +std::set<SourceUnit const*> SourceUnit::referencedSourceUnits(bool _flatten, std::set<SourceUnit const*> _skipList) const
Perhaps it is better not to expose the `_skipList` in the public interface.

2017-07-13 08:37 UTC, chriseth commented on libsolidity/ast/AST.cpp
> +			sourceUnits.insert(annotation.sourceUnit);
Can`t you move that into the if body?

2017-07-13 08:37 UTC, chriseth commented on libsolidity/ast/AST.cpp
> +			auto annotation = importDirective->annotation();
We actually only use the `sourceUnit` from the annotation, so we could store this instead in a local variable.

2017-07-13 08:37 UTC, chriseth commented on libsolidity/ast/AST.cpp
> +					sourceUnits.insert(referencedSourceUnits.begin(), referencedSourceUnits.end());
`+=` cannot be used here?

2017-07-13 08:38 UTC, chriseth commented
What is the problem with cyclic imports?

2017-07-13 08:39 UTC, axic commented
The messy `skipList` parameter.

2017-07-13 08:40 UTC, chriseth commented
We use that all the time. Perhaps some generic template solution for that would be nice...

2017-07-13 21:27 UTC, axic commented on libsolidity/ast/AST.cpp
> +					sourceUnits.insert(referencedSourceUnits.begin(), referencedSourceUnits.end());
Not sure, this was the suggested way by SE 😉

2017-07-13 21:51 UTC, axic commented on libsolidity/ast/AST.cpp
> +std::set<SourceUnit const*> SourceUnit::referencedSourceUnits(bool _flatten, std::set<SourceUnit const*> _skipList) const
Removed `std::` prefixes.

2017-07-13 21:52 UTC, axic commented on libsolidity/ast/AST.cpp
> +	for (auto const& node: nodes())
Changed.

2017-07-13 21:52 UTC, axic commented on libsolidity/ast/AST.cpp
> +			auto annotation = importDirective->annotation();
Changed.

2017-07-13 21:52 UTC, axic commented on libsolidity/ast/AST.h
> +	/// @returns a set of referenced SourceUnits. Flattens them if @a _flatten is true.
Used flatten from "flattened arrays" used by Ruby/Python, but I guess recurse could go too.

2017-07-13 21:59 UTC, axic commented on libsolidity/ast/AST.cpp
> +					sourceUnits.insert(referencedSourceUnits.begin(), referencedSourceUnits.end());
There's no such overload. The template in `CommonData` is only for vectors.

2017-07-14 09:45 UTC, chriseth commented on libsolidity/ast/AST.h
> +	/// @returns a set of referenced SourceUnits. Flattens them if @a _flatten is true.
Sure, but if flatten is false, it does not return a non-flattened structure, so I think recurse is a much better fit.

2017-07-14 09:46 UTC, chriseth commented
Rename and good to go.

2017-07-14 09:46 UTC, chriseth commented
Oh and some tests :-)

2017-07-18 18:24 UTC, axic commented
Renamed `flatten` and added tests.

2017-07-18 19:20 UTC, axic commented on libsolidity/ast/AST.cpp
> +set<SourceUnit const*> SourceUnit::referencedSourceUnits(bool _recurse, set<SourceUnit const*> _skipList) const
`skipList` could more accurately be called `visitedList`

2017-07-24 11:30 UTC, axic commented
@chriseth can you review again? Should be ready (see last comment for a possible improvement).

2017-07-26 15:59 UTC, axic commented
Need to rebase after #2599.

2017-07-27 09:07 UTC, chriseth approved these changes
This has quite bad performance, but I guess we will see whether it is acutally relevant.

2017-07-27 09:07 UTC, merged