LLL: whole contract tests for the ENS Registry.
ethereum/solidity pull request #2570
Opened 2017-07-14 11:22 UTC by benjaminion

@axic - another one for you :-)  This is again in respect of Issue #2447. It's the deployed ENS Registry by @zigguratt.

The LLL source is copy/paste from https://github.com/ethereum/ens/blob/master/contracts/ENS.lll

The tests are essentially those in the same repository, https://github.com/ethereum/ens/blob/master/test/ens_test.js

2017-07-15 17:12 UTC, axic approved these changes

2017-07-15 17:14 UTC, axic requested changes
Since it uses a unreliable way of aborting (jump to 0x2) it would be required to add tests which abort. Are there any possible cases?

2017-07-15 19:48 UTC, benjaminion commented
> Since it uses a unreliable way of aborting (jump to 0x2) it would be required to add tests which abort. Are there any possible cases?

The four tests with suffix "_fail" all trigger the jump to 0x02 in order to abort, but I don't know how to test for that explicitly. The function return is just empty: `encodeArgs()` and I can't find another way to access error data. That's why in each case I am checking that nothing actually changed in storage to confirm indirectly that it terminated via the abort.

If you've got any advice how to do it I'll gladly check explicitly for the invalid jump termination as well.

2017-07-16 21:36 UTC, axic commented on test/contracts/LLL_ENS.cpp
> +	BOOST_REQUIRE(callContractFunction("setOwner(bytes32,address)", 0x00, ACCOUNT(1)) == SILENT);
Please use explicit `encodeArgs()` instead of `SILENT` in the entire file. It is more readable to someone familiar with the tests.

2017-07-16 21:38 UTC, axic commented
There's no proper way to distinguish failure from other conditions (such as out of gas), but the best chance right now is to see if the gas usage equals the supplied gas. This should be reliable once the supplied gas exceeds what it should consume (though this can change with hard forks).

2017-07-17 07:27 UTC, benjaminion commented on test/contracts/LLL_ENS.cpp
> +	BOOST_REQUIRE(callContractFunction("setOwner(bytes32,address)", 0x00, ACCOUNT(1)) == SILENT);
OK, done.

2017-07-18 09:27 UTC, axic commented
Please add one more test which call the fallback (or any other non existent signature) to check for that case.

2017-07-18 10:23 UTC, benjaminion commented
> Please add one more test which call the fallback (or any other non existent signature) to check for that case.

Is done. There's nothing really to test for except silent exit, unless we have a way to check for abort due to jump to invalid location.

2017-07-18 10:30 UTC, axic approved these changes

2017-07-18 10:33 UTC, axic commented
Thanks, there are some improvements in plan for supporting error conditions in the RPC, that would enable us testing for them in the end-to-end tests.

2017-07-18 10:39 UTC, merged