Check for payable when comparing function types
ethereum/solidity pull request #2724
Opened 2017-08-09 22:11 UTC by axic

2017-08-10 08:41 UTC, axic commented
This oversight is not causing any issues yet, because it is checked in TypeChecker for use supplied functions.

2017-08-10 13:29 UTC, chriseth requested changes
Hm, there might have been a reason for that or it was just oversight. Please also add `_payable` to the type identifier. The idea is `x !=y <=> x.identifier() != y.identifier()`

2017-08-10 16:22 UTC, axic commented
@chriseth done

2017-08-11 08:56 UTC, chriseth approved these changes

2017-08-11 08:56 UTC, merged