No nonsense explanation of compiler options
ethereum/solidity pull request #3381
Opened 2018-01-05 15:13 UTC by fulldecent

2018-01-10 12:57 UTC, chriseth commented on docs/installing-solidity.rst
> +`Using the compiler <http://solidity.readthedocs.io/en/develop/using-the-compiler.html>`
Please use proper RST links for relative references.

2018-01-10 12:57 UTC, chriseth commented on docs/installing-solidity.rst
> +install `solcjs` from `npm` then you're on your own.
There is some documentation at gitub.com/ethereum/solc-js, though.

2018-01-10 12:58 UTC, chriseth commented on docs/installing-solidity.rst
> +`solc` by using Emscripten. `solc-js` can be used in projects directly (such as Remix).
Perhaps more specifically: in javascript projects

2018-01-10 12:58 UTC, chriseth requested changes
Thanks a lot! Just some tiny changes and this can go in!

2018-01-11 01:44 UTC, fulldecent commented
@chriseth, you got it

2018-01-11 15:44 UTC, merged