Correct FAQ answer re: decompiler
ethereum/solidity pull request #3424
Opened 2018-01-23 14:54 UTC by wbt

From the perspective of what someone asking this question might want to know in an answer.

2018-01-23 15:51 UTC, chriseth requested changes
Thanks for your pull request!

We can mention porosity under the "decompiler" section, but I would actually tone it down a little. What it produces is not valid Solidity (unless it can do more than what is stated in the readme).

Furthermore, I don't think it is relevant who created the project.

2018-01-26 18:16 UTC, wbt commented
@chriseth How's this version?

2018-01-26 18:21 UTC, chriseth commented
Wonderuful, thanks a lot!

2018-01-26 18:21 UTC, chriseth approved these changes

2018-01-26 18:22 UTC, merged