Abstract Contracts: Add note about function type
ethereum/solidity pull request #3427
Opened 2018-01-23 17:54 UTC by duaraghav8

Related issue #3423 
cc @chriseth

2018-01-23 18:06 UTC, chriseth requested changes
Wonderful, thanks a lot! The only thing I would like to request is to change `abstract function` to `function without implementation` since this is how the term is used above this paragraph.

2018-01-24 11:04 UTC, chriseth commented
There seems to be an error in the link:

```
/home/travis/build/ethereum/solidity/docs/contracts.rst:1056: WARNING: undefined label: function-types (if the link has no caption the label must precede a section header)
```

2018-02-10 08:44 UTC, duaraghav8 commented
So I researched on this a bit and realised that in syntax
```
:ref:`Function type <function-types>`
```
`function-types` must be a label declared above the Function types section. However, I don't see any other sections being labelled for other :ref: statements.
http://www.sphinx-doc.org/en/stable/markup/inline.html#role-ref

What is the convention in solidity docs for cross-document linking?

2018-02-21 17:04 UTC, chriseth approved these changes

2018-02-21 17:04 UTC, merged