[WIP] Circleci updates / changes
ethereum/solidity pull request #3490
Opened 2018-02-12 21:32 UTC by axic

2018-02-12 21:35 UTC, chriseth commented
Hm, build times are fast enough for us I think. What we are missing is a recent eth binary that does not depend on libmicrohttpd anymore so we can run the end to end tests.

2018-02-20 21:07 UTC, axic commented
@chfast this was your old branch on the repo. Can you please have a look to see if any of these changes still make sense?

2018-02-20 22:35 UTC, chfast approved these changes

2018-02-20 22:35 UTC, chfast commented on cmake/EthCompilerSettings.cmake
> +if(SANITIZE)
This is a clean up if you don't have the sanitizer-blacklist.txt file.

2018-02-20 22:35 UTC, chfast commented on scripts/install_deps.sh
> +                case $VERSION_ID in
This is a way of doing the same if you don't have `lsb_release` tool (common in docker images).

2018-02-22 22:08 UTC, chriseth requested changes
This has to be rebased, the diff is really weird.

2018-02-27 13:36 UTC, axic commented
Pulled out the lsb change (#3612). The two remaining useful changes from here are:
- sanitizer change
- using ninja in cireclci

@chfast @chriseth any of these are worth merging?

2018-02-27 13:42 UTC, chfast commented
I don't think so. The sanitizer changes are in https://github.com/ethereum/cable, so you may consider integrating this when stable enough.

Ninja speeds up builds, so you can enabled it in CIs. But you don't need this PR.

2018-02-27 13:43 UTC, closed without merging

2018-02-27 15:15 UTC, chriseth commented
I think our build is already fast enough on circle. We need to speed up the testing :)

2018-02-27 15:18 UTC, chfast commented
I'm not pushing Ninja.
BTW, Ninja also has higher requirements for correct describe dependencies, so you might find some issues in CMake scripts.