stop allow_guessing for command line option parser
ethereum/solidity pull request #3607
Opened 2018-02-27 04:34 UTC by izgzhen

this fixes https://github.com/ethereum/solidity/issues/2148

2018-02-27 09:40 UTC, chriseth commented
Thanks for the pull request! Could you add a short line to `Changelog.txt` and perhaps also a test to `test/cmdlineTests.sh`?

2018-02-27 10:59 UTC, chriseth requested changes
Please add changelog entry and tests.

2018-02-27 12:01 UTC, izgzhen commented
@chriseth thanks, will take care of it soon :)

2018-02-28 01:31 UTC, izgzhen commented
updated

2018-02-28 16:41 UTC, chriseth approved these changes

2018-02-28 16:41 UTC, chriseth commented
Thanks a lot!

2018-02-28 16:42 UTC, merged

2018-02-28 22:01 UTC, axic commented on test/cmdlineTests.sh
> +	exit 1
Should adjust indentation here.

2018-03-01 01:24 UTC, izgzhen commented on test/cmdlineTests.sh
> +	exit 1
oh, sorry