Update Tips and Tricks on structs initialization.
ethereum/solidity pull request #3626
Opened 2018-03-01 11:58 UTC by lastperson

It turns out that in such case:
```
contract Combine {
    struct Tight {
        bool a;
        bool b;
    }
    Tight t;
    function setTight() public {
        t = Tight(true, true);
    }
    function setTightOptimized() public {
        t.a = true;
        t.b = true;
    }
}
```

`setTight()` will consume ~25000 gas, while `setTightOptimized()` will consume ~20000 gas. It is just the way optimizer works right now.

2018-03-01 13:14 UTC, chriseth requested changes

2018-03-01 13:14 UTC, chriseth commented on docs/miscellaneous.rst
> +    If the storage struct has tightly packed properties, initialize it with separate assignments: ``x.a = 1; x.b = 2;``. In this way it will be easier for optimizer to update storage in one go, thus
Small typo: easier for _the_ optimizer to update

2018-03-01 15:53 UTC, chriseth approved these changes

2018-03-01 15:54 UTC, merged

2018-03-02 16:20 UTC, axic commented on docs/miscellaneous.rst
> +    If the storage struct has tightly packed properties, initialize it with separate assignments: ``x.a = 1; x.b = 2;``. In this way it will be easier for the optimizer to update storage in one go, t
Good find!