Updated typo in index.rst
ethereum/solidity pull request #3714
Opened 2018-03-13 01:30 UTC by yosyp

Fixed small typo, "also" should be "all".

2018-03-13 08:43 UTC, chriseth commented
This is not a typo. The `also` was meant to state that since smart contracts are a special case of software, any guidelines for writing software "also" applies to smart contracts.

How did you interpret it?

2018-03-13 12:31 UTC, yosyp commented
I interpreted the `also` as a mistake. Here are a few suggestions that me that sentence pair less awkward to read:
- _... Therefore, even smart contract should be ..._
- _... This software is no exception, and all smart contracts should be created following ..._
- _All software is written by humans, and may contain bugs. Since smart contracts are a special case of software, any guidelines for writing software also apply to smart contracts, and should be created following well-known best-practices in software development._

2018-03-13 13:29 UTC, chriseth commented
My personal preference would be the last version. Thanks a lot for looking into this! Unfortunately, we do not have a native English speaker on our team :)

2018-03-13 13:41 UTC, yosyp commented
Not a problem. Will be glad to read over and correct documentation as I learn more about the project.

Should I make a new PR or can the approving reviewer modify my commit?

2018-03-13 14:57 UTC, chriseth commented
If you force-push to the same branch, the pull request will just update, so please do not open a new one.

2018-03-27 14:11 UTC, axic approved these changes

2018-03-27 14:11 UTC, axic commented
Force pushed myself.

@chriseth I took the last suggested text, merge if you approve

2018-03-28 09:07 UTC, chriseth requested changes
This looks like something went wrong in the rebase process...

2018-03-28 09:07 UTC, chriseth commented on docs/index.rst
> +    Since software is written by humans, and may contain bugs.
`and may` does not sound right to me.

2018-03-28 09:07 UTC, chriseth commented on docs/index.rst
> +    Since smart contracts are a special case of software,
The previous sentence already started with `since`.

2018-03-28 09:07 UTC, chriseth commented on docs/index.rst
> +    and should be created following well-known best-practices in software development.
`and should be created` sounds like the guidelines should be created in the way stated.

2018-03-28 09:12 UTC, axic commented
> This looks like something went wrong in the rebase process...

As mentioned "I took the suggested text", which was the 3rd from the list above.

2018-03-28 09:18 UTC, chriseth commented
Oh I'm sorry, then I did not read the list properly. While I think the current paragraph should be expanded, I would not consider this PR an improvement at this stage.

2018-04-18 23:18 UTC, axic commented on docs/index.rst
> +    Since software is written by humans, and may contain bugs.
Argh, it was a bad copy paste job, it should read `All software` from the original comment. Not that it is much better :)

2018-05-15 14:41 UTC, chriseth commented
The first sentence is still weird and as there is no progress on this, I'm closing this PR.

2018-05-15 14:41 UTC, closed without merging