Add override keyword for ensuring function overrides
ethereum/solidity pull request #3737
Opened 2018-03-14 21:11 UTC by federicobond

2018-03-14 21:13 UTC, federicobond commented on libsolidity/analysis/SyntaxChecker.cpp
> +		const_cast<FunctionDefinition &>(_function).optionallyMarkAsOverride();
This is super ugly, but I couldn't come up with a better approach. We could clean this up for 0.5.0.

2018-03-15 15:32 UTC, chriseth requested changes
The use of `superFunction` is not 100% correct. superFunction points to the next higher up function of the same name in the list of linearized base contracts. See the following example:
```
contract A {
    function f() {}
}
contract B {
    function f() {}
}
contract C is A, B {
}
```

When we compile `C`, then `B.f`'s `superFunction` is set, while it is not set when we compile `B`.

It somehow already sounds like this is the correct behaviour, because we do not want C to be compilable, but the error would be different.

Could you please experiment a little with multiple inheritance and write tests for that?

The combinations I can currently think of are:

 - the example above
 - the example above plus implementation of `f` in C with `override`
 - the same without `override`.
 - the example above plus that A and B inherit from the same base class (empty)
 - the same but with `f` added to that common base class
 - the same but with `f` also added to `C`

2018-03-15 15:32 UTC, chriseth commented on Changelog.md
> + * Support and recommend using ``emit EventName();`` to call events explicitly.
This looks like a rebase problem.

2018-03-15 15:32 UTC, chriseth commented on libsolidity/analysis/StaticAnalyzer.cpp
> +				"Function signature does not override any function defined in parent contracts."
I think we call them "base contracts".

2018-03-15 15:32 UTC, chriseth commented on libsolidity/analysis/StaticAnalyzer.cpp
> +				"Function overrides a parent function but is missing an override specifier."
Perhaps just "overrides a function"?

2018-03-15 15:32 UTC, chriseth commented on libsolidity/analysis/StaticAnalyzer.cpp
> +				"Function overrides a parent function but is missing an override specifier."
Can we find out the name of the contract the overridden function is defined in? Perhaps we should even specify a secondary source location.

2018-03-15 15:32 UTC, chriseth commented on libsolidity/ast/AST.cpp
> +		[](ASTPointer<ModifierInvocation> modifier) {
Please use `const&` here

2018-06-19 23:43 UTC, axic commented
Needs to be rebased.

2018-06-23 12:48 UTC, federicobond commented
Rebased but I am not likely to continue to work on this soon. I welcome anyone to take it

2018-07-09 21:55 UTC, chriseth commented
Do we want to take that in scope for 0.5.0 or not?

2018-07-11 17:17 UTC, ekpyron commented
I think enforcing the use of ``override`` is a good idea and vote for it.

2018-07-11 18:33 UTC, federicobond commented
How would we solve the problem described by @chriseth above? Should we disallow compilation of C?

2018-07-11 21:45 UTC, chriseth commented
First suggestion: In that situation it only compiles if the most derived contract contains (or inherits) a function called `f` with a modifier `override(A,B)`. So the general rule would be:

A function that overrides a function of the same name and parameter types from a base contract `BaseContract` needs to either have a `override` or `override(BaseContract)` modifier. If a contract `C` inherits from multiple contracts which contain functions of the same name and parameter types, then `C` also has to define such a function with the modifier `override(A,B, ..., )`.

There is a special case where `C` inherits from both `A` and `B`; and `A` also inherits from `B` - not sure if `override(A)` would be sufficient is that case, but I think it is better to be explicit and require both `A` and `B`.

2018-12-05 16:16 UTC, chriseth commented
Closing as there are conflicts and this can be easily recreated.

2018-12-05 16:16 UTC, closed without merging