Add syntax testing guide to docs
ethereum/solidity pull request #3772
Opened 2018-03-21 18:42 UTC by bit-shift

Closes #3762.

Adds syntax testing guide to "How to contribute" section.

2018-03-26 14:58 UTC, axic commented on docs/contributing.rst
> +    // ----
Perhaps should explain that this separator is mandatory?

2018-03-26 15:00 UTC, axic requested changes

2018-03-26 15:00 UTC, axic commented on docs/contributing.rst
> +    // ----
Perhaps should explain that this separator is mandatory?

2018-03-27 10:01 UTC, bit-shift commented
@axic I've added some words about the test structure in general and the separator in particular. Also extended the description of the automatic update process ``isoltest`` provides.

2018-03-27 13:28 UTC, axic approved these changes

2018-03-27 13:28 UTC, merged