Short string representation of TypePointer in AST JSON
ethereum/solidity pull request #3773
Opened 2018-03-21 19:56 UTC by bit-shift

Fixes #3567

2018-03-21 20:01 UTC, axic requested changes
Please adjusts (or add) tests for this.

2018-03-23 11:20 UTC, erak commented
@axic Added missing tests.

2018-03-27 13:11 UTC, chriseth submitted a review, later dismissed

2018-03-27 13:11 UTC, chriseth commented
Looks good to me!

2018-04-05 10:26 UTC, axic requested changes
Please check the resulting `typeString` (and `typeIdentifier`). It is a good idea to take all examples from the initial issue.

2018-04-05 10:26 UTC, bit-shift commented
- [ ] Add tests for ``typeString``
- [ ] Add tests for complex use case (see issue)

2018-04-06 13:26 UTC, bit-shift commented
@axic I've realised that the tests used the legacy AST output instead of the new compact one. That's the reason why checks for ``typeName`` and ``typeString`` were missing. I've changed that...

Not sure about ``t_array$_t_array$_t_uint256_$dyn_storage_$dyn_storage_ptr`` for ``uint[][] memory rows;``. It still looks wrong, but I wasn't sure how to fix the ``richIdentifier`` for ``ArrayType``.

2018-04-06 13:43 UTC, chriseth commented
The rich identifier is fine, it is only important that it is really unique. They are not really exposed to the user as much as the other stuff is.

2018-04-09 10:29 UTC, axic submitted a review, later dismissed
Please have at least two cases, one which triggers `_short = false` and one which triggers `_short = true`.

2018-04-09 10:34 UTC, axic commented
Basically just extend all the other test cases with `typeIdentifier` expectation if they define a type.

2018-04-09 11:45 UTC, bit-shift commented
@axic The JSON AST tests are using the legacy JSON output. That's why you won't find ``typeIdentifier`` but rather ``typeName`` and ``type``. Actually those do not cover my changes since they only apply when using ``solc --ast-compact-json``. I think changing the tests such that they use the new output could be done while deprecating the legacy output for 0.5.0.

I think I'd rather add some tests that cover non-shortened type pointer as you suggested.

2018-04-09 11:49 UTC, axic commented
> The JSON AST tests are using the legacy JSON output. 

In that case I think we should introduce two sub suites to group the legacy and the "compact" tests.

2018-04-09 11:50 UTC, bit-shift commented
Great idea, will do that!

2018-04-09 12:37 UTC, axic commented
I actually meant that there can be multiple sub-levels of `BOOST_AUTO_TEST_SUITE(<name>)` within a single suite.

Also the case `documentation` contains both legacy and non-legacy tests, probably needs to be split into two.

2018-04-09 14:39 UTC, bit-shift commented
@axic Ok, my idea was to split them into 2 files right away, in order to not end up with a very large one at some point. But if you prefer a single file with multiple sub-suites, I'll put it back. I don't have a stong opinion on that.

I've pulled out the legacy part of the ``documentation`` test. Did I miss something?

2018-04-09 15:10 UTC, axic commented
I don't have any preference, but if it is a split file I'd name it `ASTLegacyJSON`.

2018-04-09 15:57 UTC, bit-shift commented
@axic I've renamed the legacy file / suite and added two tests that cover long ``typeDescriptions`` for binary operations and identifiers.

2018-04-11 10:11 UTC, chriseth commented
Please add a changelog entry.

2018-04-12 09:18 UTC, ekpyron submitted a review, later dismissed
Looks fine to me now!

2018-04-12 09:20 UTC, ekpyron commented
Rebased.

2018-04-12 09:24 UTC, chriseth commented on Changelog.md
> + * JSON AST: Use short string representation for TypePointers.
This should be a bugfix, and perhaps also phrased differently for the changelog: Remove storage qualifier for type name strings.

2018-04-12 19:06 UTC, chriseth commented
Sorry, please rebase.

2018-04-13 08:56 UTC, chriseth approved these changes

2018-04-13 08:56 UTC, merged