Fixed point pre-changes Update default decimal places to 18 Update documentation
ethereum/solidity pull request #3801
Opened 2018-03-30 20:05 UTC by meowingtwurtle

2018-03-30 20:14 UTC, axic commented on docs/types.rst
> +Conversions:
Oh, this change needs to stay in the old PR.

2018-03-30 20:14 UTC, axic commented on docs/types.rst
> -.. warning::
This needs to stay here.

2018-03-30 20:14 UTC, axic requested changes
Please also pull in the test changes or the 19 -> 18 move.

2018-03-30 20:20 UTC, meowingtwurtle commented
The tests won't pass without the rest of the fixed point code, regardless of decimal places.

2018-03-30 20:38 UTC, axic commented
> The tests won't pass without the rest of the fixed point code, regardless of decimal places.

There are tests which expect a certain error message, now they read `fixed128x19`, but after the change here they must be adjusted, just as you did in the other PR.

2018-03-30 20:45 UTC, meowingtwurtle commented
OH, sorry. Will fix those.

2018-03-30 22:30 UTC, axic commented on cmake-build-debug/CMakeFiles/3.10.2/CMakeCCompiler.cmake
> +set(CMAKE_C_COMPILER "/usr/bin/cc")
I think you've added an extra directory by mistake. I'll just force push myself.

2018-03-30 22:32 UTC, axic approved these changes

2018-03-30 23:28 UTC, axic commented
Test failure is due to #3802.

2018-04-03 09:10 UTC, chriseth approved these changes

2018-04-03 09:10 UTC, merged