Removed documentation reference to var for tuple variable assignment
ethereum/solidity pull request #3805
Opened 2018-04-02 05:02 UTC by kevinflo

This is a fix for the documentation as mentioned in https://github.com/ethereum/solidity/issues/3669
The problem was that the documentation still referenced the now-depricated var way of assigning variables from tuples

This was brought to light in discussion here https://github.com/ethereum/solidity/issues/3301#issuecomment-372589186

My first contribution attempt here. Let me know if there's anything I should change.

2018-04-03 08:45 UTC, chriseth requested changes
Perfect apart from the small wording change.

2018-04-03 08:45 UTC, chriseth commented on docs/control-structures.rst
> +            // These pre-existing variables can then be assigned to the tuple values
I think this should either say `These pre-existing variables can then be assigned from the tuple values` or `Tuple values can be assigned to these pre-existing variables`.

2018-04-03 08:46 UTC, chriseth commented
Ah, I just checked and there are some more occurrences of `var (` in the documentation. Could you please take another look?

2018-04-03 12:44 UTC, axic commented
I actually looked at this yesterday and started to change some parts of the documentation with regards to `var`.

2018-04-05 14:18 UTC, chriseth approved these changes

2018-04-05 14:19 UTC, chriseth commented
Merging, still better than nothing. But it does not close the issue.

2018-04-05 14:19 UTC, merged