Use xterm instead of dumb terminal
ethereum/solidity pull request #4095
Opened 2018-05-09 02:51 UTC by arun1595

Fixes #4045 

Makes use of `xterm` terminal to get color output in CI environment.

2018-05-09 08:55 UTC, erak requested changes
Could you also please add this to the other steps? Currently it is only set for ``test_x86_linux`` and ``test_x86_mac``.

2018-05-09 13:42 UTC, arun1595 commented
@bit-shift Sure! Will update the PR in a while.

2018-05-10 12:44 UTC, arun1595 commented
@bit-shift I've updated the PR to use `xterm` terminal for all jobs. PTAL :smile:

2018-05-11 11:00 UTC, chriseth approved these changes

2018-05-11 11:00 UTC, merged