Add a new keyword, "calldata", to allow explicitly specify data location in external function's argument list
ethereum/solidity pull request #4176
Opened 2018-05-23 04:37 UTC by sifmelcara

As mentioned in #4173 
Maybe this should be merged into `0.5.0` branch?

2018-05-23 13:39 UTC, axic commented on test/libsolidity/SolidityNameAndTypeResolution.cpp
> +	CHECK_ERROR(text, TypeError, "Data location must be specified as either \"memory\" or \"storage\".");
These could be pulled out as non-breaking changes.

2018-05-23 13:41 UTC, axic commented on libsolidity/parsing/Parser.cpp
> +						solAssert(false, "Unknown storage location.");
I think this should read `Unknown data location.`

2018-05-23 13:42 UTC, axic commented
The test cases (apart from `calldata`) cold also be merged straight away.

2018-05-23 21:38 UTC, sifmelcara commented
It seems `050` have just been merged into `develop`. Do I still need to open another PR for the non-backward compatible change?

2018-05-27 15:26 UTC, axic requested changes
Since you introduce a new token, can you please include that in the grammar?

2018-05-27 15:26 UTC, axic commented
I think we should be fine not splitting it. Can you please rebase it?

2018-05-27 15:43 UTC, sifmelcara commented
Ok. `calldata` added to `docs/grammar.txt` (are there other files I should change?). Rebased against `develop`.

2018-05-27 18:49 UTC, axic commented
Sorry, it also needs a changelog entry :)

2018-05-28 08:32 UTC, sifmelcara commented
Hmm.. Looks like the tests run on circleci have some random failure? I only changed Changelog.md, which should not make it became failed.

2018-05-28 20:14 UTC, chriseth commented on test/libsolidity/syntaxTests/dataLocations/function_argument_location_specifier_test.sol
> +// TypeError: (101-106): Location has to be memory for publicly visible functions (remove the "storage" or "calldata" keyword).
Why is there only one error? There should be two, one for `fc`, one for `fd`.

2018-05-28 20:15 UTC, chriseth commented on test/libsolidity/syntaxTests/dataLocations/function_argument_location_specifier_test.sol
> +// TypeError: (101-106): Location has to be memory for publicly visible functions (remove the "storage" or "calldata" keyword).
Ah it is a fatal one! In that case, please change this test case to have exactly one function.

2018-05-28 20:15 UTC, chriseth commented on test/libsolidity/syntaxTests/dataLocations/function_argument_location_specifier_test_external.sol
> +// TypeError: (65-70): Location has to be calldata for external functions (remove the "memory" or "storage" keyword).
Same here.

2018-05-28 20:17 UTC, chriseth requested changes
Please split negative test cases such that they are as small as possible to produce the error.

2018-05-28 20:53 UTC, chriseth commented
Please rebase since #4173  has been merged.

2018-05-28 21:32 UTC, sifmelcara commented
Those are some good advice :)
Tests updated and rebased.

2018-05-28 21:45 UTC, chriseth submitted a review, later dismissed

2018-05-28 21:46 UTC, chriseth commented
@axic fine to merge?

2018-05-30 05:32 UTC, axic requested changes
Sorry, haven't noticed, but please add a test in `SolidityTypes`:`type_identifiers`. There is an explicit test for memory and in implicit one for storage. Please add an explicit one for storage and calldata.

2018-05-30 11:25 UTC, sifmelcara commented
Hmm... No idea why the test timed out.

2018-05-30 12:40 UTC, chriseth approved these changes

2018-05-30 12:42 UTC, chriseth approved these changes

2018-05-30 12:42 UTC, merged