Disallow raw callcode (was deprecated in 0.4.12)
ethereum/solidity pull request #4313
Opened 2018-06-18 15:07 UTC by axic

2018-06-18 16:35 UTC, axic commented
@chriseth since this practically removes the possibility of using callcode, should we also remove it from `CallKind` on the `ExpressionCompiler`?

2018-06-19 17:24 UTC, chriseth commented on Changelog.md
> + * General: Disallow raw ``callcode`` (was already deprecated in 0.4.12).
Please clarify that that this is just about the address member and not the assembly opcode.

2018-06-19 17:26 UTC, chriseth requested changes
Fine apart from the changelog entry. Yes, we can remove the kind enum values, but please as part of a separate PR.

2018-06-19 17:31 UTC, axic commented
Updated.

2018-06-19 17:38 UTC, chriseth approved these changes

2018-06-19 18:00 UTC, merged