Replace IF..ELSE IF with SWITCH..CASE
ethereum/solidity pull request #4363
Opened 2018-06-27 16:01 UTC by rnaby

I think `SWITCH..CASE..DEFAULT` is much simpler than `IF..ELSE IF..ELSE`. :slightly_smiling_face:

2018-06-29 10:23 UTC, erak requested changes
Please also change the commit message to something more meaningful.

2018-06-29 10:23 UTC, erak commented on libevmasm/KnownState.cpp
> +				{
These are not needed here and can be removed again. In general, we're striving towards a coding style that supports displaying as many lines as possible on one screen.

2018-06-29 10:23 UTC, erak commented on libevmasm/KnownState.cpp
> +
The above comment also applies to the new lines that you've added.

2018-06-29 10:23 UTC, chriseth submitted a review, later dismissed

2018-07-02 09:38 UTC, rnaby commented
Some git issue happened when squashing. Will submit a clean PR.

2018-07-02 09:38 UTC, closed without merging