Disallow calling base constructors without arguments.
ethereum/solidity pull request #4378
Opened 2018-06-28 22:07 UTC by chriseth

2018-07-02 12:55 UTC, ekpyron submitted a review, later dismissed

2018-07-06 19:03 UTC, erak requested changes

2018-07-06 19:03 UTC, bit-shift commented on test/libsolidity/syntaxTests/inheritance/modfiers_in_constructor_contetxt.sol
> +// This generated an invalid warning on m1 in some compiler versions.
There's a typo in the filename. Also indentation seems to be inconsistent with our existing tests.

2018-07-10 20:04 UTC, chriseth commented
Fixed and rebased.

2018-07-18 13:20 UTC, erak submitted a review, later dismissed

2018-08-01 11:29 UTC, axic commented
Rebased.

2018-08-01 11:32 UTC, axic approved these changes

2018-08-01 12:18 UTC, merged