Prototype for abi.decode
ethereum/solidity pull request #4390
Opened 2018-06-30 16:13 UTC by chriseth

There might be an argument for rather using `abi.decode(data, (type1, type2))` instead of `abi.decode(data, type1, type2)`

2018-06-30 19:52 UTC, PhABC commented
Two questions ; 

Would the format `abi.decode(data, (type1, type2, ...))` allow for predefined decoding patterns? 

e.g. 

```javascript
struct TransferArgs{
  address from;
  address to;
  uint256 amount;
}
```
and then `abi.decode(data, TransferArgs)` ?

Also, I assume it will be possible, but just to be sure, will it be possible to decode the first `n` types and then pack the rest is a `bytes` array? Something like `abi.decode(data, {address, bytes})` instead of `abi.decode(data, {address, address, uint256})`.

2018-07-10 14:18 UTC, chriseth commented
The community seems to prefer `abi.decode(data, (type1, type2))`.

2018-08-09 20:28 UTC, ekpyron commented
Actually, this is a grammar change and should be documented in ``docs/grammar.txt``, shouldn't it?

2018-08-09 20:58 UTC, chriseth commented
@ekpyron in which way? I didn't touch the parser. `Expression = Identifier | ... | ElementaryTypeNameExpression`

2018-08-09 23:53 UTC, ekpyron commented
Ok, I hadn't noticed that a ``PrimaryExpression`` is an ``Expression`` and that a ``PrimaryExpression`` can be an ``ElementaryTypeNameExpression``. However, ``abi.decode`` can still be used with arrays, etc., and with ABIEncoderV2 even with struct's as well, can't it? That still won't fit the grammar - those aren't ``ElementaryTypeName``s, but ``TypeName``s (maybe the grammar been wrong in this regard for a while).

I wouldn't have expected to find the ``ElementaryTypeNameExpression`` as a kind of ``Expression`` - but indeed it seems one can do things like just ``int;`` and ``int[100];`` in solidity, even though they don't have any effect - I didn't know that so far :-).

2018-08-14 15:21 UTC, leonardoalt commented on libsolidity/codegen/ExpressionCompiler.cpp
> +					*firstArgType == ArrayType(DataLocation::CallData) ||
This condition is the same as the `if` condition

2018-08-14 15:39 UTC, leonardoalt commented on test/libsolidity/SolidityEndToEndTest.cpp
> +			function f(bytes data) public view returns (uint) {
Could be `pure`

2018-08-14 15:41 UTC, leonardoalt requested changes
Some of the tested functions can be `pure`

2018-08-14 20:08 UTC, chriseth commented on libsolidity/codegen/ExpressionCompiler.cpp
> +					*firstArgType == ArrayType(DataLocation::CallData) ||
Funny - what did I mean there? Replacing the condition by the assert...

2018-08-15 08:26 UTC, leonardoalt submitted a review, later dismissed

2018-08-15 08:49 UTC, chriseth commented
Rebased.

2018-08-15 09:24 UTC, ekpyron approved these changes

2018-08-15 10:31 UTC, merged