[BREAKING] Enforce STATICCALL for view and pure
ethereum/solidity pull request #4428
Opened 2018-07-04 14:30 UTC by leonardoalt

2018-07-04 15:08 UTC, erak submitted a review, later dismissed

2018-07-04 15:08 UTC, bit-shift commented on libsolidity/codegen/ExpressionCompiler.cpp
>  	bool useStaticCall =
Could this now be one line?

2018-07-05 08:38 UTC, leonardoalt commented on libsolidity/codegen/ExpressionCompiler.cpp
>  	bool useStaticCall =
Yep :)

2018-07-06 10:35 UTC, ekpyron reviewed
Changelog entry :D.

2018-07-06 10:37 UTC, ekpyron commented
And I wonder whether there should be more test cases for this...

2018-07-06 10:44 UTC, bit-shift commented
@ekpyron I also thought about that. Would you recommend to test that ``payable`` and ``nonpayable`` do not use ``STATICCALL``, also in combination with different EVM versions?

2018-07-06 10:52 UTC, ekpyron commented
@bit-shift I thought about adding more end to end tests that expect reverts on state changes when staticcall is used... but there's one test for that, maybe that suffices...
The other way round is probably rather well tested - every non-reverting function call in the end-to-end tests that changes state is a test for that.
So I'm not sure - it's probably fine as it is already...

2018-07-06 11:16 UTC, ekpyron commented
@bit-shift Maybe you're right - I just quickly looked through the end-to-end tests and it's fewer storage-writing external calls in there than I'd have expected that test this (maybe I missed a lot of them, though)...

So maybe it does make sense to add an explicit tests to ensure that payable and non-payable calls don't staticcall and don't revert when writing to the storage, just to be sure.

2018-07-06 12:42 UTC, leonardoalt commented
Added a test for that

2018-07-06 12:48 UTC, ekpyron commented on test/libsolidity/SolidityEndToEndTest.cpp
> +BOOST_AUTO_TEST_CASE(write_storage)
``write_storage_external`` maybe?

2018-07-06 12:50 UTC, ekpyron submitted a review, later dismissed
Apart from maybe changing the name of the new test, it looks fine to me.

2018-07-06 12:52 UTC, leonardoalt commented on test/libsolidity/SolidityEndToEndTest.cpp
> +BOOST_AUTO_TEST_CASE(write_storage)
Yea, better

2018-07-06 12:54 UTC, ekpyron requested changes
I just noticed: ``docs/contracts.rst`` has a section regarding ``View Functions`` that refers to STATICCALL and needs to be updated.

2018-07-06 14:04 UTC, leonardoalt commented
Thanks, missed that.
Updated now.

2018-07-06 14:14 UTC, ekpyron submitted a review, later dismissed

2018-07-09 09:41 UTC, erak submitted a review, later dismissed
Besides the tiny comment about formatting the Changelog, it looks good to me.

2018-07-09 09:41 UTC, bit-shift commented on Changelog.md
> + * Code Generator: Use STATICCALL for pure and view functions. This was already the case in the experimental 0.5.0 mode.
Should this be preformatted? "Use STATICCALL for ``pure`` and ``view`` functions."

2018-07-09 12:11 UTC, ekpyron submitted a review, later dismissed

2018-07-11 12:46 UTC, leonardoalt commented
Improved doc, rebased and squashed

2018-07-12 11:13 UTC, chriseth approved these changes

2018-07-12 11:14 UTC, merged

2018-07-12 13:27 UTC, axic commented
This reminds me: do we have a test case which tries to do state modification through inline assembly (and is not detected), but it doesn't actually changes the state due to staticcall?

I guess we do detect all these possibilities in inline assembly.

2018-07-12 17:21 UTC, chriseth commented
We have tests to detect state modification through inline assembly and thus change the state mutability of the function, so I think a semantics test would be redundant, but we can still add it of course.