Properly show constructor/fallback in FunctionDefinition.fullyQualfiedName
ethereum/solidity pull request #4557
Opened 2018-07-24 00:06 UTC by axic

This function doesn't seem to be used however.

It is only used on `ContractDefinition`, but in the AST hierarchy only `FunctionDefinition` overrides this function.

2018-07-28 00:29 UTC, axic commented on libsolidity/ast/AST.cpp
>  	return sourceUnitName() + ":" + contract->name() + "." + fname;
Also could just use `contract->fullyQualifiedName() + "." + fname` here.

2018-07-30 14:56 UTC, chriseth commented on libsolidity/ast/AST.cpp
> +	auto fname;
Please use `string` here.

2018-07-30 14:59 UTC, chriseth commented
Oh wow, why don't we get an override error from the compiler? The function is not even virtual.

2018-07-30 15:00 UTC, chriseth commented
Note that FunctionDefinition inherits from Declaration.

2018-07-30 15:02 UTC, axic commented on libsolidity/ast/AST.cpp
>  	return sourceUnitName() + ":" + contract->name() + "." + fname;
@chriseth how about this?

2018-08-02 12:55 UTC, chriseth approved these changes

2018-08-02 12:56 UTC, chriseth requested changes
Please fix the inheritance hierarchy - make the super function virtual and use the `override` keyword.

2018-08-02 12:56 UTC, chriseth commented
Or just remove the function.

2018-08-02 15:16 UTC, axic commented
@chriseth fixed and test seems passing, likely it is still not used.

2018-08-02 15:32 UTC, axic commented
Since it is not used and the only case where `fullyQualifiedName` is called is in the `CompilerStack` for contracts, I think the best way is to remove it from `Declaration` and only have it on `ContractDefinition`.

@chriseth what do you think?

2018-08-06 11:21 UTC, chriseth commented
Yes, please remove.

2018-08-06 12:48 UTC, axic commented
Updated.

2018-08-06 16:57 UTC, chriseth commented
Will squash and merge.

2018-08-06 16:58 UTC, chriseth approved these changes

2018-08-06 17:01 UTC, chriseth approved these changes

2018-08-06 17:02 UTC, merged