[WIP] Move SMT tests to use isoltest
ethereum/solidity pull request #4645
Opened 2018-08-01 18:13 UTC by axic

2018-08-02 08:30 UTC, leonardoalt commented
The `div` test is failing because it expected the solver to say unknown but got SAT. Is the CI using CVC4 as well?

2018-08-02 08:44 UTC, leonardoalt commented
Do you think the following is a good idea: one must have both solvers installed in order to update smt tests.
This way we could ensure the most precise result and have CI do the same.

2018-08-02 10:16 UTC, axic commented
> The div test is failing because it expected the solver to say unknown but got SAT. Is the CI using CVC4 as well?

I didn't finish this yesterday, but actually was thinking to keep those unknown ones in the C++ code for the moment.

2018-08-07 14:37 UTC, ekpyron commented
I rebased this and resolved some conflicts with the JSON AST test extraction.

2018-08-07 15:00 UTC, ekpyron submitted a review, later dismissed

2018-08-07 15:08 UTC, ekpyron commented
Interesting - ``smtCheckerTests/049_division.sol`` takes a long time for me to run (I locally disabled CVC4, since there's still compilation issues on Archlinux) and returns ``UNKNOWN``, hence yielding ``Overflow ... might happen here``, whereas on travis it returns ``SAT``, yielding ``Overflow ... happens here`` - I guess on travis CVC4 is enabled?

We should investigate this. In the long term we will probably have to add expectations that are specific to the enabled solvers similarly to EVM version specific tests in #4262.

I think I will create a ``test system overhaul`` project one of these days and structure all test related issues and improvement suggestions into clean issues and add them to that project (it's not too urgent, though, I think we won't do any of that before ``0.5.1``).

2018-08-07 15:09 UTC, ekpyron commented
The same test does seem to return ``UNKNOWN`` on MacOS as well, though.

2018-08-07 15:24 UTC, chriseth commented
In general I'm a bit uneasy about this change. The SMT component is not predictable. We might even get test failures depending on the CPU capacity we have because of timeouts etc.

2018-08-07 15:25 UTC, chriseth commented
Ok sorry, perhaps put differently: This is not about this PR, but in general, we should be careful about SMT tests.

2018-08-07 15:32 UTC, ekpyron commented
@chriseth That's true, but (as you noted) not really related to this PR. I created #4735 for tracking this, but I would say we should still find a more immediate solution for this PR.

2018-08-07 15:36 UTC, ekpyron commented on test/libsolidity/SMTChecker.cpp
> -	CHECK_WARNING(text, "Overflow");
Ok, the reason why this test didn't fail, resp. behave erratically before was that we didn't even check whether it was ``Overflow ... might happen`` or ``Overflow ... happens`` before.

2018-08-07 15:40 UTC, ekpyron commented
Maybe the easiest (though somewhat unsatisfactory) solution to this is *not* to extract this one test for now and to think of a better solution later on?

2018-10-17 17:19 UTC, chriseth commented
What is the state of this PR?

2018-10-17 17:33 UTC, leonardoalt commented
I think we can follow @ekpyron 's last suggestion and merge most of the tests (except the ones that use non-linear arithmetics).

2018-11-08 14:39 UTC, leonardoalt commented
Rebased and updated this PR to not extract division tests.

2018-11-08 15:00 UTC, ekpyron submitted a review, later dismissed
The numbering of the extracted tests is somewhat inconsistent (sometimes global prefixes, sometimes per-test suffixes), but probably doesn't matter too much and otherwise: looks fine.

2018-11-08 15:08 UTC, leonardoalt commented
Yea I'll submit another PR fixing that and organizing the files in dirs

2018-11-08 17:59 UTC, chriseth requested changes
Could you cleanup the commits, please? For me it looks like some back-and-forth in isoltest.cpp.

2018-11-08 23:51 UTC, leonardoalt commented
Updated @chriseth

2018-11-09 12:22 UTC, erak reviewed
In general this looks good.

2018-11-09 12:22 UTC, erak commented on test/libsolidity/smtCheckerTests/warn_on_struct.sol
> +pragma experimental ABIEncoderV2;
Could this be changed, such that it is independent from the ABIEncoderV2? I'd be in favor of trying to factor it out. The following contract seems to trigger the same warnings:
```
pragma experimental SMTChecker;
contract C {
    struct A { uint a; uint b; }
    function f() public pure returns (uint) {
        A memory a = A({ a: 1, b: 2 });
    }
}
```

2018-11-09 16:04 UTC, leonardoalt commented on test/libsolidity/smtCheckerTests/warn_on_struct.sol
> +pragma experimental ABIEncoderV2;
Makes sense!

2018-11-09 16:31 UTC, leonardoalt commented on test/libsolidity/smtCheckerTests/warn_on_struct.sol
> +pragma experimental ABIEncoderV2;
The CI tests actually fail with `TypeError: (116-124): This type is only supported in the new experimental ABI encoder. Use "pragma experimental ABIEncoderV2;" to enable the feature.` without that line. I guess we do need it here.

2018-11-14 14:00 UTC, bit-shift commented on test/libsolidity/smtCheckerTests/warn_on_struct.sol
> +pragma experimental ABIEncoderV2;
Does it still fail even with the changes I've proposed? For me it works without ``pragma experimental SMTChecker;`` and it should still test the same.

2018-11-14 15:18 UTC, leonardoalt commented on test/libsolidity/smtCheckerTests/warn_on_struct.sol
> +pragma experimental ABIEncoderV2;
To me it works outside the tests, but when running the tests it fails without pragma

2018-11-14 16:27 UTC, chriseth submitted a review, later dismissed

2018-11-14 18:56 UTC, erak submitted a review, later dismissed

2018-11-15 08:23 UTC, leonardoalt commented
@axic Can we merge this?

2018-11-19 16:40 UTC, ekpyron submitted a review, later dismissed

2018-11-22 13:35 UTC, leonardoalt approved these changes

2018-11-22 13:59 UTC, merged