added helper function that joins vectors of strings
ethereum/solidity pull request #4662
Opened 2018-08-02 14:58 UTC by evgeniuz

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] README / documentation was extended, if necessary
- [x] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### Description
Added helper function that joins vectors of strings and tests for it.

2018-08-02 15:00 UTC, axic commented
This looks great, thank you!

Can you also use this new helper in some places? One place using it is the "did you mean?" suggestion messages for unknown variable names.

2018-08-02 15:05 UTC, axic commented on libdevcore/CommonData.h
> +	if (!_lastSeparator.empty() && !_list.empty()) {
Should this allow empty lists as input?

If yes, should we just have a `if (_list.empty()) return string{}` as the first statement before calling `join`?

2018-08-02 15:12 UTC, chriseth requested changes
Thanks for the pull request!

Could you please update the coding style? We generally use `std::string const& _separator`, braces on a line of their own and tabs for indentation.

Also I think that the case where there is a last separator looks a little hacking. Perhaps it is best to just implement everything manually?

2018-08-02 22:03 UTC, evgeniuz commented
Updated coding style, refactored function in a less hackish way (it's actually better that way, now it can work with arrays as well, as it doesn't depend on `_list.back()` and `_list.empty()` anymore), also refactored `quotedAlternativesList` to use this new function.

2018-08-02 22:24 UTC, axic commented on libdevcore/CommonData.h
> +std::string join
I think this should be called something like `joinHumanReadablelList`. Any better suggestions?

2018-08-02 22:24 UTC, axic commented on libdevcore/CommonData.h
> +std::string join
Also likely it should go into the `StringUtils` file.

2018-08-02 22:26 UTC, evgeniuz commented on libdevcore/CommonData.h
> +std::string join
ok, will rename and move it right now.

2018-08-02 22:26 UTC, evgeniuz commented on libdevcore/CommonData.h
> +std::string join
maybe just joinHumanReadable?

2018-08-03 08:54 UTC, chriseth requested changes
Wonderful! There are only some small style changes left.

2018-08-03 08:54 UTC, chriseth commented on libdevcore/StringUtils.h
> +	std::string const& _separator =", ",
Please add a space after `=`

2018-08-03 08:54 UTC, chriseth commented on libdevcore/StringUtils.h
> +	for (;it != itEnd; ++it) {
Please put the `{` on a line of its own just as with function bodies (also above)

2018-08-03 08:54 UTC, chriseth commented on libdevcore/StringUtils.h
> +		} else {
Please omit braces if there is only a single statement.

2018-08-03 11:03 UTC, axic commented
@evgeniuz as a last step when all the changes are agreed on, can you please squash the commits down to a single one?

You could use `git rebase -i HEAD~4` to do it.

2018-08-03 13:18 UTC, axic commented
@chriseth do we have any more comments? I am not sure about the function name, but have no good suggestions.

2018-08-03 15:12 UTC, axic approved these changes

2018-08-03 15:13 UTC, merged