Fixes #4741 Referenced source is truncated too much
ethereum/solidity pull request #4801
Opened 2018-08-11 10:31 UTC by iamonuwa

### Your checklist for this pull request

Please review the [guidelines for contributing](http://solidity.readthedocs.io/en/latest/contributing.html) to this repository.

Please also note that this project is released with a [Contributor Code of Conduct](CONDUCT.md). By participating in this project you agree to abide by its terms.

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [ ] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### Description
Please explain the changes you made here.
Increase the length of the error message to accomodate more context about the error.
Thank you for your help!

2018-08-13 09:54 UTC, chriseth commented on libsolidity/interface/SourceReferenceFormatter.cpp
> +			line = " ... " + line.substr(0, 75) + " ... ";
Hm, I think this should rather be something like `"..." + line.substr(max(0, startColumn - 35), min(locationLength + 70, line.length())) + " ....";`, plus removing the "..." if nothing was actually cut off.

2018-08-13 09:55 UTC, chriseth requested changes
It's a good start, but I think it still needs to be adjusted a little.

Could you please also add a test in `./test/cmdlineTests.sh`?

2018-08-13 13:36 UTC, iamonuwa commented
Yeah, sure

2018-08-14 07:11 UTC, chriseth commented
Could you please remove the `...` if nothing was removed like I mentioned in https://github.com/ethereum/solidity/pull/4801#discussion_r209551492 ? Thanks!

Please also add a test for your changes.

2018-08-14 08:55 UTC, iamonuwa commented
@chriseth any guide to writing tests for this please?

2018-08-14 09:12 UTC, chriseth commented
Take a look at `cmdlinetests.sh`, especially those tests that use `test_solc_file_input_failures`.

2018-08-14 09:37 UTC, iamonuwa commented
@chriseth alright, what about checking if there is no text remaining on truncate?

2018-09-05 16:40 UTC, vs77bb commented
@chriseth I think @iamonuwa might be awaiting your feedback here!

2018-09-05 19:34 UTC, chriseth commented
@vs77bb ah thanks for mentioning, it somehow slipped my inbox.

@iamonuwa I'm sorry, but I don't really understand what you mean. Can you provide an example, please?

2018-09-11 22:41 UTC, iamonuwa commented
@chriseth I've figured it out. Writing test should submit this task tonight.

2018-09-12 01:57 UTC, liangdzou commented
@iamonuwa Since you are back for this issue. Shall I merge my code to your branch? Then, you can take care of the rest. I have added 8 test cases. Also, I think the implementation is ok.

2018-09-12 01:59 UTC, liangdzou commented
@vs77bb @iamonuwa @chriseth 
FYI, I am not interested in the bounty. @iamonuwa  can have all of them no matter which PR is merged finally.

2018-09-12 07:17 UTC, iamonuwa commented
@liangdzou alright.

2018-09-14 06:50 UTC, ekpyron commented
Superseded by #4941

2018-09-14 06:50 UTC, closed without merging