Disallow indexed reference types in events when using ABIEncoderV2
ethereum/solidity pull request #4820
Opened 2018-08-15 10:52 UTC by leonardoalt

Closes #4687

2018-08-15 12:15 UTC, chriseth commented on libsolidity/analysis/TypeChecker.cpp
> +				&& dynamic_cast<ReferenceType const*>(type(*var).get())
`&&` to the previous line

2018-08-15 12:15 UTC, chriseth commented on libsolidity/analysis/TypeChecker.cpp
> +					"Reference types cannot be indexed."
`Indexed reference types cannot yet be used with ABIEncoderV2`

2018-08-15 12:20 UTC, chriseth requested changes
Please add an endtoend test for dynamically-sized arrays both indexed and non-indexed and for both encoders (if supported) and a non-indexed struct with the new encoder.

2018-08-15 12:20 UTC, chriseth commented
Oh and the struct should be taken from storage.

2018-08-15 12:22 UTC, chriseth commented
Ah and I think we need an entry in the bug list don't we?

2018-08-15 16:16 UTC, leonardoalt commented
@chriseth Let's merge this without the json path test and I'll create a separate PR for it.

2018-08-15 20:30 UTC, chriseth approved these changes

2018-08-15 20:31 UTC, merged

2018-09-26 18:07 UTC, axic commented
I think this was working for strings, but not for structs.

Because the actual hashing is in done in `ExpressionCompiler` prior to abi encoding and that should work for strings.

As it turned out in #5102 some tests rely on it.