Update Infofeed example code and explanation
ethereum/solidity pull request #4846
Opened 2018-08-22 12:29 UTC by ChrisChinchilla

### Checklist
- [x] All tests are passing
- [x] README / documentation was extended, if necessary
- [x] Used meaningful commit messages

### Description

Closes https://github.com/ethereum/solidity/issues/4574.

I left 

> You can also use ``function setFeed(InfoFeed _feed) { feed = _feed; }``
directly.

But I'm unsure if it's appropriate or relevant anymore.

2018-09-04 11:50 UTC, chriseth commented on docs/control-structures.rst
> +You can also use ``function setFeed(InfoFeed _feed) { feed = _feed; }``
I think this paragraph can be removed now.

2018-09-04 11:50 UTC, chriseth requested changes
Fine apart from the single comment.

2018-09-05 13:48 UTC, ChrisChinchilla commented
@chriseth Removed.

2018-09-05 19:48 UTC, chriseth approved these changes

2018-09-05 19:49 UTC, merged