Fix infinite gas estimate for library bound function call
ethereum/solidity pull request #4863
Opened 2018-08-27 14:40 UTC by leonardoalt

Fixes #4471

2018-09-04 17:48 UTC, chriseth commented
Can you explain the changes in code generated? If this is just to make the gas estimator happy, I'm not sure we should do that.

2018-09-04 17:53 UTC, axic commented
> Can you explain the changes in code generated?

It is a fun reason, we went through this with @leonardoalt.

In short: in the old version `label` is swapped a couple of times and the estimator is not able to deduce it is a label due to the swaps. With reordering the code (I must admit I haven't reviewed the final version of the PR) to avoid swaps (as much as we can), while making the generator code more cohesive (subjective I guess), the estimator is also able to pick it up.

Alternatively the estimator could be improved.

2018-09-04 18:09 UTC, leonardoalt commented
The basic idea of this code is to push the jump target right before the jump.
Complementing what @axic said, there are a few `swap`s to organize the stack when the function is `bound`. The Gas Estimator then fails to infer the jump target.

2018-11-14 13:14 UTC, axic commented
@chriseth @leonardoalt can we try to get this into 0.5.1?

@ekpyron @christianparpart @bit-shift can you also review?

2018-11-14 13:16 UTC, leonardoalt commented
I will take another look at this code.

2018-11-14 13:33 UTC, ekpyron requested changes

2018-11-14 13:33 UTC, ekpyron commented on Changelog.md
> + * Gas Estimator: Fix infinite estimate for bounded library function calls.
Needs to be moved to 0.5.1 (and the PR rebased I guess).

2018-11-19 14:23 UTC, leonardoalt commented
The current code in this PR delays pushing the function label (in `FunctionCall` instead of `MemberAccess`) such that the gas estimator can figure out where to jump to. However, if there is no function call (see file `bound_no_call.sol` in this PR), too many pops are performed at the end, since
-  `a.double` has type `FunctionType` and the `sizeOnStack` of that type is the size of the label + the size of the first parameter.
- the function label was never pushed

2018-11-26 16:20 UTC, leonardoalt commented
Closing in favor of doing it properly with Yul.

2018-11-26 16:20 UTC, closed without merging