Crash when array index value is too large
ethereum/solidity pull request #4872
Opened 2018-08-30 03:17 UTC by bakaoh

Fix #4716

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] README / documentation was extended, if necessary
- [x] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### Description
Add some check to report error instead of crash

2018-09-04 17:33 UTC, chriseth requested changes
Wonderful, I would just request some tiny cosmetic changes.

2018-09-04 17:33 UTC, chriseth commented on libsolidity/analysis/TypeChecker.cpp
> +					if (!numberType->isFractional()) // error is reported above
Since you now check for `hasErrors()` this should be changed into `solAssert(!numberType->isFractional(), "")`

2018-09-04 17:33 UTC, chriseth commented on Changelog.md
> + * Type Checker: Fix crash when array index value is too large.
Perhaps better to use the word "internal error" - "crash" always sounds like a segmentation violation to me.

2018-09-04 17:33 UTC, chriseth commented on test/libsolidity/syntaxTests/types/array_index_too_large.sol
> +        return (["zeppelin"][123456789012345678901234567890123456789012345678901234567890123456789012345678]);
Ah, perhaps add a comment `// this used to cause an internal error` so that we know why the test is there.

2018-09-05 13:33 UTC, bakaoh commented
@chriseth -- i've updated :)

2018-09-05 19:46 UTC, chriseth approved these changes

2018-09-05 19:47 UTC, merged