Some turing of the documentation index.
ethereum/solidity pull request #4903
Opened 2018-09-05 08:48 UTC by chriseth

2018-09-05 08:53 UTC, ekpyron submitted a review, later dismissed

2018-09-05 10:37 UTC, ChrisChinchilla commented on docs/index.rst
> +with varying degrees of completeness and actuality. The English version stands as a reference.
I would say that especially in the context of this sentence, 'actuality' is overly complex, maybe 'accuracy' instead?

2018-09-05 10:38 UTC, ChrisChinchilla requested changes
One small thing I think needs changing.

2018-09-05 12:22 UTC, chriseth commented on docs/index.rst
> +with varying degrees of completeness and actuality. The English version stands as a reference.
I meant to say that some of them might be outdated.

2018-09-05 12:22 UTC, chriseth commented on docs/index.rst
> +with varying degrees of completeness and actuality. The English version stands as a reference.
Yeah, that's not the right word in english ;)

2018-09-05 12:40 UTC, chriseth commented
Updated.

2018-09-05 15:13 UTC, ChrisChinchilla commented on docs/index.rst
> +with varying degrees of completeness and actuality. The English version stands as a reference.
@chriseth I get you, "some might be outdated" sounds slightly rude, err, maybe just say "varying degrees of completeness", can't think of anything better right now after scouring the thesaurus. :)

2018-09-05 19:37 UTC, chriseth commented
@ChrisChinchilla do you still would like to see changes here or is it fine as it is now?

2018-09-06 15:22 UTC, ChrisChinchilla approved these changes

2018-09-06 16:00 UTC, merged