Second part of coin example.
ethereum/solidity pull request #4906
Opened 2018-09-05 09:21 UTC by chriseth

2018-09-05 09:48 UTC, leonardoalt submitted a review, later dismissed

2018-09-05 12:09 UTC, ChrisChinchilla commented on docs/introduction-to-smart-contracts.rst
> +Note that if you use
Maybe make this a proper RST / Sphinx note.

2018-09-05 12:10 UTC, ChrisChinchilla commented on docs/introduction-to-smart-contracts.rst
> +The second call to require ensures that there will not be too many coins,
For clarity might be good to code format the 'require' here.

2018-09-05 12:12 UTC, ChrisChinchilla requested changes
Some very small suggestions.

2018-09-05 12:20 UTC, chriseth commented
Updated.

2018-09-13 13:49 UTC, ekpyron commented on docs/introduction-to-smart-contracts.rst
> +    but you have to inspect the coin contract address and not the addressess of the
Typo ``addressess`` - found by spell checker.

2018-09-13 13:57 UTC, ekpyron approved these changes

2018-09-13 14:04 UTC, merged