Add syntax tests to fix #4627
ethereum/solidity pull request #5003
Opened 2018-09-17 17:26 UTC by herrBez

1. Add multiline comment test
2. Add upper case hex literal test
3. Add test for unicode escapes

### Your checklist for this pull request

Please review the [guidelines for contributing](http://solidity.readthedocs.io/en/latest/contributing.html) to this repository.

Please also note that this project is released with a [Contributor Code of Conduct](CONDUCT.md). By participating in this project you agree to abide by its terms.

### Checklist
- [ ] Code compiles correctly
- [ ] All tests are passing
- [ ] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [ ] Used meaningful commit messages

### Description
I added some syntax tests to augment the test coverage of Scanner as described here #4627. This issue should fix #4627.

Thank you for your help!

2018-09-18 07:49 UTC, herrBez commented
In the test about hexadecimal (upper case) literals, it is possible to see that we can mix upper case and lower case hexadecimal numbers. It is intended?

2018-09-18 12:42 UTC, chriseth commented
Yes, mixing case is intentional and also required for the address checksum.

2018-09-18 12:43 UTC, chriseth commented
Typo: ./test/libsolidity/syntaxTests/unicode_escape_literals.sol:18: allTogether  ==> altogether, all togethe

2018-09-18 12:43 UTC, chriseth commented
It seems the coverage run is not properly working here.

2018-09-18 12:46 UTC, chriseth commented
Could you add tests for:
 - strings with escaped newlines (not '\n' but actual newlines)
 - string escapes like `\t`, `\v`, etc.
 - strings that do not terminate before end of file
 - strings thatend in `\`, followed by end of file
 - '0.x' (read that in the source as special case, not sure if it is)
 - file ending in `1.`

2018-09-18 18:05 UTC, herrBez commented
I added some test cases for strings (at least the first 3/4 points). 


I cannot understand exactly the last three cases:

> strings thatend in \, followed by end of file

Do you mean something like:
` bytes32 escapeCharacters = "text \";`

> '0.x' (read that in the source as special case, not sure if it is)

Do you mean something like:
`bytes32 x = '0.x';`

> file ending in 1.

I cannot understand this points

2018-09-19 07:37 UTC, chriseth commented
I meant e.g. a file that contains
```
contract c { function f() pure public { "abc\
```
(without an actual newline at the end of the file!)

And the second one:
```
contract c { function f() pure public { 0.x; } }
```
Third:
```
contract c { function f() pure public { 1.
```
(without a newline at the end of the file)

2018-09-20 19:22 UTC, chriseth commented
Great! If you also add the `0.` and `1.x` cases, this can be merged.

2018-09-20 19:23 UTC, herrBez commented
Real-time answer, great :) 

Just for clarification. Should I add the case for `0.`, `1.`, `0.x` and `1.x`?

How can I name the files for the remaining cases? I cannot imagine a meaningful names.

2018-09-20 19:45 UTC, herrBez commented
Should I rebase and squash the commits to one single commit?

2018-09-20 20:42 UTC, chriseth requested changes
Yes, please squash and (potentially) rebase.

2018-09-21 09:10 UTC, herrBez commented
I am done :)

2018-09-22 09:36 UTC, herrBez commented
I am sorry, I squashed the commits, and now I cannot see the required changes :/ May I ask you to re-add the  required changes?

2018-09-24 12:43 UTC, chriseth approved these changes

2018-09-24 12:43 UTC, merged

2018-09-24 12:49 UTC, axic commented
@chriseth I think the original issue was misleading. The goal was to have coverage in `test/libsolidity/Scanner.cpp`.

2018-09-24 13:42 UTC, chriseth commented
Ah I see, sorry about that.