[DOCS] Update FAQ
ethereum/solidity pull request #5085
Opened 2018-09-25 17:32 UTC by chriseth

2018-09-25 19:19 UTC, axic requested changes

2018-09-25 19:19 UTC, axic commented on docs/frequently-asked-questions.rst
> +    pragma solidity ^0.4.0;
Please rebase and update this to `>=0.4.0 <0.6.0`

2018-09-26 09:40 UTC, leonardoalt commented on docs/frequently-asked-questions.rst
> +    library ContactHelper {
Typo on `Contact`?

2018-09-26 17:43 UTC, axic approved these changes

2018-09-26 17:43 UTC, merged