solfuzzer: adds --input-file=FILENAME command line argument (defaulting to stdin)
ethereum/solidity pull request #5134
Opened 2018-10-02 12:03 UTC by christianparpart

While debugging my other PR I had difficulties running solfuzzer on Windows and within VS2017 in debug mode due to the fact, that files are passed via stdin.

Thus I propose this change to allow passing files via command line parameter instead, yet defaulting to old behavior of using stdin if not stated otherwise.

Related to #4924.

2018-10-02 13:21 UTC, chriseth commented
Good idea!
I would propose to use the first unnamed option for the filename, though, just as with `solc`. What do you think?

2018-10-02 14:47 UTC, christianparpart commented
I am absolutely fine with that idea. I just didn't know how to realize that in the first place. I'll look into solc's solution and then adapt this one.

2018-10-09 08:39 UTC, leonardoalt submitted a review, later dismissed
Looks good to me

2018-10-09 10:01 UTC, chriseth requested changes

2018-10-09 10:01 UTC, chriseth commented on test/tools/fuzzer.cpp
> +void testConstantOptimizer(const string& input)
`string const&`

2018-10-09 10:01 UTC, chriseth commented on test/tools/fuzzer.cpp
> +			"Solidity source code input file"
The input is not always a solidity source code.

2018-10-10 14:00 UTC, chriseth approved these changes

2018-10-10 14:00 UTC, merged