[SMTChecker] Inline calls to internal functions
ethereum/solidity pull request #5189
Opened 2018-10-10 15:15 UTC by leonardoalt

2018-10-10 19:24 UTC, chriseth requested changes

2018-10-10 19:24 UTC, chriseth commented on test/libsolidity/SMTChecker.cpp
> +	CHECK_WARNING(text, "Assertion checker does not yet implement this type of function call");
Why are these tests still here?

2018-10-10 19:24 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +	return find(m_functionPath.begin(), m_functionPath.end(), _funDef) != m_functionPath.end();
could use `contains(m_functionPath, _funDef)`

2018-10-10 19:24 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +	if (hasVariable(_varDecl))
Unique identifiers like in `createExpr` are not needed because we increase the sequence number with each assignment anyway - is that correct?

2018-10-10 19:24 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +void SMTChecker::initializeFunctionParameters(FunctionDefinition const& _function)
Please clarify through its name that this is only used for a function call.

2018-10-10 19:24 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +		m_interface->addAssertion(expr(*_return.expression()) == newValue(*m_functionPath.back()->returnParameters()[0]));
Why `[0]`?

2018-10-10 19:24 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +	FunctionDefinition const* _funDef;
` = nullptr`

2018-10-10 19:24 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +		// (f)(2) needs Tuple support
Did you try `_funCall.annotation()->type->declaration()`?

2018-10-10 19:24 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +	else if (MemberAccess const* _fun = dynamic_cast<MemberAccess const*>(&_funCall.expression()))
Does this work with `f.value(x)`?

2018-10-10 19:24 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +	else if (MemberAccess const* _fun = dynamic_cast<MemberAccess const*>(&_funCall.expression()))
I think you at least still need a check that `_funDef` is non-null.

2018-10-10 19:24 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +			checkBooleanNotConstant(*_node.condition(), "For loop condition is always $VALUE.");
Can you add a test such that the check would trigger for the function when called with certain arguments, but not for the function in isolation?
I.e.
`function f(bool x) { while (x) {}; } function g() { f(true); }`

2018-10-10 19:24 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +		initializeFunctionParameters(_function);
Is it somehow possible to do that from within `inlineFunctionCall`? If yes, we could remove the `m_functionArguments`

2018-10-11 10:06 UTC, leonardoalt commented on libsolidity/formal/SMTChecker.cpp
> +		m_interface->addAssertion(expr(*_return.expression()) == newValue(*m_functionPath.back()->returnParameters()[0]));
Because we don't support tuples yet.

2018-10-11 10:09 UTC, leonardoalt commented on libsolidity/formal/SMTChecker.cpp
> +	if (hasVariable(_varDecl))
Right, this is done by the SSAVariables

2018-10-11 10:11 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +		m_interface->addAssertion(expr(*_return.expression()) == newValue(*m_functionPath.back()->returnParameters()[0]));
But you can't just take the first element. At least add an assert that there is only one element.

2018-10-11 10:32 UTC, leonardoalt commented on libsolidity/formal/SMTChecker.cpp
> +			checkBooleanNotConstant(*_node.condition(), "For loop condition is always $VALUE.");
Added a couple tests

2018-10-11 10:34 UTC, leonardoalt commented on libsolidity/formal/SMTChecker.cpp
> +		m_interface->addAssertion(expr(*_return.expression()) == newValue(*m_functionPath.back()->returnParameters()[0]));
True, at the moment this is not consistent with "support internal calls to functions that return a single value"

2018-10-11 10:39 UTC, leonardoalt commented on libsolidity/formal/SMTChecker.cpp
> +		m_interface->addAssertion(expr(*_return.expression()) == newValue(*m_functionPath.back()->returnParameters()[0]));
Actually, the return variables are fine, the non supported part is assigning them to something

2018-10-11 13:22 UTC, leonardoalt commented on test/libsolidity/SMTChecker.cpp
> +	CHECK_WARNING(text, "Assertion checker does not yet implement this type of function call");
We could keep this test for a mix of internal and external functions

2018-10-12 07:28 UTC, leonardoalt commented on libsolidity/formal/SMTChecker.cpp
> +		// (f)(2) needs Tuple support
Just tried it, it doesn't have `declaration()`.
If the `expression` of a `FunctionCall` is a `TupleExpression`, it's safe to assume it has only one element which is a function, right?

2018-10-12 08:47 UTC, leonardoalt commented on libsolidity/formal/SMTChecker.cpp
> +	else if (MemberAccess const* _fun = dynamic_cast<MemberAccess const*>(&_funCall.expression()))
`f.value(x)` has kind `SetValue`, so not supported yet.

2018-10-12 08:51 UTC, leonardoalt commented
Rebased and updated with comments

2018-10-12 13:16 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +		// (f)(2) needs Tuple support
probably, but better to assert

2018-10-15 12:07 UTC, chriseth commented
Merge conflict.

2018-10-15 12:07 UTC, chriseth commented
Also test error on windows - I think you need to modify isoltest and soltest to remove `smtChecker` if `--no-smt` is active.

2018-10-15 12:11 UTC, chriseth submitted a review, later dismissed
Fine apart from the test failures

2018-10-15 13:23 UTC, leonardoalt commented
Updated with some code from #4645 regarding SMT tests in isoltest

2018-10-15 14:48 UTC, chriseth approved these changes

2018-10-15 14:48 UTC, merged