[SMTChecker] Refactoring types
ethereum/solidity pull request #5235
Opened 2018-10-16 12:25 UTC by leonardoalt

Before this PR, SSAVariable contained a SymbolicVariable. In order to handle types better and remove this responsibility from SSAVariable, this PR swaps this relation such that now SymbolicVariable contains an SSAVariable that simply manages indices.
A lib of type utils was also created to reason about Solidity types in the SMT encoding context.

2018-10-16 14:16 UTC, chriseth requested changes

2018-10-16 14:16 UTC, chriseth commented on libsolidity/formal/SymbolicVariable.h
> +	smt::Expression current() const
currentValue?

2018-10-16 14:16 UTC, chriseth commented on libsolidity/formal/SymbolicVariable.h
> +	smt::Expression increase()
increaseSequence to distinguish from increasing the value itself?

2018-10-16 14:16 UTC, chriseth commented on libsolidity/formal/SSAVariable.h
> +	int index() const { return m_currentSequenceCounter; }
At some point we should clean up the language with respect to "sequence" and "index".

2018-10-16 14:16 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +	for (auto var: _counters)
`auto const&`?

2018-10-16 14:16 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +	for (auto var: m_variables)
`auto const&`?

2018-10-17 09:18 UTC, leonardoalt commented
I'll just go with `index` everywhere.

2018-10-17 13:59 UTC, leonardoalt commented
@chriseth Ready for review. I left the commits for now since the second one fixes the naming (`counters` x `sequence` x `index`) and the third adds `SymbolicAddressVariable`. Will squash later on.

2018-10-17 15:08 UTC, chriseth approved these changes

2018-10-17 16:35 UTC, merged