[SMTChecker] Support to mapping
ethereum/solidity pull request #5388
Opened 2018-11-09 16:18 UTC by leonardoalt

Depends on #5387

2018-11-24 18:01 UTC, axic commented
On Mac this is crashing:
```
Testing soljson via the fuzzer...
scripts/../test/cmdlineTests.sh: line 312: 28380 Segmentation fault: 11  "$REPO_ROOT"/build/test/tools/solfuzzer --quiet < "$f"
Fuzzer failed on:
pragma experimental SMTChecker;

contract C
{
	mapping (uint => mapping (uint => mapping (uint => uint))) map;
	function f(uint x) public {
		x = 42;
		map[13][14][15] = 42;
		assert(x == map[13][14][15]);
	}
}
Commandline tests FAILED
Exited with code 1
```

2018-11-24 18:13 UTC, axic commented on libsolidity/formal/SymbolicTypes.cpp
> +		}
I prefer to have an assertion here as opposed to a fallthrough.

2018-11-24 18:15 UTC, axic commented
```
  * frame #0: 0x00000001004ec1e7 solc`dev::solidity::smt::Sort::operator==(dev::solidity::smt::Sort const&) const + 23
    frame #1: 0x00000001004c5b3a solc`dev::solidity::smt::Expression::store(dev::solidity::smt::Expression, dev::solidity::smt::Expression, dev::solidity::smt::Expression) + 2122
    frame #2: 0x00000001004c46a8 solc`dev::solidity::SMTChecker::arrayAssignment(dev::solidity::Assignment const&) + 2136
    frame #3: 0x00000001004c3b07 solc`dev::solidity::SMTChecker::endVisit(dev::solidity::Assignment const&) + 1959
    frame #4: 0x0000000100225cc2 solc`dev::solidity::Assignment::accept(dev::solidity::ASTConstVisitor&) const + 146
    frame #5: 0x00000001002253ea solc`dev::solidity::ExpressionStatement::accept(dev::solidity::ASTConstVisitor&) const + 122

```

2018-11-24 18:28 UTC, leonardoalt commented
Do you think it could be related to `operator==` not being virtual?

2018-11-24 18:29 UTC, axic commented
Added assertions. It seems that `arrayAssignment` pushes an invalid expression for element.

2018-11-26 14:40 UTC, leonardoalt commented
Crash fixed. Ready for review again.

2018-11-28 22:26 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +	auto left = dynamic_cast<IndexAccess const*>(&_assignment.leftHandSide());
Why not do a dynamic cast by reference?

2018-11-28 22:27 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +	// This loop handles multi-dimensional arrays.
What about things like `a[2].x[4][3]`?

2018-11-29 09:41 UTC, leonardoalt commented on libsolidity/formal/SMTChecker.cpp
> +	auto left = dynamic_cast<IndexAccess const*>(&_assignment.leftHandSide());
`left` is reassigned later when used as a loop iterator

2018-11-29 09:43 UTC, leonardoalt commented on libsolidity/formal/SMTChecker.cpp
> +	// This loop handles multi-dimensional arrays.
What's the type of `a`?
I should perhaps phrase it differently. Solidity arrays are not supported yet, I meant SMT arrays when writing that, to support Solidity mappings.

2018-11-29 12:22 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +	// This loop handles multi-dimensional arrays.
OK, I see - but does it work or not?

I'm asking more in light of a planned architecture - you cannot just stay with mappings of mappings in the long run, you have to introduce some abstract lvalue.

2018-11-29 13:58 UTC, leonardoalt commented on libsolidity/formal/SMTChecker.cpp
> +	// This loop handles multi-dimensional arrays.
It would work by adding MemberAccess there.
But I see your point. I can rework it next week.

2018-12-05 16:57 UTC, leonardoalt commented
@chriseth Updated

2018-12-10 13:48 UTC, chriseth commented
Please add some tests that check for unsupported key or value types in mappings.

2018-12-10 13:50 UTC, chriseth commented on libsolidity/formal/SMTChecker.h
> +	void encodeArrayAssignment(IndexAccess const&, std::shared_ptr<SymbolicVariable> const&);
No parameter names?

2018-12-10 13:52 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +	m_assignmentLeftHand = true;
What about `m[x[3] = 2] = 8`? :)

2018-12-10 14:10 UTC, chriseth commented on libsolidity/formal/SMTChecker.cpp
> +		error = true;
Might also initialize `error = true;`

2018-12-10 14:13 UTC, chriseth reviewed
Apart from the comments (and the additional tests we discussed offline) this looks good, but I have the impression that a manual implementation of `visit(Assignment)`, that has a "will be assigned" parameter and returns the expression to assign to might be easier to implement than sticking with the fixed visitor pattern.

2018-12-11 17:38 UTC, chriseth commented
Needs rebase.

2018-12-12 09:43 UTC, leonardoalt commented
@chriseth updated.
Added a test with an unsupported mapping key type. It doesn't crash/throw, which is good, but it does say "expression undefined for smt solver". I already have an issue for cleaning up these cases later.

2018-12-13 09:11 UTC, chriseth commented
Please add a test for
`assert(x == y); assert(map[x] == map[y]);`

2018-12-13 15:29 UTC, chriseth requested changes
Fine apart from the requested test.

2018-12-13 15:32 UTC, chriseth commented
Ah another idea: Does passing mappings via internal function calls work? Do assignments for variables of mapping type work?

```
contract c {
  mapping(uint => uint) x;
  mapping(uint => uint) y;
  function f(bool cond, uint s) public {
    mapping(uint => uint) a = cond ? x : y;
    x[2] = 1;
    y[2] = 2;
    a[2] = 3;
    if (cond)
      assert(a[2] == x[2] && a[2] != y[2]);
    else
      assert(a[2] == y[2] && a[2] != x[2]);
  }
}
```

2018-12-13 16:13 UTC, leonardoalt commented
Nice ideas. Added tests for those. The examples from the last comment yield false positives since the SMTChecker does not consider aliasing ;)

2018-12-13 16:20 UTC, chriseth commented
@leonardoalt so can "not supporting aliasing" cause any harm? If not, why not?

2018-12-13 16:31 UTC, chriseth commented on test/libsolidity/smtCheckerTests/types/mapping_as_parameter_1.sol
> +		assert(x[a] == b);
can you add a comment that this is not yet supported?

2018-12-13 16:32 UTC, chriseth commented on test/libsolidity/smtCheckerTests/types/mapping_as_local_var_1.sol
> +		mapping(uint => uint) storage a = cond ? x : y;
Please also add a comment here.

2018-12-13 16:37 UTC, leonardoalt commented
Thinking about it, it is harmful (as in false negatives):
```
    mapping (uint => uint) a;
    mapping (uint => uint) b;
    function f() public {
        require(a[1] == b[1]);
        mapping (uint => uint) storage c = a;
        c[1] = 2;
        assert(a[1] == b[1]);
    }
```

2018-12-13 16:40 UTC, leonardoalt commented
My suggestion: we should try to support it and whenever it's not possible we clear all mapping knowledge.

2018-12-13 16:57 UTC, chriseth commented
Sounds good!

2018-12-13 16:57 UTC, chriseth commented
What does this mean for the scope of this PR?

2018-12-13 17:30 UTC, leonardoalt commented
I'll erase all mapping knowledge if there's an assignment or parameter of mapping type in this PR.

2018-12-17 13:09 UTC, chriseth approved these changes

2018-12-17 13:09 UTC, merged