Do not build LLL unless requested via the LLL cmake option
ethereum/solidity pull request #5410
Opened 2018-11-13 14:01 UTC by axic

Part of #5393.

2018-11-13 14:08 UTC, axic commented
This seemingly works on my computer, both with disabled and enabled.

2018-11-13 14:14 UTC, chfast requested changes

2018-11-13 14:14 UTC, chfast commented on CMakeLists.txt
> +option(INSTALL_LLLC "Include lllc executable in installation" LLL)
```suggestion
option(INSTALL_LLLC "Include lllc executable in installation" ${LLL})
```

2018-11-13 14:16 UTC, axic commented on CMakeLists.txt
> +option(INSTALL_LLLC "Include lllc executable in installation" LLL)
Fixed.

2018-11-13 14:25 UTC, chfast submitted a review, later dismissed

2018-11-13 14:32 UTC, axic commented
This fails on tests. This change need to be more extensive. Better to skip it for 0.5.0.

2018-11-13 14:36 UTC, axic commented
@chfast please review again, it required more extensive changes

2018-11-13 15:26 UTC, chfast submitted a review, later dismissed

2018-11-13 15:26 UTC, chfast commented on docs/lll.rst
> +    $ cmake --build
```suggestion
    $ cmake --build .
```

2018-11-13 15:26 UTC, chfast commented on test/CMakeLists.txt
>  file(GLOB liblll_sources "liblll/*.cpp")
```suggestion
    file(GLOB liblll_sources "liblll/*.cpp")
```

2018-11-13 23:51 UTC, axic commented
Rebased.

2018-11-14 09:30 UTC, axic commented
@chfast @chriseth please review, should be ready now.

2018-11-14 09:35 UTC, chfast approved these changes

2018-11-14 10:11 UTC, merged