Codegen for objects access
ethereum/solidity pull request #5616
Opened 2018-12-10 15:33 UTC by chriseth

2018-12-10 15:49 UTC, ekpyron commented
Needs fixing for clang compilation: https://github.com/ethereum/solidity/blob/7a50ff33961d988f3e8093cf6f2dacc55c4ef002/libyul/backends/evm/EVMDialect.cpp#L75

2018-12-10 16:07 UTC, chriseth commented
Updated.

2018-12-11 16:34 UTC, ekpyron approved these changes
I think this is fine - only a minor comment.

2018-12-11 16:34 UTC, ekpyron commented on test/libyul/Parser.cpp
> +	struct SimpleDialectAnalysis: public Dialect
This struct itself doesn't analyze much, does it? Maybe it should just be called ``SimpleDialect``, same as above?

2018-12-11 16:38 UTC, ekpyron requested changes

2018-12-11 16:38 UTC, ekpyron commented on libyul/backends/evm/EVMDialect.cpp
> +		AbstractAssembly& _asm,
It seems like you need to rename ``_asm`` it for the windows build, though.

2018-12-11 17:22 UTC, chriseth commented
Two renames plus a rebase.

2018-12-11 17:23 UTC, ekpyron submitted a review, later dismissed

2018-12-11 17:28 UTC, ekpyron submitted a review, later dismissed

2018-12-11 23:37 UTC, merged