Json: Provide better error message when 'settings' is not an object
ethereum/solidity pull request #5637
Opened 2018-12-12 14:49 UTC by Marenz

Fixes #5457

2018-12-12 15:06 UTC, chriseth commented on Changelog.md
> + * Commandline interface: Report better error message for json input when 'settings' is not an object
I would say preventing an internal compiler error from happening should be a bugfix and not a feature.

2018-12-12 15:08 UTC, chriseth commented
I think it makes sense to check that all the items in the json are of the right kind (object, string, array, ...) in a single PR. Could you please add the other ones?

2018-12-18 12:54 UTC, Marenz commented
Pushed an update:
* Added tests for every new check
* Added checks for every part I could find

2018-12-18 16:28 UTC, chriseth commented on libsolidity/interface/StandardCompiler.cpp
> +boost::optional<Json::Value> checkKeys(Json::Value const& _input, set<string> const& _keys, const string& _name )
```suggestion
boost::optional<Json::Value> checkKeys(Json::Value const& _input, set<string> const& _keys, const string& _name)
```

2018-12-18 16:28 UTC, chriseth commented on libsolidity/interface/StandardCompiler.cpp
> +		return formatFatalError("JSONError", "\"" + _name+ "\" must be an object");
```suggestion
		return formatFatalError("JSONError", "\"" + _name + "\" must be an object");
```

2018-12-18 16:28 UTC, chriseth commented on libsolidity/interface/StandardCompiler.cpp
> +boost::optional<Json::Value> checkSourceKeys(Json::Value const& _input, const string& _name)
```suggestion
boost::optional<Json::Value> checkSourceKeys(Json::Value const& _input, string const& _name)
```

2018-12-18 16:42 UTC, chriseth requested changes
Fine apart from the formatting changes.

2018-12-18 16:49 UTC, Marenz commented
Fixed mentioned issues

2018-12-18 17:37 UTC, Marenz commented
Fixed failing build (misplaced `&` in last fix)

2018-12-18 18:38 UTC, chriseth approved these changes

2018-12-18 18:39 UTC, merged