Update command-line tests, issue #5640
ethereum/solidity pull request #5685
Opened 2018-12-18 20:41 UTC by androlo

### Description

Put tests inside folders, divided them up into standard_json and regular solidity tests, and modified the script.

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing

```
andreas@AndreasLT:~/solidity$ ./scripts/soltest.sh --ipcpath /tmp/testeth/geth.ipc
Running 2958 test cases...

*** No errors detected
```

```
andreas@AndreasLT:~/solidity/test$ ./cmdlineTests.sh
Checking that the bug list is up to date...
Testing unknown options...
Passed
Testing overwriting files...
Testing passing files that are not found...
Testing passing files that are not files...
Testing passing empty remappings...
Testing standard input...
Testing library checksum...
Testing long library names...
Testing linking itself...
Linking completed.
Running standard JSON commandline tests...
 - default_success/
 - wrong_key_auxiliary_input/
 - wrong_key_metadata/
 - wrong_key_optimizer/
 - wrong_key_root/
 - wrong_key_settings/
 - wrong_key_source/
 - wrong_type_auxiliary_input/
 - wrong_type_auxiliary_input_smtlib2responses/
 - wrong_type_auxiliary_input_smtlib2responses_member/
 - wrong_type_metadata/
 - wrong_type_optimizer/
 - wrong_type_output_selection/
 - wrong_type_output_selection_contract/
 - wrong_type_output_selection_file/
 - wrong_type_output_selection_output/
 - wrong_type_remappings/
 - wrong_type_remappings_entry/
 - wrong_type_root/
 - wrong_type_settings/
 - wrong_type_source/
 - wrong_type_sources/
Running general commandline tests...
 - data_storage/
 - gas_test_dispatch/
 - gas_test_dispatch_optimize/
 - too_long_line/
 - too_long_line_both_sides_short/
 - too_long_line_edge_in/
 - too_long_line_edge_out/
 - too_long_line_left_short/
 - too_long_line_right_short/
Compiling various other contracts and libraries...
 - corion/
 - gnosis/
 - milestonetracker/
 - MultiSigWallet/
 - stringutils/
Compiling all examples from the documentation...
test_0057235790f1ee0c12ca44fc9ed7554ff82fd90071ad9febbe97491bcfda53ae_contracts_rst.sol
test_02c49b845d6b83698f647c19ea945ea160b470b64b1498a9017f249f763e6c36_solidity_by_example_rst.sol
test_043aeceff83edafe883f71f775edc85f296e3da3c35bd55984005da780ffc4f3_style_guide_rst.sol
test_052aa9ac67d33ea7cc95eb2093f0a59f5e74de6c01ef0908c73642a0ed2fe988_frequently_asked_questions_rst.sol
test_06de4a9e8ac7a85e4c9d412171a88d3cdcd74d34ef2ab7526126b5e9aae7e834_types_rst.sol
test_0b75e60ee3afc60293bb4feb6484002df6e29cc83e3c9ebedeb09d828d8170b8_contracts_rst.sol
test_0c6fdc11d3ccf8fb146ea1fbdafb8af04354548055fdba71ab7e4aa0ea5888c6_style_guide_rst.sol
test_0d77971c5e86205ea93197eb7c88c16a3d7322a395108ad49e7bfab23b66eda4_style_guide_rst.sol
test_0ec0c83c9b971de22b1723009b3c63f3badc0c3ffbfeda5d2056835658217ea8_solidity_by_example_rst.sol
test_132863b9e4ac86370ccf1550e0cdd8b02184fe923b56799e4cb0c9d58fd7c5a0_contracts_rst.sol
test_161f7dbdf6e33e65e0e018a34b8620e6da30444169c073ab2d50891b541d2378_structure_of_a_contract_rst.sol
test_18592ea97ff186715ae561805ccfa637a25eeef861a9d4e3795e85e35d870aaf_introduction_to_smart_contracts_rst.sol
test_19383e22dc43bbc06e08552b48a9bdeec1e7ac1a8b80de7979802e20c05a2277_contracts_rst.sol
test_19e53663af15d67fde993398d8e2f498f7ac4587595cdbe97cac2f41cc75d166_types_rst.sol
test_1c4ab77e69c274f29040fbc2fec702f00eac7b96bd85182ed180b24d1e6eb9ab_types_rst.sol
test_1d489a1bae6c0e17bfe75d8642c24a920c2fccf2a62c8f87ef59c0aca5341fe3_contracts_rst.sol
test_1db5557c6167776c3b6acc01f054bdf56e543c0da179b6c5db423cebd22797cd_contracts_rst.sol
test_1f9b414d4f2311365931bd46504678348646a8df2e43addcbda8b96de2f020e1_frequently_asked_questions_rst.sol
test_2368b7c1fb14d6cdba9889c0e47078b76a635acb86ecdbfcef5f4477994ded0a_style_guide_rst.sol
test_236e94bf49c0664936149b8d5505691553dbef6557b48b4ac6379ddd01b655e4_common_patterns_rst.sol
test_26251fac9351a96164aedee015a488397d07fc2250836c6af696d8f1e6d9e293_types_rst.sol
test_266e74280c345721b4175dc1df084a50579046aa121ee4bdfcd59237b6df3d76_style_guide_rst.sol
test_268ceda700eacd77a17ee1afd8587070f7a833f0a3619c6fc407b08e2851d210_contracts_rst.sol
test_2d43a956887a667ea46a16653544d73d2f26dc123e3f394bc8dc7fba35fa24fc_contracts_rst.sol
test_2f20f57fa44f688bfd7d8a1c8f8da4a3f0055de60c5f899c06941264c2d3105f_solidity_by_example_rst.sol
test_31ab9e6888c118962cada184cf3ff8b15fa70966902193fefae93131129ea0cc_frequently_asked_questions_rst.sol
test_378ea7fd31fc334e482c3701f6da7cbe91a804b3715efb07694f35d11afb0bb6_solidity_by_example_rst.sol
test_384619574b9ef97fdc4f7d34d3185e8881170dc3b2b4aa7b2483927725f5ee78_contracts_rst.sol
test_3e014c9f615e386f912b329d10bcfbb6c23312d839561f482f87e0ab746b0be2_control_structures_rst.sol
test_4012aea10c65f90ee71ffcb7a919940df49235537fd9d81f82fe04df6ecaa69c_style_guide_rst.sol
test_4027b644c655fb92d874189cd1843a11c9ea3d8ff5126dc63ad9d9e3895b9d6e_contracts_rst.sol
test_402d5991655a6b1f83ba66dd0559fc684c5e6c69a04998f95265dd100d15d42f_security_considerations_rst.sol
test_43c572aebfa7e36943ab5887fb5ef66a3251c4aa1e4de1c68b2e973a9cdd5e0a_security_considerations_rst.sol
test_4618c393bdf2c1ae021ac7159a1b78246b1b80c2937cbe3c55faeea3d6fd789b_contracts_rst.sol
test_461c76be31ce41de5b959f3c104dc64cf519fe79d4402ed91120b2c8563a7f55_contracts_rst.sol
test_4b8de1fd0cbffd5ee1f3882526849e7e0c2bf3d162955b5074bff1344f4d1f3b_style_guide_rst.sol
test_548bf47e7015d268d093da6593729ac9aad6842d6f1f507ccc3768899154fef5_contracts_rst.sol
test_551800cfd22b2b547d00d44a84414cb258e7d3b151fc0713444796fb1e591023_types_rst.sol
test_55868127e50a39377f40683c90bb65dba284faa53962005681c995845445f030_structure_of_a_contract_rst.sol
test_564f096d1447d7b8766600ad626c4e63cd725532c983ffd3386eb49c5dbc45dd_assembly_rst.sol
test_5670441aed4396cb170a6a191fe1082e5a7e6aa76b7619050b2f8567a49bce20_control_structures_rst.sol
test_5854f15fcd19c1bfe548955687273b7e414054a1f8e94b38204291656e631b7d_contracts_rst.sol
test_58e5a62e9eb5463450179e9338d5823dc1b7a5b15cfea93914a23f2e5b4fe115_types_rst.sol
test_59050d4d36d58691d993e1c70432a68cabc992e1670e6ed364b3fdb012890848_contracts_rst.sol
test_594437b7e48a6e754344b2617a24d9d99c7bbdb89a56ceaaa8e444c52cb0fdf4_frequently_asked_questions_rst.sol
test_5dc0c6dc9b273970ef91eb309679c2d426ba99f38d5ca73928978bbf206f9c54_solidity_by_example_rst.sol
test_5eb42f4bd47d1d31a589338fbb39435f6f342ef2b812dee0921b15567a63d860_control_structures_rst.sol
test_5eda122ebb8f3f30d47d45d1d278fd1c5ae39aafcc5434b14abe961c38e3c049_contracts_rst.sol
test_5f1106e1b2da8f552e3339d8ed2aaa4d71b1263bf6aef599c6aa43315ed15cf0_types_rst.sol
test_704f3301b31d01a98c45863118674097b603b7448426ce8257e0f343ac28b39d_contracts_rst.sol
test_71b835e6af6a9c92fced7666b8cdd2afa5f5d0bdd106b82dce90cbf0068a8a93_abi_spec_rst.sol
test_7da1e0234ed030a1c375b96cfac9f0a9357840826c804d396affd5b2028c035f_contracts_rst.sol
test_84e512f4441d2b048980147d34effe76d5298d306dda12bedf8ae1587c827041_control_structures_rst.sol
test_85fb17c6839d8a41f14e4534e41fcc5e3da732722dcde17b81b830928bf7ee55_contracts_rst.sol
test_87376d0887ced0dcbf9bbb05d4ea71b6e181db5415c3d0af37b0f4ae65a67828_control_structures_rst.sol
test_878304d7afa06180391cc5fe56dbe7f099183319c8e7c01204d06613c1ced6cc_contracts_rst.sol
test_8c0b348e5153d1bc9c355f1be31037764ce00494d877c3ec05b0c42d53611b31_contracts_rst.sol
test_8d38fa6be1e4b6aa855118d02b2d3e5099381f7e455ad657c1e0dbf405013597_contracts_rst.sol
test_912af126d614e0faf321ddb17233796d718a79de8a95c1f359643c62f7609840_common_patterns_rst.sol
test_91b3c53e118830e6838410f320817b7985b2400ef4cd0c15ba2858e0f9ce1777_structure_of_a_contract_rst.sol
test_91b854210c8c79e1a24719d1a43c77b9fa72cf559753f11024bc997b7473a1f7_contracts_rst.sol
test_925ffe39cafc7fba47cbfaeeedc7f192550edeff9ba397a9568d8bbdeb4a413b_control_structures_rst.sol
test_99459a92f7d663ad015e4ba05c05121e0e476573cefe58cd2b7c8bb79fb51ded_types_rst.sol
test_99ca760f7436986484c8273a9449fdd0158bed86a81435b99a63c20ab3cfca2e_control_structures_rst.sol
test_9ec1be1c8bc2ff83e75045b291352c8cb3f5a919d069ea92b13f58dfc9c7eccd_contracts_rst.sol
test_9f52f9710f7bd4df30629a62900ec04c2e6cf87e1961d79e80e34abe4e3d9e0c_contracts_rst.sol
test_9f7ca91f364cddb3ad717f7d8 [...]

2018-12-20 10:20 UTC, chriseth commented
looks good, thanks a lot! If you don't mind, I would like to rebase and split the commits a little.

2018-12-20 12:23 UTC, androlo commented
> looks good, thanks a lot! If you don't mind, I would like to rebase and split the commits a little.

@chriseth either do that or let me know what is wrong and i can fix. i intend on making more commits on other issues so it's nice to know what's wrong.

2018-12-20 12:54 UTC, chriseth commented
I force-pushed to your branch already - could you please review? It was just that there were too many modifications in a single commit, so it was a little hard to review.

2018-12-20 13:24 UTC, androlo commented
Not entirely sure what I'm looking at tbh, so i understand what you mean when you say it's difficult to review. 

It seems like the folders are now directly under cmdlineTests instead of two separate folders, and the standard_json tests now has `standard_` in the beginning of the folder name to distinguish them from the regular sol tests. Also the script has been modified to detect if it's standard json or not.

If that's right then I guess it should be fine.

2018-12-20 13:27 UTC, androlo commented
Really all i did was change the file names and move into folders, then updated the related script (the two sub scripts that run the tests). all the rest was just moving stuff around in the script, which didn't change anything but the order in which the tests were run.

If all you did was change folders and merged those two script sections into one then it is fine.

2018-12-20 13:29 UTC, chriseth commented
Yeah exactly. The problem was that "moving stuff around in the script" is very hard to review, so I singled that out into its own commit. The biggest change relative to yours is that I removed the additional subdirectories. Not sure if that's much better, though.

2018-12-20 13:31 UTC, androlo commented
@chriseth Ah. Ok sloppy PR by me then.. When I do other ones I will be more careful about making changes, and divide into more commits. Either way it should be fine.

2019-01-07 11:52 UTC, ekpyron requested changes
Most of it looks fine, but I think one test needs fixing, see comment below.

2019-01-07 11:52 UTC, ekpyron commented on test/cmdlineTests/standard_wrong_key_auxiliary_input.json
> -		"key1": "test"
It's a bit hard to see, but I think this one was replaced by a copy of ``standard_wrong_type_auxiliary_input`` by accident. I think it needs to be restored.

2019-01-07 11:52 UTC, ekpyron commented on test/cmdlineTests/gas_test_dispatch_optimize/input.sol
> +
I guess we don't need to introduce this new line here.

2019-01-07 14:07 UTC, chriseth commented
@ekpyron should be fixed now.

2019-01-07 14:13 UTC, ekpyron approved these changes

2019-01-07 14:29 UTC, merged