[DOCS] Split functions docs
ethereum/solidity pull request #5746
Opened 2019-01-07 13:28 UTC by ChrisChinchilla

This PR partially closes #5396 and splits functions section into smaller file.

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] README / documentation was extended, if necessary
- [x] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

2019-01-07 22:53 UTC, chriseth requested changes
This reverts a change starting in the line `When a function has multiple return types,`...

2019-01-09 10:13 UTC, ChrisChinchilla commented
@chriseth Thought I'd captured everything. Reapplied now.

2019-01-09 14:00 UTC, chriseth commented on docs/contracts/functions.rst
> +vn)`` can return multiple values.  The number of components must be	The number of components must be the same as the number of return types.
still there

2019-01-09 14:52 UTC, ChrisChinchilla commented
@chriseth Took this from `develop` so should be correct now.

2019-01-14 15:35 UTC, chriseth commented
Rebased and fixed the pragma.

2019-01-14 15:35 UTC, chriseth approved these changes

2019-01-14 15:35 UTC, merged