Ensuring we use at least boost 1.65, build static on Xenial, and adapt CircleCI accordingly.
ethereum/solidity pull request #5787
Opened 2019-01-14 11:23 UTC by christianparpart

This PR is to make sure we use at least Boost 1.65 (also on CircleCI).

As boost 1.65 is the first to also provide `boost::get` for rvalue-references.

2019-01-14 14:59 UTC, ekpyron requested changes

2019-01-14 14:59 UTC, ekpyron commented on .circleci/config.yml
> +      DEBIAN_FRONTEND: noninteractive
Can this be moved up to ``defaults``? Not sure whether there can be an ``environment`` field in ``defaults``, but in general it makes sense to have this defined in all runs.

2019-01-14 14:59 UTC, ekpyron commented on .circleci/config.yml
> +      TZ: UTC
Do we still need this given the last line?

2019-01-14 14:59 UTC, ekpyron commented on cmake/EthDependencies.cmake
> +			message(STATUS "${NAME} version: ${Boost_VERSION}")
Shouldn't this be ``${${DEP}_VERSION}`` instead of ``Boost_VERSION`` here?

2019-01-16 09:43 UTC, ekpyron approved these changes
Actually, do you think  we should provide some way of verifying the packages under https://github.com/ethereum/cpp-dependencies/releases/download/vs2017/?
I mean, if I understand you correctly, you just uploaded a local build of yours - if I'm pedantic, I don't know whether you intentionally uploaded something malicious or the system you built it on was compromised ;-).

But yeah - something that may be worth thinking about, but the PR here is fine.

2019-01-16 10:21 UTC, merged

2019-01-16 10:37 UTC, christianparpart commented
@ekpyron you're not entirely wrong. But i believe there is no process for that (yet). Even the prior releases haven't been really created "automatically" by the CI (as it should, as of reading the build/CI scripts - it's "temporarily disabled" - since years). So we leave it as is for now, and at _some_ point in the future, we should globally overhaul and streamline the whole CI process :-)