Introduce solidity_cleanup in libsolc
ethereum/solidity pull request #5852
Opened 2019-01-22 21:31 UTC by axic

2019-01-22 23:15 UTC, axic commented on libsolc/libsolc.h
> +/// NOTE: the pointers returned by solidity_license, solidity_version and solidity_compile
Actually license/version is not affected.

2019-01-23 09:34 UTC, chriseth requested changes
Please fix the comment.

2019-01-23 10:10 UTC, axic commented
Fixed, but are we happy with the naming?

2019-01-23 10:28 UTC, chriseth commented
Perhaps something like `relaseBuffer` / `freeBuffer`?

By the way, did you check this actually has an effect in emscripten?

2019-01-23 10:33 UTC, axic commented
> By the way, did you check this actually has an effect in emscripten?

Solc-js copies the result from `compile`, so calling this wouldn't have an adverse effect. Haven't checked if emscripten gets any actual benefit from this - it definitely shouldn't break anything. My motivation for this is other use cases where it is statically linked, such as Rust, but it should also help when compiling libsolc to webassembly.

2019-01-23 10:34 UTC, axic commented
> Perhaps something like `relaseBuffer` / `freeBuffer`?

I was thinking along the lines this function would "reset" the state, should we have more state in the future. If de not except anything like that then release/free might be better.

2019-01-23 10:36 UTC, chriseth commented
`cleanup` is something I would expect to call at the very end, right before shutdown, so either `releaseBuffers` or `reset` would be better in my opinion.

I would have assumed the standard-json interface to carry no state.

2019-01-23 11:00 UTC, axic commented
> I would have assumed the standard-json interface to carry no state.

I would hope we wouldn't introduce any state into this API.

2019-01-23 11:01 UTC, axic commented
@christianparpart @ekpyron @bit-shift @leonardoalt what do you think, what would be a good naming for this function?

2019-01-24 12:37 UTC, leonardoalt commented
I like `free`, especially because it's a C API ;)

2019-01-24 12:49 UTC, bshastry commented
I like `solidity_free` since `malloc`/`free` is a familiar C idiom for memory (de)allocation :)

2019-01-28 17:48 UTC, axic commented
Renamed to free, though I'm not satisfied with any of the namings :)

2019-01-30 08:42 UTC, chriseth submitted a review, later dismissed

2019-01-31 15:56 UTC, axic commented
Rebased after some other PR changed fuzzer common. Will merge once tests pass.

2019-01-31 16:26 UTC, merged