[DOCS] Create modular example
ethereum/solidity pull request #5962
Opened 2019-02-11 12:53 UTC by ChrisChinchilla

### Description

Closes https://github.com/ethereum/solidity/issues/4636

I wonder if the example needs more explanation? Nicely this also properly closes an FAQ point that we closed a while back that related to checking balances.

### Checklist
- [ ] Code compiles correctly
- [ ] All tests are passing
- [ ] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [ ] Used meaningful commit messages

2019-02-11 17:09 UTC, leonardoalt commented
I agree with https://github.com/ethereum/solidity/issues/4636#issuecomment-409585998 to use `move` instead of `send`, because of the builtin `send`.

2019-02-11 17:30 UTC, ChrisChinchilla commented
2 vs 3 on this, so updating :)

2019-02-11 18:03 UTC, leonardoalt requested changes

2019-02-11 18:03 UTC, leonardoalt commented on docs/examples/modular.rst
> +            balances.send(from, to, amount);
```suggestion
            balances.move(from, to, amount);
```

2019-02-12 10:40 UTC, leonardoalt approved these changes

2019-02-13 17:01 UTC, leonardoalt requested changes
Please rebase

2019-02-14 19:49 UTC, ChrisChinchilla commented
@leonardoalt rebased and squashed

2019-02-14 20:52 UTC, leonardoalt requested changes

2019-02-14 20:52 UTC, leonardoalt commented on docs/examples/modular.rst
> +and unexpected tokens. In the example below, the contract uses the ``send`` method
```suggestion
and unexpected tokens. In the example below, the contract uses the ``move`` method
```

2019-02-14 20:52 UTC, leonardoalt commented on docs/examples/modular.rst
> +            balances.send(from, to, amount);
```suggestion
            balances.move(from, to, amount);
```

2019-02-14 21:12 UTC, ChrisChinchilla commented
@leonardoalt I don't know why the changes keep undoing, but looks good.

2019-02-15 07:55 UTC, leonardoalt commented
Can you squash again? Sorry...

2019-02-15 20:56 UTC, ChrisChinchilla commented
Done @leonardoalt

2019-02-15 22:12 UTC, leonardoalt approved these changes

2019-02-16 22:12 UTC, merged