Add more optimisation rules for shifts
ethereum/solidity pull request #6016
Opened 2019-02-15 14:12 UTC by axic

Part of #6015.

2019-02-18 13:24 UTC, chriseth commented on libevmasm/RuleList.h
> +		{{Instruction::SHL, {0, X}}, [=]{ return u256(0); }, false},
```suggestion
		{{Instruction::SHL, {0, X}}, [=]{ return u256(0); }, true},
```

2019-02-18 13:24 UTC, chriseth commented on libevmasm/RuleList.h
> +		{{Instruction::SHR, {0, X}}, [=]{ return u256(0); }, false},
```suggestion
		{{Instruction::SHR, {0, X}}, [=]{ return u256(0); }, true},
```

2019-02-18 13:27 UTC, chriseth requested changes
The bool at the end means "potentially removes parts of the expression tree that might have side-effects". It might be that the documentation about that got lost during the refactorings.

2019-02-20 10:15 UTC, erak commented
The documentation in `SimplificationRule.h` could updated, I guess. The behavior @chriseth described is not that obvious when looking at the code / docs.

2019-02-20 10:30 UTC, axic commented
Fixed.

2019-02-20 11:19 UTC, chriseth commented on libevmasm/RuleList.h
> +		{{Instruction::SHL, {X, 0}}, [=]{ return X; }, false},
this shifts a zero by x bits and thus should be replaced by zero.

2019-02-20 12:00 UTC, axic commented
Seems the operands are reverse of shl/shr compared to sub/div. Fixed.

2019-02-20 13:46 UTC, chriseth approved these changes

2019-02-20 13:46 UTC, merged