Make unavailable opcodes errors.
ethereum/solidity pull request #6115
Opened 2019-02-26 18:23 UTC by chriseth

Fixes https://github.com/ethereum/solidity/issues/6102

This might be considered a breaking change, but we also plan to move the default VM to Constantinople with this release, so it's probably not a big deal.

2019-02-26 19:40 UTC, axic requested changes
Need to update syntax tests.

2019-02-27 16:44 UTC, leonardoalt requested changes

2019-02-27 16:44 UTC, leonardoalt commented on Changelog.md
> + * Inline Assembly: Opcodes unavailable to the currently configured EVM are errors now.
Please move it up the list.

2019-02-27 21:41 UTC, axic commented
Outside of syntax errors and other nitpicking I think the change looks good. In the future however if we add experimental opcodes not fully part of any hard fork yet, then we may need to revisit so that Dmitry can generate test cases in testeth using Solidity, but this is not a problem right now.

2019-02-27 21:46 UTC, chriseth commented
We can add an experimental VM version whose name is only known to dmitry :)

2019-02-28 15:41 UTC, axic commented on Changelog.md
> + * Inline Assembly: Opcodes unavailable to the currently configured EVM are errors now.
Opcodes -> Instructions ?

2019-02-28 15:41 UTC, axic submitted a review, later dismissed
I think this should be merged if/when we switch to "constantinople as default". Which should be tomorrow if the fork goes live today?

2019-02-28 15:43 UTC, axic commented
> Which should be tomorrow if the fork goes live today?

Apparently in ~3 hours.

2019-03-04 11:25 UTC, leonardoalt approved these changes

2019-03-04 11:26 UTC, merged