[DOCS] Improve imports documentation
ethereum/solidity pull request #6153
Opened 2019-03-04 11:55 UTC by ChrisChinchilla

### Description

### Checklist
- [ ] Code compiles correctly
- [ ] All tests are passing
- [ ] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [ ] Used meaningful commit messages

2019-03-04 11:56 UTC, ChrisChinchilla commented on docs/layout-of-source-files.rst
> +.. index:: source file, ! import, module
Not set on leaving this, was just adding terms that people might look for.

2019-03-05 15:49 UTC, erak submitted a review, later dismissed

2019-03-05 17:34 UTC, chriseth requested changes
Please squash, otherwise fine.

2019-03-06 10:08 UTC, ChrisChinchilla commented
@chriseth Squashed and rebased

2019-03-06 10:14 UTC, chriseth approved these changes

2019-03-06 10:14 UTC, merged