[DOCS] Remove random heading
ethereum/solidity pull request #6311
Opened 2019-03-18 13:24 UTC by ChrisChinchilla

### Description

Looking at this page, it didn't seem that the heading fit anything in particular, but maybe I'm wrong.

### Checklist
- [ ] Code compiles correctly
- [ ] All tests are passing
- [ ] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [ ] Used meaningful commit messages

2019-03-18 13:36 UTC, chriseth commented on docs/introduction-to-smart-contracts.rst
> -Storage
This is meant to say: First simple example on storage. The next will be a subcurrency.

2019-03-18 15:31 UTC, ChrisChinchilla commented on docs/introduction-to-smart-contracts.rst
> -Storage
In that case, I've added to the heading.

2019-03-19 09:49 UTC, erak requested changes
Unfortunately, the commit message is not very expressive.

2019-03-19 10:21 UTC, chriseth approved these changes

2019-03-19 10:21 UTC, merged