Inline Assembly: Issue error for callvalue in nonpayable function
ethereum/solidity pull request #6320
Opened 2019-03-19 16:06 UTC by leonardoalt

Fixes #6146 

I thought about creating another function, similar to the ones in the other ifs, but just for one case didn't feel worth it.

2019-03-19 16:56 UTC, Marenz submitted a review, later dismissed

2019-03-19 17:03 UTC, chriseth requested changes
Please add a test that shows it is fine to use it in a non-payable internal function.

2019-03-19 19:45 UTC, leonardoalt commented
@chriseth updated

2019-03-20 09:07 UTC, chriseth approved these changes

2019-03-20 09:07 UTC, merged