Move metadata settings into its own object.
ethereum/solidity pull request #6570
Opened 2019-04-23 19:55 UTC by chriseth

@marenz please check - I think it should be one level deeper actually.

2019-04-29 09:42 UTC, Marenz commented
LGTM. Looking at the documentation again, it seems i completely missed the "metadata" layer between "settings" and "useLiteralContent"

2019-04-29 09:43 UTC, Marenz submitted a review, later dismissed

2019-04-29 10:14 UTC, axic requested changes
Need to update the documentation in this same PR.

Otherwise looks good to me.

2019-04-29 10:15 UTC, axic commented on test/libsolidity/Metadata.cpp
> +			BOOST_CHECK(metadata["settings"]["metadata"]["useLiteralContent"].asBool());
It should also check here that the value is `true`.

2019-04-29 12:19 UTC, chriseth commented
Updated.

2019-04-29 13:02 UTC, Marenz approved these changes

2019-04-29 13:09 UTC, merged

2023-08-19 21:09 UTC, jonesk7734 reviewed
😃