[SMTChecker] Fix ICE in fixed point operations
ethereum/solidity pull request #6635
Opened 2019-04-30 15:47 UTC by leonardoalt

Fixes #6574 

I didn't add the test that failed as a new test because it now reaches a `solUnimplementedAssert` in the code generator.

2019-04-30 16:38 UTC, chriseth requested changes

2019-04-30 16:38 UTC, chriseth commented on Changelog.md
> + * SMTChecker: Fix ICE in fixed point operations.
Please move.

2019-04-30 16:47 UTC, leonardoalt commented
Updated

2019-05-02 07:48 UTC, chriseth submitted a review, later dismissed

2019-05-02 07:48 UTC, chriseth commented on Changelog.md
> + * SMTChecker: Fix ICE in fixed point operations.
Please don't use abbreviations in the changelog.

2019-05-02 07:48 UTC, chriseth commented on Changelog.md
> + * SMTChecker: Fix ICE in fixed point operations.
```suggestion
 * SMTChecker: Fix internal error in fixed point operations.
```

2019-05-02 07:51 UTC, leonardoalt commented
Updated

2019-05-02 08:59 UTC, leonardoalt commented
@chriseth updated

2019-05-02 09:16 UTC, chriseth approved these changes

2019-05-02 10:04 UTC, merged