[Docs] Better explain the modular approach.
ethereum/solidity pull request #6790
Opened 2019-05-20 13:04 UTC by chriseth

Refs https://github.com/ethereum/solidity/issues/6784

2019-05-20 15:49 UTC, guylando requested changes
"A modular approach to building your contracts helps you reduce the complexity. If you specify..." -> "A modular approach to building your contracts helps you reduce the complexity and improve the readability which will help to identify bugs and vulnerabilities during development and code review. Furthermore, when you specify..."

2019-05-22 06:50 UTC, bshastry commented on docs/examples/modular.rst
> +interactions you have to consider are only those between the specifications
`between the module specifications` instead of `between the specifications`?

2019-05-22 06:50 UTC, bshastry commented on docs/examples/modular.rst
> +It is easy to verify that it never produces negative balances or overflows
`It is easy to verify that the ``Balances`` library never produces negative balances...`? (replaced it by the Balances library)

2019-05-22 06:50 UTC, bshastry commented on docs/examples/modular.rst
>  of the ``Balances`` :ref:`library <libraries>` to check that balances sent between
Not related to this PR: Could this and other references be reformaated as `hyperlink reference <URI>`_ so as to not interrupt the flow of text. Note that the `:ref: `library <libraries>` is rendered as-is.

2019-05-23 12:02 UTC, chriseth commented
Updated.

2019-05-23 12:35 UTC, bshastry approved these changes

2019-05-23 12:36 UTC, merged