yul: AsmPrinter fix when appending type name but no type-name is available
ethereum/solidity pull request #6883
Opened 2019-06-03 15:03 UTC by christianparpart

a small fix related to #6844 where I found out that `yul::AsmPrinter` prints types names even though they are not present. I was asked to split this out. So here we go. :)

2019-06-03 18:26 UTC, ekpyron submitted a review, later dismissed

2019-06-04 08:32 UTC, leonardoalt commented on libyul/AsmPrinter.cpp
> +	if (m_yul && !_type.str().empty())
```suggestion
	if (m_yul && !_type.empty())
```

2019-06-04 08:32 UTC, leonardoalt requested changes
`YulString` has function `empty()` also, so I think we can avoid the call to `str()`

2019-06-04 09:45 UTC, ekpyron commented on libyul/AsmPrinter.cpp
> +	if (m_yul && !_type.str().empty())
Right, didn't notice that!

2019-06-05 09:58 UTC, christianparpart commented
@leonardoalt thx. didn't notice that.

2019-06-05 10:03 UTC, ekpyron approved these changes

2019-06-05 11:40 UTC, leonardoalt approved these changes

2019-06-05 11:41 UTC, merged