FunctionType: Return correct stacksize for transfer/send
ethereum/solidity pull request #7157
Opened 2019-07-31 15:38 UTC by Marenz

This is missing tests. I tried creating a syntaxTest but it seems to run a completely different logic flow not triggering this bug at all.

2019-07-31 15:54 UTC, Marenz commented
Update: Added tests. I used the cmd tests now.

2019-07-31 20:33 UTC, leonardoalt commented
Did you add it as cmd line test just for testing the PR or is the intention to keep it as final?

2019-08-01 09:06 UTC, Marenz commented
my intention was to keep it

2019-08-01 10:41 UTC, leonardoalt commented
In my opinion it doesn't fit cmd line tests and should be a syntax/semantic test.

2019-08-01 11:00 UTC, chriseth requested changes
Please change it to a semantics test.

2019-08-01 11:56 UTC, Marenz commented
Turns out, you have to call at least one function or it won't be compiled otherwise

2019-08-01 12:39 UTC, chriseth commented
@Marenz can you file a bug for that?

2019-08-01 12:39 UTC, chriseth approved these changes

2019-08-01 12:40 UTC, merged

2019-08-01 15:34 UTC, Marenz commented
Do you want an issue for this additionally to the PR https://github.com/ethereum/solidity/pull/7159#event-2526511485 that fixes it?