Add PIET to the list of Solidity tools
ethereum/solidity pull request #7541
Opened 2019-10-16 06:18 UTC by hellraiserinchief

### Description

### Checklist
- [ ] Code compiles correctly
- [ ] All tests are passing
- [ ] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [ ] Used meaningful commit messages

2019-10-16 08:06 UTC, chriseth submitted a review, later dismissed

2019-10-16 08:07 UTC, chriseth commented on docs/resources.rst
> +
Our tests are complaining about trailing whitespace here - can you please check?

2019-10-16 21:02 UTC, hellraiserinchief commented
All checks seem to pass now

2019-10-17 10:19 UTC, chriseth submitted a review, later dismissed

2019-10-17 10:19 UTC, chriseth commented
Could you please squash it into a single commit?

2019-10-18 11:11 UTC, erak submitted a review, later dismissed

2019-10-18 17:23 UTC, erak commented
@hellraiserinchief Could you please rebase? We just fixed the broken MacOS build on Circle which led to the failing test on this PR.

2019-10-18 22:09 UTC, erak approved these changes

2019-10-18 22:11 UTC, erak commented
I'm sorry, but the commits are bit messed up and do appear twice. Did you rebase onto `develop`?

2019-10-18 22:12 UTC, erak requested changes
I'm sorry, but the commits are bit messed up and do appear twice. Did you rebase onto develop? Do you need help with this?

2019-10-19 05:08 UTC, hellraiserinchief commented
> I'm sorry, but the commits are bit messed up and do appear twice. Did you rebase onto develop? Do you need help with this?

Yeah, help would be welcome, I am new to contributing to OSS

2019-10-19 07:01 UTC, hellraiserinchief commented
> > I'm sorry, but the commits are bit messed up and do appear twice. Did you rebase onto develop? Do you need help with this?
> 
> Yeah, help would be welcome, I am new to contributing to OSS

I have tried combined the commits into a single commit, please have a look and advice.

2019-10-21 13:22 UTC, Marenz approved these changes

2019-10-22 15:41 UTC, chriseth commented
Sorry, I fear you have to rebase again, the macos version change should be part of a different commit.

2019-10-23 12:24 UTC, erak commented
As @chriseth already mentioned, this needs to be rebased again, such that the changes to `.circleci/config.yaml` are not part of the PR. Also, since your working on `develop` of your fork, I'd strongly recommend to create a branch in your forked repository, and then open a PR with our `develop` as the target and your branch as the source. Your current workflow might lead to issues when trying to keep your fork up to date. Please see https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork for further advice.

2019-10-28 21:16 UTC, erak commented
@hellraiserinchief Are you able remove the change to `.circleci/config.yml`? Otherwise this PR looks good!

2019-10-28 21:18 UTC, erak requested changes
@hellraiserinchief Could you also remove the change to ``.circleci/config.yml``? Otherwise this PR looks good!

2019-10-30 17:44 UTC, hellraiserinchief commented
@erak, I will follow your advice and create a new branch to submit a new PR, instead of using the develop branch directly

2019-10-30 17:44 UTC, closed without merging