[DOCS] Add project board links to read me
ethereum/solidity pull request #7636
Opened 2019-11-05 16:21 UTC by ChrisChinchilla

### Description

Adds a link to the project read me pointing readers to the project tab for current release issues.

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] README / documentation was extended, if necessary
- [x] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

2019-11-05 16:28 UTC, Marenz requested changes

2019-11-05 16:28 UTC, Marenz commented on README.md
> +You can find our current feature and bug priorities for forthcoming release [in the projects section](https://github.com/ethereum/solidity/projects).
`forthcoming releases` or `the forthcoming release`?

2019-11-05 16:56 UTC, ChrisChinchilla commented on README.md
> +You can find our current feature and bug priorities for forthcoming release [in the projects section](https://github.com/ethereum/solidity/projects).
Whoops, yes

```suggestion
You can find our current feature and bug priorities for forthcoming releases [in the projects section](https://github.com/ethereum/solidity/projects).
```

2019-11-05 17:00 UTC, Marenz submitted a review, later dismissed

2019-11-05 17:09 UTC, chriseth requested changes
Please squash.

2019-11-06 15:30 UTC, Marenz commented
We can use "Squash and merge"

2019-11-06 15:31 UTC, axic commented
> We can use "Squash and merge"

Please don't. It doesn't leave a merge commit just pushes a commit on head :wink:

2019-11-06 15:35 UTC, Marenz commented
sounds beautiful to me, I hate merge commits ;)

2019-11-06 17:37 UTC, chriseth approved these changes

2019-11-06 17:37 UTC, merged