Add support for do/while loops
ethereum/solidity pull request #768
Opened 2016-07-30 07:43 UTC by roadriverrail

This commit adds support for a standard do <statement> while <expr>;
form of statement.  While loops were already being supported; supporting
a do/while loop mostly involves reusing code from while loops but putting
the conditional checking last.

This commit resolves issue #766

2016-08-01 09:54 UTC, chriseth commented
Thanks for the pull request and your interest in the project! We have to think about whether introducing do-while-loops is something we want to be part of the language or if they are an unnecessary complication. If you want to work on features that have already been agreed by the community, please talk to a team member in gitter.im/ethereum/solidity

2016-10-28 15:04 UTC, chriseth commented
Will change this to re-use the existing while loop ast node.

2016-10-28 15:14 UTC, roadriverrail commented
Were you going to do that yourself in the next couple of days?  I have a road trip coming up tomorrow, and I might have the free evening or two to do that.

2016-10-28 15:27 UTC, chriseth commented
oh wow, even the better :-)
So the idea is to re-use the while loop ast node to reduce complexity and add a flag to it telling whether it is a do-while or a while-do-loop. It is important that this flag is also output for the two ast outputs.

2016-10-28 15:29 UTC, roadriverrail commented
Yeah, as soon as I saw your comment, I figured that's what you had in mind.  I haven't looked at solc since I wrote this (major life changes), but I assume you already have some sort of context variable that gets passed around that I could store the flag in.  Most compilers do.

2016-10-28 16:22 UTC, chriseth commented
At the point where the ast node is created in the parser, this flag should be stored inside the ast node as a regular class member.

2016-10-28 16:25 UTC, roadriverrail commented
Got it.  Makes perfect sense.

On Fri, Oct 28, 2016 at 9:22 AM chriseth <notifications@github.com> wrote:

> At the point where the ast node is created in the parser, this flag should
> be stored inside the ast node as a regular class member.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum/solidity/pull/768#issuecomment-256964593>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAlhYKDAV71YbpyEQneCcuqeKYuzUJ1qks5q4iFAgaJpZM4JYwLU>
> .
>

2016-11-07 00:47 UTC, roadriverrail commented
Okay; this appears to be functionally comparable code without the extra class.  Also, I saw that Why3 does not appear to support do-while, so I simulate a do-while loop for its output.  I'm going to have to look at a rebase next, since the commit from main that this branch is based on has a broken "ast" and "ast-json" output.

2016-11-07 10:03 UTC, chriseth requested changes

2016-11-07 10:03 UTC, chriseth commented on libsolidity/ast/AST.h
> +                bool _isDoWhile
Please use tabs for indentation.

2016-11-07 10:03 UTC, chriseth commented on libsolidity/ast/ASTJsonConverter.cpp
> +	addJsonNode(_node,
Code style should be
```
addJsonNode(
    _node,
    _node.isDoWhile()  ?...,
    true
);
```

2016-11-07 10:03 UTC, chriseth commented on libsolidity/parsing/Parser.cpp
> +	nodeFactory.setEndPositionFromNode(body);
This should be replaced by a call to `nodeFactory.setEndPosition()` right before expecting the semicolon.

2016-11-08 05:50 UTC, roadriverrail commented on libsolidity/ast/ASTJsonConverter.cpp
> +	addJsonNode(_node,
Sorry for the style break.  Did I miss the style guide somewhere?  Or do you follow a well-known one by convention?

2016-11-08 05:51 UTC, roadriverrail commented on libsolidity/parsing/Parser.cpp
> +	nodeFactory.setEndPositionFromNode(body);
Fixed; that certainly explained some funny output I was seeing in the --asm dumps I normally use to confirm the results.

2016-11-08 09:54 UTC, chriseth commented on libsolidity/ast/AST.h
> +        bool isDoWhile() const { return m_isDoWhile; }
Here are still some spaces, probably in more places.

2016-11-08 17:07 UTC, chriseth commented
Thanks! The last thing that is missing now is an entry into the changelog file and some mention of this feature in the documentation. I can also do that after merging this PR if you want.
Oh and it seems we have a conflict in grammar.txt :-(

2016-11-08 17:09 UTC, roadriverrail commented
Yeah, I'll do the pickup merging on grammar.txt.  I can get the changelog
and docs updated, too.  Also, do you have some sort of testing framework I
should look into writing some tests for?

On Tue, Nov 8, 2016 at 9:07 AM chriseth <notifications@github.com> wrote:

> Thanks! The last thing that is missing now is an entry into the changelog
> file and some mention of this feature in the documentation. I can also do
> that after merging this PR if you want.
> Oh and it seems we have a conflict in grammar.txt :-(
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum/solidity/pull/768#issuecomment-259196594>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAlhYDneCGvCORSA7Z8nWA7KHUeukOaxks5q8KxJgaJpZM4JYwLU>
> .
>

2016-11-08 17:13 UTC, chriseth commented
Oh of course, totally forgot about tests. I think it is enough to add an end to end test, so take a look at the file SolidityEndToEndTest.cpp. You can probably copy an example there. Running the tests is a bit tricky, because you need an `eth` node. Start it with `eth --test -d /tmp/test` and then run `soltest -- --ipcpath /tmp/test/geth.ipc`.

2016-11-08 17:24 UTC, roadriverrail commented
Since we're mostly done with the CR process, I squashed the commits, updated the Changelog, and added some mention of "do" to the docs, though documentation of the control structures is pretty light.

2016-11-08 21:15 UTC, roadriverrail commented
Okay.  I should be able to add a test.  Tonight's a pretty tight schedule, but Wednesday or Thursday should be a little bit better.

2016-11-09 14:00 UTC, chriseth commented
That's great, thanks!

2016-11-10 08:13 UTC, roadriverrail commented
Okay.  I added a basic unit test modeled on the while loop test.  I see it runs the test repeatedly with different values of n and checks it against what you expect from C++, and that seems suitable enough.  I could get fancier, I suppose, with nesting and all that jazz, if there's a need.

2016-11-10 11:12 UTC, chriseth requested changes

2016-11-10 11:12 UTC, chriseth commented on test/libsolidity/SolidityEndToEndTest.cpp
> +                do
Please don't use spaces for indentation.

2016-11-10 11:12 UTC, chriseth commented on test/libsolidity/SolidityEndToEndTest.cpp
> +		} while (i <= n);
Please put the `while` on the next line.

2016-11-10 15:08 UTC, roadriverrail commented
Sincerely sorry about the style violations; I thought I checked every line for spaces last night, but it was late.  Fixed.

2016-11-10 16:13 UTC, chriseth commented
Wonderful, thanks a lot!

2016-11-10 16:13 UTC, chriseth approved these changes

2016-11-10 16:13 UTC, merged

2016-11-10 18:59 UTC, roadriverrail commented
Thanks for the patience in the review process.  solc is pretty easy to work on, so I'm hoping this will not be the last time you'll be seeing a PR from me.

2016-11-10 22:49 UTC, chriseth commented
That's great to hear! The issues marked as "soon" and/or "up-for-grabs" are probably the best to work on. If in doubt, ask on http://gitter.im/ethereum/solidity or contact me at chris@ethereum.org

2016-11-14 08:23 UTC, roadriverrail commented
Fixes #766