Use yaml anchor to store current docker image revision
ethereum/solidity pull request #7750
Opened 2019-11-19 16:10 UTC by bshastry

Fixes #7736

2019-11-19 16:21 UTC, chfast reviewed
This is ok if you only consider YAML, but Circle CI has noticed that many things in the config are duplicated and they introduced version 2.1 of the config. In particular, you can specify executors on their own: https://circleci.com/docs/2.0/configuration-reference/#executors-requires-version-21.

2019-11-19 16:24 UTC, chfast requested changes
Oh, actually this is not ok from YAML point of view. YAML only allows you to reference (read: copy) full map entries. They cannot be inserted as a substring.

2019-11-22 15:42 UTC, bshastry commented
I updated this PR to use pipeline parameters instead of a yaml anchor. Since this PR involves upgrading circle ci config version to `2.1` from `2` (in order to make use of pipeline parameters), I will wait on the CIs before marking this for review.

2019-11-22 16:23 UTC, chfast approved these changes

2019-11-25 15:54 UTC, merged