Fixes#7578: Updated/added quotes within error messages
ethereum/solidity pull request #7919
Opened 2019-12-08 03:08 UTC by birtony

### Description
Fixes #7578 

Updated existing quotes within error messages to double quotes, added new double quotes around user-defined variables.

### Checklist
- [ ] Code compiles correctly
- [ ] All tests are passing
- [ ] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [ ] Used meaningful commit messages

2019-12-08 04:43 UTC, birtony commented
@Marenz I have updated as many errors as I could find. Some tests fail due to the changes I have made to some of the error messages:
https://github.com/ethereum/solidity/blob/52ef581763c2a50b8cfb42953c702b7a033e7898/libsolidity/analysis/ViewPureChecker.cpp#L182
I have tried to update the tests accordingly:
https://github.com/ethereum/solidity/blob/52ef581763c2a50b8cfb42953c702b7a033e7898/test/libsolidity/syntaxTests/nameAndTypeResolution/010_type_conversion_for_comparison.sol#L6
https://github.com/ethereum/solidity/blob/52ef581763c2a50b8cfb42953c702b7a033e7898/test/libsolidity/syntaxTests/nameAndTypeResolution/011_type_conversion_for_comparison_invalid.sol#L5
https://github.com/ethereum/solidity/blob/52ef581763c2a50b8cfb42953c702b7a033e7898/test/libsolidity/syntaxTests/nameAndTypeResolution/013_large_string_literal.sol#L6
Please, let me know if there is anything that should update in my PR?

2019-12-09 09:23 UTC, Marenz requested changes
There still seem to be a lot of tests that need to be updated according to the CI.

2019-12-09 09:23 UTC, Marenz commented on libsolidity/analysis/SyntaxChecker.cpp
> +			"it can change its semantics. Either disable the \"Yul\" optimizer or do not use the instruction."
`Yul` is not a user defined name here :)

2019-12-09 09:23 UTC, Marenz commented on libsolidity/analysis/SyntaxChecker.cpp
> +		m_errorReporter.syntaxError(_operation.location(), "Use of unary \"+\" is disallowed.");
I am unsure if we should quote `+`. Other opinions?

2019-12-09 09:23 UTC, Marenz commented on libsolidity/analysis/SyntaxChecker.cpp
> +		m_errorReporter.syntaxError(_modifier.body().location(), "Modifier body does not contain \"_\".");
Unsure if we should quote this. Other opinions?

2019-12-09 09:23 UTC, Marenz commented on test/libsolidity/syntaxTests/nameAndTypeResolution/010_type_conversion_for_comparison.sol
> +// Warning: (20-66): Function state mutability can be restricted to "pure"
We have to check whether we want things like data types and visibility / pureness quoted

2019-12-09 10:04 UTC, erak commented
@Marenz Looking through the error messages, I'd propose the following rule of thumb for quotes:
- all keywords
- all types
- all user-defined types
- all opcodes
- all magic members
- (not sure yet) operators (like unary +)

@birtony There's a way to semi-automatically update the (at least .sol-file-based) tests. You just have to build and run `./build/test/tools/isoltest`, which compares the error messages stated by the file with the actual output from the compiler, and helps you overwrite the old error messages in the file via command line input.

2019-12-16 17:02 UTC, Marenz commented
Your proposal sounds good to me.

2020-01-06 09:46 UTC, bshastry commented
Needs rebase and test updates. IIUC, there seems to be consensus on writing a helper function to quote a string (see https://github.com/ethereum/solidity/issues/7578#issuecomment-563168826). IIUC, the helper function may look like so.

```
string quotedString(string s)
{
   return "\"" + s + "\"";
}
```

TBD: Placement of said function. My guess: somewhere in libdevcore.

2020-01-06 10:32 UTC, Marenz commented
I'll take over this PR/feature

2020-01-06 10:46 UTC, Marenz commented
@erak we often have types like `int_const` etc.. should we quote those as well? Or take this example:
```
Type int_const 5221...(1225 digits omitted)...5168 is not implicitly convertible to expected type int256.
```

2020-01-06 13:08 UTC, erak commented
@Marenz I think it makes sense to also quote `int_const` since it's a type as well (even though an internal one). What's you take on this?

2020-01-06 13:09 UTC, Marenz commented
I tend to go with quoting it as well

2020-01-07 16:46 UTC, Marenz commented
Closing in favor of https://github.com/ethereum/solidity/pull/8103

2020-01-07 16:46 UTC, closed without merging