Drop solc-js backwards compatibility for 0.6
ethereum/solidity pull request #7933
Opened 2019-12-09 13:48 UTC by axic

Reverts #7917 for 0.6.

2019-12-09 14:32 UTC, chriseth approved these changes

2019-12-09 14:33 UTC, chriseth requested changes
Actually removing my approval, we should run the tests on updated solc-js before merging.

2019-12-09 14:50 UTC, axic commented
> Actually removing my approval, we should run the tests on updated solc-js before merging.

I wouldn't merge before the solc-js part is merged.

2019-12-09 15:46 UTC, axic commented
The merge was pushed to solc-js: https://github.com/ethereum/solc-js/pull/426

Retriggering this PR.

2019-12-09 16:42 UTC, leonardoalt commented
Probably failing because of what https://github.com/ethereum/solidity/pull/7938 fixes

2019-12-09 17:35 UTC, axic commented
@chriseth should be ready now

2019-12-09 17:43 UTC, leonardoalt approved these changes

2019-12-10 09:02 UTC, chriseth approved these changes

2019-12-10 09:03 UTC, merged