[DOC] Update interfaces
ethereum/solidity pull request #7974
Opened 2019-12-11 16:31 UTC by chriseth

2019-12-11 17:02 UTC, bshastry commented on docs/contracts/interfaces.rst
> +All functions declared in interfaces are implicitly ``virtual``, which means
```suggestion
All functions declared in interfaces are implicitly ``virtual``, which means that
```

2019-12-11 18:03 UTC, leonardoalt commented
Rebased

2019-12-12 10:16 UTC, bshastry requested changes
Looks good to me apart from the tiny rewording in my previous review

2019-12-12 11:47 UTC, leonardoalt approved these changes

2019-12-12 11:51 UTC, merged