Enable more warnings in the build system
ethereum/solidity pull request #8013
Opened 2019-12-14 13:01 UTC by axic

Part of #6905.

2019-12-14 13:13 UTC, axic commented
Weird, my macos clang wasn't as pedantic as CI's :wink:

2019-12-18 17:33 UTC, axic commented on libsolidity/codegen/LValue.cpp
> -					TypePointer sourceMemberType = sourceType.memberType(member.name);
This is already done on line 327 and this was a dupliacte.

2019-12-18 17:35 UTC, axic commented
I'm not proud of the renaming for avoiding shadowing, but it did spot one mistake.

2019-12-18 18:39 UTC, axic commented
Shadowing is super annoying as it depends on compiler version, none of these failures are shown on macos.

2019-12-18 18:45 UTC, axic commented
@leonardoalt you can also check this monster

2019-12-19 14:39 UTC, Marenz requested changes
Apart from the failing tests this LGTM

2020-01-06 11:38 UTC, erak requested changes
Builds are failing. Did not take a deeper look at the specific issues, though.

2020-01-06 12:26 UTC, ekpyron commented
Do we *really* want to disallow shadowing :-)? If we really want to, I'd manage to cope, but to me personally that feels much more annoying than helpful... what mistake did that reveal?

2020-01-06 13:52 UTC, leonardoalt commented on libsolidity/interface/CompilerStack.cpp
> +			for (auto params_it = paramTypes.begin(); params_it != paramTypes.end(); ++params_it)
Style should be camel

2020-01-06 13:52 UTC, leonardoalt commented on libyul/optimiser/CommonSubexpressionEliminator.cpp
> +		if (m_value.count(identifier_name))
Camel style

2020-01-06 13:52 UTC, leonardoalt commented on libyul/optimiser/DataFlowAnalyzer.cpp
> +	if (auto sstore_vars = isSimpleStore(dev::eth::Instruction::SSTORE, _statement))
Camel

2020-01-06 13:53 UTC, leonardoalt commented on libyul/optimiser/Rematerialiser.cpp
> +		YulString identifier_name = identifier.name;
Camel

2020-01-06 13:53 UTC, leonardoalt commented on libyul/optimiser/VarNameCleaner.cpp
> +	auto identifier_name = m_translatedNames.find(_identifier.name);
Camel

2020-01-06 13:53 UTC, leonardoalt commented on test/libsolidity/ASTJSONTest.cpp
>  	{
Brackets can now be removed

2020-01-06 13:53 UTC, leonardoalt commented on test/libsolidity/ASTJSONTest.cpp
>  	{
Here too

2020-01-06 13:54 UTC, leonardoalt commented on test/libsolidity/SolidityExpressionCompiler.cpp
> -			ErrorReporter errorReporter(errors);
Maybe the idea here was to have a fresh one?
Not sure

2020-01-06 14:04 UTC, axic commented
> If we really want to, I'd manage to cope, but to me personally that feels much more annoying than helpful... what mistake did that reveal?

@ekpyron I can't fully remember, but it did find this: https://github.com/ethereum/solidity/pull/8013#discussion_r359476670

2020-01-06 14:09 UTC, ekpyron commented
> > If we really want to, I'd manage to cope, but to me personally that feels much more annoying than helpful... what mistake did that reveal?
> 
> @ekpyron I can't fully remember, but it did find this: [#8013 (comment)](https://github.com/ethereum/solidity/pull/8013#discussion_r359476670)

That's not *really* an error, though :-)... I mean it's nicer after the change, but it wasn't wrong before...

2020-01-06 14:13 UTC, axic commented
This commit 3ecbcbb001  works. I'd prefer merging that and deal with shadowing separately. Any comments?

2020-01-06 14:14 UTC, axic commented
@ekpyron btw if shadowing is annoying, don't even dare to look at implicit conversion warnings 😨

2020-01-06 14:21 UTC, ekpyron commented
> @ekpyron btw if shadowing is annoying, don't even dare to look at implicit conversion warnings fearful

Haha, yeah, I can imagine, but warnings on narrowing conversions I'd much rather have than on shadowing :-). So I'd go ahead without that commit, but yeah - feel free to vote me down on the shadowing stuff, if you think it's worthwhile :-) - I could live with it.

2020-01-08 08:10 UTC, chriseth commented
Needs rebase.

2020-01-08 10:25 UTC, chriseth commented
Will compile on my system and rebase.

2020-01-08 13:18 UTC, chriseth commented
Decision from call: do not enable shadowing warning.

2020-01-15 14:21 UTC, axic commented
@chriseth @ekpyron @leonardoalt rebased and removed shadowing

2020-01-15 16:40 UTC, axic commented
The travis failure is the bytecode uploader.

2020-01-15 17:00 UTC, chriseth approved these changes

2020-01-15 17:00 UTC, merged