[YulIR] Change expression parts to use strings instead of numbers.
ethereum/solidity pull request #8181
Opened 2020-01-23 10:19 UTC by chriseth

### Description

### Checklist
- [ ] Code compiles correctly
- [ ] All tests are passing
- [ ] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [ ] Used meaningful commit messages

2020-01-23 13:48 UTC, chriseth commented
This will make it much easier to set gas, value and salt parameters on functions. I think it is also much easier to read and verify.

2020-01-26 17:25 UTC, erak commented on libsolidity/codegen/ir/IRGenerationContext.cpp
> +string IRGenerationContext::variablePart(Expression const& _expression, std::string const& _part)
```suggestion
string IRGenerationContext::variablePart(Expression const& _expression, string const& _part)
```

2020-01-26 17:26 UTC, erak commented on libsolidity/codegen/ir/IRGeneratorForStatements.cpp
> +ostream& IRGeneratorForStatements::defineExpressionPart(Expression const& _expression, std::string const& _part)
```suggestion
ostream& IRGeneratorForStatements::defineExpressionPart(Expression const& _expression, string const& _part)
```

2020-01-26 17:27 UTC, erak requested changes
Just 2 tiny comments. Looks good otherwise.

2020-01-27 08:24 UTC, merged