Add support for reading standard-json from file
ethereum/solidity pull request #8232
Opened 2020-02-04 02:57 UTC by aarlt

Currently `--standard-json` only supports reading input from `stdin`, reading input from a specified file may simplify debugging.

2020-02-04 15:01 UTC, chriseth commented
In which circumstance couldn't you use `solc --standard-json < inputfile.json`?

2020-02-04 15:26 UTC, aarlt commented
Sure, but I wanted to use an IDE for debugging. I'm using right now CLion and there it is only possible to supply `Program arguments`. Probably there are other ways, but `solc --standard-json < inputfile.json` did not work. For me it was just easier to just enable the definition of input files. From my point of view it just simplifies debugging.

I was now also wondering how this may works with e.g. `gdb`. I just did a very superficial look, but it seem to be a bit ugly. See https://stackoverflow.com/questions/13104206/how-to-debug-a-program-that-takes-user-input-from-stdin-with-gdb#13131964

2020-02-04 15:46 UTC, chriseth commented
Added it to the discussion queue.

2020-02-05 14:22 UTC, chriseth commented
Discussion: Allow input via file and stdin, but output only to stdout.

2020-02-05 16:08 UTC, chriseth requested changes
Please modify the `--help` screen accordingly.

2020-02-11 09:57 UTC, ekpyron approved these changes

2020-02-11 11:57 UTC, merged