Fix AST JSON test on MacOS
ethereum/solidity pull request #8304
Opened 2020-02-12 11:59 UTC by erak

2020-02-12 13:56 UTC, Marenz submitted a review, later dismissed

2020-02-12 14:38 UTC, chriseth requested changes
`-p` on linux takes an argument. Why do you think `-p` can just be deleted?

2020-02-12 14:45 UTC, Marenz commented
Ah I didn't read properly. `-p` was to make sure the temp dir is created as a subdir of the parameter. It isn't strictly necessary, but we then should also remove the parameter

2020-02-14 12:42 UTC, erak commented
Updated. It now doesn't create the temp directory inside the working directory any more, since there's no platform-independent way of doing that.

2020-02-14 13:03 UTC, chriseth approved these changes

2020-02-14 13:04 UTC, merged