Add Ubuntu Focal.
ethereum/solidity pull request #8310
Opened 2020-02-12 17:48 UTC by chriseth

Closes #8195

2020-02-12 17:48 UTC, chriseth commented
Just ran the focal z3 script: https://launchpad.net/~ethereum/+archive/ubuntu/cpp-build-deps/+build/18698203

2020-02-12 18:16 UTC, ekpyron commented on scripts/install_deps.sh
>                          install_z3="libz3-dev"
This one won't work, that'd be the stock ubuntu libz3 which is too old... Actually I'm generally not sure this entire script works all that well these days...

2020-02-12 18:17 UTC, ekpyron commented on scripts/install_deps.sh
>                          install_z3="libz3-dev"
Actually wrong - focal actually has the right one I just noticed! It won't work for bionic above, though :-D.

2020-02-12 18:19 UTC, ekpyron commented
Since ubuntu focal actually has libz3-dev 4.8.7, I think we actually don't need the static Z3 PPA anymore for it and we should rather change the release PPA script from installing ``libz3-static-dev```to installing ``libz3-dev``, **if** on focal...

2020-02-12 18:22 UTC, ekpyron requested changes
We should try building against stock ``libz3-dev`` instead of our ``libz3-static-dev`` for focal.

2020-02-12 18:50 UTC, chriseth commented
Saw the comment too late. Ran the release_ppa.sh script to see if it works.

2020-02-13 21:45 UTC, ekpyron commented
New build against stock Z3 triggered here: https://launchpad.net/~ethereum/+archive/ubuntu/ethereum-dev/+build/18704560

2020-02-14 10:14 UTC, ekpyron approved these changes

2020-02-14 10:53 UTC, merged