[yul-phaser] Random algorithm
ethereum/solidity pull request #8327
Opened 2020-02-16 00:59 UTC by cameel

### Description
The sixth pull request implementing #7806. Originally a part of #8256 which is now closed. Depends on #8326.

This PR introduces the `GeneticAlgorithm` class which is the mechanism that replaces the `doSelection()` and `doMutation()` methods in `Population`. The randomized algorithm has been reimplemented as `RandomAlgorithm` and has gained a few configurable parameters.

`Population` is now just an immutable container for `Chromosome`s.

Another feature is the `Selection` class and its specializations (`RangeSelection`, `MosaicSelection` and `RandomSelection`). These are meant to be used with `Population::select()` (and in the next PR also `mutate()` and `crossover()`) to choose subsets of individuals for specific parts of the algorithm to work with.

Finally the application now runs `RandomAlgorithm` with the size of the `Population` increased to 20 and only one individual being preserved in each round.

### Dependencies
This PR is based on #8326. Unfortunately changes from that base PR will show through in the combined diff and on the commit list until it gets merged.

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

2020-02-24 16:57 UTC, chriseth commented on tools/yulPhaser/GeneticAlgorithms.cpp
> +	m_population = (
No need for `(`

2020-02-24 16:57 UTC, chriseth requested changes
Looks good apart from the small change.

2020-02-25 15:13 UTC, cameel commented on tools/yulPhaser/GeneticAlgorithms.cpp
> +	m_population = (
Removed.

2020-02-25 15:26 UTC, chriseth approved these changes

2020-02-26 13:44 UTC, merged