Added error message for virtual (library) functions; test case
ethereum/solidity pull request #8585
Opened 2020-04-03 08:02 UTC by hrkrshnn

Fixes https://github.com/ethereum/solidity/issues/8540

Adds a new erorr message: "virtual" function in a library is meaningless, since a library cannot be inherited

2020-04-03 08:15 UTC, hrkrshnn commented
@chriseth mentioned about doing external tests for this. I'll do that now.

2020-04-03 08:20 UTC, ekpyron requested changes
This one should probably get a Changelog entry. Strictly speaking it'd be a breaking change, but that would be a bit exaggerated, so we file it under Bugfixes: Type Checker: Disallow ``virtual`` for library functions.

2020-04-03 08:20 UTC, ekpyron commented on libsolidity/analysis/TypeChecker.cpp
> +										"meaningless, since a library cannot be inherited");
Maybe simply:
```suggestion
			m_errorReporter.typeError(_function.location(), "Library functions cannot be \"virtual\".");
```
?

2020-04-03 08:27 UTC, ekpyron commented
> @chriseth mentioned about doing external tests for this. I'll do that now.

Yeah, the test runs indicate that apparently a virtual library snuck into ``test/compilationTests/gnosis``, so at least that needs to be fixed.

2020-04-03 09:49 UTC, ekpyron approved these changes

2020-04-03 09:56 UTC, ekpyron commented
Can be merged once the failing compilation test is fixed.

2020-04-03 10:24 UTC, leonardoalt commented
@hrkrshnn is this WIP or can it be merged (when the tests pass)?

2020-04-03 10:25 UTC, hrkrshnn commented
@leonardoalt can me merged when the tests pass.

2020-04-03 11:29 UTC, merged

2020-04-03 21:42 UTC, chriseth commented
If this is for breaking, shouldn't the changelog entry go into the 0.7.0 part?

2020-04-06 07:13 UTC, hrkrshnn commented
> If this is for breaking, shouldn't the changelog entry go into the 0.7.0 part?

@chriseth Yes it should go to 0.7.0 part, my bad. The current plan is to push it to develop (https://github.com/ethereum/solidity/pull/8587) and revert the breaking PR (https://github.com/ethereum/solidity/pull/8588) could you revert the breaking and force push it, for a cleaner history?

2020-04-06 08:46 UTC, chriseth commented on Changelog.md
> + * Type Checker: Disallow virtual for library functions.
Changelog entry has to be moved.