Adding test for payable constructor with inheritance
ethereum/solidity pull request #8734
Opened 2020-04-22 10:03 UTC by mijovic

2020-04-27 11:27 UTC, leonardoalt requested changes

2020-04-27 11:27 UTC, leonardoalt commented on test/libsolidity/semanticTests/constructor/payable_constructor_inheritance.sol
> +// constructor(), 27 wei ->
Can you also add a call that checks the balance?

2020-05-11 20:34 UTC, mijovic commented
I think this is not working anymore after @ekpyron changes for constructors and payables. 
We should close PR without merging

2020-05-11 20:35 UTC, ekpyron commented
Yep, this would actually be a test for what we now call a low-severity bug :-). Closing it.

2020-05-11 20:35 UTC, closed without merging