Conditional strings for Whiskers.
ethereum/solidity pull request #8761
Opened 2020-04-23 14:35 UTC by chriseth

Fixes #8733

2020-04-23 18:09 UTC, mijovic submitted a review, later dismissed
Looks good to me

2020-04-24 09:01 UTC, leonardoalt requested changes
The syntax `+<b>` doesn't seem to be documented?

2020-04-24 09:01 UTC, leonardoalt commented on docs/contributing.rst
> +continues recursively either in the first or the second segment depending on the value of the boolean
```suggestion
continue recursively either in the first or the second segment depending on the value of the Boolean
```

2020-04-27 09:05 UTC, chriseth commented
I think I'll change this to use `+`

2020-04-27 11:17 UTC, leonardoalt requested changes

2020-04-27 11:17 UTC, leonardoalt commented on test/libsolutil/Whiskers.cpp
> +	BOOST_CHECK_EQUAL(Whiskers(templ)("b", "abc").render(), "<?+b>+abc</b>");
```suggestion
	BOOST_CHECK_EQUAL(Whiskers(templ)("b", "abc").render(), "+abc");
```
?

2020-04-27 11:32 UTC, chriseth commented on test/libsolutil/Whiskers.cpp
> +	BOOST_CHECK_EQUAL(Whiskers(templ)("b", "abc").render(), "<?+b>+abc</b>");
Take a closer look ;)

2020-04-27 11:46 UTC, leonardoalt commented on test/libsolutil/Whiskers.cpp
> +	BOOST_CHECK_EQUAL(Whiskers(templ)("b", "abc").render(), "<?+b>+abc</b>");
Ah ;)

2020-04-27 11:46 UTC, leonardoalt approved these changes

2020-04-27 12:07 UTC, merged