[SMTChecker] Fix internal error in tuples of tuples.
ethereum/solidity pull request #9045
Opened 2020-05-27 18:57 UTC by leonardoalt

Fixes https://github.com/ethereum/solidity/issues/8971

2020-05-28 10:51 UTC, leonardoalt commented
Added test

2020-06-04 18:41 UTC, ekpyron reviewed
Fine with merging this - will approve once the release is through and the changelog sorted out!

2020-06-04 18:41 UTC, ekpyron commented on Changelog.md
> + * SMTChecker: Fix internal error when encoding tuples of tuples.
This will need to move.

2020-06-05 10:15 UTC, leonardoalt commented
@ekpyron rebased & fixed

2020-06-05 10:16 UTC, ekpyron requested changes

2020-06-05 10:16 UTC, ekpyron commented on Changelog.md
> + * SMTChecker: Fix internal error when assigning to index access inside branches.
This doesn't look right...

2020-06-05 10:19 UTC, leonardoalt commented on Changelog.md
> + * SMTChecker: Fix internal error when assigning to index access inside branches.
Damn, wait

2020-06-05 10:21 UTC, leonardoalt commented on Changelog.md
> + * SMTChecker: Fix internal error when assigning to index access inside branches.
done

2020-06-05 10:22 UTC, ekpyron approved these changes

2020-06-05 12:21 UTC, merged