Member access sol yul
ethereum/solidity pull request #9058
Opened 2020-05-28 19:16 UTC by chriseth

2020-05-29 06:31 UTC, mijovic reviewed
Are there more tests to be activated?

2020-05-29 06:31 UTC, mijovic commented on libsolidity/codegen/ir/IRGeneratorForStatements.cpp
> +		StructType const& structType = dynamic_cast<StructType const&>(*_memberAccess.expression().annotation().type);
```suggestion
		auto const& structType = dynamic_cast<StructType const&>(*_memberAccess.expression().annotation().type);
```

2020-05-29 06:50 UTC, mijovic commented
> Are there more tests to be activated?

I added a commit that activates additional tests.

2020-05-29 07:07 UTC, mijovic commented
> > Are there more tests to be activated?
> 
> I added a commit that activates additional tests.

Even after adding more tests `semanticTests/various/negative_stack_height.sol` fails with `StackTooDeepError`.

2020-05-29 09:24 UTC, chriseth commented
Can you check if we get `StackTooDeep` only because the optimizer is not activated?

2020-05-29 09:56 UTC, mijovic commented
> Can you check if we get `StackTooDeep` only because the optimizer is not activated?

It is trying to compile it with viaYul, and it comes from `optimize()` call in `AssemblyStack`. Still, that error should be caught in SemanticTest and it should be fine as test is marked with compileViaYul: false ...

2020-06-02 18:52 UTC, ekpyron requested changes
One minor suggestion plus @mijovic's earlier suggestion - otherwise this looks good!

2020-06-02 18:52 UTC, ekpyron commented on libsolidity/codegen/ir/IRGeneratorForStatements.cpp
> +			pair<u256, unsigned> const& offsets = structType.storageOffsetsOfMember(member);
```suggestion
			auto const& [slotOffset, offsetInSlot] = structType.storageOffsetsOfMember(member);
```

2020-06-02 19:17 UTC, mijovic commented
There are more tests to be active. I remember I added commit with those, but in rebase/force push it was lost probably :)

2020-06-03 17:13 UTC, ekpyron commented on libsolidity/codegen/ir/IRGeneratorForStatements.cpp
> +			pair<u256, unsigned> const& offsets = structType.storageOffsetsOfMember(member);
This one is still open...

2020-06-03 17:16 UTC, ekpyron approved these changes

2020-06-03 17:16 UTC, ekpyron commented on libsolidity/codegen/ir/IRGeneratorForStatements.cpp
> +			pair<u256, unsigned> const& offsets = structType.storageOffsetsOfMember(member);
But well, I'd call it "optional" and am approving.

2020-06-03 17:26 UTC, mijovic approved these changes

2020-06-03 19:19 UTC, merged