Index access to fixed bytes and byte arrays.
ethereum/solidity pull request #9121
Opened 2020-06-04 08:55 UTC by chriseth

Fixes #9109

2020-06-04 09:01 UTC, leonardoalt requested changes
Test?

2020-06-04 09:14 UTC, chriseth commented
Forgot to commit test.

2020-06-04 09:59 UTC, mijovic commented on libsolidity/codegen/ir/IRGeneratorForStatements.cpp
> +		FixedBytesType const& fixedBytesType = dynamic_cast<FixedBytesType const&>(baseType);
```suggestion
		auto const& fixedBytesType = dynamic_cast<FixedBytesType const&>(baseType);
```

2020-06-04 09:59 UTC, mijovic commented on libsolidity/codegen/ir/IRGeneratorForStatements.cpp
> +			let <result> := <shl>(byte(<index>, <array>))
```suggestion
			let <result> := <shl248>(byte(<index>, <array>))
```

2020-06-04 09:59 UTC, mijovic commented on libsolidity/codegen/ir/IRGeneratorForStatements.cpp
> +		("shl", m_utils.shiftLeftFunction(256 - 8))
```suggestion
		("shl248", m_utils.shiftLeftFunction(256 - 8))
```

2020-06-04 15:13 UTC, mijovic commented on libsolidity/codegen/ir/IRGeneratorForStatements.cpp
> +		("shl", m_utils.shiftLeftFunction(256 - 8))
This needs to be changed as well

2020-06-09 08:50 UTC, leonardoalt commented on libsolidity/codegen/ir/IRGeneratorForStatements.cpp
> +		("shl", m_utils.shiftLeftFunction(256 - 8))
Fixed

2020-06-09 08:52 UTC, leonardoalt approved these changes

2020-06-09 09:18 UTC, merged