solidity-upgrade: added module to remove visibility of constructors
ethereum/solidity pull request #9255
Opened 2020-06-24 09:44 UTC by hrkrshnn

2020-06-24 11:36 UTC, Marenz requested changes
LGTM, of course test are failing and one suggestion to write something shorter

2020-06-24 11:36 UTC, Marenz commented on tools/solidityUpgrade/SourceTransform.h
> +		for (auto const& replace: toReplace)
```suggestion
		for (auto const& replace: {"public ", "public", "internal ", "internal"})
```

2020-06-24 15:54 UTC, hrkrshnn commented
The zeppelin external contracts needs fixing. I believe, the CI is using solidity-nightly to run the tests instead of 0.7.0 (whatever solc created during tests.)

2020-06-25 13:32 UTC, chriseth commented on tools/solidityUpgrade/Upgrade070.cpp
> +	// TODO If constructor is internal, maybe it makes sense to change contract to abstract. But
Yes, it should be made abstract in this case.

2020-07-07 16:23 UTC, axic commented
#9180 was merged, this needs to be rebased.

2020-07-08 13:31 UTC, hrkrshnn commented on tools/solidityUpgrade/SourceTransform.h
> +				std::regex_constants::format_first_only
Without this flag, the following would be upgraded to 

```solidity
contract test {
	/// contract upgrade
	constructor() internal {}
}
```

```solidity
abstract contract test {
	/// abstract contract upgrade
	constructor() {}
}
```

2020-07-09 12:52 UTC, Marenz requested changes

2020-07-09 12:52 UTC, Marenz commented on docs/using-the-compiler.rst
> +The above contract will not compile after 0.7.0. To bring the contract up to date with the current
The wording is a bit confusing "after 0.7.0" makes me think of "0.8.0". I suggest using "with" or "starting with".

"will no longer compile starting with 0.7.0"

2020-07-20 10:41 UTC, Marenz commented on docs/using-the-compiler.rst
> +The above contract will not compile after 0.7.0. To bring the contract up to date with the current
Any change to this?

2020-07-20 10:43 UTC, Marenz approved these changes
LGTM, only the ch_proof test is failing

2020-07-21 11:24 UTC, merged