Disallow public state variables overriding pure functions.
ethereum/solidity pull request #9416
Opened 2020-07-14 18:12 UTC by chriseth

2020-07-14 18:13 UTC, chriseth commented
I think this is totally a bugfix we want to have. It is interesting that we already have several tests that now add the new error! The problem is that in order to fix these tests, we make the base contract functions `view` instead of `pure`, but then we get many warnings: state mutability can be restricted to `view`.

Should we not issue this warning for a `virtual` function?

2020-07-14 18:19 UTC, chriseth commented
Added a second commit: Functions reading constant state variables are considered `pure` - so I think constant public state variables should also be pure.

2020-07-14 23:20 UTC, ekpyron reviewed
Yep, we should definitely have this - and the change looks fine, so "soft"-approval modulo the question of the tests.

2020-07-14 23:23 UTC, ekpyron commented
> I think this is totally a bugfix we want to have. It is interesting that we already have several tests that now add the new error! The problem is that in order to fix these tests, we make the base contract functions `view` instead of `pure`, but then we get many warnings: state mutability can be restricted to `view`.
> 
> Should we not issue this warning for a `virtual` function?

Yeah, not issuing the warning for ``virtual`` functions makes sense. We already don't for functions with empty implementation - basically because we didn't *have* ``virtual`` at the time - we could think about removing that special case and instead not warn for anything ``virtual``. (A non-virtual function with empty implementation makes little sense anyways, doesn't it?)

2020-07-15 09:53 UTC, chriseth commented
Pull request is here: https://github.com/ethereum/solidity/pull/9418

2020-07-16 13:11 UTC, Marenz requested changes

2020-07-16 13:11 UTC, Marenz commented on libsolidity/analysis/OverrideChecker.cpp
> +		if (_overriding.isFunction() && _overriding.unimplemented() && !_super.unimplemented())
This might not be needed as the proxy always returns `false` for state variables

2020-07-16 16:56 UTC, chriseth commented
Ready for review.

2020-07-20 09:16 UTC, Marenz commented
Tests are failing though?

2020-07-20 09:47 UTC, Marenz commented on libsolidity/analysis/OverrideChecker.cpp
> +		// Stricter mutability is always okay except when super is Payable
I was thinking that you don't actually need to change this whole block at all other than adding the `|| isVariable` part.
Is there an advantage of having `if (_overriding.unimplemented() && !_super.unimplemented())` outside the if-block?

The `if` would be slightly easier to read if we just do a small change

2020-07-20 12:57 UTC, chriseth commented on docs/contracts/inheritance.rst
> +        function f() external view virtual returns(uint) { return num; }
This needs the PR that virtual suppresses the warning.

2020-07-20 16:17 UTC, Marenz approved these changes

2020-07-20 16:19 UTC, merged