Disallow assigning more than once to immutables during the variable declaration
ethereum/solidity pull request #9690
Opened 2020-08-27 15:26 UTC by hrkrshnn

Closes https://github.com/ethereum/solidity/issues/9207

2020-08-27 18:07 UTC, leonardoalt requested changes
Looks good, but maybe add some more weird tests? Like
```
uint immutable z = 2;
uint immutable x = z = y = 3;
uint immutable y = 5;
```

2020-08-27 18:07 UTC, leonardoalt commented on Changelog.md
> + * Immutables: Disallow assigning more than once to immutables during the variable declaration of immutables.
```suggestion
 * Immutables: Disallow assigning immutables more than once during their declaration.
```

2020-08-27 19:18 UTC, hrkrshnn commented
```
uint immutable z = 2;
uint immutable x = z = y = 3;
uint immutable y = 5;
```

There is a crash in this test now. Because `y` gets visited first. Perhaps the right way to do it is to visit all the declarations first. Then visit the rhs.

2020-08-28 12:39 UTC, chriseth approved these changes

2020-08-28 12:39 UTC, merged